import { createHash } from 'node:crypto';
import { types } from 'node:util';
import type { Ledger } from '../ledger.js';
import { readIssuedNativeRuntimeEvidence, type HostCodexRuntimeResult, type IssuedNativeRuntimeEvidence, type NativeRuntimeEvidenceBinding } from '../host-codex-runtime.js';

const PREFIX='cue-native-runtime-receipt:';
const sha=(v:Uint8Array|string)=>createHash('sha256').update(v).digest('hex');
const hash=(v:unknown):v is string=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v);
const id=(v:unknown):v is string=>typeof v==='string'&&/^[A-Za-z0-9][A-Za-z0-9._:/-]{0,199}$/.test(v);
function record(v:unknown,keys:readonly string[]):Record<string,unknown>{if(!v||typeof v!=='object'||types.isProxy(v)||Object.getPrototypeOf(v)!==Object.prototype)throw Error('native_runtime_receipt_integrity');const ds=Object.getOwnPropertyDescriptors(v);if(Reflect.ownKeys(ds).length!==keys.length)throw Error('native_runtime_receipt_integrity');const out:Record<string,unknown>={};for(const key of keys){const d=ds[key];if(!d?.enumerable||!Object.hasOwn(d,'value'))throw Error('native_runtime_receipt_integrity');out[key]=d.value;}return out;}
function array(v:unknown,max:number):unknown[]{if(!Array.isArray(v)||types.isProxy(v)||Object.getPrototypeOf(v)!==Array.prototype||v.length>max)throw Error('native_runtime_receipt_integrity');const ds=Object.getOwnPropertyDescriptors(v);if(Reflect.ownKeys(ds).length!==v.length+1)throw Error('native_runtime_receipt_integrity');const out=[];for(let i=0;i<v.length;i++){const d=ds[String(i)];if(!d?.enumerable||!Object.hasOwn(d,'value'))throw Error('native_runtime_receipt_integrity');out.push(d.value);}return out;}
function canonical(v:unknown):string{const seen=new Set<object>();function walk(x:unknown,depth:number):unknown{if(depth>8)throw Error('native_runtime_receipt_bounds');if(x===null||typeof x==='boolean'||typeof x==='string')return x;if(typeof x==='number'){if(!Number.isSafeInteger(x)||Object.is(x,-0))throw Error('native_runtime_receipt_number');return x;}if(!x||typeof x!=='object'||types.isProxy(x)||seen.has(x))throw Error('native_runtime_receipt_plain');const array=Array.isArray(x);if(Object.getPrototypeOf(x)!==(array?Array.prototype:Object.prototype))throw Error('native_runtime_receipt_plain');seen.add(x);try{if(array){if(x.length>1024)throw Error('native_runtime_receipt_bounds');return x.map(y=>walk(y,depth+1));}const out:Record<string,unknown>={};const ds=Object.getOwnPropertyDescriptors(x);if(Reflect.ownKeys(ds).some(k=>typeof k!=='string'))throw Error('native_runtime_receipt_plain');for(const k of Object.keys(ds).sort()){if(!ds[k]?.enumerable||!Object.hasOwn(ds[k],'value'))throw Error('native_runtime_receipt_plain');out[k]=walk(ds[k]!.value,depth+1);}return out;}finally{seen.delete(x);}}const encoded=JSON.stringify(walk(v,0));if(Buffer.byteLength(encoded)>65536)throw Error('native_runtime_receipt_bounds');return encoded;}
export type NativeRuntimeReceipt=Readonly<IssuedNativeRuntimeEvidence&{receiptId:string;outcome:'succeeded'|'failed';observedAtMs:number}>;
type Row={receipt_id:string;run_id:string;task_id:string;attempt_id:string;candidate_id:string;subject_digest:string;session_handle:string;outcome:'succeeded'|'failed';payload_digest:string;payload:Buffer};
function outcome(e:IssuedNativeRuntimeEvidence):'succeeded'|'failed'{const implementation=e.role==='implementation'&&['workspace-change','approved-existing-file-change'].includes(e.verificationMode)&&e.outcomeInputs.goalVerification.passed===true;const verifier=e.role==='model'&&e.verificationMode==='read-only-result'&&e.outcomeInputs.goalVerification.passed===false&&e.outcomeInputs.goalVerification.reason==='read_only_result_received';return e.outcomeInputs.status==='completed'&&e.outcomeInputs.failureKind===null&&(implementation||verifier)?'succeeded':'failed';}
function validate(value:NativeRuntimeReceipt){const v=record(value,['version','runId','taskId','attemptId','candidateId','subjectDigest','sessionHandle','role','verificationMode','outcomeInputs','controller','workers','resources','receiptId','outcome','observedAtMs']);if(v.version!=='cue-issued-native-runtime-evidence-v1'||![v.receiptId,v.runId,v.taskId,v.attemptId,v.candidateId,v.sessionHandle].every(id)||!hash(v.subjectDigest)||!['implementation','model'].includes(v.role as string)||!['workspace-change','read-only-result','approved-existing-file-change'].includes(v.verificationMode as string)||!Number.isSafeInteger(v.observedAtMs)||Number(v.observedAtMs)<0)throw Error('native_runtime_receipt_integrity');const oi=record(v.outcomeInputs,['status','failureKind','goalVerification']),goal=record(oi.goalVerification,['passed','reason','changedPaths']);if(typeof oi.status!=='string'||oi.status.length<1||oi.status.length>128||!/^[A-Za-z0-9._:-]+$/.test(oi.status)||!(oi.failureKind===null||['crash','cleanup','termination','enforcement'].includes(oi.failureKind as string))||typeof goal.passed!=='boolean'||typeof goal.reason!=='string'||!['workspace_changed','workspace_unchanged','expected_path_not_changed','expected_content_mismatch','agent_reported_incomplete','snapshot_failed','model_not_completed','read_only_result_received'].includes(goal.reason as string)||array(goal.changedPaths,1024).some(path=>typeof path!=='string'||path.length>4096))throw Error('native_runtime_receipt_integrity');if((v.role==='implementation'&&!['workspace-change','approved-existing-file-change'].includes(v.verificationMode as string))||(v.role==='model'&&v.verificationMode!=='read-only-result'))throw Error('native_runtime_receipt_integrity');const pids:number[]=[];const process=(input:unknown)=>{const p=record(input,['pid','createdFileTime']);if(!Number.isSafeInteger(p.pid)||Number(p.pid)<1||pids.includes(Number(p.pid))||typeof p.createdFileTime!=='string'||!/^[1-9]\d{0,19}$/.test(p.createdFileTime))throw Error('native_runtime_receipt_integrity');pids.push(Number(p.pid));};process(v.controller);array(v.workers,256).forEach(process);array(v.resources,256).forEach(input=>{const r=record(input,['path','ownership','cleanup']);if(typeof r.path!=='string'||!r.path||r.path.length>32768||!/^[A-Za-z]:[\\\\/]/.test(r.path)||!['ephemeral-owned','retained-authorized'].includes(r.ownership as string)||!['absent','retained','unknown'].includes(r.cleanup as string)||(r.ownership==='retained-authorized'&&r.cleanup!=='retained')||(r.ownership==='ephemeral-owned'&&r.cleanup==='retained'))throw Error('native_runtime_receipt_integrity');});const typed=v as unknown as NativeRuntimeReceipt;if(v.outcome!==outcome(typed))throw Error('native_runtime_receipt_integrity');return typed;}
export function createNativeRuntimeReceiptStore(db:Ledger){function fail():never{throw Error('native_runtime_receipt_integrity');}function decode(row:Row){if(!Buffer.isBuffer(row.payload)||sha(row.payload)!==row.payload_digest)return fail();const value=validate(JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(row.payload)) as NativeRuntimeReceipt);if(canonical(value)!==row.payload.toString('utf8')||row.receipt_id!==value.receiptId||row.run_id!==value.runId||row.task_id!==value.taskId||row.attempt_id!==value.attemptId||row.candidate_id!==value.candidateId||row.subject_digest!==value.subjectDigest||row.session_handle!==value.sessionHandle||row.outcome!==value.outcome)return fail();return Object.freeze(value);}return Object.freeze({
 recordIssued(result:HostCodexRuntimeResult,binding:NativeRuntimeEvidenceBinding,observedAtMs:number){if(db.inTransaction)throw Error('native_runtime_receipt_outer_transaction');if(!Number.isSafeInteger(observedAtMs)||observedAtMs<0)throw Error('native_runtime_receipt_time');const evidence=readIssuedNativeRuntimeEvidence(result,binding);const receiptId=`native-runtime-${sha(canonical(evidence)).slice(0,48)}`;const value=validate(Object.freeze({...evidence,receiptId,outcome:outcome(evidence),observedAtMs}));const payload=Buffer.from(canonical(value)),digest=sha(payload);db.transaction(()=>{const old=db.prepare('SELECT * FROM native_runtime_receipt WHERE attempt_id=? OR receipt_id=? OR session_handle=?').all(value.attemptId,value.receiptId,value.sessionHandle) as Row[];if(old.length){if(old.length!==1||old[0]!.payload_digest!==digest||!old[0]!.payload.equals(payload))throw Error('native_runtime_receipt_conflict');decode(old[0]!);}else db.prepare('INSERT INTO native_runtime_receipt VALUES(?,?,?,?,?,?,?,?,?,?)').run(value.receiptId,value.runId,value.taskId,value.attemptId,value.candidateId,value.subjectDigest,value.sessionHandle,value.outcome,digest,payload);}).immediate();return Object.freeze({ref:PREFIX+digest,receipt:value});},
 read(ref:string){if(typeof ref!=='string'||!ref.startsWith(PREFIX)||!hash(ref.slice(PREFIX.length)))return null;const row=db.prepare('SELECT * FROM native_runtime_receipt WHERE payload_digest=?').get(ref.slice(PREFIX.length)) as Row|undefined;return row?decode(row):null;}
 });}



