import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {runProcessSync} from '../../daemon/dist/src/process-launch.js';
const cs=readFileSync(new URL('./native/readonly-wfp-collector.cs',import.meta.url),'utf8'),ps=readFileSync(new URL('./readonly-wfp-collector.ps1',import.meta.url),'utf8');
const fake=String.raw`
public sealed class FakeWfp : IWfpNative {
 public uint openCode,getCode,appCode,subCode,unsubCode,closeCode;public int collection=1,openCount,getCount,appCount,subCount,unsubCount,freeCount,closeCount,waitCount;public bool emit,overflow,throwFree,throwClose,throwWait,throwUnsubscribe,nested;public string nestedState="none";public IntPtr engine=new IntPtr(1),app=new IntPtr(2),subscription=new IntPtr(3);
 public uint Open(out IntPtr p){openCount++;p=openCode==0?engine:IntPtr.Zero;return openCode;} public uint GetCollection(IntPtr p,out int v){getCount++;v=collection;return getCode;}
 public uint GetAppId(string path,out IntPtr p,out byte[] b){appCount++;p=appCode==0?app:IntPtr.Zero;b=appCode==0?new byte[]{1,2}:null;return appCode;}
 public uint Subscribe(IntPtr e,WfpRequest r,byte[] a,Action<WfpEvent> cb,out IntPtr s,out object root){subCount++;s=subCode==0?subscription:IntPtr.Zero;root=cb;if(subCode==0&&emit){int n=overflow?65:1;for(int i=0;i<n;i++)cb(new WfpEvent{Timestamp=(ulong)i,IsLoopback=true,RemotePort=r.RemotePort});}return subCode;}
 public uint Unsubscribe(IntPtr e,IntPtr s){unsubCount++;if(throwUnsubscribe)throw new Exception("unsubscribe");return unsubCode;}public void Free(ref IntPtr p){freeCount++;if(throwFree)throw new Exception("free");p=IntPtr.Zero;}public uint Close(IntPtr e){closeCount++;if(throwClose)throw new Exception("close");return closeCode;}public void Wait(int n){waitCount++;if(nested){var f=new FakeWfp();nestedState=ReadonlyWfpCollector.Collect(new WfpRequest{ExecutablePath="C:\\x",PackageSid="S-1-15-2-1",RemotePort=48193,DurationMs=1},f).State+":"+f.openCount;}if(throwWait)throw new Exception("wait");}
}
public sealed class FakeLifecycle : IReadonlyWorkerLifecycle { public WorkerStartObservation start=WorkerStartObservation.Started;public WorkerDeathObservation death=WorkerDeathObservation.Dead,stopped=WorkerDeathObservation.Dead;public int starts,deaths,stops;public bool throwStart,throwDeath;public FakeWfp native;public WorkerStartObservation StartAfterSubscription(){starts++;if(native==null||native.subCount!=1||native.unsubCount!=0)throw new Exception("ordering");if(throwStart)throw new Exception("start");return start;}public WorkerDeathObservation ObserveDeath(int timeout){deaths++;if(native.unsubCount!=0)throw new Exception("early-unsubscribe");if(throwDeath)throw new Exception("death");return death;}public WorkerDeathObservation StopAndObserveDeath(){stops++;return stopped;} }
public static class LifecycleTest { public static string Run(string mode){var f=new FakeWfp();var l=new FakeLifecycle{native=f};if(mode=="disabled")f.collection=0;if(mode=="subfail")f.subCode=5;if(mode=="startreject")l.start=WorkerStartObservation.Rejected;if(mode=="startthrow")l.throwStart=true;if(mode=="alive")l.death=WorkerDeathObservation.Alive;if(mode=="cancel")l.death=WorkerDeathObservation.Cancelled;if(mode=="timeout")l.death=WorkerDeathObservation.Timeout;if(mode=="unknown")l.death=WorkerDeathObservation.Unknown;if(mode=="deaththrow")l.throwDeath=true;if(mode=="stopfail"){l.death=WorkerDeathObservation.Alive;l.stopped=WorkerDeathObservation.Unknown;}var r=ReadonlyWfpCollector.CollectWithLifecycle(new WfpRequest{ExecutablePath="C:\\node.exe",PackageSid="S-1-15-2-1",RemotePort=48193,DurationMs=1},f,l);return string.Join("|",r.State,r.Lifecycle,l.starts,l.deaths,l.stops,f.subCount,f.unsubCount,f.freeCount,f.closeCount);} }public static class CollectorTest { public static string Run(string mode){var f=new FakeWfp();if(mode=="disabled")f.collection=0;if(mode=="getfail")f.getCode=5;if(mode=="unsubfail")f.unsubCode=5;if(mode=="unsubthrow")f.throwUnsubscribe=true;if(mode=="waitthrow")f.throwWait=true;if(mode=="nested")f.nested=true;if(mode=="captured")f.emit=true;if(mode=="closefail"){f.emit=true;f.throwClose=true;}if(mode=="closereturn"){f.emit=true;f.closeCode=5;}if(mode=="freefail"){f.emit=true;f.throwFree=true;}if(mode=="overflow"){f.emit=true;f.overflow=true;}var request=new WfpRequest{ExecutablePath="C:\\node.exe",PackageSid="S-1-15-2-1",RemotePort=48193,DurationMs=1};if(mode=="invalid")request.ExecutablePath="\\\\server\\node.exe";if(mode=="invaliddevice")request.ExecutablePath="\\\\?\\C:\\node.exe";if(mode=="invalidtraversal")request.ExecutablePath="C:\\a\\..\\node.exe";if(mode=="invalidcontrol")request.ExecutablePath="C:\\bad"+(char)1+"node.exe";if(mode=="invalidsid")request.PackageSid="S-1-5-18";if(mode=="invalidduration")request.DurationMs=5001;if(mode=="invalidport")request.RemotePort=1;var r=ReadonlyWfpCollector.Collect(request,f);int secondOpen=-1;if(mode=="unsubfail"||mode=="unsubthrow"||mode=="closereturn"){var f2=new FakeWfp();ReadonlyWfpCollector.Collect(new WfpRequest{ExecutablePath="C:\\x",PackageSid="S-1-15-2-1",RemotePort=48193,DurationMs=1},f2);secondOpen=f2.openCount;}return string.Join("|",r.State,r.Events.Length,r.Overflow,f.openCount,f.getCount,f.appCount,f.subCount,f.unsubCount,f.freeCount,f.closeCount,f.waitCount,r.CollectionValue,secondOpen,f.nestedState,r.AppIdCode,r.SubscribeCode,r.UnsubscribeCode,r.CloseCode,r.OpenCode,r.GetCode);}}
`;
function run(mode){const payload=Buffer.from(cs+'\n'+fake).toString('base64'),command=`$s=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('${payload}'));Add-Type -TypeDefinition $s -Language CSharp;[CollectorTest]::Run('${mode}')`;return runProcessSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',command],{encoding:'utf8',timeout:20000,maxBuffer:65536});}
function runLifecycle(mode){const payload=Buffer.from(cs+'\n'+fake).toString('base64'),command=`$s=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('${payload}'));Add-Type -TypeDefinition $s -Language CSharp;[LifecycleTest]::Run('${mode}')`;return runProcessSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',command],{encoding:'utf8',timeout:20000,maxBuffer:65536});}
test('exact collector and injected native compile',()=>{const r=run('captured');assert.equal(r.status,0,r.stderr);assert.equal(r.stdout.trim(),'captured|1|False|1|1|1|1|1|1|1|1|1|-1|none|0|0|0|0|0|0');});
test('disabled and get failure never subscribe',()=>{for(const mode of ['disabled','getfail']){const r=run(mode);assert.equal(r.status,0,r.stderr);const x=r.stdout.trim().split('|');assert.equal(x[0],'unknown');assert.equal(x[6],'0');assert.equal(x[7],'0');}});
test('overflow stays unknown and caps copied events at 64',()=>{const r=run('overflow');assert.equal(r.status,0,r.stderr);const x=r.stdout.trim().split('|');assert.equal(x[0],'unknown');assert.equal(x[1],'64');assert.equal(x[2],'True');});
test('unsubscribe failure quarantines without free or close',()=>{const r=run('unsubfail');assert.equal(r.status,0,r.stderr);const x=r.stdout.trim().split('|');assert.equal(x[0],'unknown');assert.equal(x[7],'1');assert.equal(x[8],'0');assert.equal(x[9],'0');});
test('wait exception safely unsubscribes while unsubscribe exception quarantines',()=>{for(const mode of ['waitthrow','unsubthrow']){const r=run(mode);assert.equal(r.status,0,r.stderr);const x=r.stdout.trim().split('|');assert.equal(x[0],'unknown');assert.equal(x[7],'1');assert.equal(x[8],mode==='waitthrow'?'1':'0');assert.equal(x[9],mode==='waitthrow'?'1':'0');}});
test('poison rejects later collection and active guard rejects nested collection',()=>{for(const mode of ['unsubfail','unsubthrow','closereturn']){const x=run(mode).stdout.trim().split('|');assert.equal(x[12],'0');if(mode==='closereturn')assert.equal(x[17],'5');}const nested=run('nested').stdout.trim().split('|');assert.equal(nested[13],'unknown:0');});
test('invalid requests perform zero native calls and codes remain not-attempted',()=>{for(const mode of ['invalid','invaliddevice','invalidtraversal','invalidcontrol','invalidsid','invalidduration','invalidport']){const r=run(mode);assert.equal(r.status,0,r.stderr);const x=r.stdout.trim().split('|');assert.equal(x[3],'0',mode);for(const index of [14,15,16,17,18,19])assert.equal(x[index],'4294967295',mode);}});
test('free or close exceptions remain unknown and bounded',()=>{for(const mode of ['freefail','closefail','closereturn']){const r=run(mode);assert.equal(r.status,0,r.stderr);assert.equal(r.stdout.trim().split('|')[0],'unknown');}});
test('source uses Subscribe2 Event3 and excludes mutation and PID authority',()=>{for(const value of ['FwpmNetEventSubscribe2','struct EVENT3','struct HEADER3','FWPM_ENGINE_COLLECT_NET_EVENTS','FwpmGetAppIdFromFileName0','TYPE_CAPABILITY_DROP'])assert.ok(cs.includes(value));for(const forbidden of ['FwpmNetEventSubscribe3','FwpmEngineSetOption','NetworkIsolationSetAppContainerConfig','ProcessId','package-drop-inference'])assert.ok(!cs.includes(forbidden));assert.ok(ps.includes('wfp_collector_requires_x64'));});
test('PowerShell wrapper parses without invoking WFP',()=>{const path=new URL('./readonly-wfp-collector.ps1',import.meta.url).pathname.slice(1).replaceAll('/','\\');const command=`$e=$null;$t=$null;[Management.Automation.Language.Parser]::ParseFile('${path}',[ref]$t,[ref]$e)|Out-Null;if($e.Count){exit 1}`;const r=runProcessSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',command],{encoding:'utf8',timeout:5000,maxBuffer:65536});assert.equal(r.status,0,r.stderr);});
test('managed x64 ABI matches the frozen Windows SDK probe',()=>{const probe=String.raw`public static class ManagedLayoutProbe { static Type T(string n){return typeof(NativeWfp).GetNestedType(n,System.Reflection.BindingFlags.NonPublic);}static int S(string n){return Marshal.SizeOf(T(n));}static int O(string n,string f){return Marshal.OffsetOf(T(n),f).ToInt32();}public static string Run(){return string.Join("|",S("HEADER3"),O("HEADER3","appId"),O("HEADER3","packageSid"),S("EVENT3"),O("EVENT3","type"),O("EVENT3","detail"),S("CAPABILITY_DROP"),O("CAPABILITY_DROP","filterId"),O("CAPABILITY_DROP","isLoopback"),S("SUBSCRIPTION"),O("SUBSCRIPTION","flags"),O("SUBSCRIPTION","sessionKey"),S("VALUE_LAYOUT"),O("VALUE_LAYOUT","unionStorage"));}}`;const payload=Buffer.from(cs+'\n'+probe).toString('base64'),command=`$s=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('${payload}'));Add-Type -TypeDefinition $s -Language CSharp;[ManagedLayoutProbe]::Run()`;const r=runProcessSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',command],{encoding:'utf8',timeout:20000,maxBuffer:65536});assert.equal(r.status,0,r.stderr);assert.equal(r.stdout.trim(),'136|64|96|152|136|144|24|8|16|32|8|12|16|8');});
test('loopback matcher uses WFP host-order IPv4 and rejects reversed memory-order value',()=>{const payload=Buffer.from(cs).toString('base64'),command=`$s=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('${payload}'));Add-Type -TypeDefinition $s -Language CSharp;$m=[NativeWfp].GetMethod('IsLoopbackV4',[Reflection.BindingFlags]'NonPublic,Static');@($m.Invoke($null,@([uint32]0x7f000001)),$m.Invoke($null,@([uint32]0x0100007f)))|ConvertTo-Json -Compress`;const r=runProcessSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',command],{encoding:'utf8',timeout:20000,maxBuffer:65536});assert.equal(r.status,0,r.stderr);assert.deepEqual(JSON.parse(r.stdout),[true,false]);assert.ok(cs.includes('0x7f000001u'));});
test('lifecycle starts only after subscription and direct observed death captures',()=>{const r=runLifecycle('dead');assert.equal(r.status,0,r.stderr);assert.equal(r.stdout.trim(),'captured|dead|1|1|0|1|1|1|1');});
test('native readiness failures invoke zero lifecycle starts',()=>{for(const mode of ['disabled','subfail']){const r=runLifecycle(mode);assert.equal(r.status,0,r.stderr);const x=r.stdout.trim().split('|');assert.equal(x[0],'unknown');assert.equal(x[2],'0');}});
test('rejected start cleans safely while ambiguous start throws quarantine',()=>{let x=runLifecycle('startreject').stdout.trim().split('|');assert.deepEqual(x.slice(0,9),['unknown','start-rejected','1','0','0','1','1','1','1']);x=runLifecycle('startthrow').stdout.trim().split('|');assert.deepEqual(x.slice(0,9),['unknown','subscription-ready','1','0','0','1','0','0','0']);});
test('alive and cancelled require stop plus death and never capture',()=>{for(const mode of ['alive','cancel','timeout']){const r=runLifecycle(mode);assert.equal(r.status,0,r.stderr);const x=r.stdout.trim().split('|');assert.equal(x[0],'unknown');assert.equal(x[1],'dead');assert.equal(x[4],'1');assert.deepEqual(x.slice(6,9),['1','1','1']);}});
test('unknown death, death exception, and failed stop quarantine native lifetime',()=>{for(const mode of ['unknown','deaththrow','stopfail']){const r=runLifecycle(mode);assert.equal(r.status,0,r.stderr);const x=r.stdout.trim().split('|');assert.equal(x[0],'unknown');assert.equal(x[6],'0');assert.equal(x[7],'0');assert.equal(x[8],'0');}});
