import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {runProcessSync} from '../../daemon/dist/src/process-launch.js';
const file=new URL('./readonly-wfp-availability.ps1',import.meta.url),source=readFileSync(file,'utf8');
const match=/\$source=@'\r?\n([\s\S]*?)\r?\n'@/.exec(source);assert.ok(match,'embedded C# missing');
function compileAndFormat(args){const encoded=Buffer.from(match[1]).toString('base64'),command=`$s=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('${encoded}'));Add-Type -TypeDefinition $s -Language CSharp;[CueWfpAvailability]::Format(${args.join(',')})`;return runProcessSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',command],{encoding:'utf8',timeout:15000,maxBuffer:65536});}
test('exact embedded C# compiles and formats enabled and disabled states',()=>{for(const [value,state] of [[1,'enabled'],[0,'disabled']]){const r=compileAndFormat(['0','0','0','3',String(value),'$true']);assert.equal(r.status,0,r.stderr);const parsed=JSON.parse(r.stdout);assert.equal(parsed.version,'cue-wfp-availability-v1');assert.equal(parsed.state,state);assert.equal(parsed.collectNetEvents,value);}});
test('native errors type drift value drift and absent value remain unknown',()=>{for(const args of [['5','4294967295','0','0','0','$false'],['0','5','0','0','0','$false'],['0','0','5','3','1','$true'],['0','0','0','2','1','$true'],['0','0','0','3','2','$true'],['0','0','0','3','0','$false']]){const r=compileAndFormat(args);assert.equal(r.status,0,r.stderr);const parsed=JSON.parse(r.stdout);assert.equal(parsed.state,'unknown');assert.equal(parsed.collectNetEvents,null);}});
test('query surface is read-only and cleanup is guarded',()=>{for(const name of ['FwpmEngineOpen0','FwpmEngineGetOption0','FwpmEngineClose0','FwpmFreeMemory0','FWPM_ENGINE_COLLECT_NET_EVENTS=0','FWP_UINT32=3'])assert.ok(source.includes(name));for(const forbidden of ['FwpmEngineSetOption','FwpmNetEventSubscribe','NetworkIsolationSetAppContainerConfig','auditpol','Start-Service','TcpClient','Socket'])assert.ok(!source.includes(forbidden));assert.ok(source.includes('if(valuePtr!=IntPtr.Zero) FwpmFreeMemory0(ref valuePtr)'));assert.ok(source.includes('if(engine!=IntPtr.Zero) closeCode=FwpmEngineClose0(engine)'));});
test('FWP value union offset is derived from native alignment rather than hardcoded',()=>{assert.ok(source.includes('Marshal.OffsetOf(typeof(FWP_VALUE_LAYOUT),"unionStorage")'));assert.ok(source.includes('StructLayout(LayoutKind.Sequential)'));assert.ok(!source.includes('IntPtr.Size==8?8:4'));});
test('actual Query decoder resets partial state when a native read throws',()=>{const encoded=Buffer.from(match[1]).toString('base64'),command=`$s=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('${encoded}'));Add-Type -TypeDefinition $s -Language CSharp;$m=[CueWfpAvailability].GetMethod('TryDecode',[Reflection.BindingFlags]'NonPublic,Static');$reader=[Func[int,int]]{param($offset)if($offset -eq 0){return 3};throw 'decode'};$a=@($reader,[uint32]99,99);$ok=$m.Invoke($null,$a);@{ok=$ok;type=$a[1];value=$a[2]}|ConvertTo-Json -Compress`;const r=runProcessSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',command],{encoding:'utf8',timeout:15000,maxBuffer:65536});assert.equal(r.status,0,r.stderr);assert.deepEqual(JSON.parse(r.stdout),{value:0,type:0,ok:false});assert.ok(source.includes('catch { present=false; }'));});
test('PowerShell parses without executing the query',()=>{const command=`$e=$null;$t=$null;[Management.Automation.Language.Parser]::ParseFile('${fileURLToPath(file).replaceAll("'","''")}',[ref]$t,[ref]$e)|Out-Null;if($e.Count){$e|% Message;exit 1}`;const r=runProcessSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',command],{encoding:'utf8',timeout:5000,maxBuffer:65536});assert.equal(r.status,0,r.stderr);});
import {fileURLToPath} from 'node:url';
