CREATE TABLE IF NOT EXISTS orchestration_wait_migration(singleton INTEGER PRIMARY KEY CHECK(singleton=1),version TEXT NOT NULL CHECK(version='cue-wait-checkpoint-v1'));
CREATE TABLE IF NOT EXISTS orchestration_wait_legacy(attempt_id TEXT PRIMARY KEY REFERENCES orchestration_attempt(attempt_id),reason TEXT NOT NULL CHECK(reason='legacy-wait-unavailable'));
INSERT INTO orchestration_wait_legacy SELECT attempt_id,'legacy-wait-unavailable' FROM orchestration_attempt WHERE NOT EXISTS(SELECT 1 FROM orchestration_wait_migration);
INSERT INTO orchestration_wait_migration SELECT 1,'cue-wait-checkpoint-v1' WHERE NOT EXISTS(SELECT 1 FROM orchestration_wait_migration);

CREATE TABLE IF NOT EXISTS orchestration_wait_request(
 request_id TEXT PRIMARY KEY,run_id TEXT NOT NULL,task_id TEXT NOT NULL,attempt_id TEXT NOT NULL REFERENCES orchestration_attempt(attempt_id),identity_id TEXT NOT NULL REFERENCES orchestration_attempt_identity(identity_id),
 request_ordinal INTEGER NOT NULL CHECK(request_ordinal BETWEEN 1 AND 128),stream_id TEXT NOT NULL UNIQUE,reason TEXT NOT NULL CHECK(reason='external-response'),response_schema TEXT NOT NULL CHECK(response_schema='cue-wait-response-v1'),
 created_at_ms INTEGER NOT NULL CHECK(created_at_ms>=0),deadline_at_ms INTEGER NOT NULL CHECK(deadline_at_ms>created_at_ms),responder_id TEXT NOT NULL,responder_revision TEXT NOT NULL,
 payload_sha256 TEXT NOT NULL CHECK(length(payload_sha256)=64),payload BLOB NOT NULL CHECK(typeof(payload)='blob' AND length(payload) BETWEEN 1 AND 32768),UNIQUE(attempt_id,request_ordinal));
CREATE TABLE IF NOT EXISTS orchestration_wait_inbox(
 event_id TEXT PRIMARY KEY,event_type TEXT NOT NULL CHECK(event_type IN('response','checkpoint-partial','checkpoint-final')),
 request_id TEXT REFERENCES orchestration_wait_request(request_id),response_id TEXT,response_ordinal INTEGER,responder_id TEXT,responder_revision TEXT,
 stream_id TEXT,run_id TEXT,task_id TEXT,attempt_id TEXT NOT NULL REFERENCES orchestration_attempt(attempt_id),identity_id TEXT NOT NULL REFERENCES orchestration_attempt_identity(identity_id),source_ordinal INTEGER,kind TEXT,
 content_ref TEXT NOT NULL,content_sha256 TEXT NOT NULL CHECK(length(content_sha256)=64),content_length INTEGER NOT NULL CHECK(content_length BETWEEN 0 AND 1048576),observed_at_ms INTEGER NOT NULL CHECK(observed_at_ms>=0),
 payload_sha256 TEXT NOT NULL CHECK(length(payload_sha256)=64),payload BLOB NOT NULL CHECK(typeof(payload)='blob' AND length(payload) BETWEEN 1 AND 32768),
 CHECK((event_type='response' AND request_id IS NOT NULL AND response_id IS NOT NULL AND response_ordinal IS NOT NULL AND responder_id IS NOT NULL AND responder_revision IS NOT NULL AND stream_id IS NULL AND source_ordinal IS NULL AND kind IS NULL)
    OR(event_type<>'response' AND request_id IS NULL AND response_id IS NULL AND response_ordinal IS NULL AND responder_id IS NULL AND responder_revision IS NULL AND stream_id IS NOT NULL AND source_ordinal IS NOT NULL AND kind=CASE event_type WHEN 'checkpoint-partial' THEN 'partial' ELSE 'final' END)),
 UNIQUE(request_id,response_id),UNIQUE(stream_id,source_ordinal));
CREATE TABLE IF NOT EXISTS orchestration_wait_resolution(request_id TEXT PRIMARY KEY REFERENCES orchestration_wait_request(request_id),status TEXT NOT NULL CHECK(status IN('responded','cancelled','expired')),event_id TEXT UNIQUE REFERENCES orchestration_wait_inbox(event_id),resolved_at_ms INTEGER NOT NULL CHECK(resolved_at_ms>=0),CHECK((status='responded')=(event_id IS NOT NULL)));
CREATE TABLE IF NOT EXISTS orchestration_inbox_cursor(scope TEXT NOT NULL CHECK(scope IN('wait','checkpoint')),scope_id TEXT NOT NULL,ordinal INTEGER NOT NULL CHECK(ordinal>=1),previous_ordinal INTEGER NOT NULL CHECK(previous_ordinal=ordinal-1),event_id TEXT REFERENCES orchestration_wait_inbox(event_id),request_id TEXT REFERENCES orchestration_wait_request(request_id),resolution_status TEXT,CHECK((scope='checkpoint' AND event_id IS NOT NULL AND request_id IS NULL AND resolution_status IS NULL) OR(scope='wait' AND request_id IS NOT NULL AND resolution_status IN('responded','cancelled','expired'))),PRIMARY KEY(scope,scope_id,ordinal));
CREATE TABLE IF NOT EXISTS orchestration_checkpoint_final_seal(stream_id TEXT PRIMARY KEY,event_id TEXT NOT NULL UNIQUE REFERENCES orchestration_wait_inbox(event_id),cursor_ordinal INTEGER NOT NULL,content_ref TEXT NOT NULL,content_sha256 TEXT NOT NULL CHECK(length(content_sha256)=64),content_length INTEGER NOT NULL CHECK(content_length BETWEEN 0 AND 1048576),sealed_at_ms INTEGER NOT NULL CHECK(sealed_at_ms>=0));
CREATE TABLE IF NOT EXISTS orchestration_wait_dispatch_claim(dispatch_id TEXT PRIMARY KEY,request_id TEXT NOT NULL UNIQUE REFERENCES orchestration_wait_request(request_id),response_id TEXT NOT NULL UNIQUE,attempt_id TEXT NOT NULL REFERENCES orchestration_attempt(attempt_id),identity_id TEXT NOT NULL REFERENCES orchestration_attempt_identity(identity_id),launch_intent_sha256 TEXT NOT NULL,claim_payload_sha256 TEXT NOT NULL,content_ref TEXT NOT NULL,content_sha256 TEXT NOT NULL,content_length INTEGER NOT NULL,claimed_at_ms INTEGER NOT NULL CHECK(claimed_at_ms>=0));
CREATE TABLE IF NOT EXISTS orchestration_wait_delivery_observation(dispatch_id TEXT PRIMARY KEY REFERENCES orchestration_wait_dispatch_claim(dispatch_id),status TEXT NOT NULL CHECK(status IN('delivered','failed','unknown')),observed_at_ms INTEGER NOT NULL CHECK(observed_at_ms>=0),payload_sha256 TEXT NOT NULL CHECK(length(payload_sha256)=64),payload BLOB NOT NULL CHECK(typeof(payload)='blob' AND length(payload) BETWEEN 1 AND 32768));

CREATE TRIGGER wait_request_hash BEFORE INSERT ON orchestration_wait_request WHEN cue_sha256(NEW.payload)<>NEW.payload_sha256 BEGIN SELECT RAISE(ABORT,'wait request hash mismatch'); END;
CREATE TRIGGER wait_inbox_hash BEFORE INSERT ON orchestration_wait_inbox WHEN cue_sha256(NEW.payload)<>NEW.payload_sha256 BEGIN SELECT RAISE(ABORT,'wait inbox hash mismatch'); END;
CREATE TRIGGER wait_delivery_hash BEFORE INSERT ON orchestration_wait_delivery_observation WHEN cue_sha256(NEW.payload)<>NEW.payload_sha256 BEGIN SELECT RAISE(ABORT,'wait delivery hash mismatch'); END;
CREATE TRIGGER wait_legacy_closed BEFORE INSERT ON orchestration_wait_legacy BEGIN SELECT RAISE(ABORT,'wait legacy membership closed'); END;
CREATE TRIGGER wait_migration_replace BEFORE INSERT ON orchestration_wait_migration WHEN EXISTS(SELECT 1 FROM orchestration_wait_migration) BEGIN SELECT RAISE(ABORT,'wait migration immutable'); END;
CREATE TRIGGER wait_migration_update BEFORE UPDATE ON orchestration_wait_migration BEGIN SELECT RAISE(ABORT,'wait migration immutable'); END;
CREATE TRIGGER wait_migration_delete BEFORE DELETE ON orchestration_wait_migration BEGIN SELECT RAISE(ABORT,'wait migration immutable'); END;
CREATE TRIGGER wait_legacy_update BEFORE UPDATE ON orchestration_wait_legacy BEGIN SELECT RAISE(ABORT,'wait legacy immutable'); END;
CREATE TRIGGER wait_legacy_delete BEFORE DELETE ON orchestration_wait_legacy BEGIN SELECT RAISE(ABORT,'wait legacy immutable'); END;
CREATE TRIGGER wait_inbox_after_seal BEFORE INSERT ON orchestration_wait_inbox WHEN NEW.stream_id IS NOT NULL AND EXISTS(SELECT 1 FROM orchestration_checkpoint_final_seal WHERE stream_id=NEW.stream_id) BEGIN SELECT RAISE(ABORT,'checkpoint stream sealed'); END;
CREATE TRIGGER wait_inbox_second_final BEFORE INSERT ON orchestration_wait_inbox WHEN NEW.event_type='checkpoint-final' AND EXISTS(SELECT 1 FROM orchestration_wait_inbox WHERE stream_id=NEW.stream_id AND event_type='checkpoint-final') BEGIN SELECT RAISE(ABORT,'checkpoint final immutable'); END;
CREATE TRIGGER wait_request_replace BEFORE INSERT ON orchestration_wait_request WHEN EXISTS(SELECT 1 FROM orchestration_wait_request WHERE request_id=NEW.request_id OR (attempt_id=NEW.attempt_id AND request_ordinal=NEW.request_ordinal) OR stream_id=NEW.stream_id) BEGIN SELECT RAISE(ABORT,'wait request immutable'); END;
CREATE TRIGGER wait_inbox_replace BEFORE INSERT ON orchestration_wait_inbox WHEN EXISTS(SELECT 1 FROM orchestration_wait_inbox WHERE event_id=NEW.event_id OR (NEW.request_id IS NOT NULL AND request_id=NEW.request_id AND response_id=NEW.response_id) OR (NEW.stream_id IS NOT NULL AND stream_id=NEW.stream_id AND source_ordinal=NEW.source_ordinal)) BEGIN SELECT RAISE(ABORT,'wait inbox immutable'); END;
CREATE TRIGGER wait_resolution_replace BEFORE INSERT ON orchestration_wait_resolution WHEN EXISTS(SELECT 1 FROM orchestration_wait_resolution WHERE request_id=NEW.request_id OR event_id=NEW.event_id) BEGIN SELECT RAISE(ABORT,'wait resolution immutable'); END;
CREATE TRIGGER wait_cursor_replace BEFORE INSERT ON orchestration_inbox_cursor WHEN EXISTS(SELECT 1 FROM orchestration_inbox_cursor WHERE scope=NEW.scope AND scope_id=NEW.scope_id AND ordinal=NEW.ordinal) BEGIN SELECT RAISE(ABORT,'wait cursor immutable'); END;
CREATE TRIGGER wait_seal_replace BEFORE INSERT ON orchestration_checkpoint_final_seal WHEN EXISTS(SELECT 1 FROM orchestration_checkpoint_final_seal WHERE stream_id=NEW.stream_id OR event_id=NEW.event_id) BEGIN SELECT RAISE(ABORT,'checkpoint seal immutable'); END;
CREATE TRIGGER wait_dispatch_replace BEFORE INSERT ON orchestration_wait_dispatch_claim WHEN EXISTS(SELECT 1 FROM orchestration_wait_dispatch_claim WHERE dispatch_id=NEW.dispatch_id OR request_id=NEW.request_id OR response_id=NEW.response_id) BEGIN SELECT RAISE(ABORT,'wait dispatch immutable'); END;
CREATE TRIGGER wait_delivery_replace BEFORE INSERT ON orchestration_wait_delivery_observation WHEN EXISTS(SELECT 1 FROM orchestration_wait_delivery_observation WHERE dispatch_id=NEW.dispatch_id) BEGIN SELECT RAISE(ABORT,'wait delivery immutable'); END;
CREATE TRIGGER wait_request_current BEFORE INSERT ON orchestration_wait_request WHEN EXISTS(SELECT 1 FROM orchestration_wait_legacy WHERE attempt_id=NEW.attempt_id) OR NOT EXISTS(SELECT 1 FROM orchestration_attempt a JOIN orchestration_attempt_identity i ON i.identity_id=NEW.identity_id AND i.attempt_id=a.attempt_id JOIN orchestration_launch_intent l ON l.attempt_id=a.attempt_id WHERE a.attempt_id=NEW.attempt_id AND a.run_id=NEW.run_id AND a.task_id=NEW.task_id AND a.state='running' AND cue_sha256(i.payload)=i.payload_sha256 AND cue_sha256(l.payload)=l.payload_sha256) BEGIN SELECT RAISE(ABORT,'wait request current lineage required'); END;
CREATE TRIGGER wait_response_exact BEFORE INSERT ON orchestration_wait_inbox WHEN NEW.event_type='response' AND NOT EXISTS(SELECT 1 FROM orchestration_wait_request q WHERE q.request_id=NEW.request_id AND q.attempt_id=NEW.attempt_id AND q.identity_id=NEW.identity_id AND q.request_ordinal=NEW.response_ordinal AND q.responder_id=NEW.responder_id AND q.responder_revision=NEW.responder_revision) BEGIN SELECT RAISE(ABORT,'wait response lineage required'); END;
CREATE TRIGGER checkpoint_exact_lineage BEFORE INSERT ON orchestration_wait_inbox WHEN NEW.event_type<>'response' AND (EXISTS(SELECT 1 FROM orchestration_wait_legacy WHERE attempt_id=NEW.attempt_id) OR NOT EXISTS(SELECT 1 FROM orchestration_attempt a JOIN orchestration_attempt_identity i ON i.identity_id=NEW.identity_id AND i.attempt_id=a.attempt_id JOIN orchestration_wait_request q ON q.stream_id=NEW.stream_id AND q.attempt_id=a.attempt_id WHERE a.attempt_id=NEW.attempt_id AND a.run_id=NEW.run_id AND a.task_id=NEW.task_id AND a.state='running')) BEGIN SELECT RAISE(ABORT,'checkpoint lineage required'); END;
CREATE TRIGGER checkpoint_seal_exact BEFORE INSERT ON orchestration_checkpoint_final_seal WHEN NOT EXISTS(SELECT 1 FROM orchestration_wait_inbox e JOIN orchestration_inbox_cursor c ON c.scope='checkpoint' AND c.scope_id=NEW.stream_id AND c.ordinal=NEW.cursor_ordinal AND c.event_id=e.event_id WHERE e.event_id=NEW.event_id AND e.event_type='checkpoint-final' AND e.stream_id=NEW.stream_id AND e.source_ordinal=NEW.cursor_ordinal AND e.content_ref=NEW.content_ref AND e.content_sha256=NEW.content_sha256 AND e.content_length=NEW.content_length) BEGIN SELECT RAISE(ABORT,'checkpoint seal lineage required'); END;

CREATE TRIGGER wait_request_update BEFORE UPDATE ON orchestration_wait_request BEGIN SELECT RAISE(ABORT,'wait request immutable'); END;
CREATE TRIGGER wait_request_delete BEFORE DELETE ON orchestration_wait_request BEGIN SELECT RAISE(ABORT,'wait request immutable'); END;
CREATE TRIGGER wait_inbox_update BEFORE UPDATE ON orchestration_wait_inbox BEGIN SELECT RAISE(ABORT,'wait inbox immutable'); END;
CREATE TRIGGER wait_inbox_delete BEFORE DELETE ON orchestration_wait_inbox BEGIN SELECT RAISE(ABORT,'wait inbox immutable'); END;
CREATE TRIGGER wait_resolution_update BEFORE UPDATE ON orchestration_wait_resolution BEGIN SELECT RAISE(ABORT,'wait resolution immutable'); END;
CREATE TRIGGER wait_resolution_delete BEFORE DELETE ON orchestration_wait_resolution BEGIN SELECT RAISE(ABORT,'wait resolution immutable'); END;
CREATE TRIGGER wait_cursor_update BEFORE UPDATE ON orchestration_inbox_cursor BEGIN SELECT RAISE(ABORT,'wait cursor immutable'); END;
CREATE TRIGGER wait_cursor_delete BEFORE DELETE ON orchestration_inbox_cursor BEGIN SELECT RAISE(ABORT,'wait cursor immutable'); END;
CREATE TRIGGER wait_seal_update BEFORE UPDATE ON orchestration_checkpoint_final_seal BEGIN SELECT RAISE(ABORT,'checkpoint seal immutable'); END;
CREATE TRIGGER wait_seal_delete BEFORE DELETE ON orchestration_checkpoint_final_seal BEGIN SELECT RAISE(ABORT,'checkpoint seal immutable'); END;
CREATE TRIGGER wait_dispatch_update BEFORE UPDATE ON orchestration_wait_dispatch_claim BEGIN SELECT RAISE(ABORT,'wait dispatch immutable'); END;
CREATE TRIGGER wait_dispatch_delete BEFORE DELETE ON orchestration_wait_dispatch_claim BEGIN SELECT RAISE(ABORT,'wait dispatch immutable'); END;
CREATE TRIGGER wait_delivery_update BEFORE UPDATE ON orchestration_wait_delivery_observation BEGIN SELECT RAISE(ABORT,'wait delivery immutable'); END;
CREATE TRIGGER wait_delivery_delete BEFORE DELETE ON orchestration_wait_delivery_observation BEGIN SELECT RAISE(ABORT,'wait delivery immutable'); END;
