CREATE TABLE IF NOT EXISTS orchestration_recovery_migration(singleton INTEGER PRIMARY KEY CHECK(singleton=1),version TEXT NOT NULL CHECK(version='cue-recovery-revision-v1'));
CREATE TABLE IF NOT EXISTS orchestration_recovery_legacy(run_id TEXT PRIMARY KEY REFERENCES run(id),reason TEXT NOT NULL CHECK(reason='legacy-recovery-scope-unavailable'));
INSERT INTO orchestration_recovery_legacy SELECT id,'legacy-recovery-scope-unavailable' FROM run WHERE NOT EXISTS(SELECT 1 FROM orchestration_recovery_migration);
INSERT INTO orchestration_recovery_migration SELECT 1,'cue-recovery-revision-v1' WHERE NOT EXISTS(SELECT 1 FROM orchestration_recovery_migration);

CREATE TABLE IF NOT EXISTS orchestration_recovery_scope(
 run_id TEXT PRIMARY KEY REFERENCES run(id),envelope_hash TEXT NOT NULL REFERENCES envelope(envelope_hash),approval_id INTEGER NOT NULL REFERENCES approval_event(id),
 policy_digest TEXT NOT NULL,requirements_digest TEXT NOT NULL,original_plan_digest TEXT NOT NULL,budget_kind TEXT NOT NULL CHECK(budget_kind IN('monetary','local-invocation')),
 budget_identity TEXT NOT NULL,max_attempts_total INTEGER NOT NULL CHECK(max_attempts_total BETWEEN 1 AND 2048),deadline_ms INTEGER NOT NULL CHECK(deadline_ms>=0),
 payload_sha256 TEXT NOT NULL CHECK(length(payload_sha256)=64),payload BLOB NOT NULL CHECK(typeof(payload)='blob' AND length(payload) BETWEEN 1 AND 1048576));
CREATE TABLE IF NOT EXISTS orchestration_failure_observation(
 observation_id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES orchestration_recovery_scope(run_id),attempt_id TEXT NOT NULL REFERENCES orchestration_attempt(attempt_id),
 receipt_id TEXT NOT NULL REFERENCES orchestration_receipt(receipt_id),handoff_id TEXT NOT NULL REFERENCES orchestration_handoff(handoff_id),
 cause TEXT NOT NULL CHECK(cause IN('transient','authentication','quota','capability-mismatch','quality-failure','policy-violation','unknown')),
 observed_at_ms INTEGER NOT NULL CHECK(observed_at_ms>=0),payload_sha256 TEXT NOT NULL CHECK(length(payload_sha256)=64),payload BLOB NOT NULL CHECK(typeof(payload)='blob' AND length(payload) BETWEEN 1 AND 1048576),UNIQUE(attempt_id));
CREATE TABLE IF NOT EXISTS orchestration_recovery_decision(
 decision_id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES orchestration_recovery_scope(run_id),observation_id TEXT NOT NULL UNIQUE REFERENCES orchestration_failure_observation(observation_id),
 prior_attempt_id TEXT NOT NULL UNIQUE REFERENCES orchestration_attempt(attempt_id),action TEXT NOT NULL CHECK(action IN('retry','switch','replan','stop')),
 source_revision INTEGER NOT NULL CHECK(source_revision>=0),destination_revision INTEGER CHECK(destination_revision>=0),selected_candidate_id TEXT,
 digest TEXT NOT NULL CHECK(length(digest)=64),payload BLOB NOT NULL CHECK(typeof(payload)='blob' AND length(payload) BETWEEN 1 AND 1048576),
 CHECK((action='stop' AND destination_revision IS NULL AND selected_candidate_id IS NULL) OR (action='retry' AND destination_revision=source_revision AND selected_candidate_id IS NULL) OR (action='switch' AND destination_revision=source_revision AND selected_candidate_id IS NOT NULL) OR (action='replan' AND destination_revision=source_revision+1 AND selected_candidate_id IS NULL)));
CREATE TABLE IF NOT EXISTS orchestration_plan_revision(
 run_id TEXT NOT NULL REFERENCES orchestration_recovery_scope(run_id),revision INTEGER NOT NULL CHECK(revision>=0),parent_revision INTEGER,parent_digest TEXT,decision_id TEXT UNIQUE REFERENCES orchestration_recovery_decision(decision_id),
 plan_digest TEXT NOT NULL CHECK(length(plan_digest)=64),requirements_digest TEXT NOT NULL,policy_digest TEXT NOT NULL,envelope_hash TEXT NOT NULL,
 created_at_ms INTEGER NOT NULL CHECK(created_at_ms>=0),payload BLOB NOT NULL CHECK(typeof(payload)='blob' AND length(payload) BETWEEN 1 AND 1048576),PRIMARY KEY(run_id,revision),UNIQUE(run_id,plan_digest),
 CHECK((revision=0 AND parent_revision IS NULL AND parent_digest IS NULL AND decision_id IS NULL) OR (revision>0 AND parent_revision=revision-1 AND parent_digest IS NOT NULL AND decision_id IS NOT NULL)));
CREATE TABLE IF NOT EXISTS orchestration_revision_step(
 run_id TEXT NOT NULL,revision INTEGER NOT NULL,task_id TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN('pending','running','completed','failed','blocked','superseded')),
 payload_sha256 TEXT NOT NULL CHECK(length(payload_sha256)=64),payload BLOB NOT NULL CHECK(typeof(payload)='blob' AND length(payload) BETWEEN 1 AND 262144),PRIMARY KEY(run_id,revision,task_id),FOREIGN KEY(run_id,revision) REFERENCES orchestration_plan_revision(run_id,revision));
CREATE TABLE IF NOT EXISTS orchestration_attempt_revision(
 attempt_id TEXT PRIMARY KEY REFERENCES orchestration_attempt(attempt_id),run_id TEXT NOT NULL,revision INTEGER NOT NULL,task_id TEXT NOT NULL,
 FOREIGN KEY(run_id,revision,task_id) REFERENCES orchestration_revision_step(run_id,revision,task_id));
CREATE TABLE IF NOT EXISTS orchestration_recovery_activation(
 decision_id TEXT PRIMARY KEY REFERENCES orchestration_recovery_decision(decision_id),attempt_id TEXT NOT NULL UNIQUE REFERENCES orchestration_attempt(attempt_id),
 run_id TEXT NOT NULL,revision INTEGER NOT NULL,task_id TEXT NOT NULL,candidate_id TEXT NOT NULL,
 FOREIGN KEY(run_id,revision,task_id) REFERENCES orchestration_revision_step(run_id,revision,task_id));

CREATE TRIGGER recovery_scope_hash BEFORE INSERT ON orchestration_recovery_scope WHEN cue_sha256(NEW.payload)<>NEW.payload_sha256 BEGIN SELECT RAISE(ABORT,'recovery scope hash mismatch'); END;
CREATE TRIGGER recovery_scope_payload BEFORE INSERT ON orchestration_recovery_scope WHEN json_valid(NEW.payload)<>1 OR json_extract(NEW.payload,'$.schemaVersion')<>'cue-recovery-scope-v1' OR json_extract(NEW.payload,'$.runId')<>NEW.run_id OR json_extract(NEW.payload,'$.approvalId')<>NEW.approval_id OR json_extract(NEW.payload,'$.envelopeHash')<>NEW.envelope_hash OR json_extract(NEW.payload,'$.policyDigest')<>NEW.policy_digest OR json_extract(NEW.payload,'$.requirementsDigest')<>NEW.requirements_digest OR json_extract(NEW.payload,'$.originalPlanDigest')<>NEW.original_plan_digest OR json_extract(NEW.payload,'$.budgetKind')<>NEW.budget_kind OR json_extract(NEW.payload,'$.budgetIdentity')<>NEW.budget_identity OR json_extract(NEW.payload,'$.maxAttemptsTotal')<>NEW.max_attempts_total OR json_extract(NEW.payload,'$.deadlineMs')<>NEW.deadline_ms BEGIN SELECT RAISE(ABORT,'recovery scope payload mismatch'); END;
CREATE TRIGGER recovery_scope_budget BEFORE INSERT ON orchestration_recovery_scope WHEN NEW.budget_identity<>NEW.run_id OR (NEW.budget_kind='monetary' AND NOT EXISTS(SELECT 1 FROM integration_budget WHERE run_id=NEW.run_id)) OR (NEW.budget_kind='local-invocation' AND NOT EXISTS(SELECT 1 FROM local_invocation_budget WHERE run_id=NEW.run_id)) BEGIN SELECT RAISE(ABORT,'recovery original budget required'); END;
CREATE TRIGGER recovery_scope_contract BEFORE INSERT ON orchestration_recovery_scope WHEN NOT EXISTS(SELECT 1 FROM orchestration_retry_contract c JOIN requirement_contract_binding q ON q.run_id=c.run_id JOIN orchestration_plan p ON p.run_id=c.run_id WHERE c.run_id=NEW.run_id AND q.requirements_digest=NEW.requirements_digest AND q.policy_digest=NEW.policy_digest AND p.digest=NEW.original_plan_digest) BEGIN SELECT RAISE(ABORT,'recovery original contract required'); END;
CREATE TRIGGER failure_observation_hash BEFORE INSERT ON orchestration_failure_observation WHEN cue_sha256(NEW.payload)<>NEW.payload_sha256 BEGIN SELECT RAISE(ABORT,'failure observation hash mismatch'); END;
CREATE TRIGGER failure_observation_payload BEFORE INSERT ON orchestration_failure_observation WHEN json_valid(NEW.payload)<>1 OR json_extract(NEW.payload,'$.schemaVersion')<>'cue-failure-observation-v1' OR json_extract(NEW.payload,'$.observationId')<>NEW.observation_id OR json_extract(NEW.payload,'$.runId')<>NEW.run_id OR json_extract(NEW.payload,'$.attemptId')<>NEW.attempt_id OR json_extract(NEW.payload,'$.receiptId')<>NEW.receipt_id OR json_extract(NEW.payload,'$.handoffId')<>NEW.handoff_id OR json_extract(NEW.payload,'$.cause')<>NEW.cause OR json_extract(NEW.payload,'$.observedAtMs')<>NEW.observed_at_ms BEGIN SELECT RAISE(ABORT,'failure observation payload mismatch'); END;
CREATE TRIGGER failure_observation_lineage BEFORE INSERT ON orchestration_failure_observation WHEN NOT EXISTS(SELECT 1 FROM orchestration_attempt a JOIN orchestration_receipt r ON r.receipt_id=NEW.receipt_id AND r.attempt_id=a.attempt_id JOIN orchestration_handoff h ON h.handoff_id=NEW.handoff_id AND h.attempt_id=a.attempt_id AND h.receipt_id=r.receipt_id WHERE a.attempt_id=NEW.attempt_id AND a.run_id=NEW.run_id AND a.state='failed' AND a.cleanup_verified=1) BEGIN SELECT RAISE(ABORT,'failure observation lineage mismatch'); END;
CREATE TRIGGER recovery_decision_hash BEFORE INSERT ON orchestration_recovery_decision WHEN cue_sha256(NEW.payload)<>NEW.digest BEGIN SELECT RAISE(ABORT,'recovery decision hash mismatch'); END;
CREATE TRIGGER recovery_decision_payload BEFORE INSERT ON orchestration_recovery_decision WHEN json_valid(NEW.payload)<>1 OR json_extract(NEW.payload,'$.schemaVersion')<>'cue-recovery-decision-v1' OR json_extract(NEW.payload,'$.decisionId')<>NEW.decision_id OR json_extract(NEW.payload,'$.observationId')<>NEW.observation_id OR json_extract(NEW.payload,'$.runId')<>NEW.run_id OR json_extract(NEW.payload,'$.priorAttemptId')<>NEW.prior_attempt_id OR json_extract(NEW.payload,'$.action')<>NEW.action OR json_extract(NEW.payload,'$.sourceRevision')<>NEW.source_revision OR NOT (json_extract(NEW.payload,'$.destinationRevision') IS NEW.destination_revision) OR NOT (json_extract(NEW.payload,'$.selectedCandidateId') IS NEW.selected_candidate_id) BEGIN SELECT RAISE(ABORT,'recovery decision payload mismatch'); END;
CREATE TRIGGER recovery_revision_hash BEFORE INSERT ON orchestration_plan_revision WHEN cue_sha256(NEW.payload)<>NEW.plan_digest BEGIN SELECT RAISE(ABORT,'recovery revision hash mismatch'); END;
CREATE TRIGGER recovery_revision_scope BEFORE INSERT ON orchestration_plan_revision WHEN NOT EXISTS(SELECT 1 FROM orchestration_recovery_scope s WHERE s.run_id=NEW.run_id AND s.requirements_digest=NEW.requirements_digest AND s.policy_digest=NEW.policy_digest AND s.envelope_hash=NEW.envelope_hash AND (NEW.revision<>0 OR s.original_plan_digest=NEW.plan_digest)) BEGIN SELECT RAISE(ABORT,'recovery revision scope mismatch'); END;
CREATE TRIGGER recovery_step_hash BEFORE INSERT ON orchestration_revision_step WHEN cue_sha256(NEW.payload)<>NEW.payload_sha256 BEGIN SELECT RAISE(ABORT,'recovery step hash mismatch'); END;
CREATE TRIGGER recovery_revision_parent BEFORE INSERT ON orchestration_plan_revision WHEN NEW.revision>0 AND NOT EXISTS(SELECT 1 FROM orchestration_plan_revision p JOIN orchestration_recovery_decision d ON d.decision_id=NEW.decision_id WHERE p.run_id=NEW.run_id AND p.revision=NEW.parent_revision AND p.plan_digest=NEW.parent_digest AND d.run_id=NEW.run_id AND d.action='replan' AND d.source_revision=NEW.parent_revision AND d.destination_revision=NEW.revision) BEGIN SELECT RAISE(ABORT,'recovery revision parent mismatch'); END;
CREATE TRIGGER recovery_attempt_current BEFORE INSERT ON orchestration_attempt_revision WHEN NOT EXISTS(SELECT 1 FROM orchestration_revision_step s JOIN orchestration_attempt a ON a.attempt_id=NEW.attempt_id AND a.run_id=NEW.run_id AND a.task_id=NEW.task_id WHERE s.run_id=NEW.run_id AND s.revision=NEW.revision AND s.task_id=NEW.task_id AND s.state='running') BEGIN SELECT RAISE(ABORT,'attempt revision not current'); END;
CREATE TRIGGER recovery_decision_terminal BEFORE INSERT ON orchestration_recovery_decision WHEN NOT EXISTS(SELECT 1 FROM orchestration_failure_observation o JOIN orchestration_attempt a ON a.attempt_id=o.attempt_id JOIN orchestration_handoff h ON h.handoff_id=o.handoff_id AND h.attempt_id=a.attempt_id WHERE o.observation_id=NEW.observation_id AND o.run_id=NEW.run_id AND o.attempt_id=NEW.prior_attempt_id AND a.state='failed' AND a.cleanup_verified=1) BEGIN SELECT RAISE(ABORT,'recovery decision requires verified terminal failure'); END;
CREATE TRIGGER recovery_decision_sealed BEFORE INSERT ON orchestration_recovery_decision WHEN EXISTS(SELECT 1 FROM orchestration_recovery_decision WHERE run_id=NEW.run_id AND action='stop') BEGIN SELECT RAISE(ABORT,'recovery run sealed'); END;
CREATE TRIGGER recovery_decision_current BEFORE INSERT ON orchestration_recovery_decision WHEN NEW.source_revision<>(SELECT COALESCE(MAX(revision),-1) FROM orchestration_plan_revision WHERE run_id=NEW.run_id) BEGIN SELECT RAISE(ABORT,'recovery source revision not current'); END;
CREATE TRIGGER recovery_activation_contract BEFORE INSERT ON orchestration_recovery_activation WHEN NOT EXISTS(
 SELECT 1 FROM orchestration_recovery_decision d JOIN orchestration_attempt prior ON prior.attempt_id=d.prior_attempt_id
 JOIN orchestration_attempt next ON next.attempt_id=NEW.attempt_id AND next.run_id=NEW.run_id AND next.task_id=NEW.task_id AND next.candidate_id=NEW.candidate_id
 WHERE d.decision_id=NEW.decision_id AND d.run_id=NEW.run_id AND d.destination_revision=NEW.revision
 AND ((d.action='retry' AND prior.task_id=NEW.task_id AND NEW.candidate_id=prior.candidate_id) OR (d.action='switch' AND prior.task_id=NEW.task_id AND NEW.candidate_id=d.selected_candidate_id) OR d.action='replan'))
 BEGIN SELECT RAISE(ABORT,'recovery activation mismatch'); END;

CREATE TRIGGER recovery_legacy_closed BEFORE INSERT ON orchestration_recovery_legacy BEGIN SELECT RAISE(ABORT,'recovery legacy membership closed'); END;
CREATE TRIGGER recovery_migration_replace BEFORE INSERT ON orchestration_recovery_migration WHEN EXISTS(SELECT 1 FROM orchestration_recovery_migration) BEGIN SELECT RAISE(ABORT,'recovery migration immutable'); END;
CREATE TRIGGER recovery_scope_replace BEFORE INSERT ON orchestration_recovery_scope WHEN EXISTS(SELECT 1 FROM orchestration_recovery_scope WHERE run_id=NEW.run_id) BEGIN SELECT RAISE(ABORT,'recovery scope immutable'); END;
CREATE TRIGGER failure_observation_replace BEFORE INSERT ON orchestration_failure_observation WHEN EXISTS(SELECT 1 FROM orchestration_failure_observation WHERE observation_id=NEW.observation_id OR attempt_id=NEW.attempt_id) BEGIN SELECT RAISE(ABORT,'failure observation immutable'); END;
CREATE TRIGGER recovery_decision_replace BEFORE INSERT ON orchestration_recovery_decision WHEN EXISTS(SELECT 1 FROM orchestration_recovery_decision WHERE decision_id=NEW.decision_id OR observation_id=NEW.observation_id OR prior_attempt_id=NEW.prior_attempt_id) BEGIN SELECT RAISE(ABORT,'recovery decision immutable'); END;
CREATE TRIGGER recovery_revision_replace BEFORE INSERT ON orchestration_plan_revision WHEN EXISTS(SELECT 1 FROM orchestration_plan_revision WHERE (run_id=NEW.run_id AND revision=NEW.revision) OR decision_id=NEW.decision_id) BEGIN SELECT RAISE(ABORT,'recovery revision immutable'); END;
CREATE TRIGGER recovery_step_replace BEFORE INSERT ON orchestration_revision_step WHEN EXISTS(SELECT 1 FROM orchestration_revision_step WHERE run_id=NEW.run_id AND revision=NEW.revision AND task_id=NEW.task_id) BEGIN SELECT RAISE(ABORT,'recovery revision step immutable'); END;
CREATE TRIGGER recovery_attempt_revision_replace BEFORE INSERT ON orchestration_attempt_revision WHEN EXISTS(SELECT 1 FROM orchestration_attempt_revision WHERE attempt_id=NEW.attempt_id) BEGIN SELECT RAISE(ABORT,'attempt revision immutable'); END;
CREATE TRIGGER recovery_activation_replace BEFORE INSERT ON orchestration_recovery_activation WHEN EXISTS(SELECT 1 FROM orchestration_recovery_activation WHERE decision_id=NEW.decision_id OR attempt_id=NEW.attempt_id) BEGIN SELECT RAISE(ABORT,'recovery activation immutable'); END;

CREATE TRIGGER recovery_legacy_update BEFORE UPDATE ON orchestration_recovery_legacy BEGIN SELECT RAISE(ABORT,'recovery legacy immutable'); END;
CREATE TRIGGER recovery_legacy_delete BEFORE DELETE ON orchestration_recovery_legacy BEGIN SELECT RAISE(ABORT,'recovery legacy immutable'); END;
CREATE TRIGGER recovery_migration_update BEFORE UPDATE ON orchestration_recovery_migration BEGIN SELECT RAISE(ABORT,'recovery migration immutable'); END;
CREATE TRIGGER recovery_migration_delete BEFORE DELETE ON orchestration_recovery_migration BEGIN SELECT RAISE(ABORT,'recovery migration immutable'); END;
CREATE TRIGGER recovery_scope_update BEFORE UPDATE ON orchestration_recovery_scope BEGIN SELECT RAISE(ABORT,'recovery scope immutable'); END;
CREATE TRIGGER recovery_scope_delete BEFORE DELETE ON orchestration_recovery_scope BEGIN SELECT RAISE(ABORT,'recovery scope immutable'); END;
CREATE TRIGGER failure_observation_update BEFORE UPDATE ON orchestration_failure_observation BEGIN SELECT RAISE(ABORT,'failure observation immutable'); END;
CREATE TRIGGER failure_observation_delete BEFORE DELETE ON orchestration_failure_observation BEGIN SELECT RAISE(ABORT,'failure observation immutable'); END;
CREATE TRIGGER recovery_decision_update BEFORE UPDATE ON orchestration_recovery_decision BEGIN SELECT RAISE(ABORT,'recovery decision immutable'); END;
CREATE TRIGGER recovery_decision_delete BEFORE DELETE ON orchestration_recovery_decision BEGIN SELECT RAISE(ABORT,'recovery decision immutable'); END;
CREATE TRIGGER recovery_revision_update BEFORE UPDATE ON orchestration_plan_revision BEGIN SELECT RAISE(ABORT,'recovery revision immutable'); END;
CREATE TRIGGER recovery_revision_delete BEFORE DELETE ON orchestration_plan_revision BEGIN SELECT RAISE(ABORT,'recovery revision immutable'); END;
CREATE TRIGGER recovery_step_update BEFORE UPDATE OF run_id,revision,task_id,payload_sha256,payload ON orchestration_revision_step BEGIN SELECT RAISE(ABORT,'recovery revision step immutable'); END;
CREATE TRIGGER recovery_step_delete BEFORE DELETE ON orchestration_revision_step BEGIN SELECT RAISE(ABORT,'recovery revision step immutable'); END;
CREATE TRIGGER recovery_attempt_revision_update BEFORE UPDATE ON orchestration_attempt_revision BEGIN SELECT RAISE(ABORT,'attempt revision immutable'); END;
CREATE TRIGGER recovery_attempt_revision_delete BEFORE DELETE ON orchestration_attempt_revision BEGIN SELECT RAISE(ABORT,'attempt revision immutable'); END;
CREATE TRIGGER recovery_activation_update BEFORE UPDATE ON orchestration_recovery_activation BEGIN SELECT RAISE(ABORT,'recovery activation immutable'); END;
CREATE TRIGGER recovery_activation_delete BEFORE DELETE ON orchestration_recovery_activation BEGIN SELECT RAISE(ABORT,'recovery activation immutable'); END;
