CREATE TABLE IF NOT EXISTS change_recovery_migration(singleton INTEGER PRIMARY KEY CHECK(singleton=1),version TEXT NOT NULL CHECK(version='cue-change-recovery-v1'));
CREATE TABLE IF NOT EXISTS change_recovery_legacy(attempt_id TEXT PRIMARY KEY REFERENCES orchestration_attempt(attempt_id),reason TEXT NOT NULL CHECK(reason='legacy-change-recovery-unavailable'));
INSERT INTO change_recovery_legacy SELECT attempt_id,'legacy-change-recovery-unavailable' FROM orchestration_attempt WHERE state IN('running','blocked') AND NOT EXISTS(SELECT 1 FROM change_recovery_migration);
INSERT INTO change_recovery_migration SELECT 1,'cue-change-recovery-v1' WHERE NOT EXISTS(SELECT 1 FROM change_recovery_migration);

CREATE TABLE IF NOT EXISTS change_target_contract(run_id TEXT NOT NULL,task_id TEXT NOT NULL,target_id TEXT NOT NULL,relative_path TEXT NOT NULL,max_backup_bytes INTEGER NOT NULL CHECK(max_backup_bytes>=0),PRIMARY KEY(run_id,task_id,target_id),UNIQUE(run_id,task_id,relative_path),FOREIGN KEY(run_id,task_id) REFERENCES orchestration_step(run_id,task_id));
CREATE TRIGGER change_target_before_attempt BEFORE INSERT ON change_target_contract WHEN EXISTS(SELECT 1 FROM orchestration_attempt WHERE run_id=NEW.run_id) OR EXISTS(SELECT 1 FROM approval_event WHERE run_id=NEW.run_id AND decision='accept') BEGIN SELECT RAISE(ABORT,'change target contract too late'); END;
CREATE TRIGGER change_target_update BEFORE UPDATE ON change_target_contract BEGIN SELECT RAISE(ABORT,'change target contract immutable'); END;
CREATE TRIGGER change_target_delete BEFORE DELETE ON change_target_contract BEGIN SELECT RAISE(ABORT,'change target contract immutable'); END;

CREATE TABLE IF NOT EXISTS change_set(
 change_set_id TEXT PRIMARY KEY,run_id TEXT NOT NULL,task_id TEXT NOT NULL,attempt_id TEXT NOT NULL UNIQUE REFERENCES orchestration_attempt(attempt_id),
 stage_envelope_hash TEXT NOT NULL REFERENCES envelope(envelope_hash),launch_intent_id TEXT NOT NULL UNIQUE REFERENCES orchestration_launch_intent(attempt_id),
 worktree_realpath TEXT NOT NULL,approved_targets_json TEXT NOT NULL CHECK(json_valid(approved_targets_json)),scan_limits_json TEXT NOT NULL CHECK(json_valid(scan_limits_json)),
 preimage_manifest_digest TEXT NOT NULL CHECK(length(preimage_manifest_digest)=64),created_at_ms INTEGER NOT NULL CHECK(created_at_ms>=0),
 payload_sha256 TEXT NOT NULL CHECK(length(payload_sha256)=64),payload BLOB NOT NULL CHECK(typeof(payload)='blob' AND length(payload) BETWEEN 1 AND 1048576));
CREATE TABLE IF NOT EXISTS change_entry(
 change_set_id TEXT NOT NULL REFERENCES change_set(change_set_id),ordinal INTEGER NOT NULL CHECK(ordinal>=0),relative_path TEXT NOT NULL,
 object_kind TEXT NOT NULL CHECK(object_kind IN('absent','file','directory','symlink','reparse','other','unknown')),canonical_parent TEXT NOT NULL,
 canonical_realpath TEXT,file_identity TEXT,byte_length INTEGER CHECK(byte_length IS NULL OR byte_length>=0),sha256 TEXT CHECK(sha256 IS NULL OR length(sha256)=64),
 restorable INTEGER NOT NULL CHECK(restorable IN(0,1)),restorable_reason TEXT NOT NULL,preimage BLOB,
 payload_sha256 TEXT NOT NULL CHECK(length(payload_sha256)=64),payload BLOB NOT NULL CHECK(typeof(payload)='blob' AND length(payload) BETWEEN 1 AND 1048576),
 PRIMARY KEY(change_set_id,ordinal),UNIQUE(change_set_id,relative_path),CHECK((restorable=1 AND object_kind IN('absent','file') AND (object_kind='absent' OR preimage IS NOT NULL)) OR restorable=0));
CREATE TABLE IF NOT EXISTS change_observation(
 observation_id TEXT PRIMARY KEY,change_set_id TEXT NOT NULL REFERENCES change_set(change_set_id),ordinal INTEGER NOT NULL,
 status TEXT NOT NULL CHECK(status IN('unchanged','created','modified','deleted','moved','type-changed','outside-manifest','unknown')),
 object_kind TEXT NOT NULL CHECK(object_kind IN('absent','file','directory','symlink','reparse','other','unknown')),canonical_parent TEXT NOT NULL,
 canonical_realpath TEXT,file_identity TEXT,byte_length INTEGER CHECK(byte_length IS NULL OR byte_length>=0),sha256 TEXT CHECK(sha256 IS NULL OR length(sha256)=64),observed_bytes BLOB,
 observed_at_ms INTEGER NOT NULL CHECK(observed_at_ms>=0),payload_sha256 TEXT NOT NULL CHECK(length(payload_sha256)=64),payload BLOB NOT NULL CHECK(typeof(payload)='blob' AND length(payload) BETWEEN 1 AND 1048576),
 FOREIGN KEY(change_set_id,ordinal) REFERENCES change_entry(change_set_id,ordinal),UNIQUE(change_set_id,ordinal,observed_at_ms));
CREATE TABLE IF NOT EXISTS external_effect_intent(
 intent_id TEXT PRIMARY KEY,attempt_id TEXT NOT NULL REFERENCES orchestration_attempt(attempt_id),operation TEXT NOT NULL,account_id TEXT NOT NULL,resource_id TEXT NOT NULL,
 idempotency_key TEXT NOT NULL UNIQUE,expected_transition_digest TEXT NOT NULL CHECK(length(expected_transition_digest)=64),created_at_ms INTEGER NOT NULL CHECK(created_at_ms>=0),
 payload_sha256 TEXT NOT NULL CHECK(length(payload_sha256)=64),payload BLOB NOT NULL CHECK(typeof(payload)='blob' AND length(payload) BETWEEN 1 AND 1048576));
CREATE TABLE IF NOT EXISTS external_effect_observation(
 observation_id TEXT PRIMARY KEY,intent_id TEXT NOT NULL REFERENCES external_effect_intent(intent_id),status TEXT NOT NULL CHECK(status IN('confirmed-applied','confirmed-not-applied','unknown')),
 observer_id TEXT NOT NULL,observer_revision TEXT NOT NULL,observed_at_ms INTEGER NOT NULL CHECK(observed_at_ms>=0),payload_sha256 TEXT NOT NULL CHECK(length(payload_sha256)=64),
 payload BLOB NOT NULL CHECK(typeof(payload)='blob' AND length(payload) BETWEEN 1 AND 1048576));
CREATE TABLE IF NOT EXISTS held_recovery(
 case_id TEXT PRIMARY KEY,attempt_id TEXT NOT NULL UNIQUE REFERENCES orchestration_attempt(attempt_id),change_set_id TEXT REFERENCES change_set(change_set_id),
 state TEXT NOT NULL CHECK(state IN('held','reconciled-stop','eligible-for-disposition')),revision INTEGER NOT NULL DEFAULT 0 CHECK(revision>=0),reason TEXT NOT NULL,
 final_seal TEXT CHECK(final_seal IS NULL OR length(final_seal)=64),updated_at_ms INTEGER NOT NULL CHECK(updated_at_ms>=0),payload_sha256 TEXT NOT NULL CHECK(length(payload_sha256)=64),
 payload BLOB NOT NULL CHECK(typeof(payload)='blob' AND length(payload) BETWEEN 1 AND 1048576));
CREATE TABLE IF NOT EXISTS held_recovery_transition(
 case_id TEXT NOT NULL REFERENCES held_recovery(case_id),revision INTEGER NOT NULL CHECK(revision>=0),from_state TEXT,to_state TEXT NOT NULL,
 reason TEXT NOT NULL,observed_at_ms INTEGER NOT NULL CHECK(observed_at_ms>=0),payload_sha256 TEXT NOT NULL CHECK(length(payload_sha256)=64),
 payload BLOB NOT NULL CHECK(typeof(payload)='blob' AND length(payload) BETWEEN 1 AND 1048576),PRIMARY KEY(case_id,revision));
CREATE TABLE IF NOT EXISTS integration_verification_result(
 result_id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES run(id),attempt_id TEXT NOT NULL UNIQUE REFERENCES orchestration_attempt(attempt_id),revision INTEGER NOT NULL CHECK(revision>=0),
 verdict TEXT NOT NULL CHECK(verdict IN('pass','fail','unknown')),checker_revision TEXT NOT NULL,created_at_ms INTEGER NOT NULL CHECK(created_at_ms>=0),
 payload_sha256 TEXT NOT NULL CHECK(length(payload_sha256)=64),payload BLOB NOT NULL CHECK(typeof(payload)='blob' AND length(payload) BETWEEN 1 AND 1048576));

CREATE TRIGGER change_set_hash BEFORE INSERT ON change_set WHEN cue_sha256(NEW.payload)<>NEW.payload_sha256 OR cue_sha256(NEW.approved_targets_json) IS NULL BEGIN SELECT RAISE(ABORT,'change set hash mismatch'); END;
CREATE TRIGGER change_set_payload BEFORE INSERT ON change_set WHEN json_extract(NEW.payload,'$.changeSetId')<>NEW.change_set_id OR json_extract(NEW.payload,'$.runId')<>NEW.run_id OR json_extract(NEW.payload,'$.taskId')<>NEW.task_id OR json_extract(NEW.payload,'$.attemptId')<>NEW.attempt_id OR json_extract(NEW.payload,'$.stageEnvelopeHash')<>NEW.stage_envelope_hash OR json_extract(NEW.payload,'$.launchIntentId')<>NEW.launch_intent_id OR json_extract(NEW.payload,'$.worktreeRealpath')<>NEW.worktree_realpath OR json_extract(NEW.payload,'$.preimageManifestDigest')<>NEW.preimage_manifest_digest OR json(NEW.approved_targets_json)<>json_extract(NEW.payload,'$.targets') OR json(NEW.scan_limits_json)<>json_extract(NEW.payload,'$.limits') OR json_extract(NEW.payload,'$.createdAtMs')<>NEW.created_at_ms BEGIN SELECT RAISE(ABORT,'change set payload mismatch'); END;
CREATE TRIGGER change_set_lineage BEFORE INSERT ON change_set WHEN NOT EXISTS(SELECT 1 FROM orchestration_attempt a JOIN orchestration_stage_envelope s ON s.attempt_id=a.attempt_id JOIN orchestration_launch_intent l ON l.attempt_id=NEW.launch_intent_id AND l.attempt_id=a.attempt_id JOIN workspace_write_lease w ON w.run_id=a.run_id AND lower(w.worktree_realpath)=lower(NEW.worktree_realpath) WHERE a.attempt_id=NEW.attempt_id AND a.run_id=NEW.run_id AND a.task_id=NEW.task_id AND a.state='running' AND s.stage_envelope_hash=NEW.stage_envelope_hash) BEGIN SELECT RAISE(ABORT,'change set launch authority mismatch'); END;
CREATE TRIGGER change_set_targets BEFORE INSERT ON change_set WHEN (SELECT COUNT(*) FROM change_target_contract WHERE run_id=NEW.run_id AND task_id=NEW.task_id)=0 OR (SELECT COUNT(*) FROM json_each(NEW.approved_targets_json))<>(SELECT COUNT(*) FROM change_target_contract WHERE run_id=NEW.run_id AND task_id=NEW.task_id) OR EXISTS(SELECT 1 FROM json_each(NEW.approved_targets_json) j WHERE NOT EXISTS(SELECT 1 FROM change_target_contract c WHERE c.run_id=NEW.run_id AND c.task_id=NEW.task_id AND lower(c.relative_path)=lower(j.value))) BEGIN SELECT RAISE(ABORT,'change targets not preapproved'); END;
CREATE TRIGGER change_entry_hash BEFORE INSERT ON change_entry WHEN cue_sha256(NEW.payload)<>NEW.payload_sha256 OR (NEW.preimage IS NOT NULL AND NEW.sha256<>cue_sha256(NEW.preimage)) BEGIN SELECT RAISE(ABORT,'change entry hash mismatch'); END;
CREATE TRIGGER change_entry_payload BEFORE INSERT ON change_entry WHEN json_extract(NEW.payload,'$.relativePath')<>NEW.relative_path OR json_extract(NEW.payload,'$.objectKind')<>NEW.object_kind OR json_extract(NEW.payload,'$.canonicalParent')<>NEW.canonical_parent OR NOT(json_extract(NEW.payload,'$.canonicalRealpath') IS NEW.canonical_realpath) OR NOT(json_extract(NEW.payload,'$.fileIdentity') IS NEW.file_identity) OR NOT(json_extract(NEW.payload,'$.byteLength') IS NEW.byte_length) OR NOT(json_extract(NEW.payload,'$.sha256') IS NEW.sha256) OR json_extract(NEW.payload,'$.restorable')<>NEW.restorable OR json_extract(NEW.payload,'$.restorableReason')<>NEW.restorable_reason BEGIN SELECT RAISE(ABORT,'change entry payload mismatch'); END;
CREATE TRIGGER change_observation_hash BEFORE INSERT ON change_observation WHEN cue_sha256(NEW.payload)<>NEW.payload_sha256 OR (NEW.observed_bytes IS NOT NULL AND NEW.sha256<>cue_sha256(NEW.observed_bytes)) BEGIN SELECT RAISE(ABORT,'change observation hash mismatch'); END;
CREATE TRIGGER change_observation_payload BEFORE INSERT ON change_observation WHEN json_extract(NEW.payload,'$.observationId')<>NEW.observation_id OR json_extract(NEW.payload,'$.changeSetId')<>NEW.change_set_id OR json_extract(NEW.payload,'$.ordinal')<>NEW.ordinal OR json_extract(NEW.payload,'$.status')<>NEW.status OR json_extract(NEW.payload,'$.objectKind')<>NEW.object_kind OR json_extract(NEW.payload,'$.canonicalParent')<>NEW.canonical_parent OR NOT(json_extract(NEW.payload,'$.canonicalRealpath') IS NEW.canonical_realpath) OR NOT(json_extract(NEW.payload,'$.fileIdentity') IS NEW.file_identity) OR NOT(json_extract(NEW.payload,'$.byteLength') IS NEW.byte_length) OR NOT(json_extract(NEW.payload,'$.sha256') IS NEW.sha256) OR json_extract(NEW.payload,'$.observedAtMs')<>NEW.observed_at_ms BEGIN SELECT RAISE(ABORT,'change observation payload mismatch'); END;
CREATE TRIGGER external_intent_hash BEFORE INSERT ON external_effect_intent WHEN cue_sha256(NEW.payload)<>NEW.payload_sha256 BEGIN SELECT RAISE(ABORT,'external intent hash mismatch'); END;
CREATE TRIGGER external_intent_payload BEFORE INSERT ON external_effect_intent WHEN json_extract(NEW.payload,'$.intentId')<>NEW.intent_id OR json_extract(NEW.payload,'$.attemptId')<>NEW.attempt_id OR json_extract(NEW.payload,'$.operation')<>NEW.operation OR json_extract(NEW.payload,'$.accountId')<>NEW.account_id OR json_extract(NEW.payload,'$.resourceId')<>NEW.resource_id OR json_extract(NEW.payload,'$.idempotencyKey')<>NEW.idempotency_key OR json_extract(NEW.payload,'$.expectedTransitionDigest')<>NEW.expected_transition_digest BEGIN SELECT RAISE(ABORT,'external intent payload mismatch'); END;
CREATE TRIGGER external_observation_hash BEFORE INSERT ON external_effect_observation WHEN cue_sha256(NEW.payload)<>NEW.payload_sha256 BEGIN SELECT RAISE(ABORT,'external observation hash mismatch'); END;
CREATE TRIGGER external_observation_identity BEFORE INSERT ON external_effect_observation WHEN json_extract(NEW.payload,'$.intentId')<>NEW.intent_id OR json_extract(NEW.payload,'$.status')<>NEW.status OR json_extract(NEW.payload,'$.observerId')<>NEW.observer_id OR json_extract(NEW.payload,'$.observerRevision')<>NEW.observer_revision BEGIN SELECT RAISE(ABORT,'external observation identity mismatch'); END;
CREATE TRIGGER held_recovery_hash_insert BEFORE INSERT ON held_recovery WHEN cue_sha256(NEW.payload)<>NEW.payload_sha256 OR NEW.revision<>0 OR NEW.state<>'held' OR NEW.final_seal IS NOT NULL BEGIN SELECT RAISE(ABORT,'held recovery initial state mismatch'); END;
CREATE TRIGGER held_recovery_payload_insert BEFORE INSERT ON held_recovery WHEN json_extract(NEW.payload,'$.caseId')<>NEW.case_id OR json_extract(NEW.payload,'$.attemptId')<>NEW.attempt_id OR NOT(json_extract(NEW.payload,'$.changeSetId') IS NEW.change_set_id) OR json_extract(NEW.payload,'$.state')<>NEW.state OR json_extract(NEW.payload,'$.revision')<>NEW.revision BEGIN SELECT RAISE(ABORT,'held recovery payload mismatch'); END;
CREATE TRIGGER held_recovery_transition_hash BEFORE INSERT ON held_recovery_transition WHEN cue_sha256(NEW.payload)<>NEW.payload_sha256 BEGIN SELECT RAISE(ABORT,'held transition hash mismatch'); END;
CREATE TRIGGER held_recovery_cas BEFORE UPDATE ON held_recovery WHEN NEW.revision<>OLD.revision+1 OR NEW.attempt_id<>OLD.attempt_id OR NOT(NEW.change_set_id IS OLD.change_set_id) OR NEW.state='held' OR OLD.final_seal IS NOT NULL OR NEW.final_seal IS NULL OR NOT EXISTS(SELECT 1 FROM held_recovery_transition t WHERE t.case_id=OLD.case_id AND t.revision=NEW.revision AND t.from_state=OLD.state AND t.to_state=NEW.state) BEGIN SELECT RAISE(ABORT,'held recovery invalid transition'); END;
CREATE TRIGGER held_recovery_payload_update BEFORE UPDATE ON held_recovery WHEN cue_sha256(NEW.payload)<>NEW.payload_sha256 OR json_extract(NEW.payload,'$.caseId')<>NEW.case_id OR json_extract(NEW.payload,'$.attemptId')<>NEW.attempt_id OR json_extract(NEW.payload,'$.state')<>NEW.state OR json_extract(NEW.payload,'$.revision')<>NEW.revision OR json_extract(NEW.payload,'$.finalSeal')<>NEW.final_seal BEGIN SELECT RAISE(ABORT,'held recovery payload mismatch'); END;
CREATE TRIGGER held_recovery_delete BEFORE DELETE ON held_recovery BEGIN SELECT RAISE(ABORT,'held recovery immutable'); END;
CREATE TRIGGER verification_hash BEFORE INSERT ON integration_verification_result WHEN cue_sha256(NEW.payload)<>NEW.payload_sha256 OR json_extract(NEW.payload,'$.resultId')<>NEW.result_id OR json_extract(NEW.payload,'$.attemptId')<>NEW.attempt_id OR json_extract(NEW.payload,'$.verdict')<>NEW.verdict BEGIN SELECT RAISE(ABORT,'integration result mismatch'); END;
CREATE TRIGGER verification_lineage BEFORE INSERT ON integration_verification_result WHEN json_extract(NEW.payload,'$.runId')<>NEW.run_id OR json_extract(NEW.payload,'$.revision')<>NEW.revision OR json_extract(NEW.payload,'$.checkerRevision')<>NEW.checker_revision OR NOT EXISTS(SELECT 1 FROM orchestration_attempt a JOIN orchestration_attempt_revision r ON r.attempt_id=a.attempt_id WHERE a.attempt_id=NEW.attempt_id AND a.run_id=NEW.run_id AND r.revision=NEW.revision) BEGIN SELECT RAISE(ABORT,'integration result lineage mismatch'); END;
CREATE TRIGGER verification_pass_payload BEFORE INSERT ON integration_verification_result WHEN NEW.verdict='pass' AND (json_extract(NEW.payload,'$.facts.lineage')<>1 OR json_extract(NEW.payload,'$.facts.terminal')<>1 OR json_extract(NEW.payload,'$.facts.handoffValid')<>1 OR json_extract(NEW.payload,'$.facts.heldOpen')<>0 OR json_extract(NEW.payload,'$.facts.changesCurrent')<>1 OR json_extract(NEW.payload,'$.facts.effectUnknown')<>0 OR json_extract(NEW.payload,'$.facts.effectConflict')<>0 OR json_extract(NEW.payload,'$.facts.evidence')<>'pass' OR json_extract(NEW.payload,'$.facts.postSeal')<>0) BEGIN SELECT RAISE(ABORT,'integration pass payload unavailable'); END;
CREATE TRIGGER verification_pass_authority BEFORE INSERT ON integration_verification_result WHEN NEW.verdict='pass' AND (EXISTS(SELECT 1 FROM held_recovery h WHERE h.attempt_id=NEW.attempt_id AND h.state='held') OR NOT EXISTS(SELECT 1 FROM orchestration_handoff h JOIN orchestration_attempt a ON a.attempt_id=h.attempt_id WHERE h.attempt_id=NEW.attempt_id AND a.run_id=NEW.run_id AND a.cleanup_verified=1 AND a.state IN('completed','failed')) OR EXISTS(SELECT 1 FROM external_effect_intent i WHERE i.attempt_id=NEW.attempt_id AND NOT EXISTS(SELECT 1 FROM external_effect_observation o WHERE o.intent_id=i.intent_id AND o.status IN('confirmed-applied','confirmed-not-applied'))) OR EXISTS(SELECT 1 FROM change_set c WHERE c.attempt_id=NEW.attempt_id AND NOT EXISTS(SELECT 1 FROM change_observation o WHERE o.change_set_id=c.change_set_id)) ) BEGIN SELECT RAISE(ABORT,'integration pass facts unavailable'); END;
CREATE TRIGGER verification_pass_disabled BEFORE INSERT ON integration_verification_result WHEN NEW.verdict='pass' BEGIN SELECT RAISE(ABORT,'integration pass authority not wired'); END;

CREATE TRIGGER change_set_update BEFORE UPDATE ON change_set BEGIN SELECT RAISE(ABORT,'change set immutable'); END;
CREATE TRIGGER change_set_delete BEFORE DELETE ON change_set BEGIN SELECT RAISE(ABORT,'change set immutable'); END;
CREATE TRIGGER change_entry_update BEFORE UPDATE ON change_entry BEGIN SELECT RAISE(ABORT,'change entry immutable'); END;
CREATE TRIGGER change_entry_delete BEFORE DELETE ON change_entry BEGIN SELECT RAISE(ABORT,'change entry immutable'); END;
CREATE TRIGGER change_observation_update BEFORE UPDATE ON change_observation BEGIN SELECT RAISE(ABORT,'change observation immutable'); END;
CREATE TRIGGER change_observation_delete BEFORE DELETE ON change_observation BEGIN SELECT RAISE(ABORT,'change observation immutable'); END;
CREATE TRIGGER external_intent_update BEFORE UPDATE ON external_effect_intent BEGIN SELECT RAISE(ABORT,'external intent immutable'); END;
CREATE TRIGGER external_intent_delete BEFORE DELETE ON external_effect_intent BEGIN SELECT RAISE(ABORT,'external intent immutable'); END;
CREATE TRIGGER external_observation_update BEFORE UPDATE ON external_effect_observation BEGIN SELECT RAISE(ABORT,'external observation immutable'); END;
CREATE TRIGGER external_observation_delete BEFORE DELETE ON external_effect_observation BEGIN SELECT RAISE(ABORT,'external observation immutable'); END;
CREATE TRIGGER held_transition_update BEFORE UPDATE ON held_recovery_transition BEGIN SELECT RAISE(ABORT,'held transition immutable'); END;
CREATE TRIGGER held_transition_delete BEFORE DELETE ON held_recovery_transition BEGIN SELECT RAISE(ABORT,'held transition immutable'); END;
CREATE TRIGGER verification_update BEFORE UPDATE ON integration_verification_result BEGIN SELECT RAISE(ABORT,'integration result immutable'); END;
CREATE TRIGGER verification_delete BEFORE DELETE ON integration_verification_result BEGIN SELECT RAISE(ABORT,'integration result immutable'); END;
