CREATE TABLE IF NOT EXISTS native_change_journal_migration(singleton INTEGER PRIMARY KEY CHECK(singleton=1),version TEXT NOT NULL CHECK(version='cue-native-change-journal-v1'));
CREATE TABLE IF NOT EXISTS native_change_journal_legacy(attempt_id TEXT PRIMARY KEY REFERENCES orchestration_attempt(attempt_id),reason TEXT NOT NULL CHECK(reason='legacy-native-journal-unavailable'));
INSERT INTO native_change_journal_legacy SELECT attempt_id,'legacy-native-journal-unavailable' FROM orchestration_attempt WHERE NOT EXISTS(SELECT 1 FROM native_change_journal_migration);

CREATE TABLE IF NOT EXISTS change_root_contract(
 run_id TEXT NOT NULL,task_id TEXT NOT NULL,worktree_realpath TEXT NOT NULL,
 volume_serial TEXT NOT NULL CHECK(length(volume_serial)=16 AND volume_serial NOT GLOB '*[^0-9a-f]*'),
 file_id TEXT NOT NULL CHECK(length(file_id)=32 AND file_id NOT GLOB '*[^0-9a-f]*'),
 snapshot_protocol TEXT NOT NULL CHECK(snapshot_protocol='cue-change-snapshot-v1'),
 snapshot_helper_sha256 TEXT NOT NULL CHECK(length(snapshot_helper_sha256)=64 AND snapshot_helper_sha256 NOT GLOB '*[^0-9a-f]*'),
 observed_at_ms INTEGER NOT NULL CHECK(observed_at_ms>=0),payload_sha256 TEXT NOT NULL CHECK(length(payload_sha256)=64),
 payload BLOB NOT NULL CHECK(typeof(payload)='blob' AND length(payload) BETWEEN 1 AND 1048576),
 PRIMARY KEY(run_id,task_id),FOREIGN KEY(run_id,task_id) REFERENCES orchestration_step(run_id,task_id));
CREATE TRIGGER change_root_hash BEFORE INSERT ON change_root_contract WHEN cue_sha256(NEW.payload)<>NEW.payload_sha256 BEGIN SELECT RAISE(ABORT,'change root hash mismatch'); END;
CREATE TRIGGER change_root_payload BEFORE INSERT ON change_root_contract WHEN json_valid(NEW.payload)<>1 OR json_extract(NEW.payload,'$.schemaVersion') IS NOT 'cue-change-root-contract-v1' OR NOT(json_extract(NEW.payload,'$.runId') IS NEW.run_id) OR NOT(json_extract(NEW.payload,'$.taskId') IS NEW.task_id) OR NOT(json_extract(NEW.payload,'$.worktreeRealpath') IS NEW.worktree_realpath) OR NOT(json_extract(NEW.payload,'$.volumeSerial') IS NEW.volume_serial) OR NOT(json_extract(NEW.payload,'$.fileId') IS NEW.file_id) OR NOT(json_extract(NEW.payload,'$.snapshotProtocol') IS NEW.snapshot_protocol) OR NOT(json_extract(NEW.payload,'$.snapshotHelperSha256') IS NEW.snapshot_helper_sha256) OR NOT(json_extract(NEW.payload,'$.observedAtMs') IS NEW.observed_at_ms) OR json_type(NEW.payload,'$.targets')<>'array' BEGIN SELECT RAISE(ABORT,'change root payload mismatch'); END;
CREATE TRIGGER change_root_authority BEFORE INSERT ON change_root_contract WHEN NOT EXISTS(SELECT 1 FROM run r JOIN envelope e ON e.envelope_hash=r.envelope_hash WHERE r.id=NEW.run_id AND lower(e.worktree_realpath)=lower(NEW.worktree_realpath)) OR NOT EXISTS(SELECT 1 FROM change_target_contract c WHERE c.run_id=NEW.run_id AND c.task_id=NEW.task_id) OR EXISTS(SELECT 1 FROM approval_event WHERE run_id=NEW.run_id AND decision='accept') OR EXISTS(SELECT 1 FROM orchestration_attempt WHERE run_id=NEW.run_id) BEGIN SELECT RAISE(ABORT,'change root contract authority mismatch'); END;
CREATE TRIGGER change_root_update BEFORE UPDATE ON change_root_contract BEGIN SELECT RAISE(ABORT,'change root contract immutable'); END;
CREATE TRIGGER change_root_delete BEFORE DELETE ON change_root_contract BEGIN SELECT RAISE(ABORT,'change root contract immutable'); END;
CREATE TRIGGER change_target_after_root BEFORE INSERT ON change_target_contract WHEN EXISTS(SELECT 1 FROM change_root_contract WHERE run_id=NEW.run_id AND task_id=NEW.task_id) BEGIN SELECT RAISE(ABORT,'change target contract sealed'); END;
CREATE TRIGGER change_root_targets BEFORE INSERT ON change_root_contract WHEN (SELECT COUNT(*) FROM json_each(NEW.payload,'$.targets'))<>(SELECT COUNT(*) FROM change_target_contract WHERE run_id=NEW.run_id AND task_id=NEW.task_id) OR EXISTS(SELECT 1 FROM json_each(NEW.payload,'$.targets') j WHERE NOT EXISTS(SELECT 1 FROM change_target_contract c WHERE c.run_id=NEW.run_id AND c.task_id=NEW.task_id AND c.target_id=json_extract(j.value,'$.targetId') AND c.relative_path=json_extract(j.value,'$.relativePath') AND c.max_backup_bytes=json_extract(j.value,'$.maxBackupBytes'))) BEGIN SELECT RAISE(ABORT,'change root targets mismatch'); END;

CREATE TABLE IF NOT EXISTS change_native_binding(
 change_set_id TEXT PRIMARY KEY REFERENCES change_set(change_set_id),run_id TEXT NOT NULL,task_id TEXT NOT NULL,
 volume_serial TEXT NOT NULL CHECK(length(volume_serial)=16 AND volume_serial NOT GLOB '*[^0-9a-f]*'),file_id TEXT NOT NULL CHECK(length(file_id)=32 AND file_id NOT GLOB '*[^0-9a-f]*'),
 snapshot_protocol TEXT NOT NULL CHECK(snapshot_protocol='cue-change-snapshot-v1'),snapshot_helper_sha256 TEXT NOT NULL CHECK(length(snapshot_helper_sha256)=64 AND snapshot_helper_sha256 NOT GLOB '*[^0-9a-f]*'),
 payload_sha256 TEXT NOT NULL CHECK(length(payload_sha256)=64),payload BLOB NOT NULL CHECK(typeof(payload)='blob' AND length(payload) BETWEEN 1 AND 1048576),
 FOREIGN KEY(run_id,task_id) REFERENCES change_root_contract(run_id,task_id));
CREATE TRIGGER change_native_binding_hash BEFORE INSERT ON change_native_binding WHEN cue_sha256(NEW.payload)<>NEW.payload_sha256 BEGIN SELECT RAISE(ABORT,'change native binding hash mismatch'); END;
CREATE TRIGGER change_native_binding_payload BEFORE INSERT ON change_native_binding WHEN json_valid(NEW.payload)<>1 OR json_extract(NEW.payload,'$.schemaVersion') IS NOT 'cue-change-native-binding-v1' OR NOT(json_extract(NEW.payload,'$.changeSetId') IS NEW.change_set_id) OR NOT(json_extract(NEW.payload,'$.runId') IS NEW.run_id) OR NOT(json_extract(NEW.payload,'$.taskId') IS NEW.task_id) OR NOT(json_extract(NEW.payload,'$.volumeSerial') IS NEW.volume_serial) OR NOT(json_extract(NEW.payload,'$.fileId') IS NEW.file_id) OR NOT(json_extract(NEW.payload,'$.snapshotProtocol') IS NEW.snapshot_protocol) OR NOT(json_extract(NEW.payload,'$.snapshotHelperSha256') IS NEW.snapshot_helper_sha256) BEGIN SELECT RAISE(ABORT,'change native binding payload mismatch'); END;
CREATE TRIGGER change_native_binding_authority BEFORE INSERT ON change_native_binding WHEN NOT EXISTS(SELECT 1 FROM change_set s JOIN change_root_contract r ON r.run_id=s.run_id AND r.task_id=s.task_id WHERE s.change_set_id=NEW.change_set_id AND s.run_id=NEW.run_id AND s.task_id=NEW.task_id AND s.worktree_realpath=r.worktree_realpath AND r.volume_serial=NEW.volume_serial AND r.file_id=NEW.file_id AND r.snapshot_protocol=NEW.snapshot_protocol AND r.snapshot_helper_sha256=NEW.snapshot_helper_sha256) BEGIN SELECT RAISE(ABORT,'change native binding authority mismatch'); END;
CREATE TRIGGER change_native_binding_update BEFORE UPDATE ON change_native_binding BEGIN SELECT RAISE(ABORT,'change native binding immutable'); END;
CREATE TRIGGER change_native_binding_delete BEFORE DELETE ON change_native_binding BEGIN SELECT RAISE(ABORT,'change native binding immutable'); END;
CREATE TRIGGER change_observation_after_seal BEFORE INSERT ON change_observation WHEN EXISTS(SELECT 1 FROM held_recovery h WHERE h.change_set_id=NEW.change_set_id AND (h.state<>'held' OR h.final_seal IS NOT NULL)) BEGIN SELECT RAISE(ABORT,'change observation sealed'); END;

INSERT INTO native_change_journal_migration SELECT 1,'cue-native-change-journal-v1' WHERE NOT EXISTS(SELECT 1 FROM native_change_journal_migration);
CREATE TRIGGER native_change_journal_legacy_insert BEFORE INSERT ON native_change_journal_legacy BEGIN SELECT RAISE(ABORT,'native journal legacy sealed'); END;
CREATE TRIGGER native_change_journal_legacy_update BEFORE UPDATE ON native_change_journal_legacy BEGIN SELECT RAISE(ABORT,'native journal legacy immutable'); END;
CREATE TRIGGER native_change_journal_legacy_delete BEFORE DELETE ON native_change_journal_legacy BEGIN SELECT RAISE(ABORT,'native journal legacy immutable'); END;
