import { createHash } from 'node:crypto';
import type { Ledger } from '../ledger.js';

const sha=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex');
/** Read-only groundwork. It cannot create a pass until the production verifier is
 * registered and the database pass-denial trigger is replaced by a complete gate. */
export function inspectIntegrationVerification(db:Ledger,input:{attemptId:string;acceptanceEvaluationId:string}){
  const attempt=db.prepare('SELECT attempt_id,run_id,state,cleanup_verified FROM orchestration_attempt WHERE attempt_id=?').get(input.attemptId) as {attempt_id:string;run_id:string;state:string;cleanup_verified:number}|undefined;if(!attempt)throw Error('integration_attempt_missing');
  const blockers:string[]=[];const revision=db.prepare('SELECT revision FROM orchestration_attempt_revision WHERE attempt_id=?').get(input.attemptId) as {revision:number}|undefined,current=db.prepare('SELECT MAX(revision) revision FROM orchestration_plan_revision WHERE run_id=?').get(attempt.run_id) as {revision:number|null};if(!revision||revision.revision!==current.revision)blockers.push('revision-lineage-unverified');
  const handoff=db.prepare('SELECT payload,payload_sha256 FROM orchestration_handoff WHERE attempt_id=?').get(input.attemptId) as {payload:Buffer;payload_sha256:string}|undefined;if(!handoff||sha(handoff.payload)!==handoff.payload_sha256)blockers.push('terminal-handoff-unverified');if(!['completed','failed'].includes(attempt.state)||attempt.cleanup_verified!==1)blockers.push('cleanup-unverified');
  if(db.prepare("SELECT 1 FROM held_recovery WHERE attempt_id=? AND state='held'").get(input.attemptId))blockers.push('held-recovery-open');
  const set=db.prepare('SELECT change_set_id FROM change_set WHERE attempt_id=?').get(input.attemptId) as {change_set_id:string}|undefined;if(!set)blockers.push('change-set-missing');else{const total=(db.prepare('SELECT COUNT(*) n FROM change_entry WHERE change_set_id=?').get(set.change_set_id) as {n:number}).n,latest=db.prepare('SELECT o.status FROM change_observation o JOIN (SELECT ordinal,MAX(observed_at_ms) at FROM change_observation WHERE change_set_id=? GROUP BY ordinal) x ON x.ordinal=o.ordinal AND x.at=o.observed_at_ms WHERE o.change_set_id=?').all(set.change_set_id,set.change_set_id) as {status:string}[];if(total<1||latest.length!==total||latest.some(o=>['unknown','outside-manifest','moved','type-changed'].includes(o.status)))blockers.push('change-state-unverified');}
  const evaluation=db.prepare('SELECT run_id,payload,payload_sha256 FROM acceptance_evaluation WHERE id=?').get(input.acceptanceEvaluationId) as {run_id:string;payload:string;payload_sha256:string}|undefined;if(!evaluation||evaluation.run_id!==attempt.run_id||sha(evaluation.payload)!==evaluation.payload_sha256)blockers.push('acceptance-evaluation-unverified');else try{const value=JSON.parse(evaluation.payload),required=(value.outcomes??[]).filter((o:any)=>o.required);if(value.context?.runId!==attempt.run_id||value.context?.revision!==revision?.revision||!required.length||required.some((o:any)=>o.verdict!=='pass'))blockers.push('required-evidence-unverified');}catch{blockers.push('acceptance-evaluation-unverified');}
  const effects=db.prepare('SELECT intent_id FROM external_effect_intent WHERE attempt_id=?').all(input.attemptId) as {intent_id:string}[];for(const effect of effects){const statuses=(db.prepare('SELECT DISTINCT status FROM external_effect_observation WHERE intent_id=?').all(effect.intent_id) as {status:string}[]).map(o=>o.status);if(statuses.length!==1||statuses[0]==='unknown')blockers.push('external-effect-unverified');}
  blockers.push('registered-current-observer-not-wired','all-revision-attempt-lineage-not-wired','cumulative-scope-not-wired');return Object.freeze({attemptId:input.attemptId,verdict:'unknown' as const,blockers:Object.freeze([...new Set(blockers)].sort())});
}
