import { createHash } from 'node:crypto';
import { isAbsolute, relative } from 'node:path';
import { types } from 'node:util';

export const NATIVE_EXISTING_FILE_CHECKER_ID='cue-native-existing-file-artifacts';
export const NATIVE_EXISTING_FILE_CHECKER_REVISION='v1';
const sha=(v:string)=>createHash('sha256').update(v).digest('hex');
const digest=(v:unknown):v is string=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v);
function exact(v:unknown,keys:readonly string[]):Record<string,unknown>{if(!v||typeof v!=='object'||types.isProxy(v)||Object.getPrototypeOf(v)!==Object.prototype)throw Error('native_checker_record');const d=Object.getOwnPropertyDescriptors(v);if(Reflect.ownKeys(d).length!==keys.length||keys.some(k=>!d[k]?.enumerable||!Object.hasOwn(d[k],'value')))throw Error('native_checker_fields');return Object.fromEntries(keys.map(k=>[k,d[k]!.value]));}
export type NativeExpectedArtifact=Readonly<{targetId:string;relativePath:string;maxBytes:number;expectedSha256:string;expectedByteLength:number;originalSha256:string}>;
export type NativeObservedArtifact=Readonly<{targetId:string;relativePath:string;sha256:string;byteLength:number;sourceRef:string}>;
function array(value:unknown,max:number):unknown[]{if(!Array.isArray(value)||types.isProxy(value)||Object.getPrototypeOf(value)!==Array.prototype||value.length<1||value.length>max)throw Error('native_checker_targets');const ds=Object.getOwnPropertyDescriptors(value);if(Reflect.ownKeys(ds).length!==value.length+1)throw Error('native_checker_targets');const out:unknown[]=[];for(let i=0;i<value.length;i++){const d=ds[String(i)];if(!d?.enumerable||!Object.hasOwn(d,'value'))throw Error('native_checker_targets');out.push(d.value);}return out;}
function target(input:unknown):NativeExpectedArtifact{const v=exact(input,['targetId','relativePath','maxBytes','expectedSha256','expectedByteLength','originalSha256']);if(typeof v.targetId!=='string'||!/^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$/.test(v.targetId)||typeof v.relativePath!=='string'||!v.relativePath||isAbsolute(v.relativePath)||relative('.',v.relativePath).split(/[\\/]/).includes('..')||!Number.isSafeInteger(v.maxBytes)||Number(v.maxBytes)<1||Number(v.maxBytes)>16*1024*1024||!digest(v.expectedSha256)||!digest(v.originalSha256)||!Number.isSafeInteger(v.expectedByteLength)||Number(v.expectedByteLength)<0||Number(v.expectedByteLength)>Number(v.maxBytes)||v.expectedSha256===v.originalSha256)throw Error('native_checker_target');return Object.freeze(v) as unknown as NativeExpectedArtifact;}
export function createNativeExistingFileContract(input:unknown){const targets=Object.freeze(array(input,64).map(target));const paths=targets.map(x=>x.relativePath.toLocaleLowerCase('en-US')),ids=targets.map(x=>x.targetId);if(new Set(paths).size!==paths.length||new Set(ids).size!==ids.length)throw Error('native_checker_duplicate');const ordered=Object.freeze([...targets].sort((a,b)=>a.relativePath.localeCompare(b.relativePath,'en-US')));const parametersDigest=sha(JSON.stringify({version:'approved-existing-file-artifacts-v1',checkerId:NATIVE_EXISTING_FILE_CHECKER_ID,checkerRevision:NATIVE_EXISTING_FILE_CHECKER_REVISION,targets:ordered}));return Object.freeze({version:'approved-existing-file-artifacts-v1' as const,checkerId:NATIVE_EXISTING_FILE_CHECKER_ID,checkerRevision:NATIVE_EXISTING_FILE_CHECKER_REVISION,parametersDigest,targets:ordered});}
export function verifyNativeExistingFileArtifacts(contract:ReturnType<typeof createNativeExistingFileContract>,observed:unknown){const c=createNativeExistingFileContract(contract.targets);if(c.parametersDigest!==contract.parametersDigest||contract.checkerId!==NATIVE_EXISTING_FILE_CHECKER_ID||contract.checkerRevision!==NATIVE_EXISTING_FILE_CHECKER_REVISION)return Object.freeze({verdict:'unknown' as const,reasons:Object.freeze(['contract-integrity'])});let observedItems:unknown[];try{observedItems=array(observed,64);}catch{return Object.freeze({verdict:'fail' as const,reasons:Object.freeze(['artifact-set-mismatch'])});}if(observedItems.length!==c.targets.length)return Object.freeze({verdict:'fail' as const,reasons:Object.freeze(['artifact-set-mismatch'])});try{const values=observedItems.map(v=>{const x=exact(v,['targetId','relativePath','sha256','byteLength','sourceRef']);if(typeof x.targetId!=='string'||typeof x.relativePath!=='string'||!digest(x.sha256)||!Number.isSafeInteger(x.byteLength)||Number(x.byteLength)<0||typeof x.sourceRef!=='string'||!x.sourceRef)return (()=>{throw Error('artifact')})();return x as unknown as NativeObservedArtifact;});const byId=new Map(values.map(v=>[v.targetId,v]));if(byId.size!==values.length)return Object.freeze({verdict:'fail' as const,reasons:Object.freeze(['artifact-set-mismatch'])});for(const expected of c.targets){const actual=byId.get(expected.targetId);if(!actual||actual.relativePath!==expected.relativePath||actual.sha256!==expected.expectedSha256||actual.byteLength!==expected.expectedByteLength||actual.byteLength>expected.maxBytes)return Object.freeze({verdict:'fail' as const,reasons:Object.freeze([`artifact-mismatch:${expected.targetId}`])});}return Object.freeze({verdict:'pass' as const,reasons:Object.freeze([])});}catch{return Object.freeze({verdict:'unknown' as const,reasons:Object.freeze(['artifact-invalid'])});}}

