import { createHash } from 'node:crypto';
import { types } from 'node:util';
import type { Ledger } from '../ledger.js';
import type { CompletionEstimate } from './policy.js';
import { readRunSelectionPolicy } from './policy-store.js';

const VERSION='cue-initial-default-v1' as const;
const hash=(value:string|Uint8Array):string=>createHash('sha256').update(value).digest('hex');
function fail(code:string):never{throw Error(`initial_default_${code}`);}
function fields(value:unknown,keys:readonly string[]):Record<string,unknown>{if(!value||typeof value!=='object'||types.isProxy(value)||Object.getPrototypeOf(value)!==Object.prototype)fail('input');const descriptors=Object.getOwnPropertyDescriptors(value);if(Reflect.ownKeys(descriptors).length!==keys.length)fail('fields');const copy:Record<string,unknown>={};for(const key of keys){const descriptor=descriptors[key];if(!descriptor||!descriptor.enumerable||!Object.hasOwn(descriptor,'value'))fail('accessor');copy[key]=descriptor.value;}return copy;}
function id(value:unknown):string{if(typeof value!=='string'||!/^[a-zA-Z0-9][a-zA-Z0-9._:/-]{0,127}$/u.test(value))fail('id');return value;}
function text(value:unknown):string{if(typeof value!=='string'||!value.trim()||value.length>256||/[\u0000-\u001f\u007f]/u.test(value))fail('text');return value;}
function integer(value:unknown):number{if(!Number.isSafeInteger(value)||(value as number)<0)fail('integer');return value as number;}
function revision(value:unknown):number{const result=integer(value);if(result<1)fail('revision');return result;}
function digest(value:unknown):string{if(typeof value!=='string'||!/^[0-9a-f]{64}$/u.test(value))fail('digest');return value;}
function finite(value:unknown):number{if(typeof value!=='number'||!Number.isFinite(value)||value<0||value>Number.MAX_SAFE_INTEGER)fail('number');return value;}
function snapshotEstimate(value:unknown):Readonly<CompletionEstimate>{const data=fields(value,['scope','quality','expectedCost','conservativeMaxCost','expectedTimeMs','conservativeMaxTimeMs','currency','source','observedAtMs']);if(data.scope!=='verified-completion-total')fail('scope');const quality=finite(data.quality),expectedCost=finite(data.expectedCost),maxCost=finite(data.conservativeMaxCost),expectedTimeMs=finite(data.expectedTimeMs),maxTimeMs=finite(data.conservativeMaxTimeMs),observedAtMs=integer(data.observedAtMs);if(quality>1||maxCost<expectedCost||maxTimeMs<expectedTimeMs)fail('estimate');return Object.freeze({scope:'verified-completion-total',quality,expectedCost,conservativeMaxCost:maxCost,expectedTimeMs,conservativeMaxTimeMs:maxTimeMs,currency:text(data.currency),source:text(data.source),observedAtMs});}

export interface InitialDefaultConfig {version:typeof VERSION;runId:string;policyId:string;policyRevision:number;policyDigest:string;defaultCandidateId:string;conservativeEstimate:CompletionEstimate;source:string;boundAtMs:number}
export interface StoredInitialDefault extends Omit<InitialDefaultConfig,'conservativeEstimate'>{readonly conservativeEstimate:Readonly<CompletionEstimate>;readonly digest:string}
export interface InitialDefaultAttempt {version:typeof VERSION;attemptId:string;runId:string;requestId:string;disposition:'legacy-observation-absent'|'no-statistics';candidateId:string;defaultDigest:string;observation:Readonly<{source:string;observedAtMs:number}>|null}
export interface StoredInitialDefaultAttempt extends InitialDefaultAttempt {readonly digest:string}

function migration(db:Ledger):boolean{const names=db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name IN('initial_default_migration','initial_default','initial_default_attempt')").all() as {name:string}[];if(!names.length)return false;if(names.length!==3)fail('migration_incomplete');const marker=db.prepare("SELECT 1 ok FROM initial_default_migration WHERE singleton=1 AND version='cue-initial-default-v1'").get() as {ok:number}|undefined;if(!marker)fail('migration_incomplete');return true;}
function snapshotConfig(value:unknown):Readonly<InitialDefaultConfig>{const data=fields(value,['version','runId','policyId','policyRevision','policyDigest','defaultCandidateId','conservativeEstimate','source','boundAtMs']);if(data.version!==VERSION)fail('version');return Object.freeze({version:VERSION,runId:id(data.runId),policyId:id(data.policyId),policyRevision:revision(data.policyRevision),policyDigest:digest(data.policyDigest),defaultCandidateId:id(data.defaultCandidateId),conservativeEstimate:snapshotEstimate(data.conservativeEstimate),source:text(data.source),boundAtMs:integer(data.boundAtMs)});}
function validateAgainstPolicy(db:Ledger,value:Readonly<InitialDefaultConfig>):void{const bound=readRunSelectionPolicy(db,value.runId);if(!bound||bound.snapshot.policyId!==value.policyId||bound.snapshot.revision!==value.policyRevision||bound.snapshot.digest!==value.policyDigest)fail('policy');const policy=bound.snapshot.policy,estimate=value.conservativeEstimate,budget=db.prepare('SELECT currency,policy_revision FROM integration_budget WHERE run_id=?').get(value.runId) as {currency:string;policy_revision:string}|undefined;if(!budget||budget.currency!==estimate.currency||budget.policy_revision!==`${value.policyId}:${value.policyRevision}`)fail('budget');if(!policy.allowedCandidateIds.includes(value.defaultCandidateId)||estimate.currency!==policy.currency||estimate.quality<policy.qualityMinimum)fail('candidate');if(estimate.observedAtMs>value.boundAtMs||value.boundAtMs-estimate.observedAtMs>policy.maxEstimateAgeMs)fail('stale');if(policy.costLimit!==null&&estimate.conservativeMaxCost!>policy.costLimit)fail('cost');if(policy.remainingTimeMs!==null&&estimate.conservativeMaxTimeMs!>policy.remainingTimeMs)fail('time');}
type DefaultRow={run_id:string;policy_id:string;policy_revision:number;policy_digest:string;default_candidate_id:string;digest:string;payload:Buffer};
function decodeDefault(db:Ledger,row:DefaultRow):StoredInitialDefault{if(!Buffer.isBuffer(row.payload))fail('payload');const parsed=JSON.parse(row.payload.toString()),config=snapshotConfig(parsed),encoded=JSON.stringify(config),d=hash(encoded);if(row.payload.toString()!==encoded||row.digest!==d||row.run_id!==config.runId||row.policy_id!==config.policyId||row.policy_revision!==config.policyRevision||row.policy_digest!==config.policyDigest||row.default_candidate_id!==config.defaultCandidateId)fail('integrity');validateAgainstPolicy(db,config);return Object.freeze({...config,digest:d});}
export function readInitialDefault(db:Ledger,runId:string):StoredInitialDefault|null{id(runId);if(!migration(db))return null;const row=db.prepare('SELECT * FROM initial_default WHERE run_id=?').get(runId) as DefaultRow|undefined;return row?decodeDefault(db,row):null;}
export function bindInitialDefault(db:Ledger,input:InitialDefaultConfig):StoredInitialDefault{if(!migration(db))fail('migration_missing');const config=snapshotConfig(input);validateAgainstPolicy(db,config);const encoded=JSON.stringify(config),d=hash(encoded);return db.transaction(()=>{const old=readInitialDefault(db,config.runId);if(old){if(old.digest!==d)fail('binding_conflict');return old;}db.prepare('INSERT INTO initial_default VALUES(?,?,?,?,?,?,?)').run(config.runId,config.policyId,config.policyRevision,config.policyDigest,config.defaultCandidateId,d,Buffer.from(encoded));return readInitialDefault(db,config.runId)!;}).immediate();}

function snapshotAttempt(value:unknown):Readonly<InitialDefaultAttempt>{const data=fields(value,['version','attemptId','runId','requestId','disposition','candidateId','defaultDigest','observation']);if(data.version!==VERSION||!['legacy-observation-absent','no-statistics'].includes(data.disposition as string))fail('attempt');let observation:Readonly<{source:string;observedAtMs:number}>|null=null;if(data.observation!==null){const observed=fields(data.observation,['source','observedAtMs']);observation=Object.freeze({source:text(observed.source),observedAtMs:integer(observed.observedAtMs)});}if((data.disposition==='legacy-observation-absent')!==(observation===null))fail('attempt');return Object.freeze({version:VERSION,attemptId:id(data.attemptId),runId:id(data.runId),requestId:id(data.requestId),disposition:data.disposition as InitialDefaultAttempt['disposition'],candidateId:id(data.candidateId),defaultDigest:digest(data.defaultDigest),observation});}
type AttemptRow={attempt_id:string;run_id:string;request_id:string;disposition:InitialDefaultAttempt['disposition'];candidate_id:string;default_digest:string;digest:string;payload:Buffer};
function decodeAttempt(db:Ledger,row:AttemptRow):StoredInitialDefaultAttempt{if(!Buffer.isBuffer(row.payload))fail('attempt_payload');const attempt=snapshotAttempt(JSON.parse(row.payload.toString())),encoded=JSON.stringify(attempt),d=hash(encoded),config=readInitialDefault(db,attempt.runId);if(row.payload.toString()!==encoded||row.digest!==d||row.attempt_id!==attempt.attemptId||row.run_id!==attempt.runId||row.request_id!==attempt.requestId||row.disposition!==attempt.disposition||row.candidate_id!==attempt.candidateId||row.default_digest!==attempt.defaultDigest||!config||config.digest!==attempt.defaultDigest)fail('attempt_integrity');return Object.freeze({...attempt,digest:d});}
export function readInitialDefaultAttempt(db:Ledger,attemptId:string):StoredInitialDefaultAttempt|null{id(attemptId);if(!migration(db))return null;const row=db.prepare('SELECT * FROM initial_default_attempt WHERE attempt_id=?').get(attemptId) as AttemptRow|undefined;return row?decodeAttempt(db,row):null;}
export function recordInitialDefaultAttempt(db:Ledger,input:InitialDefaultAttempt):StoredInitialDefaultAttempt{if(!db.inTransaction)fail('claim_transaction_required');const attempt=snapshotAttempt(input),config=readInitialDefault(db,attempt.runId);if(!config||config.digest!==attempt.defaultDigest)fail('attempt_default');if(attempt.disposition==='no-statistics'&&attempt.candidateId!==config.defaultCandidateId)fail('attempt_candidate');const encoded=JSON.stringify(attempt),d=hash(encoded),old=readInitialDefaultAttempt(db,attempt.attemptId);if(old){if(old.digest!==d)fail('attempt_conflict');return old;}db.prepare('INSERT INTO initial_default_attempt VALUES(?,?,?,?,?,?,?,?)').run(attempt.attemptId,attempt.runId,attempt.requestId,attempt.disposition,attempt.candidateId,attempt.defaultDigest,d,Buffer.from(encoded));return readInitialDefaultAttempt(db,attempt.attemptId)!;}
