import {afterEach,describe,expect,test,vi} from 'vitest';
import {createHash} from 'node:crypto';
import {mkdtempSync,mkdirSync,readFileSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {openLedger,type Ledger} from '../src/ledger.js';
import {envelopeHash,normalizeEnvelope} from '../src/envelope.js';
import {saveSelectionPolicy} from '../src/selection/policy-store.js';
import {createIntegrationCatalog} from '../src/integration-catalog.js';
import {SUBJECT_FIELDS,subjectDigest,type MeasurementSubject} from '../src/measurement-subject.js';
import {WRITE_PROBES,MODEL_PROBES} from '../src/capability-admission.js';
import {compareWriteExistingNative,identifyChangeSnapshotRoot} from '../src/change-snapshot-host.js';
import {createOrchestrationDriver} from '../../app/orchestration-driver.mjs';
import {createOrchestrationStore} from '../src/orchestration/store.js';

const roots:string[]=[],dbs:Ledger[]=[];afterEach(()=>{vi.restoreAllMocks();for(const db of dbs.splice(0))if(db.open)db.close();for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
const time=Date.parse('2026-09-15T00:00:00.000Z'),sha=(value:string|Buffer)=>createHash('sha256').update(value).digest('hex');
async function until(check:()=>boolean){for(let i=0;i<100&&!check();i++)await new Promise(resolve=>setTimeout(resolve,5));expect(check()).toBe(true);}

function fixture(work:string,replacement:string,marker=true,launchTimeoutMs=1000,executionInput?:{root:string;onCreate?(path:string):void;throwCreate?:boolean}|false,stageActions:string[]=['file_change'],executionOutcome:'succeeded'|'failed'='succeeded',cleanupUnknown=false,verificationMode:'verified'|'false'|'throw'='verified'){
 const root=mkdtempSync(join(tmpdir(),'cue-driver-publication-'));roots.push(root);const path=join(root,'ledger.db'),db=openLedger(path);dbs.push(db);
 const generatedExecutionRoot=executionInput===undefined?mkdtempSync(join(tmpdir(),'cue-driver-execution-')):null;if(generatedExecutionRoot){roots.push(generatedExecutionRoot);writeFileSync(join(generatedExecutionRoot,'target.txt'),'isolated');}
 const execution=executionInput===false?undefined:executionInput??{root:generatedExecutionRoot!};
 const envelope=normalizeEnvelope({run_id:'workflow',worktree_realpath:work,allowed_actions:[...new Set([...stageActions,'read'])],egress:[],expires_at:'2026-09-16T00:00:00.000Z',autonomy_level:'bounded'});
 const run={taskId:'root-task',runId:'workflow',envelopeHash:envelopeHash(envelope),envelope,goal:'publish staged bytes',scope:'code'};
 db.prepare("INSERT INTO task VALUES('root-task','awaiting_approval',NULL,'now')").run();db.prepare("INSERT INTO envelope VALUES(?,?,'[]','now')").run(run.envelopeHash,work);db.prepare("INSERT INTO run VALUES('workflow','root-task',?,0,'now')").run(run.envelopeHash);
 const policy=saveSelectionPolicy(db,{policyId:'policy',expectedRevision:null,createdAt:new Date(time).toISOString(),sourceVersion:'fixture',policy:{version:'cue-selection-v1',mode:'efficiency',qualityMinimum:.5,costBasis:1,timeBasisMs:1,currency:'TEST',costLimit:null,remainingTimeMs:null,maxEstimateAgeMs:100,allowedCandidateIds:['agent'],pinnedCandidateId:null}});
 const subject=Object.fromEntries(SUBJECT_FIELDS.map(key=>[key,key.endsWith('Sha256')?'a'.repeat(64):key])) as MeasurementSubject,evidence=new Map<string,Buffer>(),refs:Record<string,{id:string;sha256:string}>={};
 for(const probe of [...WRITE_PROBES,...MODEL_PROBES]){const bytes=Buffer.from(JSON.stringify({probe,subjectDigest:subjectDigest(subject),measuredAt:new Date(time-1).toISOString(),kind:'live',status:'pass'}));evidence.set(probe,bytes);refs[probe]={id:probe,sha256:sha(bytes)};}
 const catalog=createIntegrationCatalog({now:()=>time,maxAgeMs:100,currentSubjectDigest:()=>subjectDigest(subject)},[{canonicalId:'agent',toolId:'fixture',kind:'agent',aliases:[],installation:'installed',protocol:'verified',authReference:'fixture-account',authAvailable:true,sourceVersion:'fixture',observedAt:new Date(time).toISOString(),subjectDigest:subjectDigest(subject),binding:null}]);
 let release!:()=>void;const completion=new Promise<'succeeded'|'failed'>(resolve=>{release=()=>resolve(executionOutcome);}),staged=new Map<string,Buffer>(),controls:{onOpen:()=>void|Promise<void>;onRead:()=>void|Promise<void>;onAuthorize:()=>boolean;executeResult?:unknown;throwExecute:boolean}={onOpen:()=>{},onRead:()=>{},onAuthorize:()=>true,throwExecute:false};let launches=0,opens=0,reads=0,writes=0,creates=0;const writable=stageActions.includes('file_change'),configuration:any={policy:{policyId:'policy',revision:1,digest:policy.digest},requirementIds:['req'],proposedPlan:{revision:'plan1',policyRevision:'policy:1',policyDigest:policy.digest,tasks:[{id:'make',role:'implementation',ownerId:'maker',requirementIds:['req'],dependencyIds:[],candidateIds:['agent'],scopeIds:['work']},{id:'check',role:'verifier',ownerId:'checker',requirementIds:['req'],dependencyIds:['make'],candidateIds:['agent'],scopeIds:[]}]},scopes:[{id:'work',worktreeRealpath:work,allowedActions:[...new Set([...stageActions,'read'])],egress:[]}],budget:{runId:'workflow',currency:'TEST',unit:'micro',limitUnits:100,policyRevision:'policy:1',source:'fixture',observedAtMs:time},...(writable?{changeTargets:[{taskId:'make',targetId:'target',relativePath:'target.txt',maxBackupBytes:1024}],stagedPublication:true,...(execution?{executionStaging:true}:{})}:{}),limits:{launchTimeoutMs,taskTimeoutMs:5000,pollMs:2}};
 const publicationIdentity=execution?identifyChangeSnapshotRoot(work):null,executionIdentity=execution?identifyChangeSnapshotRoot(execution.root):null;if(execution&&(publicationIdentity?.state!=='ok'||executionIdentity?.state!=='ok'))throw Error('fixture_native_identity');
 const publicationRootIdentity=publicationIdentity?.state==='ok'?publicationIdentity.identity:null,executionRootIdentity=executionIdentity?.state==='ok'?executionIdentity.identity:null;
 let candidate:any;
 const host:any={now:()=>time,catalog,prepare:()=>configuration,verifyFinalBilling:()=>true,...(execution?{executionStaging:{inspectCleanRoot:()=>({worktreeRealpath:work,rootIdentity:publicationRootIdentity,baseCommitId:'3'.repeat(40),trackedModified:[],staged:[],untracked:[],conflicted:[],detached:false,unborn:false,reparseFree:true}),factory:{protocol:'cue-attempt-staging-factory-v1',sha256:'4'.repeat(64),create:()=>{creates++;execution.onCreate?.(path);if(execution.throwCreate)throw Error('fixture-create-failed');return{worktreeRealpath:execution.root,rootIdentity:executionRootIdentity,reparseFree:true};},inspectRoot:(value:any)=>value,cleanup:()=>({rootAbsent:true,metadataAbsent:true,evidenceSha256:'7'.repeat(64)}),inspectCleanup:()=>{if(cleanupUnknown)return{rootAbsent:false,metadataAbsent:false,evidenceSha256:'7'.repeat(64),reason:'fixture-cleanup-unknown'};rmSync(execution.root,{recursive:true,force:true});return{rootAbsent:true,metadataAbsent:true,evidenceSha256:'7'.repeat(64)};}}}}:{}),
  finalPublication:{authorize:()=>controls.onAuthorize(),openStagedAttempt:async(contract:any)=>{opens++;await controls.onOpen();expect(contract).toMatchObject({version:'cue-staged-existing-files-v1',stagingOnly:true,targets:[{relativePath:'target.txt',maxBytes:1024}]});expect(readFileSync(join(work,'target.txt'),'utf8')).toBe('P');staged.set(contract.contractId,Buffer.from(replacement));return{contractId:contract.contractId};},readStagedReplacement:async(input:any)=>{reads++;await controls.onRead();return Buffer.from(staged.get(input.contractId)!);},execute:(input:any)=>{writes++;if(controls.throwExecute)throw Error('fixture-pending');return controls.executeResult??compareWriteExistingNative(input);}},
  authority:{authorizePlan:()=>true,authorizeClaim:()=>true,authorizeStage:()=>true,verifyReceipt:(context:any,receipt:any)=>{if(verificationMode==='throw')throw Error('fixture-receipt-unverified');const identity=db.prepare('SELECT identity_id FROM orchestration_attempt_identity WHERE attempt_id=?').get(context.attemptId) as any;return{outcomeVerified:verificationMode==='verified',cleanupVerified:verificationMode==='verified',...(verificationMode==='verified'?{handoff:{handoffId:`handoff-${receipt.attemptId}`,identityId:identity.identity_id,artifacts:[{kind:'fixture',sourceRef:'fixture-artifact'}]}}:{})};},authorizeHandoffArtifact:(ref:string)=>ref==='fixture-artifact',resolveHandoffArtifact:(ref:string)=>ref==='fixture-artifact'?Buffer.from('artifact'):null},
  runtime:{evidence:{now:()=>time,maxAgeMs:100,resolveEvidence:(ref:any)=>evidence.get(ref.id)},authorizeRun:()=>true,resolveCandidate:(_id:string,_attempt:string,_role:string,binding:any)=>(candidate={kind:'agent',supportedRoles:['implementation','model'],cancellation:'supported',usage:'unsupported',availability:'ready',typedActivitySource:'host-codex-controller-v1',durableExecutionRef:'session-handle-v1',...(marker?{stagedPublication:'attempt-owned-existing-files-v1'}:{}),buildCurrentSubject:()=>subject,evidenceReferences:()=>refs,launch:async(context:any)=>{launches++;if(context.stagedPublication){expect(context.stagedPublication.stagingOnly).toBe(true);expect(readFileSync(join(work,'target.txt'),'utf8')).toBe('P');}const handle=`session-${sha(context.runId).slice(0,20)}`;db.prepare('INSERT INTO session_handle VALUES(?,?,?,?,?,?)').run(handle,100+launches,'fixture-start',binding.owner.cwd,binding.owner.task_id,binding.owner.run_id);return{durableRef:`session:${handle}`,completion,cancel:async()=>{}};}}),verifyCleanup:async(context:any)=>({runId:context.runId,subjectDigest:context.subjectDigest,result:'verified-clean',evidenceRef:'fixture-clean'})},
  engine:{observeInitialSelection:()=>null,observeCandidates:()=>[{id:'agent',checks:{eligible:true,authenticated:true,compatible:true,dataAllowed:true,resourceAvailable:true,quotaAvailable:true},estimate:{scope:'verified-completion-total',quality:1,expectedCost:1,conservativeMaxCost:1,expectedTimeMs:1,conservativeMaxTimeMs:1,currency:'TEST',source:'fixture',observedAtMs:time}}],reservation:(context:any)=>({runId:context.request.runId,attemptId:context.request.attemptId,requestId:context.request.requestId,currency:'TEST',unit:'micro',upperUnits:1,source:'fixture',observedAtMs:time,scope:'verified-completion-attempt-total'}),verifyBudgetMapping:()=>true,authorizeExecution:()=>true,receipts:(context:any)=>({billing:null,execution:{runId:context.request.runId,taskId:context.request.taskId,attemptId:context.request.attemptId,receiptId:`receipt-${context.request.attemptId}`,revision:1,outcome:executionOutcome,cleanup:'clean',evidenceRef:'fixture-clean',observedAtMs:time}})},stage:()=>({worktreeRealpath:execution?.root??work,allowedActions:stageActions,egress:[],expiresAt:envelope.expires_at,autonomyLevel:'bounded'})};
 const driver=createOrchestrationDriver({db,host});driver.prepare(run);db.prepare("INSERT INTO approval_event(run_id,envelope_hash,thread_id,item_id,approval_id,request_ordinal,decision,created_at) VALUES('workflow',?,'desktop','goal','approval',0,'accept','now')").run(run.envelopeHash);driver.activate(run);
 return{root,path,db,driver,host,get candidate(){return candidate;},run,release,controls,configuration,get creates(){return creates;},get counts(){return{launches,opens,reads,writes};}};
}

describe.runIf(process.platform==='win32')('driver staged existing-file publication',()=>{
 test('isolated execution durably stages once while capture and publication stay on the approved root',async()=>{
  const work=mkdtempSync(join(tmpdir(),'cue-driver-publication-work-'));roots.push(work);writeFileSync(join(work,'target.txt'),'P');const executionRoot=mkdtempSync(join(tmpdir(),'cue-driver-execution-'));roots.push(executionRoot);writeFileSync(join(executionRoot,'target.txt'),'isolated');let observed=false;
  const f=fixture(work,'A',true,1000,{root:executionRoot,onCreate:path=>{const other=openLedger(path);try{expect(other.prepare('SELECT count(*) n FROM attempt_staging_setup').get()).toEqual({n:1});expect(other.prepare('SELECT count(*) n FROM orchestration_attempt').get()).toEqual({n:1});expect(other.prepare('SELECT count(*) n FROM workspace_write_lease').get()).toEqual({n:1});observed=true;}finally{other.close();}}});
  const started=f.driver.start(f.run);await until(()=>f.counts.launches===1);expect(observed).toBe(true);expect(f.creates).toBe(1);expect((f.db.prepare('SELECT cwd FROM session_handle').get() as any).cwd).toBe(executionRoot);expect((f.db.prepare('SELECT worktree_realpath FROM change_set').get() as any).worktree_realpath).toBe(work);f.release();await started;expect(readFileSync(join(work,'target.txt'),'utf8')).toBe('A');expect(f.db.prepare('SELECT result FROM attempt_staging_cleanup').get()).toEqual({result:'active_cleanup_verified'});expect(f.db.prepare('SELECT count(*) n FROM workspace_write_lease').get()).toEqual({n:0});
 });
 test('failed clean staged execution durably discards its exact isolated root without publication and releases the lease',async()=>{
  const work=mkdtempSync(join(tmpdir(),'cue-driver-publication-work-'));roots.push(work);writeFileSync(join(work,'target.txt'),'P');const f=fixture(work,'A',true,1000,undefined,['file_change'],'failed');const started=f.driver.start(f.run);await until(()=>f.counts.launches===1);f.release();await started;expect(f.counts).toEqual({launches:1,opens:1,reads:0,writes:0});expect(readFileSync(join(work,'target.txt'),'utf8')).toBe('P');expect(f.db.prepare('SELECT receipt_id FROM attempt_staging_discard_authorization').get()).toBeDefined();expect(f.db.prepare('SELECT result FROM attempt_staging_discard').get()).toEqual({result:'discard_verified'});expect(f.db.prepare('SELECT count(*) n FROM attempt_staging_cleanup').get()).toEqual({n:0});expect(f.db.prepare('SELECT count(*) n FROM change_publication_intent').get()).toEqual({n:0});expect(f.db.prepare('SELECT count(*) n FROM workspace_write_lease').get()).toEqual({n:0});expect(f.db.prepare(`SELECT json_extract(payload,'$.outcome') outcome,json_extract(payload,'$.cleanup') cleanup FROM orchestration_receipt`).get()).toEqual({outcome:'failed',cleanup:'clean'});
 });
 test('unknown failed-clean discard is durable, keeps the lease, and refuses terminal receipt persistence',async()=>{
  const work=mkdtempSync(join(tmpdir(),'cue-driver-publication-work-'));roots.push(work);writeFileSync(join(work,'target.txt'),'P');const f=fixture(work,'A',true,1000,undefined,['file_change'],'failed',true);const started=f.driver.start(f.run);await until(()=>f.counts.launches===1);f.release();await started;expect(f.counts).toEqual({launches:1,opens:1,reads:0,writes:0});expect(readFileSync(join(work,'target.txt'),'utf8')).toBe('P');expect(f.db.prepare('SELECT result FROM attempt_staging_discard').get()).toEqual({result:'discard_unknown'});expect(f.db.prepare('SELECT count(*) n FROM workspace_write_lease').get()).toEqual({n:1});expect(f.db.prepare('SELECT count(*) n FROM orchestration_receipt').get()).toEqual({n:0});expect(()=>f.db.prepare('DELETE FROM workspace_write_lease').run()).toThrow('attempt staging cleanup unresolved');expect(f.driver.snapshot('workflow')).toMatchObject({state:'blocked',reason:'change_publication_unresolved'});
 });
 test('durable pre-clean authorization reopens without re-invoking a drifting verifier and rejects a changed receipt',async()=>{
  const work=mkdtempSync(join(tmpdir(),'cue-driver-publication-work-'));roots.push(work);writeFileSync(join(work,'target.txt'),'P');const f=fixture(work,'A',true,1000,undefined,['file_change'],'failed');const started=f.driver.start(f.run);await until(()=>f.counts.launches===1);const attempt=(f.db.prepare("SELECT attempt_id FROM orchestration_attempt WHERE task_id='make'").get() as any).attempt_id;const receipt={runId:'workflow',taskId:'make',attemptId:attempt,receiptId:`receipt-${attempt}`,revision:1,outcome:'failed' as const,cleanup:'clean' as const,evidenceRef:'fixture-clean',observedAtMs:time};createOrchestrationStore(f.db,f.host.authority).prepareFinish(receipt);f.host.authority.verifyReceipt=()=>{throw Error('fixture-verifier-drift');};const reopened=createOrchestrationStore(f.db,f.host.authority);expect(()=>reopened.prepareFinish(receipt)).not.toThrow();expect(()=>reopened.prepareFinish({...receipt,revision:2})).toThrow('discard_authorization_mismatch');f.release();await started;expect(f.db.prepare('SELECT result FROM attempt_staging_discard').get()).toEqual({result:'discard_verified'});expect(f.db.prepare('SELECT count(*) n FROM workspace_write_lease').get()).toEqual({n:0});
 });
 test.each(['false','throw'] as const)('unverified failed-clean receipt (%s) cannot authorize or physically discard staging',async verificationMode=>{
  const work=mkdtempSync(join(tmpdir(),'cue-driver-publication-work-'));roots.push(work);writeFileSync(join(work,'target.txt'),'P');const executionRoot=mkdtempSync(join(tmpdir(),'cue-driver-execution-'));roots.push(executionRoot);writeFileSync(join(executionRoot,'target.txt'),'isolated');const f=fixture(work,'A',true,1000,{root:executionRoot},['file_change'],'failed',false,verificationMode);const started=f.driver.start(f.run);await until(()=>f.counts.launches===1);f.release();await started;expect(readFileSync(join(executionRoot,'target.txt'),'utf8')).toBe('isolated');expect(f.db.prepare('SELECT count(*) n FROM attempt_staging_discard_authorization').get()).toEqual({n:0});expect(f.db.prepare('SELECT count(*) n FROM attempt_staging_discard').get()).toEqual({n:0});expect(f.db.prepare('SELECT count(*) n FROM orchestration_receipt').get()).toEqual({n:0});expect(f.db.prepare('SELECT count(*) n FROM workspace_write_lease').get()).toEqual({n:1});
 });
 test('factory failure is terminal, durable, lease-held, and replay creates zero more roots',async()=>{
  const work=mkdtempSync(join(tmpdir(),'cue-driver-publication-work-'));roots.push(work);writeFileSync(join(work,'target.txt'),'P');const executionRoot=mkdtempSync(join(tmpdir(),'cue-driver-execution-'));roots.push(executionRoot);const f=fixture(work,'A',true,1000,{root:executionRoot,throwCreate:true});
  await f.driver.start(f.run);expect(f.creates).toBe(1);expect(f.counts.launches).toBe(0);expect(f.db.prepare('SELECT count(*) n FROM attempt_staging_setup').get()).toEqual({n:1});expect(f.db.prepare('SELECT result FROM attempt_staging_cleanup').get()).toEqual({result:'create_unknown'});expect(f.db.prepare('SELECT count(*) n FROM workspace_write_lease').get()).toEqual({n:1});await f.driver.start(f.run);expect(f.creates).toBe(1);expect(f.counts.launches).toBe(0);
 });
 test('an approved writable run without attempt-owned staging refuses before launch and cannot be upgraded later',async()=>{
  const work=mkdtempSync(join(tmpdir(),'cue-driver-publication-work-'));roots.push(work);writeFileSync(join(work,'target.txt'),'P');const f=fixture(work,'A',true,1000,false);let creates=0;f.configuration.executionStaging=true;f.host.executionStaging={inspectCleanRoot:()=>{throw Error('must-not-inspect');},factory:{protocol:'cue-attempt-staging-factory-v1',sha256:'4'.repeat(64),create:()=>{creates++;throw Error('must-not-create');}}};expect(f.db.prepare('SELECT enabled FROM run_staging_authority').get()).toEqual({enabled:0});expect(()=>f.db.prepare('UPDATE run_staging_authority SET enabled=1').run()).toThrow('immutable');await f.driver.start(f.run);expect(f.counts).toEqual({launches:0,opens:0,reads:0,writes:0});expect(f.driver.snapshot('workflow')).toMatchObject({state:'blocked',reason:'existing_file_publication_unsupported'});expect(readFileSync(join(work,'target.txt'),'utf8')).toBe('P');expect(creates).toBe(0);
 });
 test('approved factory identity drift refuses before create and claim mutation',async()=>{
  const work=mkdtempSync(join(tmpdir(),'cue-driver-publication-work-'));roots.push(work);writeFileSync(join(work,'target.txt'),'P');const executionRoot=mkdtempSync(join(tmpdir(),'cue-driver-execution-'));roots.push(executionRoot);const f=fixture(work,'A',true,1000,{root:executionRoot});f.host.executionStaging.factory.sha256='8'.repeat(64);await f.driver.start(f.run);expect(f.creates).toBe(0);expect(f.counts.launches).toBe(0);expect(f.db.prepare('SELECT count(*) n FROM attempt_staging_setup').get()).toEqual({n:0});expect(f.db.prepare('SELECT count(*) n FROM workspace_write_lease').get()).toEqual({n:0});
 });
 test('one staged writer commits and a stale journal cannot overwrite it; replay launches and writes zero',async()=>{
  const shared=mkdtempSync(join(tmpdir(),'cue-driver-publication-work-'));roots.push(shared);writeFileSync(join(shared,'target.txt'),'P');const winner=fixture(shared,'A'),loser=fixture(shared,'B');
  const win=winner.driver.start(winner.run),loss=loser.driver.start(loser.run);await until(()=>winner.counts.launches===1&&loser.counts.launches===1);expect(readFileSync(join(shared,'target.txt'),'utf8')).toBe('P');
  winner.release();await win;expect(readFileSync(join(shared,'target.txt'),'utf8')).toBe('A');expect(winner.counts).toEqual({launches:1,opens:1,reads:1,writes:1});expect(winner.db.prepare('SELECT state FROM change_publication_result').get()).toEqual({state:'committed'});expect(winner.db.prepare('SELECT count(*) n FROM workspace_write_lease').get()).toEqual({n:0});
  loser.release();await loss;expect(readFileSync(join(shared,'target.txt'),'utf8')).toBe('A');expect(loser.counts).toEqual({launches:1,opens:1,reads:1,writes:1});expect(loser.db.prepare('SELECT state FROM change_publication_result').get()).toEqual({state:'contention'});expect(loser.db.prepare('SELECT count(*) n FROM workspace_write_lease').get()).toEqual({n:1});expect(loser.driver.snapshot('workflow')).toMatchObject({state:'blocked',reason:'change_publication_unresolved'});
  const before={...loser.counts};await loser.driver.start(loser.run);expect(loser.counts).toEqual(before);loser.db.close();const reopened=openLedger(loser.path);dbs.push(reopened);const replay=createOrchestrationDriver({db:reopened,host:loser.host});expect(()=>replay.prepare(loser.run)).toThrow('change target contract sealed');expect(loser.counts).toEqual(before);expect(readFileSync(join(shared,'target.txt'),'utf8')).toBe('A');
 });
 test('missing adapter staging marker refuses before adapter launch and keeps the preimage lease',async()=>{
  const work=mkdtempSync(join(tmpdir(),'cue-driver-publication-work-'));roots.push(work);writeFileSync(join(work,'target.txt'),'P');const f=fixture(work,'A',false);await f.driver.start(f.run);expect(f.counts).toEqual({launches:0,opens:0,reads:0,writes:0});expect(readFileSync(join(work,'target.txt'),'utf8')).toBe('P');expect(f.driver.snapshot('workflow')).toMatchObject({state:'blocked',reason:'existing_file_publication_unsupported'});expect(f.db.prepare('SELECT count(*) n FROM workspace_write_lease').get()).toEqual({n:1});
 });
 test('capability removed during staging registration is rechecked before adapter launch',async()=>{
  const work=mkdtempSync(join(tmpdir(),'cue-driver-publication-work-'));roots.push(work);writeFileSync(join(work,'target.txt'),'P');const f=fixture(work,'A');f.controls.onOpen=()=>{delete f.candidate.stagedPublication;};await f.driver.start(f.run);expect(f.counts).toEqual({launches:0,opens:1,reads:0,writes:0});expect(readFileSync(join(work,'target.txt'),'utf8')).toBe('P');expect(f.driver.snapshot('workflow')).toMatchObject({state:'blocked',reason:'existing_file_publication_unsupported'});
 });
 test.each([{stageActions:['command']},{stageActions:['write_stdin']},{stageActions:['shell']},{stageActions:['file_change','command']}])('effect-capable actions $stageActions refuse before staging registration or adapter launch',async({stageActions})=>{
  const work=mkdtempSync(join(tmpdir(),'cue-driver-publication-work-'));roots.push(work);writeFileSync(join(work,'target.txt'),'P');const f=fixture(work,'A',true,1000,stageActions.includes('file_change')?undefined:false,stageActions);await f.driver.start(f.run);expect(f.counts).toEqual({launches:0,opens:0,reads:0,writes:0});expect(readFileSync(join(work,'target.txt'),'utf8')).toBe('P');expect(f.driver.snapshot('workflow')).toMatchObject({state:'blocked',reason:'existing_file_publication_unsupported'});
 });
 test.each([{name:'timeout',open:()=>new Promise<void>(()=>{})},{name:'rejection',open:()=>Promise.reject(Error('fixture-registration-rejected'))}])('staging registration $name refuses before adapter launch',async({open})=>{
  const work=mkdtempSync(join(tmpdir(),'cue-driver-publication-work-'));roots.push(work);writeFileSync(join(work,'target.txt'),'P');const f=fixture(work,'A',true,25);f.controls.onOpen=open;await f.driver.start(f.run);expect(f.counts).toEqual({launches:0,opens:1,reads:0,writes:0});expect(readFileSync(join(work,'target.txt'),'utf8')).toBe('P');expect(f.driver.snapshot('workflow')).toMatchObject({state:'blocked',reason:'change_publication_staging_unavailable'});expect(f.db.prepare('SELECT count(*) n FROM workspace_write_lease').get()).toEqual({n:1});expect(f.db.prepare('SELECT count(*) n FROM change_publication_intent').get()).toEqual({n:0});expect(f.db.prepare('SELECT count(*) n FROM change_publication_result').get()).toEqual({n:0});expect(f.db.prepare('SELECT count(*) n FROM orchestration_receipt').get()).toEqual({n:0});
 });
 test.each([{name:'pending',pending:true,result:undefined},{name:'unknown',pending:false,result:{state:'unknown',reason:'fixture'}}])('$name publication cannot finish or release the lease',async({pending,result})=>{
  const work=mkdtempSync(join(tmpdir(),'cue-driver-publication-work-'));roots.push(work);writeFileSync(join(work,'target.txt'),'P');const f=fixture(work,'A');f.controls.throwExecute=pending;f.controls.executeResult=result;const started=f.driver.start(f.run);await until(()=>f.counts.launches===1);f.release();await started;expect(readFileSync(join(work,'target.txt'),'utf8')).toBe('P');expect(f.driver.snapshot('workflow')).toMatchObject({state:'blocked',reason:'change_publication_unresolved'});expect(f.db.prepare('SELECT count(*) n FROM workspace_write_lease').get()).toEqual({n:1});expect(f.db.prepare('SELECT count(*) n FROM orchestration_receipt').get()).toEqual({n:0});expect(f.db.prepare('SELECT count(*) n FROM change_publication_intent').get()).toEqual({n:1});
 });
 test('cancellation or callback timeout after staged read performs no native write',async()=>{
  const work=mkdtempSync(join(tmpdir(),'cue-driver-publication-work-'));roots.push(work);writeFileSync(join(work,'target.txt'),'P');const cancelled=fixture(work,'A');cancelled.controls.onRead=()=>{cancelled.driver.stop('workflow');};const started=cancelled.driver.start(cancelled.run);await until(()=>cancelled.counts.launches===1);cancelled.release();await started;expect(cancelled.counts.writes).toBe(0);expect(readFileSync(join(work,'target.txt'),'utf8')).toBe('P');
  const other=mkdtempSync(join(tmpdir(),'cue-driver-publication-work-'));roots.push(other);writeFileSync(join(other,'target.txt'),'P');const timed=fixture(other,'A',true,25);timed.controls.onRead=()=>new Promise(()=>{});const waiting=timed.driver.start(timed.run);await until(()=>timed.counts.launches===1);timed.release();await waiting;expect(timed.counts).toMatchObject({reads:1,writes:0});expect(readFileSync(join(other,'target.txt'),'utf8')).toBe('P');expect(timed.db.prepare('SELECT count(*) n FROM workspace_write_lease').get()).toEqual({n:1});
 });
 test('callback drift after staged read blocks before native publication',async()=>{
  const work=mkdtempSync(join(tmpdir(),'cue-driver-publication-work-'));roots.push(work);writeFileSync(join(work,'target.txt'),'P');const f=fixture(work,'A');f.controls.onRead=()=>{f.host.finalPublication.authorize=()=>false;};const started=f.driver.start(f.run);await until(()=>f.counts.launches===1);f.release();await started;expect(f.counts).toMatchObject({reads:1,writes:0});expect(readFileSync(join(work,'target.txt'),'utf8')).toBe('P');expect(f.db.prepare('SELECT count(*) n FROM workspace_write_lease').get()).toEqual({n:1});
 });
 test('authorize callback stop is rechecked before intent or native write',async()=>{
  const work=mkdtempSync(join(tmpdir(),'cue-driver-publication-work-'));roots.push(work);writeFileSync(join(work,'target.txt'),'P');const f=fixture(work,'A');let authorizeCalls=0;f.controls.onAuthorize=()=>{authorizeCalls++;f.driver.stop('workflow');return true;};const started=f.driver.start(f.run);await until(()=>f.counts.launches===1);f.release();await started;expect(authorizeCalls).toBe(1);expect(f.counts).toMatchObject({reads:1,writes:0});expect(readFileSync(join(work,'target.txt'),'utf8')).toBe('P');expect(f.db.prepare('SELECT count(*) n FROM change_publication_intent').get()).toEqual({n:0});expect(f.db.prepare('SELECT count(*) n FROM change_publication_result').get()).toEqual({n:0});expect(f.db.prepare('SELECT count(*) n FROM orchestration_receipt').get()).toEqual({n:0});expect(f.db.prepare('SELECT count(*) n FROM workspace_write_lease').get()).toEqual({n:1});
 });
});
