import { mkdtempSync, mkdirSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { isAbsolute, join, relative } from 'node:path';
import { afterEach, describe, expect, test } from 'vitest';
import { createStagedExistingFilePublicationHost } from '../../app/staged-existing-file-publication-host.mjs';
import { stagedPublicationContractId } from '../../app/staged-publication-contract.mjs';
import { identifyChangeSnapshotRoot } from '../src/change-snapshot-host.js';

const roots:string[]=[]; afterEach(()=>{for(const root of roots.splice(0)){const exact=realpathSync.native(root),base=join(realpathSync.native(tmpdir()),'cue-staged-publication-host-');if(!isAbsolute(exact)||!exact.startsWith(base)||relative(exact,root)!=='')throw Error('fixture_cleanup_target_untrusted');rmSync(exact,{recursive:true,force:true});}});
function fixture(){
 const owner=realpathSync.native(mkdtempSync(join(tmpdir(),'cue-staged-publication-host-')));roots.push(owner);const publication=join(owner,'publication'),execution=join(owner,'execution');mkdirSync(publication);mkdirSync(execution);writeFileSync(join(execution,'target.txt'),'replacement\n');
 const observed=identifyChangeSnapshotRoot(execution);if(observed.state!=='ok')throw Error('native helper unavailable');const attemptId='attempt',changeSetId='changes',contractId=stagedPublicationContractId(attemptId,changeSetId);
 const row:any={run_id:'run',task_id:'make',publication_worktree_realpath:publication,execution_worktree_realpath:execution,execution_volume_serial:observed.identity.volumeSerial,execution_file_id:observed.identity.fileId,stage_envelope_hash:'stage',parent_envelope_hash:'parent',plan_digest:'a'.repeat(64),change_set_id:changeSetId,approved_targets_json:'["target.txt"]'};
 let active=true;const db:any={open:true,prepare(sql:string){return{get(...args:any[]){if(sql.includes('FROM attempt_staging_setup'))return active&&args[0]===attemptId&&args[1]===changeSetId?row:undefined;if(sql.includes('FROM change_target_contract'))return args[2]==='target.txt'?{max_backup_bytes:1024}:undefined;if(sql.includes('FROM attempt_staging_authority'))return active?{1:1}:undefined;throw Error('unexpected query');}}}};
 const authority:any[]=[];const host=createStagedExistingFilePublicationHost({db,authorizePublication:(value:any)=>{authority.push(value);return true;}});const contract:any={version:'cue-staged-existing-files-v1',contractId,runId:'run',taskId:'make',attemptId,changeSetId,worktreeRealpath:publication,stagingOnly:true,targets:[{relativePath:'target.txt',maxBytes:1024}]};return{host,contract,authority,expire:()=>{active=false;}};
}
describe.runIf(process.platform==='win32')('production staged existing-file publication host',()=>{
 test('opens only ledger-bound staging and reads exact bytes from the native-identified execution root',async()=>{const f=fixture();await expect(f.host.openStagedAttempt(f.contract)).resolves.toEqual({contractId:f.contract.contractId});await expect(f.host.readStagedReplacement({...f.contract,targets:undefined,version:undefined,worktreeRealpath:undefined} as any)).rejects.toThrow();const input={contractId:f.contract.contractId,runId:'run',taskId:'make',attemptId:'attempt',changeSetId:'changes',relativePath:'target.txt',maxBytes:1024,stagingOnly:true as const};await expect(f.host.readStagedReplacement(input)).resolves.toEqual(Buffer.from('replacement\n'));expect(f.host.authorize({fixture:true} as any)).toBe(true);expect(f.authority).toEqual([{fixture:true}]);f.expire();await expect(f.host.readStagedReplacement(input)).rejects.toThrow('staged_publication_read_expired');},15000);
 test('rejects tampered, duplicate, missing, traversal and unopened contracts',async()=>{const f=fixture();for(const bad of [{...f.contract,contractId:'stage-bad'},{...f.contract,attemptId:'other'},{...f.contract,targets:[]},{...f.contract,targets:[...f.contract.targets,...f.contract.targets]},{...f.contract,targets:[{relativePath:'../target.txt',maxBytes:1024}]},{...f.contract,targets:[{relativePath:'target.txt',maxBytes:1025}]}])await expect(f.host.openStagedAttempt(bad)).rejects.toThrow();await expect(f.host.readStagedReplacement({contractId:f.contract.contractId,runId:'run',taskId:'make',attemptId:'attempt',changeSetId:'changes',relativePath:'target.txt',maxBytes:1024,stagingOnly:true as const})).rejects.toThrow('staged_publication_read_unbound');},15000);
 test('rejects hostile target accessors without invoking them or touching the ledger',async()=>{let getters=0,queries=0;const targets:any[]=[];Object.defineProperty(targets,'0',{enumerable:true,get(){getters++;return{relativePath:'target.txt',maxBytes:1024};}});targets.length=1;const db:any={open:true,prepare(){queries++;throw Error('ledger touched');}};const host=createStagedExistingFilePublicationHost({db,authorizePublication:()=>true});const contract={version:'cue-staged-existing-files-v1',contractId:stagedPublicationContractId('attempt','changes'),runId:'run',taskId:'make',attemptId:'attempt',changeSetId:'changes',worktreeRealpath:'C:\\fixture',stagingOnly:true,targets};await expect(host.openStagedAttempt(contract as any)).rejects.toThrow('staged_publication_contract_invalid');expect({getters,queries}).toEqual({getters:0,queries:0});});
});
