import { afterEach,describe,expect,it,vi } from 'vitest';
import { createHash } from 'node:crypto';
import { linkSync,mkdtempSync,mkdirSync,readFileSync,rmSync,writeFileSync } from 'node:fs';
import { basename,dirname,join,resolve } from 'node:path';import { tmpdir } from 'node:os';
import { openLedger,type Ledger } from '../src/ledger.js';
import { captureChangeSet,observeChangeSet,registerNativeChangeJournal,restoreStoppedChangeSet } from '../src/change-records.js';
import { createHandoffActivityStore } from '../src/orchestration/handoff-activity.js';
const roots:string[]=[],dbs:Ledger[]=[];afterEach(()=>{dbs.splice(0).forEach(db=>db.open&&db.close());const base=resolve(tmpdir());roots.splice(0).forEach(root=>{const target=resolve(root);if(dirname(target)!==base||!basename(target).startsWith('cue-s4-change-'))throw new Error('unsafe_test_cleanup');rmSync(target,{recursive:true,force:true});});});const hash=(v:string|Uint8Array)=>createHash('sha256').update(v).digest('hex');
function fixture(approved=['a.txt']){const root=mkdtempSync(join(tmpdir(),'cue-s4-change-'));roots.push(root);const db=openLedger(join(root,'ledger.db'));dbs.push(db);const work=join(root,'work');mkdirSync(work);const parent=hash('parent'),stage=hash('stage'),plan=hash('plan'),policy=hash('policy'),selection=hash('selection'),subject=hash('subject');db.prepare("INSERT INTO task VALUES('root','running',NULL,'now')").run();db.prepare('INSERT INTO envelope VALUES(?,?,?,?)').run(parent,work,'[]','now');db.prepare("INSERT INTO run VALUES('run','root',?,0,'now')").run(parent);db.prepare("INSERT INTO orchestration_plan VALUES('run',?,?,?)").run(parent,plan,JSON.stringify({revision:'plan',tasks:[{id:'stage',role:'implementation',dependencyIds:[]}]}));db.prepare("INSERT INTO orchestration_step VALUES('run','stage','running')").run();registerNativeChangeJournal(db,{runId:'run',worktreeRealpath:work,targets:approved.map((relativePath,index)=>({taskId:'stage',targetId:`target-${index}`,relativePath,maxBackupBytes:1024})),observedAtMs:0});db.prepare("INSERT INTO orchestration_attempt VALUES('attempt','run','stage','candidate','running','{}',?,NULL,0)").run(work);db.prepare("INSERT INTO task VALUES('stage-task','running',NULL,'now')").run();db.prepare('INSERT INTO envelope VALUES(?,?,?,?)').run(stage,work,'[]','now');db.prepare("INSERT INTO run VALUES('attempt','stage-task',?,0,'now')").run(stage);db.prepare("INSERT INTO orchestration_stage_envelope VALUES('attempt','run','stage','stage-task','attempt',?,?,?,?,?,?,?,?)").run(parent,stage,plan,policy,'{}','{}','{}','{}');db.prepare("INSERT INTO attempt_selection VALUES('attempt','run','request','monetary',?,?)").run(selection,'{}');db.prepare("INSERT INTO workspace_write_lease VALUES(?,'run','now')").run(work);const store=createHandoffActivityStore(db,{authorizeArtifact:()=>false,resolveArtifact:()=>null});store.recordLaunchIntent({runId:'run',taskId:'stage',attemptId:'attempt',candidateId:'candidate',selectionDigest:selection,expectedSubjectDigest:subject,tool:{id:'tool',revision:'r'},model:null,parentEnvelopeHash:parent,stageEnvelopeHash:stage,planDigest:plan,policyDigest:policy});return {work,db,stage,intentId:'attempt'};}
describe('S4 bounded native change records',()=>{
 it('captures and freshly observes exact native bytes',()=>{const f=fixture(['a.txt','new.txt']);writeFileSync(join(f.work,'a.txt'),'before');captureChangeSet(f.db,{changeSetId:'set',runId:'run',taskId:'stage',attemptId:'attempt',stageEnvelopeHash:f.stage,launchIntentId:f.intentId,worktree:f.work,targets:['a.txt','new.txt'],limits:{maxTargets:4,maxBackupBytes:1024},nowMs:1});writeFileSync(join(f.work,'a.txt'),'differ');expect(observeChangeSet(f.db,'set',{nowMs:2}).map(x=>x.status)).toEqual(['modified','unchanged']);writeFileSync(join(f.work,'new.txt'),'created');const fresh=observeChangeSet(f.db,'set',{nowMs:2});expect(fresh.map(x=>x.status)).toEqual(['modified','created']);expect((f.db.prepare('SELECT MAX(observed_at_ms) at FROM change_observation').get() as any).at).toBe(3);});
 it('rejects traversal, aliases, and hard links without a fallback',()=>{const f=fixture();expect(()=>captureChangeSet(f.db,{runId:'run',taskId:'stage',attemptId:'attempt',stageEnvelopeHash:f.stage,launchIntentId:f.intentId,worktree:f.work,targets:['../escape'],limits:{maxTargets:2,maxBackupBytes:20}})).toThrow(/target_invalid/);writeFileSync(join(f.work,'a.txt'),'x');linkSync(join(f.work,'a.txt'),join(f.work,'b.txt'));expect(()=>captureChangeSet(f.db,{runId:'run',taskId:'stage',attemptId:'attempt',stageEnvelopeHash:f.stage,launchIntentId:f.intentId,worktree:f.work,targets:['a.txt'],limits:{maxTargets:2,maxBackupBytes:20}})).toThrow(/snapshot/);expect((f.db.prepare('SELECT COUNT(*) n FROM change_set').get() as any).n).toBe(0);});
 it('rejects stored preimage byte substitution under its original digest label',()=>{const f=fixture();writeFileSync(join(f.work,'a.txt'),'before');captureChangeSet(f.db,{changeSetId:'set',runId:'run',taskId:'stage',attemptId:'attempt',stageEnvelopeHash:f.stage,launchIntentId:f.intentId,worktree:f.work,targets:['a.txt'],limits:{maxTargets:2,maxBackupBytes:20}});const original=f.db.prepare("SELECT sha256 FROM change_entry WHERE change_set_id='set' AND relative_path='a.txt'").get() as {sha256:string};f.db.exec('DROP TRIGGER change_entry_update');f.db.prepare("UPDATE change_entry SET preimage=? WHERE change_set_id='set' AND relative_path='a.txt'").run(Buffer.from('substituted'));expect((f.db.prepare("SELECT sha256 FROM change_entry WHERE change_set_id='set' AND relative_path='a.txt'").get() as {sha256:string}).sha256).toBe(original.sha256);expect(()=>captureChangeSet(f.db,{changeSetId:'set',runId:'run',taskId:'stage',attemptId:'attempt',stageEnvelopeHash:f.stage,launchIntentId:f.intentId,worktree:f.work,targets:['a.txt'],limits:{maxTargets:2,maxBackupBytes:20}})).toThrow('change_set_replay_mismatch');expect((f.db.prepare('SELECT COUNT(*) n FROM change_set').get() as {n:number}).n).toBe(1);});
 it('rejects restore authority before invoking a supplied host',()=>{const f=fixture();writeFileSync(join(f.work,'a.txt'),'x');captureChangeSet(f.db,{changeSetId:'set',runId:'run',taskId:'stage',attemptId:'attempt',stageEnvelopeHash:f.stage,launchIntentId:f.intentId,worktree:f.work,targets:['a.txt'],limits:{maxTargets:2,maxBackupBytes:20}});const replaceIfExact=vi.fn(()=>true),removeIfExact=vi.fn(()=>true);expect(()=>restoreStoppedChangeSet(f.db,'set',{replaceIfExact,removeIfExact})).toThrow('restore_authority_missing');expect(replaceIfExact).not.toHaveBeenCalled();expect(removeIfExact).not.toHaveBeenCalled();});
 it('keeps an authorized stopped restore inert without atomic race closure',()=>{const f=fixture();const target=join(f.work,'a.txt');writeFileSync(target,'before');captureChangeSet(f.db,{changeSetId:'set',runId:'run',taskId:'stage',attemptId:'attempt',stageEnvelopeHash:f.stage,launchIntentId:f.intentId,worktree:f.work,targets:['a.txt'],limits:{maxTargets:2,maxBackupBytes:20}});const payload=Buffer.from(JSON.stringify({schemaVersion:'cue-recovery-decision-v1',decisionId:'fixture-stop',observationId:'fixture-observation',runId:'run',priorAttemptId:'attempt',action:'stop',sourceRevision:0,destinationRevision:null,selectedCandidateId:null}));f.db.pragma('foreign_keys = OFF');f.db.exec('DROP TRIGGER recovery_decision_hash; DROP TRIGGER recovery_decision_payload; DROP TRIGGER recovery_decision_terminal; DROP TRIGGER recovery_decision_current');f.db.prepare('INSERT INTO orchestration_recovery_decision VALUES(?,?,?,?,?,?,?,?,?,?)').run('fixture-stop','run','fixture-observation','attempt','stop',0,null,null,hash(payload),payload);f.db.pragma('foreign_keys = ON');const replaceIfExact=vi.fn(()=>true),removeIfExact=vi.fn(()=>true);expect(restoreStoppedChangeSet(f.db,'set',{replaceIfExact,removeIfExact})).toEqual({restored:false,reason:'atomic-race-closure-unsupported'});expect(replaceIfExact).not.toHaveBeenCalled();expect(removeIfExact).not.toHaveBeenCalled();expect(readFileSync(target,'utf8')).toBe('before');});
});
