import { afterEach,describe,expect,it } from 'vitest';
import type { Ledger } from '../src/ledger.js';
import type { SelectionCandidate } from '../src/selection/policy.js';
import { bindInitialDefault,readInitialDefaultAttempt } from '../src/selection/initial-default.js';
import { createInitialSelectionLedgerFixture,initialSelectionRequest } from './fixtures/initial-selection-ledger.js';

const dbs:Ledger[]=[];afterEach(()=>{for(const db of dbs.splice(0))if(db.open)db.close();});
const checks={eligible:true,authenticated:true,compatible:true,dataAllowed:true,resourceAvailable:true,quotaAvailable:true};
const empirical=(edit:Record<string,unknown>={})=>({scope:'verified-completion-total' as const,quality:.9,expectedCost:2,conservativeMaxCost:3,expectedTimeMs:2,conservativeMaxTimeMs:3,currency:'TEST',source:'facts',observedAtMs:1000,...edit});
function configured(options:Parameters<typeof createInitialSelectionLedgerFixture>[0]={}){const f=createInitialSelectionLedgerFixture(options);dbs.push(f.db);const value=bindInitialDefault(f.db,{version:'cue-initial-default-v1',runId:'run',policyId:f.policy.policyId,policyRevision:f.policy.revision,policyDigest:f.policy.digest,defaultCandidateId:'agent',conservativeEstimate:{scope:'verified-completion-total',quality:.9,expectedCost:20,conservativeMaxCost:30,expectedTimeMs:1000,conservativeMaxTimeMs:2000,currency:'TEST',source:'trusted-baseline',observedAtMs:1000},source:'trusted-host',boundAtMs:1000});return{...f,default:value};}
function noStatistics(f:ReturnType<typeof configured>){f.truth.candidates=[{id:'agent',checks:{...checks},estimate:null}];f.truth.initialObservation={version:'cue-initial-observation-v1',candidateId:'agent',disposition:'no-statistics',source:'trusted-no-samples',observedAtMs:1000};}

describe('S2 initial default engine wiring',()=>{
  it('uses the configured baseline for explicit no-statistics and exact replay invokes no callbacks',async()=>{const f=configured();noStatistics(f);expect(await f.engine.start(f.plan,initialSelectionRequest)).toMatchObject({candidateId:'agent',replayed:false,launch:'started'});expect(readInitialDefaultAttempt(f.db,'attempt-1')).toMatchObject({disposition:'no-statistics',candidateId:'agent',observation:{source:'trusted-no-samples',observedAtMs:1000}});expect(await f.engine.start(f.plan,initialSelectionRequest)).toMatchObject({replayed:true,launch:'not-relaunched'});expect(f.truth).toMatchObject({observations:1,initialObservations:1,authorizations:1,reservations:1,preparations:1,launches:1});expect(f.db.prepare('SELECT COUNT(*) n FROM integration_budget_reservation').get()).toEqual({n:1});});
  it('keeps the no-config path exact and a configured null hook records only a legacy marker',async()=>{const legacy=createInitialSelectionLedgerFixture();dbs.push(legacy.db);await legacy.engine.start(legacy.plan,initialSelectionRequest);expect(legacy.truth.initialObservations).toBe(0);expect(readInitialDefaultAttempt(legacy.db,'attempt-1')).toBeNull();const f=configured({candidateIds:['agent','known']});f.truth.candidates=[{id:'agent',checks:{...checks},estimate:null},{id:'known',checks:{...checks},estimate:empirical({expectedCost:1,conservativeMaxCost:1})}];f.truth.initialObservation=null;expect((await f.engine.start(f.plan,initialSelectionRequest)).candidateId).toBe('known');expect(readInitialDefaultAttempt(f.db,'attempt-1')).toMatchObject({disposition:'legacy-observation-absent',candidateId:'known',observation:null});});
  it('snapshots candidates before the initial hook can mutate them',async()=>{const f=configured(),candidate:SelectionCandidate={id:'agent',checks:{...checks},estimate:null};f.host.observeCandidates=()=>[candidate];f.host.observeInitialSelection=()=>{(candidate.checks as {eligible:boolean}).eligible=false;return{version:'cue-initial-observation-v1',candidateId:'agent',disposition:'no-statistics',source:'trusted',observedAtMs:1000}};expect((await f.engine.start(f.plan,initialSelectionRequest)).candidateId).toBe('agent');});
  it('never overwrites non-null stale, low-quality, wrong-currency, or required unknown-bound facts',async()=>{for(const estimate of [empirical({observedAtMs:899}),empirical({quality:.4}),empirical({currency:'USD'}),empirical({conservativeMaxCost:null}),empirical({conservativeMaxTimeMs:null})]){const f=configured({costLimit:100,remainingTimeMs:5000});f.truth.candidates=[{id:'agent',checks:{...checks},estimate} as SelectionCandidate];f.truth.initialObservation=null;await expect(f.engine.start(f.plan,initialSelectionRequest)).rejects.toThrow(/engine_selection/);expect(f.truth.launches).toBe(0);}});
  it('rejects a no-statistics declaration when valid empirical facts exist',async()=>{const f=configured();f.truth.candidates=[{id:'agent',checks:{...checks},estimate:empirical()}];f.truth.initialObservation={version:'cue-initial-observation-v1',candidateId:'agent',disposition:'no-statistics',source:'trusted',observedAtMs:1000};await expect(f.engine.start(f.plan,initialSelectionRequest)).rejects.toThrow(/contradicts_empirical/);expect(readInitialDefaultAttempt(f.db,'attempt-1')).toBeNull();expect(f.truth.launches).toBe(0);});
  it('retains every eligibility check and rejects pin, task, plan, and forced mismatches',async()=>{for(const key of Object.keys(checks) as (keyof typeof checks)[]){const f=configured();noStatistics(f);if(key==='eligible')f.truth.eligible=false;else f.truth.candidates[0]={...f.truth.candidates[0]!,checks:{...checks,[key]:false}};await expect(f.engine.start(f.plan,initialSelectionRequest)).rejects.toThrow(/engine_selection/);expect(f.truth.launches).toBe(0);}const pinned=configured({candidateIds:['agent','pinned'],pinnedCandidateId:'pinned'});noStatistics(pinned);pinned.truth.candidates.push({id:'pinned',checks:{...checks},estimate:empirical()});await expect(pinned.engine.start(pinned.plan,initialSelectionRequest)).rejects.toThrow(/pin-unavailable/);const forced=configured({candidateIds:['agent','other']});noStatistics(forced);await expect(forced.engine.start(forced.plan,{...initialSelectionRequest,revision:0,planDigest:forced.plan.digest,recoveryDecisionId:'recovery',forcedCandidateId:'other'})).rejects.toThrow(/engine_selection/);});
  it('rejects stale, malformed, proxy, and accessor observations without traps or launch',async()=>{const stale=configured();noStatistics(stale);stale.truth.initialObservation={...(stale.truth.initialObservation as object),observedAtMs:899};await expect(stale.engine.start(stale.plan,initialSelectionRequest)).rejects.toThrow(/stale_or_mismatched/);const hostile=configured();noStatistics(hostile);let traps=0;hostile.truth.initialObservation=new Proxy({}, {get(){traps++;throw Error('trap')}});await expect(hostile.engine.start(hostile.plan,initialSelectionRequest)).rejects.toThrow(/observation_invalid/);expect(traps).toBe(0);const accessor=configured();noStatistics(accessor);const observation={version:'cue-initial-observation-v1',candidateId:'agent',disposition:'no-statistics',source:'trusted',observedAtMs:1000};Object.defineProperty(observation,'source',{enumerable:true,get(){traps++;return'trusted'}});accessor.truth.initialObservation=observation;await expect(accessor.engine.start(accessor.plan,initialSelectionRequest)).rejects.toThrow(/observation_invalid/);expect(traps).toBe(0);});
  it('requires the configured marker on replay and rolls it back with later preparation failure',async()=>{const missing=configured();noStatistics(missing);await missing.engine.start(missing.plan,initialSelectionRequest);missing.db.exec('DROP TRIGGER initial_default_attempt_delete');missing.db.prepare("DELETE FROM initial_default_attempt WHERE attempt_id='attempt-1'").run();await expect(missing.engine.start(missing.plan,initialSelectionRequest)).rejects.toThrow(/replay_binding_missing/);expect(missing.truth.launches).toBe(1);const failed=configured();noStatistics(failed);failed.truth.failPreparation=true;await expect(failed.engine.start(failed.plan,initialSelectionRequest)).rejects.toThrow('fixture_prepare_failure');expect(failed.db.prepare('SELECT COUNT(*) n FROM initial_default_attempt').get()).toEqual({n:0});expect(failed.db.prepare('SELECT COUNT(*) n FROM orchestration_attempt').get()).toEqual({n:0});expect(failed.db.prepare('SELECT COUNT(*) n FROM integration_budget_reservation').get()).toEqual({n:0});expect(failed.db.prepare("SELECT COUNT(*) n FROM artifact WHERE kind='initial-selection-baseline'").get()).toEqual({n:0});});
});
