import { afterEach,describe,expect,it,vi } from 'vitest';
import { createHash } from 'node:crypto';
import { mkdtempSync,rmSync } from 'node:fs';import { join } from 'node:path';import { tmpdir } from 'node:os';
import { openLedger,type Ledger } from '../src/ledger.js';import { createHeldRecovery,reconcileHeldRecovery,recordExternalEffectIntent,type ExternalEffectObserver,type ExternalEffectVerifier } from '../src/held-recovery.js';
const roots:string[]=[];const dbs:Ledger[]=[];afterEach(()=>{dbs.splice(0).forEach(db=>db.open&&db.close());roots.splice(0).forEach(root=>rmSync(root,{recursive:true,force:true}));});const hash=(x:string|Uint8Array)=>createHash('sha256').update(x).digest('hex');
function seed(){const root=mkdtempSync(join(tmpdir(),'cue-s4-held-'));roots.push(root);const db=openLedger(join(root,'ledger.db'));dbs.push(db);const envelope=hash('e');db.prepare("INSERT INTO task VALUES('task','running',NULL,'now')").run();db.prepare("INSERT INTO envelope VALUES(?,?,'[]','now')").run(envelope,root);db.prepare("INSERT INTO run VALUES('run','task',?,0,'now')").run(envelope);db.prepare("INSERT INTO orchestration_plan VALUES('run',?,?,?)").run(envelope,hash('plan'),'{}');db.prepare("INSERT INTO orchestration_step VALUES('run','step','running')").run();db.prepare("INSERT INTO orchestration_attempt VALUES('attempt','run','step','candidate','failed','{}',?,NULL,1)").run(root);return db;}
function ready(db:Ledger,status:'confirmed-applied'|'confirmed-not-applied'='confirmed-not-applied'){
  const evidence=Buffer.from('provider-authenticated-receipt'),transition=hash('transition');
  db.exec('DROP TRIGGER change_set_lineage; DROP TRIGGER change_set_targets');const launch=Buffer.from('{"fixture":"launch"}');db.prepare('INSERT INTO orchestration_launch_intent VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run('attempt','run','step','candidate',hash('selection'),hash('subject'),'tool','r1',null,null,hash('e'),hash('e'),hash('plan'),hash('policy'),hash(launch),launch);const set={schemaVersion:'cue-change-set-v1',changeSetId:'changes',runId:'run',taskId:'step',attemptId:'attempt',stageEnvelopeHash:hash('e'),launchIntentId:'attempt',worktreeRealpath:'fixture',targets:['file'],limits:{maxTargets:1,maxBackupBytes:1},preimageManifestDigest:hash('manifest'),createdAtMs:1},se=JSON.stringify(set);
  db.prepare('INSERT INTO change_set VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run('changes','run','step','attempt',hash('e'),'attempt','fixture','["file"]','{"maxTargets":1,"maxBackupBytes":1}',hash('manifest'),1,hash(se),Buffer.from(se));
  const entry={schemaVersion:'cue-change-entry-v1',relativePath:'file',objectKind:'absent',canonicalParent:'fixture',canonicalRealpath:null,fileIdentity:null,byteLength:null,sha256:null,comparisonHash:null,restorable:true,restorableReason:'created-file-removable'},ee=JSON.stringify(entry);db.prepare('INSERT INTO change_entry VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run('changes',0,'file','absent','fixture',null,null,null,null,1,'created-file-removable',null,hash(ee),Buffer.from(ee));
  const change={...entry,schemaVersion:'cue-change-observation-v1',observationId:'change-observation',changeSetId:'changes',ordinal:0,status:'unchanged',observedAtMs:1},ce=JSON.stringify(change);db.prepare('INSERT INTO change_observation VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run('change-observation','changes',0,'unchanged','absent','fixture',null,null,null,null,null,1,hash(ce),Buffer.from(ce));
  createHeldRecovery(db,{caseId:'case',attemptId:'attempt',changeSetId:'changes',reason:'interrupted',nowMs:1});recordExternalEffectIntent(db,{intentId:'effect',attemptId:'attempt',operation:'mail',accountId:'account',resourceId:'resource',idempotencyKey:'key',expectedTransitionDigest:transition,nowMs:1});
  const result={status,observedAtMs:2,accountId:'account',resourceId:'resource',evidenceRef:'provider:receipt/1',evidenceSha256:hash(evidence),providerRevision:'provider-r1',finality:'final' as const,details:{provider:'fixture'}};
  const observer:ExternalEffectObserver={id:'observer',revision:'observer-r1',observe:vi.fn(async intent=>{expect(Object.isFrozen(intent)).toBe(true);return result;})};
  const verifier:ExternalEffectVerifier={id:'deployment-verifier',revision:'deploy-r1',verify:vi.fn(async request=>{expect(Object.isFrozen(request)).toBe(true);expect(request.intent).toMatchObject({intentId:'effect',attemptId:'attempt',operation:'mail',idempotencyKey:'key',expectedTransitionDigest:transition});expect(request.observer).toEqual({id:'observer',revision:'observer-r1'});return {authenticated:true as const,intent:{...request.intent},observer:{...request.observer},status:request.observation.status,observedAtMs:request.observation.observedAtMs,accountId:request.observation.accountId,resourceId:request.observation.resourceId,evidenceRef:request.observation.evidenceRef,evidenceSha256:request.observation.evidenceSha256,providerRevision:request.observation.providerRevision,finality:'final' as const,evidence};})};return{observer,verifier,evidence,result};
}
describe('S4 held recovery',()=>{it('persists unknown work and never invokes start, resume, reserve, restore, or resend callbacks',async()=>{const db=seed();createHeldRecovery(db,{caseId:'case',attemptId:'attempt',reason:'interrupted',nowMs:1});recordExternalEffectIntent(db,{intentId:'effect',attemptId:'attempt',operation:'mail',accountId:'account',resourceId:'resource',idempotencyKey:'key',expectedTransitionDigest:hash('transition'),nowMs:1});const forbidden=vi.fn(()=>{throw Error('must not run');});const result=await reconcileHeldRecovery(db,'case',new Map(),2);expect(result.state).toBe('held');expect(forbidden).not.toHaveBeenCalled();expect(db.prepare("SELECT state,revision FROM held_recovery WHERE case_id='case'").get()).toEqual({state:'held',revision:0});expect(db.pragma('foreign_key_check')).toEqual([]);});
it('rejects raw stale transitions and immutable-row tampering',()=>{const db=seed();createHeldRecovery(db,{caseId:'case',attemptId:'attempt',reason:'interrupted',nowMs:1});expect(()=>db.prepare("UPDATE held_recovery SET state='eligible-for-disposition',revision=1 WHERE case_id='case'").run()).toThrow(/invalid transition|payload mismatch/);expect(()=>db.prepare("DELETE FROM held_recovery WHERE case_id='case'").run()).toThrow(/immutable/);});});

describe('S4 authenticated external observations',()=>{
  it.each([['confirmed-not-applied','eligible-for-disposition'],['confirmed-applied','reconciled-stop']] as const)('persists an auditable v2 %s receipt before the decisive transition',async(status,state)=>{const db=seed(),f=ready(db,status);const result=await reconcileHeldRecovery(db,'case',new Map([['mail',f.observer]]),3,()=>true,()=>true,f.verifier);expect(result).toMatchObject({state,revision:1});const row=db.prepare("SELECT * FROM external_effect_observation WHERE intent_id='effect'").get() as any,payload=JSON.parse(Buffer.from(row.payload).toString('utf8'));expect(payload).toMatchObject({schemaVersion:'cue-external-effect-observation-v2',intentId:'effect',intent:{intentId:'effect',attemptId:'attempt',accountId:'account',resourceId:'resource',idempotencyKey:'key',expectedTransitionDigest:hash('transition')},observer:{id:'observer',revision:'observer-r1'},evidence:{ref:'provider:receipt/1',sha256:hash(f.evidence),providerRevision:'provider-r1',finality:'final',verifierId:'deployment-verifier',verifierRevision:'deploy-r1'}});expect(hash(Buffer.from(row.payload).toString('utf8'))).toBe(row.payload_sha256);expect(db.pragma('foreign_key_check')).toEqual([]);});
  it('keeps held and inserts no decisive row when verifier is absent, malformed, mismatched, throws, or replays another binding',async()=>{for(const mode of ['absent','malformed','mismatch','throw','replay'] as const){const db=seed(),f=ready(db),base=await f.verifier.verify(Object.freeze({intent:{intentId:'effect',attemptId:'attempt',operation:'mail',accountId:'account',resourceId:'resource',idempotencyKey:'key',expectedTransitionDigest:hash('transition'),createdAtMs:1},observer:{id:'observer',revision:'observer-r1'},observation:f.result})),verifier=mode==='absent'?undefined:mode==='malformed'?{...f.verifier,verify:async()=>({authenticated:false}) as any}:mode==='mismatch'?{...f.verifier,verify:async()=>({...base,evidence:Buffer.from('wrong')})}:mode==='replay'?{...f.verifier,verify:async()=>({...base,intent:{...base.intent,intentId:'other'}})}:{...f.verifier,verify:async()=>{throw Error('denied');}};const result=await reconcileHeldRecovery(db,'case',new Map([['mail',f.observer]]),3,()=>true,()=>true,verifier as any);expect(result).toMatchObject({state:'held',revision:0});expect(db.prepare('SELECT COUNT(*) n FROM external_effect_observation').get()).toEqual({n:0});db.close();dbs.splice(dbs.indexOf(db),1);}}
  );
  it('does not discard historical unknown/conflict or let a legacy assertion acquire authority',async()=>{for(const historical of ['unknown','conflict','legacy'] as const){const db=seed(),f=ready(db);const insert=(id:string,status:string)=>{const body={schemaVersion:'cue-external-effect-observation-v1',observationId:id,intentId:'effect',status,observerId:'legacy',observerRevision:'r0',observedAtMs:1,accountId:'account',resourceId:'resource',details:null},encoded=JSON.stringify(body);db.prepare('INSERT INTO external_effect_observation VALUES(?,?,?,?,?,?,?,?)').run(id,'effect',status,'legacy','r0',1,hash(encoded),Buffer.from(encoded));};if(historical==='unknown')insert('old-unknown','unknown');else if(historical==='conflict'){insert('old-a','confirmed-applied');insert('old-b','confirmed-not-applied');}else insert('old-legacy','confirmed-not-applied');const result=await reconcileHeldRecovery(db,'case',historical==='legacy'?new Map():new Map([['mail',f.observer]]),3,()=>true,()=>true,historical==='legacy'?undefined:f.verifier);expect(result).toMatchObject({state:'held',revision:0});expect(db.prepare("SELECT COUNT(*) n FROM external_effect_observation WHERE json_extract(payload,'$.schemaVersion')='cue-external-effect-observation-v2'").get()).toEqual({n:0});db.close();dbs.splice(dbs.indexOf(db),1);}});
  it('rejects accessor details, stale observations, and proxied verifier bytes without invoking hostile properties',async()=>{for(const mode of ['accessor','stale','proxy-bytes'] as const){const db=seed(),f=ready(db),touched=vi.fn(),observer:ExternalEffectObserver={...f.observer,observe:async()=>mode==='accessor'?{...f.result,details:Object.defineProperty({},'secret',{enumerable:true,get(){touched();return 'x';}})}:mode==='stale'?{...f.result,observedAtMs:0}:f.result},verifier:ExternalEffectVerifier={...f.verifier,verify:async request=>({...await f.verifier.verify(request),evidence:new Proxy(f.evidence,{})})};const result=await reconcileHeldRecovery(db,'case',new Map([['mail',observer]]),3,()=>true,()=>true,verifier);expect(result).toMatchObject({state:'held',revision:0});expect(touched).not.toHaveBeenCalled();expect(db.prepare('SELECT COUNT(*) n FROM external_effect_observation').get()).toEqual({n:0});db.close();dbs.splice(dbs.indexOf(db),1);}});
  it.each(['observer','verifier'] as const)('bounds a pending %s callback and leaves every decisive counter unchanged',async(mode)=>{vi.useFakeTimers();try{const db=seed(),f=ready(db),observer:ExternalEffectObserver=mode==='observer'?{...f.observer,observe:async()=>new Promise(()=>{})}:f.observer,verifier:ExternalEffectVerifier=mode==='verifier'?{...f.verifier,verify:async()=>new Promise(()=>{})}:f.verifier,pending=reconcileHeldRecovery(db,'case',new Map([['mail',observer]]),3,()=>true,()=>true,verifier);await vi.advanceTimersByTimeAsync(5001);await expect(pending).resolves.toMatchObject({state:'held',revision:0});expect(db.prepare('SELECT COUNT(*) n FROM external_effect_observation').get()).toEqual({n:0});}finally{vi.useRealTimers();}});
  it('rejects a compact shared-reference DAG before verifier invocation',async()=>{const db=seed(),f=ready(db);let dag:unknown={leaf:true};for(let i=0;i<24;i++)dag={a:dag,b:dag};const observer:ExternalEffectObserver={...f.observer,observe:async()=>({...f.result,details:dag})};await expect(reconcileHeldRecovery(db,'case',new Map([['mail',observer]]),3,()=>true,()=>true,f.verifier)).resolves.toMatchObject({state:'held',revision:0});expect(f.verifier.verify).not.toHaveBeenCalled();expect(db.prepare('SELECT COUNT(*) n FROM external_effect_observation').get()).toEqual({n:0});});
});
