import { describe,expect,it } from 'vitest';
import { createNativeExistingFileContract,verifyNativeExistingFileArtifacts } from '../src/verification/native-existing-file-checker.js';
const h=(c:string)=>c.repeat(64);
const target={targetId:'target',relativePath:'src/target.ts',maxBytes:100,expectedSha256:h('a'),expectedByteLength:12,originalSha256:h('b')};
describe('native deterministic existing-file checker',()=>{
 it('commits exact expected bytes and accepts only the exact artifact set',()=>{const c=createNativeExistingFileContract([target]);expect(c.parametersDigest).toMatch(/^[a-f0-9]{64}$/);expect(verifyNativeExistingFileArtifacts(c,[{targetId:'target',relativePath:'src/target.ts',sha256:h('a'),byteLength:12,sourceRef:'staged:x'}])).toEqual({verdict:'pass',reasons:[]});for(const changed of [{sha256:h('c')},{byteLength:13},{relativePath:'src/other.ts'}])expect(verifyNativeExistingFileArtifacts(c,[{targetId:'target',relativePath:'src/target.ts',sha256:h('a'),byteLength:12,sourceRef:'staged:x',...changed}]).verdict).toBe('fail');});
 it('rejects missing extra duplicate unchanged and hostile expectations before callbacks',()=>{expect(()=>createNativeExistingFileContract([])).toThrow();expect(()=>createNativeExistingFileContract([target,target])).toThrow();expect(()=>createNativeExistingFileContract([{...target,expectedSha256:target.originalSha256}])).toThrow();const hostile={};Object.defineProperty(hostile,'targetId',{enumerable:true,get(){throw Error('read')}});expect(()=>createNativeExistingFileContract([hostile])).toThrow('fields');const accessor:any=[];Object.defineProperty(accessor,'0',{enumerable:true,get(){throw Error('touched')}});Object.defineProperty(accessor,'length',{value:1});expect(()=>createNativeExistingFileContract(accessor)).toThrow('targets');const c=createNativeExistingFileContract([target]);expect(verifyNativeExistingFileArtifacts(c,[]).verdict).toBe('fail');expect(verifyNativeExistingFileArtifacts(c,[{targetId:'target',relativePath:'src/target.ts',sha256:h('a'),byteLength:12,sourceRef:'x'},{targetId:'extra',relativePath:'x',sha256:h('a'),byteLength:1,sourceRef:'x'}]).verdict).toBe('fail');});
});

