import { afterEach,describe,expect,it } from 'vitest';
import { createExplorationBudgetStore } from '../src/selection/exploration-budget.js';
import { createBudgetManager } from '../src/budget.js';
import { bindInitialDefault } from '../src/selection/initial-default.js';
import { createLocalOrchestrationEngine } from '../src/orchestration/engine.js';
import { createInitialSelectionLedgerFixture,initialSelectionRequest } from './fixtures/initial-selection-ledger.js';

const dbs:ReturnType<typeof createInitialSelectionLedgerFixture>['db'][]=[];
afterEach(()=>{for(const db of dbs.splice(0))if(db.open)db.close();});
function fixture(options:Parameters<typeof createInitialSelectionLedgerFixture>[0]={}){const f=createInitialSelectionLedgerFixture(options);dbs.push(f.db);return f;}
function grant(f:ReturnType<typeof fixture>,limitUnits=60){return createExplorationBudgetStore(f.db).preauthorize({runId:'run',policyId:f.policy.policyId,policyRevision:f.policy.revision,policyDigest:f.policy.digest,candidateId:'agent',currency:'TEST',unit:'micro',limitUnits,authorizedAt:'2026-09-14T00:00:00.000Z',sourceVersion:'engine-test-v1'});}
function request(digest:string,candidateId='agent'){return {...initialSelectionRequest,exploration:{version:'cue-exploration-request-v1' as const,authorizationDigest:digest,candidateId}};}

describe('S2 explicit exploration engine wiring',()=>{
  it('keeps a grant inert without an explicit flag',async()=>{const f=fixture(),a=grant(f);await f.engine.start(f.plan,initialSelectionRequest);expect(a.candidateId).toBe('agent');expect(f.db.prepare('SELECT count(*) n FROM exploration_budget_reservation').get()).toEqual({n:0});});
  it('atomically reserves ordinary and exploration budgets and exact replay launches once',async()=>{const f=fixture(),a=grant(f),input=request(a.payloadSha256);await f.engine.start(f.plan,input);expect(f.db.prepare('SELECT count(*) n FROM exploration_budget_reservation').get()).toEqual({n:1});expect(f.budget.summary('run').committedUnits).toBe(40n);await f.engine.start(f.plan,input);expect(f.truth).toMatchObject({launches:1,observations:1,authorizations:1,reservations:1,preparations:1});expect(createExplorationBudgetStore(f.db).summary('run').committedUnits).toBe(40n);});
  it('rejects missing, wrong digest, candidate, and pin mismatch before launch',async()=>{for(const mode of ['missing','digest','candidate','pin'] as const){const f=fixture(mode==='pin'?{candidateIds:['agent','other'],pinnedCandidateId:'other'}:{});const a=mode==='missing'?null:grant(f);const digest=mode==='digest'?'0'.repeat(64):a?.payloadSha256??'0'.repeat(64);await expect(f.engine.start(f.plan,request(digest,mode==='candidate'?'other':'agent'))).rejects.toThrow();expect(f.truth.launches).toBe(0);expect(f.db.prepare('SELECT count(*) n FROM integration_budget_reservation').get()).toEqual({n:0});}});
  it('rejects nested proxies and accessors without invoking them',async()=>{const f=fixture(),a=grant(f);let calls=0;await expect(f.engine.start(f.plan,{...initialSelectionRequest,exploration:new Proxy({version:'cue-exploration-request-v1',authorizationDigest:a.payloadSha256,candidateId:'agent'}, {}) as never})).rejects.toThrow(/invalid_engine_exploration/);await expect(f.engine.start(f.plan,{...initialSelectionRequest,exploration:{version:'cue-exploration-request-v1',authorizationDigest:a.payloadSha256,get candidateId(){calls++;return'agent';}} as never})).rejects.toThrow(/invalid_engine_exploration/);expect(calls).toBe(0);expect(f.truth.observations).toBe(0);});
  it('snapshots caller intent and rejects missing or extra nested fields',async()=>{const f=fixture(),a=grant(f),exploration={version:'cue-exploration-request-v1' as const,authorizationDigest:a.payloadSha256,candidateId:'agent'},input={...initialSelectionRequest,exploration};const started=f.engine.start(f.plan,input);exploration.candidateId='mutated';await started;expect(f.truth.launches).toBe(1);for(const bad of [{version:'cue-exploration-request-v1',authorizationDigest:a.payloadSha256},{version:'cue-exploration-request-v1',authorizationDigest:a.payloadSha256,candidateId:'agent',extra:true}])await expect(f.engine.start(f.plan,{...initialSelectionRequest,attemptId:'bad-'+Object.keys(bad).length,requestId:'bad-'+Object.keys(bad).length,exploration:bad as never})).rejects.toThrow(/invalid_engine_exploration/);});
  it('fails explicit exploration on missing 041 schema while no-flag selection does not query it',async()=>{const ordinary=fixture();ordinary.db.exec('DROP TABLE exploration_budget_reservation; DROP TABLE exploration_budget_authorization');await ordinary.engine.start(ordinary.plan,initialSelectionRequest);expect(ordinary.truth.launches).toBe(1);const explicit=fixture(),a=grant(explicit);explicit.db.exec('DROP TABLE exploration_budget_reservation; DROP TABLE exploration_budget_authorization');await expect(explicit.engine.start(explicit.plan,request(a.payloadSha256))).rejects.toThrow(/migration_unavailable/);expect(explicit.truth.observations).toBe(0);});
  it('rejects a missing runtime guard before host callbacks or reservation side effects',async()=>{const f=fixture(),a=grant(f);let callbacks=0;f.host.verifyBudgetMapping=()=>{callbacks++;return true};f.db.exec('DROP TRIGGER exploration_budget_reservation_no_update');await expect(f.engine.start(f.plan,request(a.payloadSha256))).rejects.toThrow(/migration_unavailable/);expect(callbacks).toBe(0);expect(f.truth).toMatchObject({launches:0,observations:0,authorizations:0,reservations:0,preparations:0});for(const table of ['integration_budget_reservation','exploration_budget_reservation','orchestration_attempt','artifact'])expect(f.db.prepare(`SELECT count(*) n FROM ${table}`).get()).toEqual({n:0});});
  it('rejects explicit exploration on the local engine before policy or host side effects',async()=>{const f=fixture(),a=grant(f);let effects=0;const local=createLocalOrchestrationEngine(f.db,{} as never,{maxRequestAgeMs:1000,now:()=>{effects++;return 1000},observeCandidate:()=>{effects++;return{} as never},authorizeExecution:()=>{effects++;return true},prepareExecution:()=>{effects++;return undefined},receipts:()=>{effects++;return{execution:null}}});await expect(local.start(f.plan,request(a.payloadSha256))).rejects.toThrow(/local_engine_exploration_unsupported/);expect(effects).toBe(0);});
  it('rejects exploration combined with a configured no-statistics fallback',async()=>{const f=fixture(),a=grant(f);bindInitialDefault(f.db,{version:'cue-initial-default-v1',runId:'run',policyId:f.policy.policyId,policyRevision:f.policy.revision,policyDigest:f.policy.digest,defaultCandidateId:'agent',conservativeEstimate:{scope:'verified-completion-total',quality:1,expectedCost:1,conservativeMaxCost:1,expectedTimeMs:1,conservativeMaxTimeMs:1,currency:'TEST',source:'trusted',observedAtMs:1000},source:'trusted',boundAtMs:1000});f.truth.candidates=[{...f.truth.candidates[0]!,estimate:null}];f.truth.initialObservation={version:'cue-initial-observation-v1',candidateId:'agent',disposition:'no-statistics',source:'host',observedAtMs:1000};await expect(f.engine.start(f.plan,request(a.payloadSha256))).rejects.toThrow(/conflict/);expect(f.truth.launches).toBe(0);});
  it('retains ordinary stale and required-bound filters for enrolled candidates',async()=>{const f=fixture({costLimit:10}),a=grant(f);f.truth.candidates=[{...f.truth.candidates[0]!,estimate:{...f.truth.candidates[0]!.estimate!,conservativeMaxCost:null}}];await expect(f.engine.start(f.plan,request(a.payloadSha256))).rejects.toThrow(/engine_selection/);expect(f.truth.authorizations).toBe(0);});
  it('rolls back both reservations and claim when later preparation fails',async()=>{const f=fixture(),a=grant(f);f.truth.failPreparation=true;await expect(f.engine.start(f.plan,request(a.payloadSha256))).rejects.toThrow('fixture_prepare_failure');for(const table of ['integration_budget_reservation','exploration_budget_reservation','orchestration_attempt','artifact'])expect(f.db.prepare(`SELECT count(*) n FROM ${table}`).get()).toEqual({n:0});});
  it('denies a new exploration when authoritative overrun creates subcap debt while ordinary room remains',async()=>{const f=fixture(),a=grant(f,40),store=createExplorationBudgetStore(f.db);f.db.transaction(()=>{f.budget.reserve({runId:'run',requestId:'prior',attemptId:'prior-attempt',currency:'TEST',unit:'micro',upperUnits:40,source:'fixture',observedAtMs:1000,scope:'verified-completion-attempt-total'});store.reserve({runId:'run',requestId:'prior',attemptId:'prior-attempt',candidateId:'agent',upperUnits:40});}).immediate();const trusted=createBudgetManager(f.db,{verifyFinalReceipt:r=>r.source==='trusted'});trusted.observe({runId:'run',requestId:'prior',receiptId:'final',revision:1,currency:'TEST',unit:'micro',kind:'actual',units:50,providerFinal:true,source:'trusted',observedAtMs:1001});expect(f.budget.summary('run').remainingUnits).toBe(50n);expect(store.summary('run').debtUnits).toBe(10n);await expect(f.engine.start(f.plan,request(a.payloadSha256))).rejects.toThrow(/limit_exceeded/);expect(f.db.prepare("SELECT count(*) n FROM orchestration_attempt WHERE attempt_id='attempt-1'").get()).toEqual({n:0});expect(f.db.prepare("SELECT count(*) n FROM integration_budget_reservation WHERE request_id='request-1'").get()).toEqual({n:0});});
  it('requires matching replay linkage and changed intent fails the request journal',async()=>{const f=fixture(),a=grant(f),input=request(a.payloadSha256);await f.engine.start(f.plan,input);const guard=f.db.prepare("SELECT sql FROM sqlite_master WHERE type='trigger' AND name='exploration_budget_reservation_no_delete'").get() as {sql:string};f.db.exec('DROP TRIGGER exploration_budget_reservation_no_delete');f.db.prepare('DELETE FROM exploration_budget_reservation').run();f.db.exec(guard.sql);await expect(f.engine.start(f.plan,input)).rejects.toThrow(/replay_binding_missing/);await expect(f.engine.start(f.plan,{...initialSelectionRequest})).rejects.toThrow(/replay_mismatch/);});
  it('revalidates canonical exploration and ordinary reservation lineage on replay',async()=>{for(const target of ['payload','upper'] as const){const f=fixture(),a=grant(f),input=request(a.payloadSha256);await f.engine.start(f.plan,input);if(target==='payload'){const guard=f.db.prepare("SELECT sql FROM sqlite_master WHERE type='trigger' AND name='exploration_budget_reservation_no_update'").get() as {sql:string};f.db.exec('DROP TRIGGER exploration_budget_reservation_no_update');f.db.prepare("UPDATE exploration_budget_reservation SET payload='{}'").run();f.db.exec(guard.sql);}else f.db.prepare('UPDATE integration_budget_reservation SET upper_units=41').run();await expect(f.engine.start(f.plan,input)).rejects.toThrow(/corrupt_reservation/);expect(f.truth.launches).toBe(1);}});
});
