import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import { createHash } from 'node:crypto';
import { mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { openLedger, type Ledger } from '../src/ledger.js';
import { measureReadonlyVerifierControl, snapshotReadonlyVerifierControl, verifyReadonlyVerifierControl } from '../src/readonly-verifier-control.js';
import { renderReadonlyWfpLauncher, sha256 } from '../scripts/build-readonly-wfp-launcher.mjs';

type Mode='failure'|'tamper-acl';
const state=vi.hoisted(()=>({mode:'failure' as Mode,spawns:0,launcher:'',expected:Buffer.alloc(0),decoded:Buffer.alloc(0)}));
vi.mock('../src/change-snapshot-host.js',()=>({identifyChangeSnapshotRoot:()=>({state:'ok',identity:{volumeSerial:'1',fileId:'2'}})}));
vi.mock('../src/process-termination.js',()=>({terminateVerifiedTree:vi.fn(),verifyProcessesDead:vi.fn()}));
vi.mock('../src/process-launch.js',()=>{
 class Events{listeners=new Map<string,((v:any)=>void)[]>();on(n:string,f:(v:any)=>void){this.listeners.set(n,[...(this.listeners.get(n)??[]),f]);return this;}once(n:string,f:(v:any)=>void){return this.on(n,f);}emit(n:string,v?:any){for(const f of this.listeners.get(n)??[])f(v);}}
 return{resolveOwnedExecutable:()=> 'C:\\Windows\\powershell.exe',spawnOwned:(db:any,owner:any)=>{const index=state.spawns++,child=new Events() as any;child.stdout=new Events();child.stderr=new Events();child.pid=800+index;child.exitCode=null;child.kill=vi.fn();
  if(index===0)queueMicrotask(()=>{child.stdout.emit('data','O:BAG:BAD:(A;;FA;;;SY)');if(state.mode==='tamper-acl')writeFileSync(state.launcher,'tampered');child.exitCode=0;child.emit('close',0);});
  else{db.prepare('INSERT INTO session_handle VALUES(?,?,?,?,?,?)').run(`session-${index}`,child.pid,'fixture',owner.cwd,owner.task_id,owner.run_id);child.stdin=new Events() as any;child.stdin.end=(value:string)=>{const encoded=[...value.matchAll(/FromBase64String\('([^']+)'\)/gu)].map(m=>m[1]!);state.decoded=Buffer.from(encoded[0]!,'base64');const payload=JSON.parse(Buffer.from(encoded[1]!,'base64').toString());queueMicrotask(()=>{rmSync(payload.runtimeRoot,{recursive:true,force:true});const frame=JSON.stringify({version:'cue-readonly-wfp-diagnostic-v1',nonce:payload.nonce,rootIdentity:payload.rootIdentity,state:'captured',overflow:false,events:[]});child.stdout.emit('data',`CUE_READONLY_PID=321;CREATED_FILE_TIME=12345678901\nCUE_READONLY_WFP=${frame}\nCUE_READONLY_CLEANUP=${JSON.stringify({nonce:payload.nonce,rootIdentity:payload.rootIdentity,aclRestored:true,profileAbsent:true})}\n`);child.stderr.emit('data','fixture_wfp_readiness_unknown');child.exitCode=23;child.emit('close',23);});};}
  return{child,session:{...owner,handle:`session-${index}`,pid:child.pid,start_time:'fixture'}};}};
});

const roots:string[]=[],dbs:Ledger[]=[];const sha=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex');
beforeEach(()=>{state.mode='failure';state.spawns=0;state.decoded=Buffer.alloc(0);});
afterEach(()=>{for(const db of dbs.splice(0))if(db.open)db.close();for(const root of roots.splice(0)){const resolved=resolve(root),base=resolve(tmpdir());if(!resolved.startsWith(base))throw Error('temp escaped');rmSync(resolved,{recursive:true,force:true});}});
function seed(db:Ledger,worktree:string){const envelope='a'.repeat(64),plan='b'.repeat(64),policy='c'.repeat(64),subject='d'.repeat(64),payload=JSON.stringify({tasks:[{id:'verify',role:'verifier'}]});db.prepare("INSERT INTO task VALUES('parent','running',NULL,'now')").run();db.prepare("INSERT INTO task VALUES('verify','running',NULL,'now')").run();db.prepare("INSERT INTO envelope VALUES(?,?,'[]','now')").run(envelope,worktree);db.prepare("INSERT INTO run VALUES('workflow','parent',?,0,'now')").run(envelope);db.prepare("INSERT INTO run VALUES('attempt','verify',?,0,'now')").run(envelope);db.prepare('INSERT INTO orchestration_plan VALUES(?,?,?,?)').run('workflow',envelope,plan,payload);db.prepare("INSERT INTO orchestration_step VALUES('workflow','verify','running')").run();db.prepare("INSERT INTO orchestration_attempt VALUES('attempt','workflow','verify','checker','running','{}',?,NULL,0)").run(worktree);const intent=Buffer.from('{}');db.prepare('INSERT INTO orchestration_launch_intent VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run('attempt','workflow','verify','checker','e'.repeat(64),subject,'fixture-tool','v1',null,null,envelope,envelope,plan,policy,sha(intent),intent);}
async function setup(mode:Mode){state.mode=mode;const root=mkdtempSync(join(tmpdir(),'cue-wfp-bootstrap-'));roots.push(root);const worktree=join(root,'worktree'),runtime=join(root,'runtime'),launcher=join(root,'wfp.ps1'),executable=join(root,'checker.exe');mkdirSync(worktree);mkdirSync(runtime);writeFileSync(executable,'checker');const generated=renderReadonlyWfpLauncher({launcher:readFileSync(resolve('src/readonly-verifier-launch.ps1'),'utf8'),collector:readFileSync(resolve('../scripts/reuse/native/readonly-wfp-collector.cs'),'utf8'),adapter:readFileSync(resolve('src/readonly-wfp-observation.cs'),'utf8')});writeFileSync(launcher,generated);state.launcher=launcher;state.expected=Buffer.from(generated);const db=openLedger(join(root,'ledger.db'));dbs.push(db);seed(db,realpathSync.native(worktree));const control=measureReadonlyVerifierControl({executable,launcher});expect(snapshotReadonlyVerifierControl(control)).toEqual(control);expect(verifyReadonlyVerifierControl(control)).toBe(true);const argv=['--fixture'],timeoutMs=100,environmentContractDigest=sha(JSON.stringify({version:'cue-readonly-env-v1',keys:['APPDATA','HOME','LOCALAPPDATA','TEMP','TMP','USERPROFILE','SystemRoot','WINDIR'],systemRoot:process.env.SystemRoot??'C:\\Windows'})),command={argv,timeoutMs,commandDigest:''};command.commandDigest=sha(JSON.stringify({argv,timeoutMs,control:control.sha256,environmentContractDigest}));const stage={attemptId:'attempt',owner:{cwd:realpathSync.native(worktree),task_id:'verify',run_id:'attempt'},envelope:{worktree_realpath:realpathSync.native(worktree),egress:[],allowed_actions:['command']}} as any;const {createReadonlyVerifierWorker}=await import('../src/readonly-verifier-worker.js');const worker=createReadonlyVerifierWorker({db,control,runtimeRootBase:runtime,resolveBinding:()=>({stage,command})});return{db,worker,launcher,generated};}

test('generated self-contained launcher is hash-pinned and transported byte-exact before readiness fails closed',async()=>{const f=await setup('failure');expect(sha256(f.generated)).toBe(sha(readFileSync(f.launcher)));const result=await f.worker.launch('attempt',new AbortController().signal);expect(state.decoded).toEqual(state.expected);expect(f.generated).not.toMatch(/Assembly\.Load|runtimeLoad|payloadAuthority|permissionVerified/u);expect(result).toMatchObject({outcome:'failed',identityRef:null,cleanupRef:null,wfpDiagnostic:{state:'unknown',overflow:false,events:[]}});expect(f.db.prepare('SELECT count(*) n FROM readonly_verifier_identity').get()).toEqual({n:0});expect(f.db.prepare('SELECT count(*) n FROM readonly_verifier_cleanup').get()).toEqual({n:0});});
test('tamper before launch causes zero spawns',async()=>{const f=await setup('failure');writeFileSync(f.launcher,'tampered');await expect(f.worker.launch('attempt',new AbortController().signal)).rejects.toThrow('readonly_control_drift');expect(state.spawns).toBe(0);});
test('tamper during ACL prevents native worker launch and persists no authority',async()=>{const f=await setup('tamper-acl');await expect(f.worker.launch('attempt',new AbortController().signal)).rejects.toThrow('readonly_control_drift');expect(state.spawns).toBe(1);expect(f.db.prepare('SELECT count(*) n FROM readonly_verifier_identity').get()).toEqual({n:0});expect(f.db.prepare('SELECT count(*) n FROM readonly_verifier_cleanup').get()).toEqual({n:0});});
