import { afterEach, describe, expect, test } from 'vitest';
import { spawn, spawnSync, type ChildProcess } from 'node:child_process';
import { createHash } from 'node:crypto';
import { EventEmitter } from 'node:events';
import { existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { PassThrough } from 'node:stream';
import { tmpdir } from 'node:os';
import { basename, dirname, isAbsolute, join, relative, resolve } from 'node:path';
import { observeProcessTree, terminateVerifiedTree } from '../src/process-termination.js';
import { openLedger } from '../src/ledger.js';

type Identity={pid:number;createdAt:string};type ChildReceipt={pid:number|null;createdAt:string|null;closed:boolean;error:string|null;exitCode:number|null;signal:string|null;stderr:string};type Root={path:string;retain:boolean;children:ChildReceipt[];observations:any[]};type Owned={identity:Identity|null;closed:Promise<any[]>;root:Root;receipt:ChildReceipt};
const fixture=join(process.cwd(),'test','fixtures','integration-public-driver-startup-crash-child.mjs'),roots:Root[]=[],children=new Map<ChildProcess,Owned>();
const sha=(value:string|Buffer)=>createHash('sha256').update(value).digest('hex');
class JsonFrames{private queue:any[]=[];private waiters:Array<{resolve:(value:any)=>void;reject:(error:Error)=>void;timer:NodeJS.Timeout}>=[];private terminal:Error|null=null;private pending=Buffer.alloc(0);private readonly onData:(chunk:Buffer|string)=>void;private readonly onEnd:()=>void;private readonly onError:(error:unknown)=>void;private readonly onClose:()=>void;constructor(private stream:NodeJS.ReadableStream,private lifecycle:EventEmitter){this.onData=chunk=>{const bytes=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);for(let offset=0;offset<bytes.length;){const newline=bytes.indexOf(10,offset),end=newline===-1?bytes.length:newline,segment=bytes.subarray(offset,end),length=this.pending.length+segment.length;if(length>64*1024){this.stop(Error('public_driver_restart_frame_oversize'),true);return}if(segment.length)this.pending=Buffer.concat([this.pending,segment],length);if(newline===-1)return;const frame=this.pending;this.pending=Buffer.alloc(0);let value;try{value=JSON.parse(frame.toString('utf8'))}catch{this.stop(Error('public_driver_restart_invalid_frame'),true);return}const waiter=this.waiters.shift();if(waiter){clearTimeout(waiter.timer);waiter.resolve(value)}else if(this.queue.length<16)this.queue.push(value);else{this.stop(Error('public_driver_restart_frame_queue_overflow'),true);return}offset=newline+1}};this.onEnd=()=>this.pending.length?this.stop(Error('public_driver_restart_invalid_frame'),true):this.stop(Error('public_driver_restart_frame_eof'),false);this.onError=error=>this.stop(error instanceof Error?error:Error(String(error)),true);this.onClose=()=>this.pending.length?this.stop(Error('public_driver_restart_invalid_frame'),true):this.stop(Error('public_driver_restart_premature_close'),false);stream.on('data',this.onData);stream.once('end',this.onEnd);lifecycle.once('error',this.onError);lifecycle.once('close',this.onClose)}private stop(error:Error,discard:boolean){if(this.terminal)return;this.terminal=error;this.stream.removeListener('data',this.onData);this.stream.removeListener('end',this.onEnd);this.lifecycle.removeListener('error',this.onError);this.lifecycle.removeListener('close',this.onClose);this.pending=Buffer.alloc(0);if(discard)this.queue=[];for(const waiter of this.waiters.splice(0)){clearTimeout(waiter.timer);waiter.reject(error)}}next(timeoutMs=10_000):Promise<any>{if(this.queue.length)return Promise.resolve(this.queue.shift());if(this.terminal)return Promise.reject(this.terminal);return new Promise((resolve,reject)=>{const waiter={resolve,reject,timer:setTimeout(()=>{this.waiters=this.waiters.filter(value=>value!==waiter);reject(Error('public_driver_restart_frame_timeout'))},timeoutMs)};this.waiters.push(waiter)})}}
const closedOf=(child:ChildProcess)=>new Promise<any[]>(resolve=>child.once('close',(...args)=>resolve(args)));
const childErrorOf=(child:EventEmitter,root:Root,receipt:ChildReceipt)=>new Promise<Error>(resolveError=>child.on('error',error=>{const value=error instanceof Error?error:Error(String(error));root.retain=true;receipt.error=value.message;resolveError(value)}));
const within=<T>(promise:Promise<T>,timeoutMs:number,label:string)=>new Promise<T>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error(label)),timeoutMs);promise.then(value=>{clearTimeout(timer);resolve(value)},error=>{clearTimeout(timer);reject(error)})});
const writeObservations=(root:Root)=>{const value=process.env.CUE_PUBLIC_DRIVER_RESTART_OBSERVATIONS_RECORD,target=resolve(root.path);if(!value||!isAbsolute(value))throw Error('public_driver_restart_observations_record_path');const record=resolve(value),rel=relative(target,record);if(!rel||(!isAbsolute(rel)&&rel.split(/[\\/]/u)[0]!=='..')||!existsSync(dirname(record)))throw Error('public_driver_restart_observations_record_path');writeFileSync(record,JSON.stringify({kind:'public-driver-restart-observations',root:target,observations:root.observations},null,2))};
async function observeIdentity(pid:number){const deadline=Date.now()+10_000;do{const row=observeProcessTree(pid).descendants.find(value=>value.pid===pid);if(row)return{pid:row.pid,createdAt:row.createdAt};await new Promise(resolve=>setTimeout(resolve,25))}while(Date.now()<deadline);throw Error('public_driver_restart_identity_timeout')}
async function closeExact(child:ChildProcess,identity:Identity,closed=closedOf(child)){if(child.exitCode===null&&child.signalCode===null){const row=observeProcessTree(identity.pid).descendants.find(value=>value.pid===identity.pid);if(!row){await within(closed,10_000,'public_driver_restart_absent_close_timeout');return}if(row.createdAt!==identity.createdAt)throw Error('public_driver_restart_identity_changed');await Promise.resolve(terminateVerifiedTree(identity.pid,identity.createdAt))}await within(closed,10_000,'public_driver_restart_close_timeout')}
async function closeUnidentified(child:ChildProcess,closed:Promise<any[]>){child.stdin?.end();await within(closed,10_000,'public_driver_restart_unidentified_close_timeout')}
async function startOwned(mode:string,database:string,worktree:string,localData:string,root:Root){const child=spawn(process.execPath,[fixture,mode,database,worktree],{cwd:process.cwd(),windowsHide:true,env:{...process.env,LOCALAPPDATA:localData},stdio:['pipe','pipe','pipe']}),closed=closedOf(child),receipt:ChildReceipt={pid:child.pid??null,createdAt:null,closed:false,error:null,exitCode:null,signal:null,stderr:''},childError=childErrorOf(child,root,receipt);child.stderr!.on('data',chunk=>{const remaining=64*1024-Buffer.byteLength(receipt.stderr);if(remaining>0){const bytes=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);receipt.stderr+=bytes.subarray(0,remaining).toString('utf8')}});root.children.push(receipt);const owned:Owned={identity:null,closed,root,receipt};children.set(child,owned);closed.then(([code,signal])=>{receipt.closed=true;receipt.exitCode=code;receipt.signal=signal});try{if(!child.pid)throw Error('public_driver_restart_spawn_pid_missing');const identity=await Promise.race([observeIdentity(child.pid),childError.then(error=>Promise.reject(error))]);owned.identity=identity;receipt.pid=identity.pid;receipt.createdAt=identity.createdAt;const frames=new JsonFrames(child.stdout!,child),hello=await Promise.race([frames.next(30_000),childError.then(error=>Promise.reject(error))]);if(hello.kind!=='identity'||hello.mode!==mode||hello.pid!==identity.pid||hello.createdAt!==identity.createdAt)throw Error('public_driver_restart_handshake_mismatch');child.stdin!.write('continue\n');return{child,closed,frames,identity,receipt}}catch(error){root.retain=true;receipt.error=error instanceof Error?error.message:String(error);try{await closeUnidentified(child,closed);children.delete(child)}catch(closeError){receipt.error+=`; ${closeError instanceof Error?closeError.message:String(closeError)}`}root.observations.push({identity:owned.identity,failure:{error:receipt.error,exitCode:receipt.exitCode,signal:receipt.signal,stderr:receipt.stderr}});writeObservations(root);throw error}}
async function nextOwned(owned:Awaited<ReturnType<typeof startOwned>>,root:Root,timeoutMs:number){try{return await owned.frames.next(timeoutMs)}catch(error){try{await within(owned.closed,10_000,'public_driver_restart_failure_close_timeout')}catch(closeError){owned.receipt.error=`${error instanceof Error?error.message:String(error)}; ${closeError instanceof Error?closeError.message:String(closeError)}`}const message=owned.receipt.error??(error instanceof Error?error.message:String(error));root.observations.push({identity:owned.identity,failure:{error:message,exitCode:owned.receipt.exitCode,signal:owned.receipt.signal,stderr:owned.receipt.stderr}});writeObservations(root);throw Error(`${message}; exit=${owned.receipt.exitCode}; signal=${owned.receipt.signal}; stderr=${owned.receipt.stderr}`)}}
afterEach(async()=>{const failures:unknown[]=[];for(const [child,owned] of [...children]){try{if(owned.identity)await closeExact(child,owned.identity,owned.closed);else await closeUnidentified(child,owned.closed);children.delete(child)}catch(error){owned.root.retain=true;owned.receipt.error=error instanceof Error?error.message:String(error);failures.push(error)}}const base=resolve(tmpdir()),recordValue=process.env.CUE_PUBLIC_DRIVER_RESTART_CLEANUP_RECORD;for(const root of roots.splice(0)){let absent=false,recordPath='';try{writeObservations(root)}catch(error){root.retain=true;failures.push(error)}try{const target=resolve(root.path);if(!recordValue||!isAbsolute(recordValue)||resolve(recordValue).startsWith(target))throw Error('public_driver_restart_cleanup_record_path');recordPath=resolve(recordValue);writeFileSync(recordPath,JSON.stringify({kind:'public-driver-restart-cleanup',phase:'before-delete',root:target,absent:false,retained:root.retain,children:root.children},null,2));if(!isAbsolute(target)||dirname(target)!==base||!basename(target).startsWith('cue-public-driver-restart-')||lstatSync(target).isSymbolicLink())throw Error('public_driver_restart_cleanup_path');if(!root.retain){rmSync(target,{recursive:true,force:true});if(existsSync(target))throw Error('public_driver_restart_cleanup_failed');absent=true}}catch(error){root.retain=true;failures.push(error)}try{if(!recordPath)throw Error('public_driver_restart_cleanup_record_unavailable');writeFileSync(recordPath,JSON.stringify({kind:'public-driver-restart-cleanup',phase:'complete',root:resolve(root.path),absent,retained:root.retain,children:root.children},null,2))}catch(error){failures.push(error)}}if(failures.length)throw new AggregateError(failures,'public_driver_restart_cleanup_unverified')},30_000);

test('bounded frame reader rejects timeout, oversize chunk, queue overflow, malformed EOF, and close timeout',async()=>{const missing=new PassThrough(),missingLife=new EventEmitter(),timeout=new JsonFrames(missing,missingLife);await expect(timeout.next(5)).rejects.toThrow('public_driver_restart_frame_timeout');const oversized=new PassThrough(),oversizedLife=new EventEmitter(),bounded=new JsonFrames(oversized,oversizedLife);oversized.write('x'.repeat(64*1024+1));await expect(bounded.next()).rejects.toThrow('public_driver_restart_frame_oversize');const queued=new PassThrough(),queuedLife=new EventEmitter(),limited=new JsonFrames(queued,queuedLife);queued.write(Array.from({length:17},(_,index)=>JSON.stringify({index})).join('\n')+'\n');await expect(limited.next()).rejects.toThrow('public_driver_restart_frame_queue_overflow');const malformed=new PassThrough(),malformedLife=new EventEmitter(),eof=new JsonFrames(malformed,malformedLife);malformed.end('{');await expect(eof.next()).rejects.toThrow('public_driver_restart_invalid_frame');await expect(within(new Promise(()=>{}),5,'public_driver_restart_close_timeout')).rejects.toThrow('public_driver_restart_close_timeout')});
test('bounded frame reader drains valid frames after stream and lifecycle completion',async()=>{const finalStream=new PassThrough(),finalLife=new EventEmitter(),final=new JsonFrames(finalStream,finalLife);finalStream.end('{"final":true}\n');await new Promise(resolve=>finalStream.once('end',resolve));await expect(final.next()).resolves.toEqual({final:true});await expect(final.next()).rejects.toThrow('public_driver_restart_frame_eof');const multipleStream=new PassThrough(),multipleLife=new EventEmitter(),multiple=new JsonFrames(multipleStream,multipleLife);multipleStream.write('{"n":1}\n{"n":2}\n');multipleLife.emit('close');await expect(multiple.next()).resolves.toEqual({n:1});await expect(multiple.next()).resolves.toEqual({n:2});await expect(multiple.next()).rejects.toThrow('public_driver_restart_premature_close')});
test('child error observer is immediate, permanent, and records retention',async()=>{const lifecycle=new EventEmitter(),root:Root={path:'fixture',retain:false,children:[],observations:[]},receipt:ChildReceipt={pid:null,createdAt:null,closed:false,error:null,exitCode:null,signal:null,stderr:''},observed=childErrorOf(lifecycle,root,receipt);lifecycle.emit('error',Error('spawn-failed'));await expect(observed).resolves.toMatchObject({message:'spawn-failed'});expect(root.retain).toBe(true);expect(receipt.error).toBe('spawn-failed');expect(lifecycle.listenerCount('error')).toBe(1);expect(()=>lifecycle.emit('error',Error('late-error'))).not.toThrow();expect(receipt.error).toBe('late-error')});
test('exact cleanup awaits close when the observed process is already absent',async()=>{const child=Object.assign(new EventEmitter(),{exitCode:null,signalCode:null}) as unknown as ChildProcess,closed=closedOf(child);queueMicrotask(()=>child.emit('close',1,null));await expect(closeExact(child,{pid:2_147_483_647,createdAt:'absent'},closed)).resolves.toBeUndefined()});
test('exact cleanup refuses a present process with changed creation identity',async()=>{const child=Object.assign(new EventEmitter(),{exitCode:null,signalCode:null}) as unknown as ChildProcess;await expect(closeExact(child,{pid:process.pid,createdAt:'changed'},new Promise(()=>{}))).rejects.toThrow('public_driver_restart_identity_changed')});
test('shared restart host constructs and refuses public replay without effects',async()=>{const root=mkdtempSync(join(tmpdir(),'cue-public-driver-snapshot-')),database=join(root,'ledger.db'),db=openLedger(database);try{
 const {createOrchestrationDriver}=await import('../../app/orchestration-driver.mjs');
 // @ts-expect-error The executable fixture intentionally has no declaration file.
 const {createRestartHost}=await import('./fixtures/integration-public-driver-startup-crash-child.mjs'),counts={launches:0,authorizeCalls:0,opens:0,reads:0,executeCalls:0},driver=createOrchestrationDriver({db,host:createRestartHost(counts)});expect(()=>driver.start('workflow')).toThrow('driver_prepare_missing');expect(()=>driver.snapshot('workflow')).toThrow('driver_prepare_missing');expect(counts).toEqual({launches:0,authorizeCalls:0,opens:0,reads:0,executeCalls:0})}finally{db.close();rmSync(root,{recursive:true,force:true})}});
test('native callback binds exactly one durable intent before write',async()=>{
 // @ts-expect-error The executable fixture intentionally has no declaration file.
 const {resolvePublicationIntent}=await import('./fixtures/integration-public-driver-startup-crash-child.mjs'),input={root:'C:\\owned',expectedRoot:{volumeSerial:'root-volume',fileId:'root-file'},target:'target.txt',expected:{identity:{volumeSerial:'file-volume',fileId:'file-id'},byteLength:6,sha256:sha('before')},replacement:Buffer.from('after'),maxBytes:1024},attemptId='attempt-id',payload=Buffer.from(JSON.stringify({publicationId:'publication-id',attemptId,worktreeRealpath:input.root,relativePath:input.target,maxBytes:input.maxBytes,rootIdentity:input.expectedRoot,preimage:input.expected,replacement:{byteLength:input.replacement.length,sha256:sha(input.replacement)}})),row={publication_id:'publication-id',payload_sha256:sha(payload),payload};let rows=[row],query='',args:any[]=[];const db:any={prepare:(sql:string)=>({all:(...values:any[])=>{query=sql;args=values;return rows}})},native=()=>{const intent=resolvePublicationIntent(db,attemptId,input);return{intent,wrote:true}};expect(native()).toEqual({intent:{publicationId:'publication-id',payloadSha256:sha(payload),payload:payload.toString('utf8')},wrote:true});expect(query).toContain('attempt_id=?');expect(args).toEqual([attemptId,input.root,input.expectedRoot.volumeSerial,input.expectedRoot.fileId,input.target,input.maxBytes,input.expected.identity.volumeSerial,input.expected.identity.fileId,input.expected.byteLength,input.expected.sha256,input.replacement.length,sha(input.replacement)]);rows=[row,row];expect(()=>native()).toThrow('public_driver_restart_intent_binding');rows=[];expect(()=>native()).toThrow('public_driver_restart_intent_binding');rows=[{...row,payload_sha256:'0'.repeat(64)}];expect(()=>native()).toThrow('public_driver_restart_intent_corrupt')});

describe.skipIf(process.platform!=='win32'||process.env.CUE_ACTUAL_PUBLIC_DRIVER_RESTART!=='1')('A04 public-driver startup crash/restart',()=>{
 test('holds the public driver native write across real daemon ownership restart without relaunch or resend',async()=>{
  const rootRecord:Root={path:mkdtempSync(join(tmpdir(),'cue-public-driver-restart-')),retain:false,children:[],observations:[]};roots.push(rootRecord);const root=rootRecord.path,database=join(root,'ledger.db'),worktree=join(root,'worktree'),localData=join(root,'local-app-data'),target=join(worktree,'target.txt');mkdirSync(worktree);mkdirSync(localData);expect(spawnSync('git',['init'],{cwd:worktree,windowsHide:true}).status).toBe(0);expect(spawnSync('git',['config','user.name','Cue fixture'],{cwd:worktree,windowsHide:true}).status).toBe(0);expect(spawnSync('git',['config','user.email','cue-fixture@example.invalid'],{cwd:worktree,windowsHide:true}).status).toBe(0);writeFileSync(target,'before');expect(spawnSync('git',['add','target.txt'],{cwd:worktree,windowsHide:true}).status).toBe(0);expect(spawnSync('git',['commit','-m','fixture base'],{cwd:worktree,windowsHide:true}).status).toBe(0);
  const firstOwned=await startOwned('crash-window',database,worktree,localData,rootRecord),first=firstOwned.child,before=await nextOwned(firstOwned,rootRecord,60_000);rootRecord.observations.push({identity:firstOwned.identity,frame:before});writeObservations(rootRecord);expect(before).toMatchObject({kind:'effect',mode:'crash-window',intentCount:1,resultCount:0,outcome:{state:'committed'},fileBytes:'published-by-public-driver',counts:{launches:1,opens:1,reads:1,writes:1}});expect(before.pid).toBe(firstOwned.identity.pid);expect(before.createdAt).toBe(firstOwned.identity.createdAt);expect(before.fileSha256).toBe(sha('published-by-public-driver'));await closeExact(first,firstOwned.identity,firstOwned.closed);children.delete(first);expect(firstOwned.receipt.stderr).toBe('');
  const secondOwned=await startOwned('restart',database,worktree,localData,rootRecord),second=secondOwned.child,restarted=await nextOwned(secondOwned,rootRecord,60_000);rootRecord.observations.push({identity:secondOwned.identity,frame:restarted});writeObservations(rootRecord);const [code]=await within(secondOwned.closed,10_000,'public_driver_restart_close_timeout');children.delete(second);expect(code,secondOwned.receipt.stderr).toBe(0);expect(restarted.pid).not.toBe(before.pid);expect(restarted).toMatchObject({kind:'restart',mode:'restart',replayRefusal:'driver_prepare_missing',snapshotRefusal:'driver_prepare_missing',ledgerTask:{state:'blocked'},attempt:{state:'blocked',cleanup_verified:0},heldRow:{state:'held',revision:0,final_seal:null},heldTransitionCount:1,gitStatusArtifacts:[{content:' M target.txt\n'}],leaseCount:1,receiptCount:0,acceptanceCount:0,attemptCount:1,replacementAttemptCount:0,resultCount:0,recoveryCount:1,launches:0,authorizeCalls:0,opens:0,reads:0,executeCalls:0,fileBytes:'published-by-public-driver'});expect(restarted.heldRow.payload_sha256).toBe(sha(restarted.heldRow.payload));expect(restarted.fileSha256).toBe(before.fileSha256);expect(readFileSync(target,'utf8')).toBe('published-by-public-driver');
 },120_000);
});
