import { afterEach, expect, test } from 'vitest';
import { mkdirSync, mkdtempSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { createHash } from 'node:crypto';
import { openLedger, type Ledger } from '../src/ledger.js';
import { holdInterruptedJournalRecoveries } from '../src/journal-recovery.js';
import { reconcileInterruptedWrites } from '../src/recovery.js';
import { captureChangeSet, observeChangeSet, registerNativeChangeJournal } from '../src/change-records.js';
import { createHandoffActivityStore } from '../src/orchestration/handoff-activity.js';

const roots:string[]=[],dbs:Ledger[]=[];
afterEach(()=>{for(const db of dbs.splice(0))if(db.open)db.close();for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
function fixture(){const root=mkdtempSync(join(tmpdir(),'cue-journal-recovery-'));roots.push(root);const work=join(root,'work');mkdirSync(work);const path=join(root,'ledger.sqlite');const db=openLedger(path);dbs.push(db);const now='2026-09-12T00:00:00.000Z';
  db.prepare('INSERT INTO task VALUES(?,?,?,?)').run('root','running',null,now);db.prepare('INSERT INTO envelope VALUES(?,?,?,?)').run('env',work,'[]',now);db.prepare('INSERT INTO run VALUES(?,?,?,?,?)').run('run','root','env',1,now);
  db.prepare('INSERT INTO orchestration_plan VALUES(?,?,?,?)').run('run','env','digest','{}');for(const id of ['one','two'])db.prepare('INSERT INTO orchestration_step VALUES(?,?,?)').run('run',id,'running');
  db.prepare('INSERT INTO workspace_write_lease VALUES(?,?,?)').run(work,'run',now);for(const [id,state,clean] of [['one','running',0],['two','completed',1]] as const){const claim=JSON.stringify({attemptId:id,candidateId:'candidate',observedAtMs:1,runId:'run',taskId:id});db.prepare('INSERT INTO orchestration_attempt VALUES(?,?,?,?,?,?,?,?,?)').run(id,'run',id,'candidate',state,claim,work,now,clean);}
  return{root,work,path,db};}

test('startup holds every attempt in an interrupted workspace before reconciliation and replay is exact',()=>{const f=fixture();const first=holdInterruptedJournalRecoveries(f.db,f.work,10);expect(first).toHaveLength(2);expect(f.db.prepare('SELECT attempt_id,state,change_set_id FROM held_recovery ORDER BY attempt_id').all()).toEqual([{attempt_id:'one',state:'held',change_set_id:null},{attempt_id:'two',state:'held',change_set_id:null}]);const bytes=f.db.serialize();expect(holdInterruptedJournalRecoveries(f.db,f.work,20)).toEqual(first);expect(f.db.serialize()).toEqual(bytes);});

test('close and reopen preserves missing journal holds and retains a cleanup-verified writer lease',()=>{const f=fixture();holdInterruptedJournalRecoveries(f.db,f.work,10);f.db.close();const reopened=openLedger(f.path);dbs.push(reopened);expect(holdInterruptedJournalRecoveries(reopened,f.work,20)).toHaveLength(2);reopened.prepare("UPDATE orchestration_attempt SET state='blocked' WHERE attempt_id='one'").run();expect(reconcileInterruptedWrites(reopened,f.work,()=>'' )).toBe(1);expect(reopened.prepare('SELECT COUNT(*) n FROM workspace_write_lease').get()).toEqual({n:1});expect(reopened.prepare("SELECT write_in_progress FROM run WHERE id='run'").get()).toEqual({write_in_progress:1});});

test('tampered held payload aborts startup before process handling and retains ownership',()=>{const f=fixture();holdInterruptedJournalRecoveries(f.db,f.work,10);f.db.exec('DROP TRIGGER held_recovery_payload_update; DROP TRIGGER held_recovery_cas');f.db.prepare("UPDATE held_recovery SET payload=x'00',payload_sha256=? WHERE attempt_id='one'").run('0'.repeat(64));expect(()=>holdInterruptedJournalRecoveries(f.db,f.work,20)).toThrow('held_recovery_corrupt');expect(f.db.prepare('SELECT COUNT(*) n FROM workspace_write_lease').get()).toEqual({n:1});expect(f.db.prepare("SELECT state FROM orchestration_attempt WHERE attempt_id='one'").get()).toEqual({state:'running'});});

const hash=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex');
function journalFixture(){const root=mkdtempSync(join(tmpdir(),'cue-journal-recovery-'));roots.push(root);const work=join(root,'work');mkdirSync(work);const db=openLedger(join(root,'journal.sqlite'));dbs.push(db);const parent=hash('parent'),stage=hash('stage'),plan=hash('plan'),policy=hash('policy'),selection=hash('selection'),subject=hash('subject');db.prepare("INSERT INTO task VALUES('root','running',NULL,'now')").run();db.prepare('INSERT INTO envelope VALUES(?,?,?,?)').run(parent,work,'[]','now');db.prepare("INSERT INTO run VALUES('run','root',?,1,'now')").run(parent);db.prepare("INSERT INTO orchestration_plan VALUES('run',?,?,?)").run(parent,plan,'{}');db.prepare("INSERT INTO orchestration_step VALUES('run','stage','running')").run();registerNativeChangeJournal(db,{runId:'run',worktreeRealpath:work,targets:[{taskId:'stage',targetId:'target',relativePath:'a.txt',maxBackupBytes:1024}],observedAtMs:0});db.prepare("INSERT INTO orchestration_attempt VALUES('attempt','run','stage','candidate','running','{}',?,'now',0)").run(work);db.prepare("INSERT INTO task VALUES('stage-task','running',NULL,'now')").run();db.prepare('INSERT INTO envelope VALUES(?,?,?,?)').run(stage,work,'[]','now');db.prepare("INSERT INTO run VALUES('attempt','stage-task',?,0,'now')").run(stage);db.prepare("INSERT INTO orchestration_stage_envelope VALUES('attempt','run','stage','stage-task','attempt',?,?,?,?,?,?,?,?)").run(parent,stage,plan,policy,'{}','{}','{}','{}');db.prepare("INSERT INTO attempt_selection VALUES('attempt','run','request','monetary',?,?)").run(selection,'{}');db.prepare("INSERT INTO workspace_write_lease VALUES(?,'run','now')").run(work);createHandoffActivityStore(db,{authorizeArtifact:()=>false,resolveArtifact:()=>null}).recordLaunchIntent({runId:'run',taskId:'stage',attemptId:'attempt',candidateId:'candidate',selectionDigest:selection,expectedSubjectDigest:subject,tool:{id:'tool',revision:'r'},model:null,parentEnvelopeHash:parent,stageEnvelopeHash:stage,planDigest:plan,policyDigest:policy});writeFileSync(join(work,'a.txt'),'before');captureChangeSet(db,{changeSetId:'set',runId:'run',taskId:'stage',attemptId:'attempt',stageEnvelopeHash:stage,launchIntentId:'attempt',worktree:work,targets:['a.txt'],limits:{maxTargets:1,maxBackupBytes:1024},nowMs:1});holdInterruptedJournalRecoveries(db,work,2);return{root,work,db};}

test.skipIf(process.platform!=='win32')('tampered journal becomes a fresh unknown observation and remains held',()=>{const f=journalFixture();f.db.exec('DROP TRIGGER change_native_binding_update');f.db.prepare("UPDATE change_native_binding SET payload=x'00' WHERE change_set_id='set'").run();expect(observeChangeSet(f.db,'set',{nowMs:3}).map(x=>x.status)).toEqual(['unknown']);expect(f.db.prepare("SELECT state FROM held_recovery WHERE attempt_id='attempt'").get()).toEqual({state:'held'});expect(f.db.prepare('SELECT COUNT(*) n FROM workspace_write_lease').get()).toEqual({n:1});});

test.skipIf(process.platform!=='win32')('root replacement is freshly observed as unknown and keeps the exact lease',()=>{const f=journalFixture();renameSync(f.work,join(f.root,'old-work'));mkdirSync(f.work);expect(observeChangeSet(f.db,'set',{nowMs:3}).map(x=>x.status)).toEqual(['unknown']);expect(f.db.prepare("SELECT state FROM held_recovery WHERE attempt_id='attempt'").get()).toEqual({state:'held'});expect(f.db.prepare('SELECT worktree_realpath,run_id,acquired_at FROM workspace_write_lease').get()).toEqual({worktree_realpath:f.work,run_id:'run',acquired_at:'now'});});
