import {afterEach,beforeEach,expect,test,vi} from 'vitest';
import {createHash} from 'node:crypto';
import {mkdirSync,mkdtempSync,readFileSync,rmSync,writeFileSync} from 'node:fs';
import {basename,isAbsolute,join,relative,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {openLedger,type Ledger} from '../src/ledger.js';
import {createReadonlyVerifierWorker} from '../src/readonly-verifier-worker.js';

type Mode='valid'|'missing'|'invalid'|'duplicate'|'bad-exit'|'no-pid'|'bad-cleanup'|'control-tamper';
const state=vi.hoisted(()=>({mode:'valid' as Mode,spawns:0,verifyCalls:0,runtimeBase:''}));
vi.mock('../src/change-snapshot-host.js',()=>({identifyChangeSnapshotRoot:()=>({state:'ok',identity:{volumeSerial:'1',fileId:'2'}})}));
vi.mock('../src/readonly-verifier-control.js',()=>({snapshotReadonlyVerifierControl:(v:unknown)=>v,verifyReadonlyVerifierControl:()=>{state.verifyCalls++;return state.mode!=='control-tamper'||state.verifyCalls===1;}}));
vi.mock('../src/process-termination.js',()=>({terminateVerifiedTree:vi.fn(),verifyProcessesDead:vi.fn()}));
vi.mock('../src/process-launch.js',()=>{
 class Events{listeners=new Map<string,((v?:any)=>void)[]>();on(n:string,f:(v?:any)=>void){this.listeners.set(n,[...(this.listeners.get(n)??[]),f]);return this;}once(n:string,f:(v?:any)=>void){return this.on(n,f);}emit(n:string,v?:any){for(const f of this.listeners.get(n)??[])f(v);}}
 return{resolveOwnedExecutable:()=> 'C:\\Windows\\powershell.exe',spawnOwned:(db:any,owner:any)=>{const index=state.spawns++,child=new Events() as any;child.stdout=new Events();child.stderr=new Events();child.pid=700+index;child.exitCode=null;child.kill=vi.fn();
  if(index===0)queueMicrotask(()=>{child.stdout.emit('data','O:BAG:BAD:(A;;FA;;;SY)');child.exitCode=0;child.emit('close',0);});
  else{db.prepare('INSERT INTO session_handle VALUES(?,?,?,?,?,?)').run('session-attempt',child.pid,'fixture-start',owner.cwd,owner.task_id,owner.run_id);child.stdin=new Events() as any;child.stdin.end=(value:string)=>{const encoded=/-PayloadBase64 '([^']+)'/u.exec(value)![1]!,p=JSON.parse(Buffer.from(encoded,'base64').toString());queueMicrotask(()=>{const target=resolve(p.runtimeRoot),rel=relative(resolve(state.runtimeBase),target);if(!rel||isAbsolute(rel)||rel.split(/[\\/]/u)[0]==='..')throw Error('fixture runtime escaped');rmSync(target,{recursive:true,force:true});const diagnostic={version:'cue-readonly-wfp-diagnostic-v1',nonce:p.nonce,rootIdentity:p.rootIdentity,state:'captured',overflow:false,events:[]};let frames=state.mode==='missing'?'':`CUE_READONLY_WFP=${state.mode==='invalid'?'{bad}':JSON.stringify(diagnostic)}\r\n`;if(state.mode==='duplicate')frames+=frames;const pid=state.mode==='no-pid'?'':`CUE_READONLY_PID=321;CREATED_FILE_TIME=12345678901\r\n`;const cleanup={nonce:state.mode==='bad-cleanup'?'f'.repeat(64):p.nonce,rootIdentity:p.rootIdentity,aclRestored:true,profileAbsent:true};child.stdout.emit('data',pid+frames+`CUE_READONLY_CLEANUP=${JSON.stringify(cleanup)}\r\n`);child.exitCode=state.mode==='bad-exit'?23:0;child.emit('close',child.exitCode);});};}
  return{child,session:{...owner,handle:index===0?'acl-session':'session-attempt',pid:child.pid,start_time:'fixture-start'}};}};
});

const roots:string[]=[],dbs:Ledger[]=[];const sha=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex');
beforeEach(()=>{state.mode='valid';state.spawns=0;state.verifyCalls=0;state.runtimeBase='';});
afterEach(()=>{for(const db of dbs.splice(0))if(db.open)db.close();for(const root of roots.splice(0)){const base=resolve(tmpdir()),target=resolve(root),rel=relative(base,target);if(!rel||isAbsolute(rel)||rel.split(/[\\/]/u)[0]==='..'||!basename(target).startsWith('cue-wfp-diag-authority-'))throw Error('fixture root escaped');rmSync(target,{recursive:true,force:true});}});
function seed(db:Ledger,worktree:string){const envelope='a'.repeat(64),plan='b'.repeat(64),policy='c'.repeat(64),subject='d'.repeat(64),payload=JSON.stringify({tasks:[{id:'verify',role:'verifier'}]});db.prepare("INSERT INTO task VALUES('parent','running',NULL,'now')").run();db.prepare("INSERT INTO task VALUES('verify','running',NULL,'now')").run();db.prepare("INSERT INTO envelope VALUES(?,?,'[]','now')").run(envelope,worktree);db.prepare("INSERT INTO run VALUES('workflow','parent',?,0,'now')").run(envelope);db.prepare("INSERT INTO task VALUES('stage-task-ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff','running',NULL,'now')").run();db.prepare("INSERT INTO envelope VALUES(?,?,'[]','now')").run('9'.repeat(64),worktree);db.prepare("INSERT INTO run VALUES('attempt','stage-task-ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',?,0,'now')").run('9'.repeat(64));db.prepare('INSERT INTO orchestration_plan VALUES(?,?,?,?)').run('workflow',envelope,plan,payload);db.prepare("INSERT INTO orchestration_step VALUES('workflow','verify','running')").run();db.prepare("INSERT INTO orchestration_attempt VALUES('attempt','workflow','verify','checker','running','{}',?,NULL,0)").run(worktree);db.prepare('INSERT INTO orchestration_stage_envelope VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run('attempt','workflow','verify','stage-task-ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff','attempt',envelope,'9'.repeat(64),'b'.repeat(64),'c'.repeat(64),'{}','{}','[]','{}');const intent=Buffer.from('{}');db.prepare('INSERT INTO orchestration_launch_intent VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run('attempt','workflow','verify','checker','e'.repeat(64),subject,'fixture-tool','v1',null,null,envelope,envelope,plan,policy,sha(intent),intent);}
async function run(mode:Mode){state.mode=mode;const root=mkdtempSync(join(tmpdir(),'cue-wfp-diag-authority-'));roots.push(root);const worktree=join(root,'worktree'),runtime=join(root,'runtime');mkdirSync(worktree);mkdirSync(runtime);state.runtimeBase=resolve(runtime);const db=openLedger(join(root,'ledger.db'));dbs.push(db);seed(db,resolve(worktree));const launcher=join(root,'launcher.ps1'),executable=join(root,'checker.exe');writeFileSync(launcher,'fixture');writeFileSync(executable,'fixture');const control={executable,launcher,executableSha256:'1'.repeat(64),launcherSha256:sha(readFileSync(launcher)),sha256:'2'.repeat(64)} as any,argv=['--fixture'],timeoutMs=100,environmentContractDigest=sha(JSON.stringify({version:'cue-readonly-env-v1',keys:['APPDATA','HOME','LOCALAPPDATA','TEMP','TMP','USERPROFILE','SystemRoot','WINDIR'],systemRoot:process.env.SystemRoot??'C:\\Windows'})),command={argv,timeoutMs,commandDigest:''};command.commandDigest=sha(JSON.stringify({argv,timeoutMs,control:control.sha256,environmentContractDigest}));const stage={attemptId:'attempt',owner:{cwd:resolve(worktree),task_id:'stage-task-ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',run_id:'attempt'},envelope:{worktree_realpath:resolve(worktree),egress:[],allowed_actions:['command']}} as any;const result=await createReadonlyVerifierWorker({db,control,runtimeRootBase:runtime,resolveBinding:()=>({stage,command})}).launch('attempt',new AbortController().signal);return{db,result};}

test.each(['valid','missing','invalid','duplicate'] as const)('%s diagnostic preserves the pre-existing successful authority result',async mode=>{const f=await run(mode);expect(f.result).toMatchObject({outcome:'succeeded'});expect(f.result.identityRef).toMatch(/^cue-readonly-identity:/);expect(f.result.cleanupRef).toMatch(/^cue-readonly-cleanup:/);expect(f.result.wfpDiagnostic.state).toBe(mode==='valid'?'captured':'unknown');expect(f.db.prepare('SELECT count(*) n FROM readonly_verifier_identity').get()).toEqual({n:1});expect(f.db.prepare('SELECT count(*) n FROM readonly_verifier_cleanup').get()).toEqual({n:1});});
test.each(['bad-exit','no-pid','bad-cleanup','control-tamper'] as const)('valid diagnostic cannot promote %s',async mode=>{const f=await run(mode);expect(f.result).toMatchObject({outcome:'failed',identityRef:null,cleanupRef:null,wfpDiagnostic:{state:'unknown'}});expect(f.db.prepare('SELECT count(*) n FROM readonly_verifier_identity').get()).toEqual({n:0});expect(f.db.prepare('SELECT count(*) n FROM readonly_verifier_cleanup').get()).toEqual({n:0});});
