import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import { createHash } from 'node:crypto';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { openLedger, type Ledger } from '../src/ledger.js';
import { createReadonlyVerifierWorker } from '../src/readonly-verifier-worker.js';

type Mode='success'|'wrong-nonce'|'death-unknown';
const state=vi.hoisted(()=>({mode:'success' as Mode,spawns:0,dead:vi.fn()}));
vi.mock('../src/change-snapshot-host.js',()=>({identifyChangeSnapshotRoot:()=>({state:'ok',identity:{volumeSerial:'1',fileId:'2'}})}));
vi.mock('../src/readonly-verifier-control.js',()=>({snapshotReadonlyVerifierControl:(v:unknown)=>v,verifyReadonlyVerifierControl:()=>true}));
vi.mock('../src/process-termination.js',()=>({terminateVerifiedTree:vi.fn(),verifyProcessesDead:state.dead}));
vi.mock('../src/process-launch.js',()=>{
 class Events{listeners=new Map<string,((v:any)=>void)[]>();on(n:string,f:(v:any)=>void){this.listeners.set(n,[...(this.listeners.get(n)??[]),f]);return this;}once(n:string,f:(v:any)=>void){return this.on(n,f);}emit(n:string,v?:any){for(const f of this.listeners.get(n)??[])f(v);}}
 return{resolveOwnedExecutable:()=> 'C:\\Windows\\powershell.exe',spawnOwned:(db:any,owner:any)=>{const index=state.spawns++,child=new Events() as any;child.stdout=new Events();child.stderr=new Events();child.pid=700+index;child.exitCode=null;child.kill=vi.fn();
   if(index===0)queueMicrotask(()=>{child.stdout.emit('data','O:BAG:BAD:(A;;FA;;;SY)');child.exitCode=0;child.emit('close',0);});else{const handle='session-attempt';db.prepare('INSERT INTO session_handle VALUES(?,?,?,?,?,?)').run(handle,child.pid,'fixture-start',owner.cwd,owner.task_id,owner.run_id);child.stdin=new Events() as any;child.stdin.end=(value:string)=>{const encoded=/-PayloadBase64 '([^']+)'/u.exec(value)![1]!,payload=JSON.parse(Buffer.from(encoded,'base64').toString()),nonce=state.mode==='wrong-nonce'?'f'.repeat(64):payload.nonce;queueMicrotask(()=>{rmSync(payload.runtimeRoot,{recursive:true,force:true});child.stdout.emit('data',`CUE_READONLY_PID=321;CREATED_FILE_TIME=12345678901\r\nCUE_READONLY_CLEANUP=${JSON.stringify({nonce,rootIdentity:'1:2',aclRestored:true,profileAbsent:true})}\r\n`);child.exitCode=0;child.emit('close',0);});};}
   return{child,session:{...owner,handle:index===0?'acl-session':'session-attempt',pid:child.pid,start_time:'fixture-start'}};}};
});

const roots:string[]=[],dbs:Ledger[]=[];beforeEach(()=>{state.mode='success';state.spawns=0;state.dead.mockReset();});afterEach(()=>{for(const db of dbs.splice(0))if(db.open)db.close();for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
const sha=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex');
function seed(db:Ledger,worktree:string){const envelope='a'.repeat(64),planDigest='b'.repeat(64),policyDigest='c'.repeat(64),subject='d'.repeat(64),payload=JSON.stringify({tasks:[{id:'verify',role:'verifier'}]});db.prepare("INSERT INTO task VALUES('parent','running',NULL,'now')").run();db.prepare("INSERT INTO task VALUES('verify','running',NULL,'now')").run();db.prepare("INSERT INTO envelope VALUES(?,?,'[]','now')").run(envelope,worktree);db.prepare("INSERT INTO run VALUES('workflow','parent',?,0,'now')").run(envelope);db.prepare("INSERT INTO task VALUES('stage-task-ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff','running',NULL,'now')").run();db.prepare("INSERT INTO envelope VALUES(?,?,'[]','now')").run('9'.repeat(64),worktree);db.prepare("INSERT INTO run VALUES('attempt','stage-task-ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',?,0,'now')").run('9'.repeat(64));db.prepare("INSERT INTO orchestration_plan VALUES('workflow',?,?,?)").run(envelope,planDigest,payload);db.prepare("INSERT INTO orchestration_step VALUES('workflow','verify','running')").run();db.prepare("INSERT INTO orchestration_attempt VALUES('attempt','workflow','verify','checker','running','{}',?,NULL,0)").run(worktree);db.prepare('INSERT INTO orchestration_stage_envelope VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run('attempt','workflow','verify','stage-task-ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff','attempt',envelope,'9'.repeat(64),'b'.repeat(64),'c'.repeat(64),'{}','{}','[]','{}');const intent=Buffer.from('{}');db.prepare('INSERT INTO orchestration_launch_intent VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run('attempt','workflow','verify','checker','e'.repeat(64),subject,'fixture-tool','v1',null,null,envelope,envelope,planDigest,policyDigest,sha(intent),intent);return subject;}
async function fixture(mode:Mode){state.mode=mode;const root=mkdtempSync(join(tmpdir(),'cue-readonly-ledger-'));roots.push(root);const worktree=join(root,'worktree'),runtime=join(root,'runtime'),path=join(root,'ledger.db');mkdirSync(worktree);mkdirSync(runtime);const db=openLedger(path);dbs.push(db);const subject=seed(db,resolve(worktree)),launcher=join(root,'launcher.ps1'),executable=join(root,'checker.exe');writeFileSync(launcher,'fixture');writeFileSync(executable,'fixture');const control={executable,launcher,executableSha256:'1'.repeat(64),launcherSha256:sha(readFileSync(launcher)),sha256:'2'.repeat(64)} as any,argv=['--fixture'],timeoutMs=100,environmentContractDigest=sha(JSON.stringify({version:'cue-readonly-env-v1',keys:['APPDATA','HOME','LOCALAPPDATA','TEMP','TMP','USERPROFILE','SystemRoot','WINDIR'],systemRoot:process.env.SystemRoot??'C:\\Windows'})),command={argv,timeoutMs,commandDigest:''};command.commandDigest=sha(JSON.stringify({argv,timeoutMs,control:control.sha256,environmentContractDigest}));const stage={attemptId:'attempt',owner:{cwd:resolve(worktree),task_id:'stage-task-ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',run_id:'attempt'},envelope:{worktree_realpath:resolve(worktree),egress:[],allowed_actions:['command']}} as any;const result=await createReadonlyVerifierWorker({db,control,runtimeRootBase:runtime,resolveBinding:()=>({stage,command})}).launch('attempt',new AbortController().signal);return{root,path,db,result,subject};}

test('exact payload nonce persists real identity and cleanup across reopen',async()=>{const f=await fixture('success');expect(f.result.outcome).toBe('succeeded');expect(f.result.identityRef).toMatch(/^cue-readonly-identity:/);expect(f.result.cleanupRef).toMatch(/^cue-readonly-cleanup:/);expect(f.db.prepare('SELECT count(*) n FROM readonly_verifier_identity').get()).toEqual({n:1});expect(f.db.prepare('SELECT count(*) n FROM readonly_verifier_cleanup').get()).toEqual({n:1});f.db.close();const reopened=openLedger(f.path);dbs.push(reopened);const identity=reopened.prepare('SELECT attempt_id,subject_digest,payload FROM readonly_verifier_identity').get() as any,cleanup=reopened.prepare('SELECT attempt_id,payload FROM readonly_verifier_cleanup').get() as any;expect(identity.attempt_id).toBe('attempt');expect(identity.subject_digest).toBe(f.subject);expect(JSON.parse(identity.payload.toString()).worker).toEqual({pid:321,createdFileTime:'12345678901'});expect(cleanup.attempt_id).toBe('attempt');expect(JSON.parse(cleanup.payload.toString()).result).toBe('verified-clean');});

test.each(['wrong-nonce','death-unknown'] as const)('%s persists no clean authority',async mode=>{if(mode==='death-unknown')state.dead.mockImplementation(()=>{throw Error('unknown');});const f=await fixture(mode);expect(f.result).toMatchObject({outcome:'failed',identityRef:null,cleanupRef:null});expect(f.db.prepare('SELECT count(*) n FROM readonly_verifier_identity').get()).toEqual({n:0});expect(f.db.prepare('SELECT count(*) n FROM readonly_verifier_cleanup').get()).toEqual({n:0});});
