import { afterEach,describe,expect,it,vi } from 'vitest';
import { createHash } from 'node:crypto';
const issuer=vi.hoisted(()=>({read:vi.fn()}));
vi.mock('../src/host-codex-runtime.js',async original=>({...await original(),readIssuedNativeRuntimeEvidence:issuer.read}));
import { openLedger,type Ledger } from '../src/ledger.js';
import { createNativeRuntimeReceiptStore } from '../src/orchestration/native-runtime-receipts.js';
const dbs:Ledger[]=[];afterEach(()=>{issuer.read.mockReset();for(const db of dbs.splice(0))db.close();});
function fixture(){const db=openLedger();dbs.push(db);const h='a'.repeat(64),h2='b'.repeat(64),stageTask='stage-task-'+'c'.repeat(64);db.prepare('INSERT INTO task VALUES(?,?,?,?)').run('task','running',null,new Date(0).toISOString());db.prepare('INSERT INTO task VALUES(?,?,?,?)').run('implement','running',null,new Date(0).toISOString());db.prepare('INSERT INTO envelope VALUES(?,?,?,?)').run(h,'C:\\work','[]',new Date(0).toISOString());db.prepare('INSERT INTO run(id,task_id,envelope_hash,started_at) VALUES(?,?,?,?)').run('run','task',h,new Date(0).toISOString());db.prepare('INSERT INTO task VALUES(?,?,?,?)').run(stageTask,'running',null,new Date(0).toISOString());db.prepare('INSERT INTO envelope VALUES(?,?,?,?)').run(h2,'C:\\stage','[]',new Date(0).toISOString());db.prepare('INSERT INTO run(id,task_id,envelope_hash,started_at) VALUES(?,?,?,?)').run('attempt',stageTask,h2,new Date(0).toISOString());db.prepare('INSERT INTO orchestration_plan VALUES(?,?,?,?)').run('run',h,h,'{}');db.prepare('INSERT INTO orchestration_step VALUES(?,?,?)').run('run','implement','running');db.prepare('INSERT INTO orchestration_attempt VALUES(?,?,?,?,?,?,?,?,?)').run('attempt','run','implement','candidate','running','{}','C:\\stage',null,0);db.prepare('INSERT INTO orchestration_stage_envelope VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run('attempt','run','implement',stageTask,'attempt',h,h2,h,h,'{}','{}','[]','{}');db.prepare('INSERT INTO session_handle VALUES(?,?,?,?,?,?)').run('session',123,'time','C:\\stage',stageTask,'attempt');const binding={runId:'run',taskId:'implement',attemptId:'attempt',candidateId:'candidate',subjectDigest:'b'.repeat(64),sessionHandle:'session',role:'implementation' as const,verificationMode:'approved-existing-file-change' as const};const evidence={version:'cue-issued-native-runtime-evidence-v1',...binding,outcomeInputs:{status:'completed',failureKind:null,goalVerification:{passed:true,reason:'workspace_changed',changedPaths:['target.txt']}},controller:{pid:123,createdFileTime:'133000000000000000'},workers:[{pid:124,createdFileTime:'133000000000000001'}],resources:[{path:'C:\\temp\\owned',ownership:'ephemeral-owned',cleanup:'absent'},{path:'C:\\profile',ownership:'retained-authorized',cleanup:'retained'}]};const result={};issuer.read.mockImplementation((given,bound)=>{if(given!==result||JSON.stringify(bound)!==JSON.stringify(binding))throw Error('native_runtime_evidence_unissued');return evidence;});return{db,binding,evidence,result};}
describe('native runtime receipt persistence',()=>{
 it('records only issuer evidence, round trips exact lineage and replays',()=>{const f=fixture(),s=createNativeRuntimeReceiptStore(f.db),saved=s.recordIssued(f.result as any,f.binding,1);expect(s.read(saved.ref)).toEqual(saved.receipt);expect(s.recordIssued(f.result as any,f.binding,1)).toEqual(saved);expect(()=>s.recordIssued({...f.result} as any,f.binding,1)).toThrow('unissued');});
 it('preserves authentic proof across a failed insert and exact retry',()=>{const f=fixture(),s=createNativeRuntimeReceiptStore(f.db);f.db.exec("CREATE TRIGGER fixture_refuse BEFORE INSERT ON native_runtime_receipt BEGIN SELECT RAISE(ABORT,'fixture_refuse'); END;");expect(()=>s.recordIssued(f.result as any,f.binding,1)).toThrow('fixture_refuse');f.db.exec('DROP TRIGGER fixture_refuse');expect(s.recordIssued(f.result as any,f.binding,1).ref).toMatch(/^cue-native-runtime-receipt:/);expect(issuer.read).toHaveBeenCalledTimes(2);});
 it('never promotes a read-only verifier signal into implementation success',()=>{const f=fixture(),s=createNativeRuntimeReceiptStore(f.db),cross={...f.evidence,verificationMode:'read-only-result',outcomeInputs:{status:'completed',failureKind:null,goalVerification:{passed:false,reason:'read_only_result_received',changedPaths:[]}}};issuer.read.mockReturnValue(cross);expect(()=>s.recordIssued(f.result as any,{...f.binding,verificationMode:'read-only-result'} as any,1)).toThrow('integrity');});
 it('detects direct SQL denormalized and canonical inner-shape tampering',()=>{const f=fixture(),s=createNativeRuntimeReceiptStore(f.db),saved=s.recordIssued(f.result as any,f.binding,1);f.db.exec('DROP TRIGGER native_runtime_receipt_no_update');f.db.prepare("UPDATE native_runtime_receipt SET candidate_id='other'").run();expect(()=>s.read(saved.ref)).toThrow('integrity');f.db.prepare("UPDATE native_runtime_receipt SET candidate_id='candidate'").run();const row=f.db.prepare('SELECT payload FROM native_runtime_receipt').get() as {payload:Buffer},value=JSON.parse(row.payload.toString());value.workers=[{pid:124,createdFileTime:'bad'}];const sort=(x:any):any=>Array.isArray(x)?x.map(sort):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,sort(x[k])])):x,payload=Buffer.from(JSON.stringify(sort(value))),digest=createHash('sha256').update(payload).digest('hex');f.db.prepare('UPDATE native_runtime_receipt SET payload=?,payload_digest=?').run(payload,digest);expect(()=>s.read(`cue-native-runtime-receipt:${digest}`)).toThrow('integrity');});
});




