import{afterEach,expect,test}from'vitest';import {createHash} from 'node:crypto';import {saveSelectionPolicy,bindRunSelectionPolicy} from '../src/selection/policy-store.js';import {validateTaskPlan} from '../src/orchestration/plan.js';import {createOrchestrationStore} from '../src/orchestration/store.js';import{openLedger}from'../src/ledger.js';import{bindAccountIdentities,readAccountIdentities,type AccountIdentity}from'../src/orchestration/account-binding.js';
const handles:ReturnType<typeof openLedger>[]=[];afterEach(()=>handles.splice(0).forEach(db=>db.open&&db.close()));const hash=(s:string)=>createHash('sha256').update(s).digest('hex');const h='a'.repeat(64);function fixture(){const db=openLedger();handles.push(db);db.prepare("INSERT INTO task VALUES('t','awaiting_approval',NULL,'now')").run();db.prepare("INSERT INTO envelope VALUES(?,?,?,'now')").run(h,'w','[]');db.prepare("INSERT INTO run VALUES('r','t',?,0,'now')").run(h);const policy=saveSelectionPolicy(db,{policyId:'p',expectedRevision:null,createdAt:new Date(1).toISOString(),sourceVersion:'fixture',policy:{version:'cue-selection-v1',mode:'efficiency',qualityMinimum:.5,costBasis:1,timeBasisMs:1,currency:'TEST',costLimit:null,remainingTimeMs:null,maxEstimateAgeMs:1000,allowedCandidateIds:['c','d'],pinnedCandidateId:null}});bindRunSelectionPolicy(db,{runId:'r',policyId:'p',revision:1,digest:policy.digest,boundAt:new Date(1).toISOString()});const approval={policyRevision:'p:1',policyDigest:policy.digest,requirementIds:['req'],allowedCandidateIds:['c','d'],allowedScopeIds:[]};const plan=validateTaskPlan(approval,{revision:'plan1',policyRevision:'p:1',policyDigest:policy.digest,tasks:[{id:'make',role:'model-producer',ownerId:'maker',requirementIds:['req'],dependencyIds:[],candidateIds:['c','d'],scopeIds:[]},{id:'check',role:'verifier',ownerId:'checker',requirementIds:['req'],dependencyIds:['make'],candidateIds:['c'],scopeIds:[]}]});createOrchestrationStore(db,{authorizePlan:()=>true,authorizeClaim:()=>true,verifyReceipt:()=>({outcomeVerified:false,cleanupVerified:false})}).install('r',plan);const value:AccountIdentity={runId:'r',candidateId:'c',authReference:'acct',toolId:'tool',sourceVersion:'v1',subjectDigest:h,modelId:null,endpointId:null,planDigest:plan.digest,policyDigest:policy.digest,envelopeHash:h};return{db,value};}
test('binds canonical opaque account identity exactly and replays',()=>{const f=fixture();const first=f.db.transaction(()=>bindAccountIdentities(f.db,[f.value])).immediate();expect(first[0]).toMatchObject({authReference:'acct',candidateId:'c'});expect(f.db.transaction(()=>bindAccountIdentities(f.db,[f.value])).immediate()[0].digest).toBe(first[0].digest);expect(Object.isFrozen(readAccountIdentities(f.db,'r')[0])).toBe(true);f.db.close();});
test('rejects changed identity and detects payload deletion/corruption',()=>{const f=fixture();f.db.transaction(()=>bindAccountIdentities(f.db,[f.value])).immediate();expect(()=>f.db.transaction(()=>bindAccountIdentities(f.db,[{...f.value,authReference:'other'}])).immediate()).toThrow('conflict');f.db.exec('DROP TRIGGER account_identity_no_update');f.db.prepare("UPDATE orchestration_account_identity SET payload=x'00' WHERE run_id='r'").run();expect(()=>readAccountIdentities(f.db,'r')).toThrow();f.db.close();});

const bind=(f:ReturnType<typeof fixture>,values:AccountIdentity[])=>f.db.transaction(()=>bindAccountIdentities(f.db,values)).immediate();
test('rejects hostile plain-data and mixed batches before writes even when outer transaction catches',()=>{const f=fixture();let traps=0;const accessor={...f.value};Object.defineProperty(accessor,'authReference',{enumerable:true,get(){traps++;return 'acct'}});const proxy=new Proxy(f.value,{get(){traps++;throw Error('trap')}});const bads:any[]=[[],[accessor],[proxy],[{...f.value,authReference:null}],[{...f.value,extra:true}],[f.value,f.value],[f.value,{...f.value,runId:'other',candidateId:'d'}],[f.value,{...f.value,candidateId:'d',subjectDigest:'bad'}]];for(const values of bads){f.db.transaction(()=>{expect(()=>bindAccountIdentities(f.db,values)).toThrow();expect(f.db.prepare('SELECT count(*) n FROM orchestration_account_identity').get()).toEqual({n:0});}).immediate();}expect(traps).toBe(0);});
test('SQL rejects scalar, digest and approved lineage substitutions',()=>{const f=fixture(),text=JSON.stringify(f.value),insert=(c:string,d:string,t:string)=>f.db.prepare('INSERT INTO orchestration_account_identity VALUES(?,?,?,?)').run('r',c,d,Buffer.from(t));expect(()=>insert('foreign',hash(text),text)).toThrow('insert binding');expect(()=>insert('c','b'.repeat(64),text)).toThrow('insert binding');const wrong=JSON.stringify({...f.value,planDigest:'b'.repeat(64)});expect(()=>insert('c',hash(wrong),wrong)).toThrow('insert binding');expect(f.db.prepare('SELECT count(*) n FROM orchestration_account_identity').get()).toEqual({n:0});});
test('does not partially extend an already bound candidate set',()=>{const f=fixture();bind(f,[f.value]);expect(()=>bind(f,[f.value,{...f.value,candidateId:'d'}])).toThrow('conflict');expect(readAccountIdentities(f.db,'r')).toHaveLength(1);});
test('refuses identity backfill after approval',()=>{const f=fixture();f.db.prepare("INSERT INTO approval_event(run_id,envelope_hash,thread_id,item_id,approval_id,request_ordinal,decision,created_at) VALUES('r',?,'d','i','a',0,'accept','now')").run(h);expect(()=>bind(f,[f.value])).toThrow('legacy_approved');expect(readAccountIdentities(f.db,'r')).toEqual([]);});
test('detects scalar drift even after guard name restoration',()=>{const f=fixture();bind(f,[f.value]);f.db.exec("DROP TRIGGER account_identity_no_update; UPDATE orchestration_account_identity SET candidate_id='d'; CREATE TRIGGER account_identity_no_update BEFORE UPDATE ON orchestration_account_identity BEGIN SELECT RAISE(ABORT,'immutable'); END;");expect(()=>readAccountIdentities(f.db,'r')).toThrow('integrity');});
test('binds endpoint identity and refuses missing guard',()=>{const f=fixture(),v={...f.value,modelId:'model',endpointId:'endpoint-a'};bind(f,[v]);expect(()=>bind(f,[{...v,endpointId:'endpoint-b'}])).toThrow('conflict');f.db.exec('DROP TRIGGER account_identity_insert_guard');expect(()=>readAccountIdentities(f.db,'r')).toThrow('migration_partial');});
