import {afterEach,describe,expect,it,vi} from 'vitest';
import {createHash} from 'node:crypto';
import {basename,dirname,join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {mkdtempSync,mkdirSync,readFileSync,rmSync,writeFileSync} from 'node:fs';
import {openLedger,type Ledger} from '../src/ledger.js';
import {captureChangeSet,registerNativeChangeJournal} from '../src/change-records.js';
import {createHandoffActivityStore} from '../src/orchestration/handoff-activity.js';
import {createFinalPublicationStore} from '../src/final-publication.js';

const roots:string[]=[],dbs:Ledger[]=[];
afterEach(()=>{dbs.splice(0).forEach(db=>db.open&&db.close());const base=resolve(tmpdir());for(const root of roots.splice(0)){const target=resolve(root);if(dirname(target)!==base||!basename(target).startsWith('cue-final-publication-'))throw Error('unsafe_test_cleanup');rmSync(target,{recursive:true,force:true});}});
const hash=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex');
function fixture(sharedWork?:string){
 const root=mkdtempSync(join(tmpdir(),'cue-final-publication-'));roots.push(root);const file=join(root,'ledger.db'),work=sharedWork??join(root,'work');if(!sharedWork)mkdirSync(work);writeFileSync(join(work,'final.txt'),'before');
 const db=openLedger(file);dbs.push(db);const parent=hash('parent'),stage=hash('stage'),plan=hash('plan'),policy=hash('policy'),selection=hash('selection'),subject=hash('subject');
 db.prepare("INSERT INTO task VALUES('root','running',NULL,'now')").run();db.prepare('INSERT INTO envelope VALUES(?,?,?,?)').run(parent,work,'[]','now');db.prepare("INSERT INTO run VALUES('run','root',?,0,'now')").run(parent);db.prepare("INSERT INTO orchestration_plan VALUES('run',?,?,?)").run(parent,plan,JSON.stringify({revision:'plan',tasks:[{id:'stage',role:'implementation',dependencyIds:[]}]}));db.prepare("INSERT INTO orchestration_step VALUES('run','stage','running')").run();
 registerNativeChangeJournal(db,{runId:'run',worktreeRealpath:work,targets:[{taskId:'stage',targetId:'final-target',relativePath:'final.txt',maxBackupBytes:1024}],observedAtMs:0});
 db.prepare("INSERT INTO workspace_write_lease VALUES(?,'run','lease-a')").run(work);db.prepare("INSERT INTO orchestration_attempt VALUES('attempt','run','stage','candidate','running','{}',?,'lease-a',0)").run(work);db.prepare("INSERT INTO task VALUES('stage-task','running',NULL,'now')").run();db.prepare('INSERT INTO envelope VALUES(?,?,?,?)').run(stage,work,'[]','now');db.prepare("INSERT INTO run VALUES('attempt','stage-task',?,0,'now')").run(stage);db.prepare("INSERT INTO orchestration_stage_envelope VALUES('attempt','run','stage','stage-task','attempt',?,?,?,?,?,?,?,?)").run(parent,stage,plan,policy,'{}','{}','{}','{}');db.prepare("INSERT INTO attempt_selection VALUES('attempt','run','request','monetary',?,?)").run(selection,'{}');
 createHandoffActivityStore(db,{authorizeArtifact:()=>false,resolveArtifact:()=>null}).recordLaunchIntent({runId:'run',taskId:'stage',attemptId:'attempt',candidateId:'candidate',selectionDigest:selection,expectedSubjectDigest:subject,tool:{id:'tool',revision:'r'},model:null,parentEnvelopeHash:parent,stageEnvelopeHash:stage,planDigest:plan,policyDigest:policy});
 captureChangeSet(db,{changeSetId:'set',runId:'run',taskId:'stage',attemptId:'attempt',stageEnvelopeHash:stage,launchIntentId:'attempt',worktree:work,targets:['final.txt'],limits:{maxTargets:1,maxBackupBytes:1024},nowMs:1});
 return{root,file,work,db,target:join(work,'final.txt')};
}
function committed(input:any){writeFileSync(join(input.root,input.target),input.replacement);return{state:'committed' as const,rootIdentity:input.expectedRoot,before:input.expected,after:{identity:input.expected.identity,byteLength:input.replacement.length,sha256:hash(input.replacement)}};}

describe('durable final existing-file publication',()=>{
 it('uses the pinned native helper for an existing-file win and a stale-preimage loss',()=>{
  const winner=fixture(),loser=fixture(winner.work),win=createFinalPublicationStore(winner.db,{authorize:()=>true,nowMs:10}).publish({publicationId:'native-win',changeSetId:'set',relativePath:'final.txt',replacement:Buffer.from('A')});expect(win).toMatchObject({state:'committed',after:{sha256:hash('A')}});expect(readFileSync(winner.target,'utf8')).toBe('A');
  const loss=createFinalPublicationStore(loser.db,{authorize:()=>true,nowMs:10}).publish({publicationId:'native-loss',changeSetId:'set',relativePath:'final.txt',replacement:Buffer.from('B')});expect(loss).toEqual({publicationId:'native-loss',state:'contention',reason:'native-contention'});expect(readFileSync(loser.target,'utf8')).toBe('A');
 });
 it('commits intent before the write, protects copied bytes, and replays without callbacks',()=>{
  const f=fixture(),replacement=Buffer.from('after'),authorize=vi.fn((context:any)=>{expect((f.db.prepare('SELECT count(*) n FROM change_publication_intent').get() as any).n).toBe(0);expect(Object.isFrozen(context.target.preimage)).toBe(true);replacement.fill(120);return true;}),execute=vi.fn((input:any)=>{expect((f.db.prepare('SELECT count(*) n FROM change_publication_intent').get() as any).n).toBe(1);return committed(input);});
  const store=createFinalPublicationStore(f.db,{authorize,execute,nowMs:10}),result=store.publish({publicationId:'publication-a',changeSetId:'set',relativePath:'final.txt',replacement});
  expect(result).toMatchObject({state:'committed',after:{byteLength:5,sha256:hash('after')}});expect(readFileSync(f.target,'utf8')).toBe('after');expect(authorize).toHaveBeenCalledTimes(1);expect(execute).toHaveBeenCalledTimes(1);
  expect(store.publish({publicationId:'publication-a',changeSetId:'set',relativePath:'final.txt',replacement:Buffer.from('after')})).toEqual(result);expect(authorize).toHaveBeenCalledTimes(1);expect(execute).toHaveBeenCalledTimes(1);
  expect(()=>store.publish({publicationId:'publication-a',changeSetId:'set',relativePath:'final.txt',replacement:Buffer.from('other')})).toThrow('change_publication_conflict');
 });
 it('leaves a thrown post-intent execution pending across reopen and holds its exact lease',()=>{
  const f=fixture(),execute=vi.fn(()=>{throw Error('simulated-crash-after-intent');}),store=createFinalPublicationStore(f.db,{authorize:()=>true,execute,nowMs:10});expect(()=>store.publish({publicationId:'crash',changeSetId:'set',relativePath:'final.txt',replacement:Buffer.from('after')})).toThrow('simulated-crash-after-intent');expect(store.read('crash')).toEqual({publicationId:'crash',state:'pending'});expect(()=>f.db.prepare("DELETE FROM workspace_write_lease WHERE run_id='run'").run()).toThrow('change publication outcome unresolved');
  f.db.close();dbs.splice(dbs.indexOf(f.db),1);const reopened=openLedger(f.file);dbs.push(reopened);const authorize=vi.fn(()=>true),relaunch=vi.fn();const next=createFinalPublicationStore(reopened,{authorize,execute:relaunch});expect(next.publish({publicationId:'crash',changeSetId:'set',relativePath:'final.txt',replacement:Buffer.from('after')})).toEqual({publicationId:'crash',state:'pending'});expect(authorize).not.toHaveBeenCalled();expect(relaunch).not.toHaveBeenCalled();expect(readFileSync(f.target,'utf8')).toBe('before');
 });
 it('keeps a completed write pending when terminal persistence fails and stores malformed host output as unknown',()=>{
  const f=fixture(),store=createFinalPublicationStore(f.db,{authorize:()=>true,execute:(input:any)=>{const result=committed(input);f.db.exec("CREATE TRIGGER fixture_result_failure BEFORE INSERT ON change_publication_result BEGIN SELECT RAISE(ABORT,'fixture result failure'); END");return result;},nowMs:10});expect(()=>store.publish({publicationId:'persist-failure',changeSetId:'set',relativePath:'final.txt',replacement:Buffer.from('after')})).toThrow('fixture result failure');expect(readFileSync(f.target,'utf8')).toBe('after');expect(store.read('persist-failure')).toEqual({publicationId:'persist-failure',state:'pending'});expect(()=>f.db.prepare("DELETE FROM workspace_write_lease WHERE run_id='run'").run()).toThrow('change publication outcome unresolved');
  const other=fixture(),malformed=new Proxy({state:'committed'},{}),unknown=createFinalPublicationStore(other.db,{authorize:()=>true,execute:()=>malformed as never,nowMs:10}).publish({publicationId:'malformed',changeSetId:'set',relativePath:'final.txt',replacement:Buffer.from('after')});expect(unknown).toEqual({publicationId:'malformed',state:'unknown',reason:'native-unknown'});expect(readFileSync(other.target,'utf8')).toBe('before');expect(()=>other.db.prepare("DELETE FROM workspace_write_lease WHERE run_id='run'").run()).toThrow('change publication outcome unresolved');
 });
 it('persists bounded contention and unknown outcomes with truthful lease behavior',()=>{
  const f=fixture(),contention=createFinalPublicationStore(f.db,{authorize:()=>true,execute:()=>({state:'contention',reason:'private path C:/secret'}),nowMs:10});expect(contention.publish({publicationId:'loser',changeSetId:'set',relativePath:'final.txt',replacement:Buffer.from('B')})).toEqual({publicationId:'loser',state:'contention',reason:'native-contention'});expect(readFileSync(f.target,'utf8')).toBe('before');
  const outcome=f.db.prepare("SELECT reason FROM change_publication_result WHERE publication_id='loser'").get();expect(outcome).toEqual({reason:'native-contention'});f.db.prepare("UPDATE orchestration_attempt SET cleanup_verified=1 WHERE attempt_id='attempt'").run();f.db.prepare("DELETE FROM workspace_write_lease WHERE run_id='run'").run();
 });
 it('rejects hostile terminal labels and downgrades incomplete host receipts to unknown',()=>{
  const f=fixture(),pending=createFinalPublicationStore(f.db,{authorize:()=>true,execute:()=>{throw Error('pause');},nowMs:10});expect(()=>pending.publish({publicationId:'hostile-result',changeSetId:'set',relativePath:'final.txt',replacement:Buffer.from('after')})).toThrow('pause');const body={schemaVersion:'cue-change-publication-result-v1',publicationId:'hostile-result',state:'contention',reason:'forged',rootIdentity:null,before:null,after:null,recordedAtMs:11},encoded=Buffer.from(JSON.stringify(body));expect(()=>f.db.prepare('INSERT INTO change_publication_result VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run('hostile-result','contention','forged',null,null,null,null,null,null,null,null,null,null,11,hash(encoded),encoded)).toThrow();expect(pending.read('hostile-result')).toEqual({publicationId:'hostile-result',state:'pending'});
  const other=fixture(),malformed=createFinalPublicationStore(other.db,{authorize:()=>true,execute:()=>({state:'contention'} as never),nowMs:10}).publish({publicationId:'incomplete',changeSetId:'set',relativePath:'final.txt',replacement:Buffer.from('after')});expect(malformed).toEqual({publicationId:'incomplete',state:'unknown',reason:'native-unknown'});expect(()=>other.db.prepare("DELETE FROM workspace_write_lease WHERE run_id='run'").run()).toThrow('change publication outcome unresolved');
 });
 it('denies malformed input, absent authority, expiry, and outer transactions before write',()=>{
  let f=fixture(),execute=vi.fn();let store=createFinalPublicationStore(f.db,{authorize:()=>false,execute});expect(()=>store.publish({publicationId:'denied',changeSetId:'set',relativePath:'final.txt',replacement:Buffer.from('x')})).toThrow('change_publication_authority_denied');expect(execute).not.toHaveBeenCalled();expect((f.db.prepare('SELECT count(*) n FROM change_publication_intent').get() as any).n).toBe(0);
  expect(()=>store.publish({publicationId:'bad',changeSetId:'set',relativePath:'missing.txt',replacement:Buffer.from('x')})).toThrow('change_publication_journal_invalid');expect(()=>store.publish({publicationId:'large',changeSetId:'set',relativePath:'final.txt',replacement:Buffer.alloc(1025)})).toThrow('change_publication_journal_invalid');
  store=createFinalPublicationStore(f.db,{authorize:()=>{f.db.prepare("UPDATE orchestration_attempt SET state='blocked' WHERE attempt_id='attempt'").run();return true;},execute});expect(()=>store.publish({publicationId:'expired',changeSetId:'set',relativePath:'final.txt',replacement:Buffer.from('x')})).toThrow();expect(execute).not.toHaveBeenCalled();expect((f.db.prepare('SELECT count(*) n FROM change_publication_intent').get() as any).n).toBe(0);
  f=fixture();store=createFinalPublicationStore(f.db,{authorize:()=>true,execute});expect(()=>f.db.transaction(()=>store.publish({publicationId:'nested',changeSetId:'set',relativePath:'final.txt',replacement:Buffer.from('x')}))()).toThrow('change_publication_outer_transaction');expect(execute).not.toHaveBeenCalled();expect((f.db.prepare('SELECT count(*) n FROM change_publication_intent').get() as any).n).toBe(0);
 });
 it('fails startup on a partial guard set and keeps intent/result rows immutable',()=>{
  const f=fixture(),store=createFinalPublicationStore(f.db,{authorize:()=>true,execute:committed,nowMs:10});store.publish({publicationId:'sealed',changeSetId:'set',relativePath:'final.txt',replacement:Buffer.from('after')});expect(()=>f.db.prepare("UPDATE change_publication_intent SET relative_path='other' WHERE publication_id='sealed'").run()).toThrow('immutable');expect(()=>f.db.prepare("DELETE FROM change_publication_result WHERE publication_id='sealed'").run()).toThrow('immutable');f.db.exec('DROP TRIGGER change_publication_result_no_update');f.db.close();dbs.splice(dbs.indexOf(f.db),1);expect(()=>openLedger(f.file)).toThrow('change_publication_migration_partial');
 });
});
