import {afterEach,expect,test} from 'vitest';
import {createHash} from 'node:crypto';
import {mkdirSync,mkdtempSync,rmSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {openLedger,type Ledger} from '../src/ledger.js';
import {normalizeEnvelope,envelopeHash} from '../src/envelope.js';
import {saveSelectionPolicy} from '../src/selection/policy-store.js';
import {createIntegrationCatalog} from '../src/integration-catalog.js';
import {SUBJECT_FIELDS,subjectDigest,type MeasurementSubject} from '../src/measurement-subject.js';
import {WRITE_PROBES,MODEL_PROBES} from '../src/capability-admission.js';
import {createOrchestrationDriver} from '../../app/orchestration-driver.mjs';

const roots:string[]=[],dbs:Ledger[]=[];afterEach(async()=>{for(const db of dbs.splice(0))if(db.open)db.close();const prefix=resolve(tmpdir(),'cue-release-refusal-');for(const root of roots.splice(0)){const target=resolve(root);if(!target.startsWith(prefix))throw Error('fixture_cleanup_scope');rmSync(target,{recursive:true,force:true})}});
const now=Date.parse('2026-09-15T00:00:00.000Z'),sha=(b:Uint8Array)=>createHash('sha256').update(b).digest('hex');
function fixture(){
 const root=mkdtempSync(join(tmpdir(),'cue-release-refusal-')),work=join(root,'work');roots.push(root);mkdirSync(work);const db=openLedger();dbs.push(db);
 const envelope=normalizeEnvelope({run_id:'run',worktree_realpath:work,allowed_actions:['read'],egress:[],expires_at:'2026-09-16T00:00:00.000Z',autonomy_level:'bounded'}),eh=envelopeHash(envelope),run={taskId:'root',runId:'run',envelopeHash:eh,envelope,autonomy:3,copy:{},goal:'scope refusal',scope:'code'};
 db.prepare("INSERT INTO task VALUES('root','awaiting_approval',NULL,'now')").run();db.prepare("INSERT INTO envelope VALUES(?,?,'[]','now')").run(eh,work);db.prepare("INSERT INTO run VALUES('run','root',?,0,'now')").run(eh);
 const policy=saveSelectionPolicy(db,{policyId:'policy',expectedRevision:null,createdAt:new Date(now).toISOString(),sourceVersion:'fixture',policy:{version:'cue-selection-v1',mode:'efficiency',qualityMinimum:.5,costBasis:1,timeBasisMs:1,currency:'TEST',costLimit:100,remainingTimeMs:null,maxEstimateAgeMs:1000,allowedCandidateIds:['agent'],pinnedCandidateId:'agent'}});
 const subject=Object.fromEntries(SUBJECT_FIELDS.map(k=>[k,k.endsWith('Sha256')?'a'.repeat(64):k])) as MeasurementSubject,evidence=new Map<string,Buffer>(),refs:any={};for(const probe of [...WRITE_PROBES,...MODEL_PROBES]){const bytes=Buffer.from(JSON.stringify({probe,subjectDigest:subjectDigest(subject),measuredAt:new Date(now-1).toISOString(),kind:'live',status:'pass'}));evidence.set(probe,bytes);refs[probe]={id:probe,sha256:sha(bytes)}}
 const state={launches:0,accountRef:'approved-account',candidateId:'agent',budgetLimit:100,stageActions:[] as string[],configurationCalls:0};
 const catalog=()=>createIntegrationCatalog({now:()=>now,maxAgeMs:1000,currentSubjectDigest:()=>subjectDigest(subject)},[{canonicalId:'agent',toolId:'fixture',kind:'agent',aliases:[],installation:'installed',protocol:'verified',authReference:state.accountRef,authAvailable:true,sourceVersion:'fixture',observedAt:new Date(now).toISOString(),subjectDigest:subjectDigest(subject),binding:null}]);
 const configuration=()=>({policy:{policyId:'policy',revision:1,digest:policy.digest},requirementIds:['req'],proposedPlan:{revision:'plan1',policyRevision:'policy:1',policyDigest:policy.digest,tasks:[{id:'read-task',role:'model-producer',ownerId:'maker',requirementIds:['req'],dependencyIds:[],candidateIds:[state.candidateId],scopeIds:[]},{id:'check-task',role:'verifier',ownerId:'checker',requirementIds:['req'],dependencyIds:['read-task'],candidateIds:['agent'],scopeIds:[]}]},scopes:[],budget:{runId:'run',currency:'TEST',unit:'micro',limitUnits:state.budgetLimit,policyRevision:'policy:1',source:'fixture',observedAtMs:now},limits:{launchTimeoutMs:100,taskTimeoutMs:100,pollMs:1}});
 const host:any={now:()=>now,catalog:catalog(),prepare:()=>{state.configurationCalls++;return configuration()},verifyFinalBilling:()=>true,authority:{authorizePlan:()=>true,authorizeClaim:()=>true,authorizeStage:()=>true,verifyReceipt:()=>({outcomeVerified:false,cleanupVerified:true}),authorizeHandoffArtifact:()=>false,resolveHandoffArtifact:()=>null},runtime:{evidence:{now:()=>now,maxAgeMs:1000,resolveEvidence:(ref:any)=>evidence.get(ref.id)},authorizeRun:()=>true,verifyCleanup:async(context:any)=>({runId:context.runId,subjectDigest:context.subjectDigest,result:'verified-clean',evidenceRef:'fixture-clean'}),resolveCandidate:()=>({kind:'agent',supportedRoles:['model'],cancellation:'supported',usage:'unsupported',availability:'ready',typedActivitySource:'host-codex-controller-v1',durableExecutionRef:'session-handle-v1',buildCurrentSubject:()=>subject,evidenceReferences:()=>refs,launch:async(context:any)=>{state.launches++;expect(context.accountIdentity.reference).toBe('approved-account');return{durableRef:'session:fixture-unresolved',completion:Promise.resolve('failed'),cancel:async()=>{}}}})},engine:{observeCandidates:()=>[{id:'agent',checks:{eligible:true,authenticated:true,compatible:true,dataAllowed:true,resourceAvailable:true,quotaAvailable:true},estimate:{scope:'verified-completion-total',quality:1,expectedCost:1,conservativeMaxCost:1,expectedTimeMs:1,conservativeMaxTimeMs:1,currency:'TEST',source:'fixture',observedAtMs:now}}],reservation:(context:any)=>({runId:'run',attemptId:context.request.attemptId,requestId:context.request.requestId,currency:'TEST',unit:'micro',upperUnits:1,source:'fixture',observedAtMs:now,scope:'verified-completion-attempt-total'}),verifyBudgetMapping:()=>true,authorizeExecution:()=>true,receipts:()=>({billing:null,execution:null})},stage:()=>({worktreeRealpath:work,allowedActions:state.stageActions,egress:[],expiresAt:envelope.expires_at,autonomyLevel:'bounded'})};
 const approve=()=>db.prepare("INSERT INTO approval_event(run_id,envelope_hash,thread_id,item_id,approval_id,request_ordinal,decision,created_at) VALUES('run',?,'desktop','goal','approval',0,'accept','now')").run(eh);
 return{db,run,state,host,catalog,approve,driver:()=>createOrchestrationDriver({db,host})};
}
const activity=(db:Ledger)=>({attempts:(db.prepare('SELECT count(*) n FROM orchestration_attempt').get() as any).n,leases:(db.prepare('SELECT count(*) n FROM workspace_write_lease').get() as any).n,reservations:(db.prepare('SELECT count(*) n FROM integration_budget_reservation').get() as any).n,sessions:(db.prepare('SELECT count(*) n FROM session_handle').get() as any).n});

test('outside approved model is refused before orchestration activity',async()=>{const f=fixture();f.state.candidateId='outside-model';const driver=f.driver();expect(()=>driver.prepare(f.run)).toThrow('invalid_plan:scope-expansion');expect(f.state.launches).toBe(0);expect(activity(f.db)).toEqual({attempts:0,leases:0,reservations:0,sessions:0});await driver.close()});
test('expanded task permission never reaches the adapter',async()=>{const f=fixture();f.state.stageActions=['file_change'];const driver=f.driver();driver.prepare(f.run);f.approve();driver.activate(f.run);const before=activity(f.db);await driver.start(f.run);await driver.settled();const after=activity(f.db);expect(f.state.launches).toBe(0);expect(after.sessions).toBe(0);expect(after.attempts).toBeGreaterThanOrEqual(before.attempts);expect(driver.snapshot('run').reason).toBeTruthy();await driver.close()});
test('changed opaque account reference is refused for the same candidate and subject',async()=>{const f=fixture(),first=f.driver();first.prepare(f.run);await first.close();f.state.accountRef='outside-account';f.host.catalog=f.catalog();const reopened=f.driver();expect(()=>reopened.prepare(f.run)).toThrow('account_identity_conflict');expect(f.state.launches).toBe(0);expect(activity(f.db)).toEqual({attempts:0,leases:0,reservations:0,sessions:0});await reopened.close()});
test('budget increase on reopen is refused without adapter activity',async()=>{const f=fixture(),first=f.driver();first.prepare(f.run);await first.close();f.state.budgetLimit=101;const reopened=f.driver();expect(()=>reopened.prepare(f.run)).toThrow('budget_policy_mismatch');expect(f.state.launches).toBe(0);expect(activity(f.db)).toEqual({attempts:0,leases:0,reservations:0,sessions:0});await reopened.close()});
test('approved opaque reference reaches one adapter but does not claim terminal cleanup',async()=>{
 const f=fixture(),driver=f.driver();driver.prepare(f.run);f.approve();driver.activate(f.run);await driver.start(f.run);expect(f.state.launches).toBe(1);expect(activity(f.db).sessions).toBe(0);await expect(driver.settled()).rejects.toThrow('orchestration_cleanup_unverified');await expect(driver.close()).rejects.toThrow('orchestration_cleanup_unverified');
});
