import { afterEach,expect,test } from 'vitest';
import { mkdtempSync,readFileSync,rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { createHash } from 'node:crypto';
import { openLedger,type Ledger } from '../src/ledger.js';
import { createGeneratedJsonHandoffAuthority } from '../../app/generated-json-handoff-authority.mjs';
import { createHandoffActivityStore } from '../src/orchestration/handoff-activity.js';

const dbs:Ledger[]=[],roots:string[]=[];afterEach(()=>{for(const db of dbs.splice(0))if(db.open)db.close();for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
const sha=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex');
function exactHandoff(){const root=mkdtempSync(join(tmpdir(),'cue-recovery-handoff-'));roots.push(root);const file=join(root,'ledger.sqlite'),db=openLedger(file);dbs.push(db);const parent=sha('parent'),stage=sha('stage'),plan=sha('plan'),policy=sha('policy'),selection=sha('selection'),subject=sha('subject');
  db.prepare("INSERT INTO task VALUES('root','running',NULL,'now')").run();db.prepare("INSERT INTO envelope VALUES(?,'C:\\work','[]','now')").run(parent);db.prepare("INSERT INTO run VALUES('run','root',?,0,'now')").run(parent);db.prepare("INSERT INTO orchestration_plan VALUES('run',?,?,?)").run(parent,plan,JSON.stringify({revision:'plan',tasks:[{id:'stage',role:'implementation',dependencyIds:[]}]}));db.prepare("INSERT INTO orchestration_step VALUES('run','stage','running')").run();db.prepare("INSERT INTO orchestration_attempt VALUES('attempt','run','stage','candidate','running','{}','C:\\work',NULL,0)").run();db.prepare("INSERT INTO task VALUES('stage-task','running',NULL,'now')").run();db.prepare("INSERT INTO envelope VALUES(?,'C:\\work','[]','now')").run(stage);db.prepare("INSERT INTO run VALUES('attempt','stage-task',?,0,'now')").run(stage);db.prepare("INSERT INTO session_handle VALUES('session-attempt',1,'now','C:\\work','stage-task','attempt')").run();db.prepare("INSERT INTO orchestration_stage_envelope VALUES('attempt','run','stage','stage-task','attempt',?,?,?,?,?,?,?,?)").run(parent,stage,plan,policy,'{}','{}','{}','{}');db.prepare("INSERT INTO attempt_selection VALUES('attempt','run','request','monetary',?,?)").run(selection,'{}');
  let bytes:Uint8Array=Buffer.from('trusted bytes'),allowed=true;const reader=()=>createHandoffActivityStore(db,{authorizeArtifact:(ref,attempt)=>allowed&&ref==='artifact-ref'&&attempt==='attempt',resolveArtifact:(ref,attempt)=>allowed&&ref==='artifact-ref'&&attempt==='attempt'?bytes:null}),store=reader();store.recordLaunchIntent({runId:'run',taskId:'stage',attemptId:'attempt',candidateId:'candidate',selectionDigest:selection,expectedSubjectDigest:subject,tool:{id:'tool',revision:'unknown'},model:null,parentEnvelopeHash:parent,stageEnvelopeHash:stage,planDigest:plan,policyDigest:policy});store.recordAttemptIdentity({identityId:'identity',attemptId:'attempt',subjectDigest:subject,durableRef:'session:session-attempt',observedAtMs:1});const receipt=JSON.stringify({attemptId:'attempt',receiptId:'receipt',revision:1,outcome:'succeeded',cleanup:'clean'}),handoff=store.prepareHandoff({handoffId:'handoff',attemptId:'attempt',receiptId:'receipt',receiptRevision:1,identityId:'identity',outcome:'succeeded',cleanup:'clean',artifacts:[{kind:'output',sourceRef:'artifact-ref'}]});db.transaction(()=>{db.prepare("INSERT INTO orchestration_receipt VALUES('receipt','attempt',1,?)").run(receipt);store.commitHandoff(handoff);store.commitTerminalState('attempt','completed');}).immediate();return{root,file,db,reader,setBytes:(value:Buffer)=>{bytes=value;},deny:()=>{allowed=false;}};}

test('offline handoff authority fails closed without persisted exact-attempt artifacts',()=>{const db=openLedger();dbs.push(db);const authority=createGeneratedJsonHandoffAuthority({db});expect(authority.resolveHandoffArtifact('generated-output:missing','attempt')).toBeNull();expect(authority.authorizeHandoffArtifact('verified-input:missing','attempt')).toBe(false);expect(()=>db.transaction(()=>createGeneratedJsonHandoffAuthority({db}))()).toThrow('generated_handoff_authority_unavailable');});

test('startup registers the offline resolver and leaves decisive external authority deployment supplied',()=>{const main=readFileSync(new URL('../../app/main.mjs',import.meta.url),'utf8'),host=readFileSync(new URL('../../app/native-recovery-host.mjs',import.meta.url),'utf8');expect(main).toContain('createGeneratedJsonHandoffAuthority({db})');expect(main).toContain('createNativeRecoveryHost({ guard, daemon, worktree, handoffAuthority:');expect(host).toContain("handoffs.readTerminalIntegrity(attemptId).status==='verified'");expect(host).toContain('externalEffectObservers=new Map(), externalEffectVerifier');expect(host).toContain('reconcileHeldRecovery(db,held.caseId,externalEffectObservers,Date.now(),authority,handoffValid,externalEffectVerifier)');expect(host).not.toMatch(/SELECT 1 FROM orchestration_handoff WHERE/);});

test('offline resolver module contains no qualification, settings, execution, or network dependency',()=>{const source=readFileSync(new URL('../../app/generated-json-handoff-authority.mjs',import.meta.url),'utf8');expect(source).toContain('generatedOutputs.read(');expect(source).not.toMatch(/^import .*?(qualification|settings|executor)/im);expect(source).not.toMatch(/fetch\(|launch\(/);});

test('exact-attempt terminal reader survives reopen and rejects missing, changed, unauthorized, wrong-attempt, and corrupt artifacts',()=>{const f=exactHandoff();expect(f.reader().readTerminalIntegrity('attempt').status).toBe('verified');expect(f.reader().readTerminalIntegrity('wrong-attempt').status).toBe('integrity-unavailable');f.db.close();const reopened=openLedger(f.file);dbs.push(reopened);expect(createHandoffActivityStore(reopened,{authorizeArtifact:(ref,attempt)=>ref==='artifact-ref'&&attempt==='attempt',resolveArtifact:(ref,attempt)=>ref==='artifact-ref'&&attempt==='attempt'?Buffer.from('trusted bytes'):null}).readTerminalIntegrity('attempt').status).toBe('verified');reopened.close();dbs.splice(dbs.indexOf(reopened),1);
  const changed=openLedger(f.file);dbs.push(changed);const changedReader=createHandoffActivityStore(changed,{authorizeArtifact:()=>true,resolveArtifact:()=>Buffer.from('changed bytes')});expect(changedReader.readTerminalIntegrity('attempt').status).toBe('integrity-unavailable');changed.close();dbs.splice(dbs.indexOf(changed),1);
  const denied=openLedger(f.file);dbs.push(denied);expect(createHandoffActivityStore(denied,{authorizeArtifact:()=>false,resolveArtifact:()=>null}).readTerminalIntegrity('attempt').status).toBe('integrity-unavailable');denied.exec('DROP TRIGGER handoff_artifact_no_update');denied.prepare("UPDATE orchestration_handoff_artifact SET sha256=? WHERE handoff_id='handoff'").run('f'.repeat(64));expect(createHandoffActivityStore(denied,{authorizeArtifact:()=>true,resolveArtifact:()=>Buffer.from('trusted bytes')}).readTerminalIntegrity('attempt').status).toBe('integrity-unavailable');});
