import { afterEach, expect, test } from 'vitest';
import { rmSync } from 'node:fs';
import { join } from 'node:path';
import { openLedger, type Ledger } from '../src/ledger.js';
import { bindRunSelectionPolicy, readRunSelectionPolicy, saveSelectionPolicy, type StoredSelectionPolicy } from '../src/selection/policy-store.js';
import { createPolicyPromotionStore, qualifiedPolicyComparisonDigest, type QualifiedPolicyComparison } from '../src/selection/policy-promotion.js';

const handles:Ledger[]=[];const files:string[]=[];
afterEach(()=>{for(const db of handles.splice(0))if(db.open)db.close();for(const file of files.splice(0))rmSync(file,{force:true})});
const h=(c:string)=>c.repeat(64);
function db(file?:string){const value=openLedger(file);handles.push(value);return value}
function policy(database:Ledger,id:string,mode:'efficiency'|'performance'='efficiency',currency='TEST'){return saveSelectionPolicy(database,{policyId:id,expectedRevision:null,createdAt:'2026-09-15T00:00:00.000Z',sourceVersion:'fixture',policy:{version:'cue-selection-v1',mode,qualityMinimum:.5,costBasis:1,timeBasisMs:1000,currency,costLimit:null,remainingTimeMs:null,maxEstimateAgeMs:1000,allowedCandidateIds:['agent'],pinnedCandidateId:null}})}
const identity=(p:StoredSelectionPolicy)=>({policyId:p.policyId,revision:p.revision,digest:p.digest});
function qualification(baseline:StoredSelectionPolicy,candidate:StoredSelectionPolicy,overrides:Record<string,unknown>={}):QualifiedPolicyComparison{
  const body={version:'cue-qualified-policy-comparison-v1',authority:'host-authenticated-empirical-comparison',qualificationId:'qualification-1',authorityId:'synthetic-test-authority',baseline:identity(baseline),candidate:identity(candidate),dataset:{id:'dataset',revision:'r1',digest:h('1'),caseCommitments:[h('2'),h('3')]},holdout:{id:'holdout',revision:'r1',digest:h('4'),caseCommitments:[h('5')]},metric:{id:'quality',revision:'r1',digest:h('6')},environment:{id:'environment',revision:'r1',digest:h('7')},accountLimits:{id:'limits',revision:'r1',digest:h('8')},measures:{baselineFactDigests:[h('9')],candidateFactDigests:[h('a')],qualityDelta:.1,elapsedDeltaMs:-5,costDeltaUnits:-2},priceTimeEvidenceDigest:h('b'),trialEvidenceDigest:h('c'),comparisonEvidenceDigest:h('d'),verdict:'qualified-improvement',qualifiedAtMs:1000,...overrides} as Omit<QualifiedPolicyComparison,'digest'>;
  return Object.freeze({...body,digest:qualifiedPolicyComparisonDigest(body)}) as QualifiedPolicyComparison;
}
function setup(database=db()){const baseline=policy(database,'baseline'),candidate=policy(database,'candidate'),q=qualification(baseline,candidate);let calls=0;const store=createPolicyPromotionStore(database,{resolveQualification(id){calls++;return id===q.qualificationId?q:null}},()=>2000);store.initialize({transitionId:'initialize-1',channelId:'default',mode:'efficiency',policy:identity(baseline),recordedAtMs:900});return{database,baseline,candidate,q,store,calls:()=>calls}}
const promote=(f:ReturnType<typeof setup>,extra:Record<string,unknown>={})=>f.store.promote({transitionId:'promote-1',channelId:'default',expectedGeneration:1,candidate:identity(f.candidate),qualificationId:'qualification-1',recordedAtMs:1100,...extra});

test('refuses descriptive, malformed, overlapping, future, wrong-mode and wrong-currency qualification without writes',()=>{
  const cases:((f:ReturnType<typeof setup>)=>unknown)[]=[
    ()=>({version:'cue-evaluation-comparison-snapshot-v1',authority:'immutable-projection-membership-descriptive-only',promotionEligible:false}),
    (f:ReturnType<typeof setup>)=>({...f.q,dataset:{...f.q.dataset,caseCommitments:[h('5')]},digest:h('0')}),
    (f:ReturnType<typeof setup>)=>qualification(f.baseline,f.candidate,{qualifiedAtMs:3000}),
    (f:ReturnType<typeof setup>)=>qualification(f.baseline,f.candidate,{measures:{...f.q.measures,qualityDelta:-.1,elapsedDeltaMs:5,costDeltaUnits:2}}),
  ];
  for(const make of cases){const database=db(),baseline=policy(database,'baseline'),candidate=policy(database,'candidate');let calls=0;const store=createPolicyPromotionStore(database,{resolveQualification(){calls++;return make({database,baseline,candidate,q:qualification(baseline,candidate),store:null as never,calls:()=>calls})}},()=>2000);store.initialize({transitionId:'init',channelId:'default',mode:'efficiency',policy:identity(baseline),recordedAtMs:1});expect(()=>store.promote({transitionId:'promote',channelId:'default',expectedGeneration:1,candidate:identity(candidate),qualificationId:'qualification-1',recordedAtMs:2})).toThrow();expect(calls).toBe(1);expect(database.prepare('SELECT count(*) n FROM selection_policy_deployment_transition').get()).toEqual({n:1});expect(database.prepare('SELECT count(*) n FROM selection_policy_qualification').get()).toEqual({n:0})}
  const f=setup();let resolverCalls=0;const malformed=createPolicyPromotionStore(f.database,{resolveQualification(){resolverCalls++;return f.q}},()=>2000);const candidate=Object.defineProperty({},'policyId',{get(){throw Error('getter')}});expect(()=>malformed.promote({transitionId:'bad',channelId:'default',expectedGeneration:1,candidate,qualificationId:'qualification-1',recordedAtMs:2})).toThrow();expect(resolverCalls).toBe(0);
  for(const [id,mode,currency] of [['wrong-mode','performance','TEST'],['wrong-currency','efficiency','OTHER']] as const){const p=policy(f.database,id,mode,currency),q=qualification(f.baseline,p,{qualificationId:`q-${id}`});const store=createPolicyPromotionStore(f.database,{resolveQualification(){return q}},()=>2000);expect(()=>store.promote({transitionId:`t-${id}`,channelId:'default',expectedGeneration:1,candidate:identity(p),qualificationId:q.qualificationId,recordedAtMs:2})).toThrow();}
  expect(f.database.prepare('SELECT count(*) n FROM selection_policy_deployment_transition').get()).toEqual({n:1});
});

test('promotes from a canonical synthetic authority, persists it, and exact replay needs no resolver',()=>{const f=setup();const result=promote(f);expect(result).toMatchObject({generation:2,latestTransitionId:'promote-1',policy:{policyId:'candidate'}});expect(f.calls()).toBe(1);const replay=createPolicyPromotionStore(f.database,{resolveQualification(){throw Error('must-not-run')}},()=>2000);expect(promote({...f,store:replay})).toEqual(result);expect(f.database.prepare('SELECT count(*) n FROM selection_policy_qualification').get()).toEqual({n:1});expect(()=>promote({...f,store:replay},{recordedAtMs:1101})).toThrow(/transition-conflict/)});

test('revalidates the deployment after a resolver side effect and leaves the losing request write-free',()=>{const f=setup();const alternate=policy(f.database,'alternate');const q2=qualification(f.baseline,alternate,{qualificationId:'qualification-2'});const winner=createPolicyPromotionStore(f.database,{resolveQualification(){return q2}},()=>2000);let fired=false;const loser=createPolicyPromotionStore(f.database,{resolveQualification(){if(!fired){fired=true;winner.promote({transitionId:'winner',channelId:'default',expectedGeneration:1,candidate:identity(alternate),qualificationId:'qualification-2',recordedAtMs:1001})}return f.q}},()=>2000);expect(()=>loser.promote({transitionId:'loser',channelId:'default',expectedGeneration:1,candidate:identity(f.candidate),qualificationId:'qualification-1',recordedAtMs:1002})).toThrow(/generation-conflict/);expect(f.database.prepare("SELECT group_concat(transition_id,',') ids FROM selection_policy_deployment_transition ORDER BY ordinal").get()).toEqual({ids:'initialize-1,winner'});expect(loser.readDeployment('default')?.policy.policyId).toBe('alternate')});

test('reverts only the exact latest promotion predecessor and preserves immutable run binding',()=>{const f=setup();bindRunSelectionPolicy(f.database,{runId:'existing-run',...identity(f.baseline),boundAt:'2026-09-15T00:00:01.000Z'});promote(f);expect(()=>f.store.revert({transitionId:'bad-revert',channelId:'default',expectedGeneration:2,promotionTransitionId:'initialize-1',recordedAtMs:1200})).toThrow(/revert-predecessor/);const reverted=f.store.revert({transitionId:'revert-1',channelId:'default',expectedGeneration:2,promotionTransitionId:'promote-1',recordedAtMs:1200});expect(reverted).toMatchObject({generation:3,policy:{policyId:'baseline'}});expect(readRunSelectionPolicy(f.database,'existing-run')?.snapshot.policyId).toBe('baseline');expect(f.store.revert({transitionId:'revert-1',channelId:'default',expectedGeneration:2,promotionTransitionId:'promote-1',recordedAtMs:1200})).toEqual(reverted);expect(()=>f.store.revert({transitionId:'again',channelId:'default',expectedGeneration:3,promotionTransitionId:'promote-1',recordedAtMs:1300})).toThrow(/revert-predecessor/)});

test('reopens with a verified chain and fails closed on schema, head, transition, and qualification tampering',()=>{const file=join(process.cwd(),`.policy-promotion-${process.pid}-${Date.now()}.db`);files.push(file);let database=db(file);const f=setup(database);promote(f);database.close();handles.splice(handles.indexOf(database),1);database=openLedger(file);handles.push(database);const reopened=createPolicyPromotionStore(database,{resolveQualification(){throw Error('unused')}},()=>2000);expect(reopened.readDeployment('default')).toMatchObject({generation:2,policy:{policyId:'candidate'}});expect(()=>database.prepare("UPDATE selection_policy_deployment_head SET generation=3 WHERE channel_id='default'").run()).toThrow(/policy_deployment_head/);database.exec('DROP TRIGGER selection_policy_qualification_no_update');database.prepare("UPDATE selection_policy_qualification SET body_json='{}'").run();expect(()=>reopened.readDeployment('default')).toThrow(/qualification/);const partial=openLedger();handles.push(partial);partial.exec('DROP TABLE policy_deployment_migration');expect(()=>createPolicyPromotionStore(partial,{resolveQualification(){return null}},()=>1)).toThrow(/schema/)});

test('rejects caller transactions so caught errors cannot commit partial deployment writes',()=>{const f=setup();let caught=false;f.database.transaction(()=>{try{promote(f)}catch{caught=true}})();expect(caught).toBe(true);expect(f.database.prepare('SELECT count(*) n FROM selection_policy_deployment_transition').get()).toEqual({n:1});expect(f.calls()).toBe(0)});
