import { afterEach, describe, expect, it } from 'vitest';
import { createHash } from 'node:crypto';
import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import Database from 'better-sqlite3';
import { openLedger, type Ledger } from '../src/ledger.js';
import { validateTaskPlan } from '../src/orchestration/plan.js';
import { createOrchestrationStore } from '../src/orchestration/store.js';
const dbs:Ledger[]=[],roots:string[]=[];afterEach(()=>{for(const db of dbs.splice(0))if(db.open)db.close();for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
const h=(v:string|Uint8Array)=>createHash('sha256').update(v).digest('hex');
function fixture(){
 const root=mkdtempSync(join(tmpdir(),'cue-wait-'));roots.push(root);const path=join(root,'ledger.db'),db=openLedger(path);dbs.push(db);const parent=h('parent'),stage=h('stage'),policy=h('policy'),subject=h('subject'),selection=h('selection');
 db.prepare("INSERT INTO task VALUES('root','running',NULL,'now')").run();db.prepare('INSERT INTO envelope VALUES(?,?,?,?)').run(parent,root,'[]','now');db.prepare("INSERT INTO run VALUES('run','root',?,0,'now')").run(parent);
 const plan=validateTaskPlan({policyRevision:'p1',policyDigest:policy,requirementIds:['req'],allowedCandidateIds:['candidate'],allowedScopeIds:['scope']},{revision:'plan',policyRevision:'p1',policyDigest:policy,tasks:[{id:'stage',role:'implementation',ownerId:'owner',requirementIds:['req'],dependencyIds:[],candidateIds:['candidate'],scopeIds:['scope']},{id:'verify',role:'verifier',ownerId:'checker',requirementIds:['req'],dependencyIds:['stage'],candidateIds:['candidate'],scopeIds:['scope']}]});
 let clock=1000;const flags={request:true,responder:true,claim:true,checkpoint:true,terminal:false,checkpointRemaining:null as number|null};const content=new Map<string,Buffer>([['response-ref',Buffer.from('response')],['c1',Buffer.from('one')],['c2',Buffer.from('two')],['c3',Buffer.from('three')],['c4',Buffer.from('final')]]);
 const authority={authorizePlan:()=>true,authorizeClaim:()=>flags.claim,verifyReceipt:(_c:any,r:any)=>flags.terminal?({outcomeVerified:true,cleanupVerified:true,handoff:{handoffId:'handoff',identityId:'identity',artifacts:[{kind:'checkpoint',sourceRef:'c4'}]}}):({outcomeVerified:false,cleanupVerified:false}),authorizeHandoffArtifact:(r:string)=>content.has(r),resolveHandoffArtifact:(r:string)=>content.get(r)??null,wait:{now:()=>clock,authorizeWaitRequest:()=>flags.request,authorizeResponder:()=>flags.responder,authorizeResponseContent:(r:string)=>content.has(r),resolveResponseContent:(r:string)=>content.get(r)??null,authorizeCheckpoint:()=>flags.checkpoint&&(flags.checkpointRemaining===null||flags.checkpointRemaining-->0),authorizeCheckpointContent:(r:string)=>content.has(r),resolveCheckpointContent:(r:string)=>content.get(r)??null}};
 const store=createOrchestrationStore(db,authority);store.install('run',plan);store.claim({runId:'run',taskId:'stage',attemptId:'attempt',candidateId:'candidate',observedAtMs:clock});
 db.prepare("INSERT INTO task VALUES('stage-task','running',NULL,'now')").run();db.prepare('INSERT INTO envelope VALUES(?,?,?,?)').run(stage,root,'[]','now');db.prepare("INSERT INTO run VALUES('attempt','stage-task',?,0,'now')").run(stage);db.prepare("INSERT INTO session_handle VALUES('session-attempt',1,'now',?,'stage-task','attempt')").run(root);
 db.prepare("INSERT INTO orchestration_stage_envelope VALUES('attempt','run','stage','stage-task','attempt',?,?,?,?,?,?,?,?)").run(parent,stage,plan.digest,policy,'{}',JSON.stringify({expires_at:new Date(5000).toISOString()}),'{}','{}');
 db.prepare("INSERT INTO attempt_selection VALUES('attempt','run','request','monetary',?,?)").run(selection,'{}');
 store.handoffActivity.recordLaunchIntent({runId:'run',taskId:'stage',attemptId:'attempt',candidateId:'candidate',selectionDigest:selection,expectedSubjectDigest:subject,tool:{id:'tool',revision:'unknown'},model:null,parentEnvelopeHash:parent,stageEnvelopeHash:stage,planDigest:plan.digest,policyDigest:policy});
 store.handoffActivity.recordAttemptIdentity({identityId:'identity',attemptId:'attempt',subjectDigest:subject,durableRef:'session:session-attempt',observedAtMs:clock});
 const request=(ordinal=1)=>({requestId:`request-${ordinal}`,runId:'run',taskId:'stage',attemptId:'attempt',identityId:'identity',requestOrdinal:ordinal,streamId:`stream-${ordinal}`,reason:'external-response' as const,responseSchema:'cue-wait-response-v1' as const,createdAtMs:clock,deadlineAtMs:4000,expectedResponder:{id:'responder',revision:'v1'}});
 return {root,path,db,store,queue:store.requestQueue!,content,flags,request,setClock:(n:number)=>clock=n};
}
describe('S3 durable wait and checkpoint queue',()=>{
 it('persists one authorized response and claims it against the existing attempt exactly once',()=>{const f=fixture(),q=f.queue;q.request(f.request());q.respond({eventId:'response-event',requestId:'request-1',responseId:'response-1',responseOrdinal:1,responder:{id:'responder',revision:'v1'},contentRef:'response-ref',observedAtMs:1000});const first=f.store.claimWaitResponse({requestId:'request-1',responseId:'response-1',claimedAtMs:1001});expect(first).toMatchObject({newlyClaimed:true,attemptId:'attempt'});expect(f.store.claimWaitResponse({requestId:'request-1',responseId:'response-1',claimedAtMs:1001})).toMatchObject({newlyClaimed:false,dispatchId:first.dispatchId});expect(f.db.prepare('SELECT COUNT(*)n FROM orchestration_attempt').get()).toEqual({n:1});expect(f.db.prepare('SELECT COUNT(*)n FROM orchestration_wait_dispatch_claim').get()).toEqual({n:1});});
 it('retains out of order checkpoints and seals only the contiguous final',()=>{const f=fixture(),q=f.queue;q.request(f.request());for(const n of [3,1,2,4])q.checkpoint({eventId:`e-${n}`,streamId:'stream-1',runId:'run',taskId:'stage',attemptId:'attempt',identityId:'identity',sourceOrdinal:n,kind:n===4?'final':'partial',contentRef:`c${n}`,observedAtMs:1000});expect(q.status('attempt')).toMatchObject({requests:1});expect(f.db.prepare("SELECT MAX(ordinal)n FROM orchestration_inbox_cursor WHERE scope='checkpoint'").get()).toEqual({n:4});const seal=f.db.prepare('SELECT content_sha256 FROM orchestration_checkpoint_final_seal').get() as any;expect(seal.content_sha256).toBe(h('final'));expect(()=>q.checkpoint({eventId:'late',streamId:'stream-1',runId:'run',taskId:'stage',attemptId:'attempt',identityId:'identity',sourceOrdinal:5,kind:'partial',contentRef:'c1',observedAtMs:1000})).toThrow('sealed');expect((f.db.prepare('SELECT COUNT(*)n FROM orchestration_checkpoint_final_seal').get() as any).n).toBe(1);});
 it('makes cancellation and expiry first-winner resolutions and rejects late response',()=>{const f=fixture(),q=f.queue;q.request(f.request());q.resolve('request-1','cancelled',1000);expect(()=>q.respond({eventId:'late',requestId:'request-1',responseId:'late',responseOrdinal:1,responder:{id:'responder',revision:'v1'},contentRef:'response-ref',observedAtMs:1000})).toThrow('inactive');expect(q.reconcileWait('attempt')).toMatchObject({cursor:1});expect(()=>q.resolve('request-1','expired',4000)).toThrow('conflict');});
 it('rejects non-enumerable required fields without writes and stops reconciliation after authority is revoked',()=>{const f=fixture(),q=f.queue,hostile={...f.request()} as any;Object.defineProperty(hostile,'requestId',{value:'hidden',enumerable:false});expect(()=>q.request(hostile)).toThrow('invalid_wait_input');expect(f.db.prepare('SELECT COUNT(*)n FROM orchestration_wait_request').get()).toEqual({n:0});q.request(f.request());q.resolve('request-1','cancelled',1000);f.flags.request=false;expect(q.reconcileWait('attempt')).toMatchObject({cursor:0,advanced:0});f.flags.request=true;q.checkpoint({eventId:'future',streamId:'stream-1',runId:'run',taskId:'stage',attemptId:'attempt',identityId:'identity',sourceOrdinal:2,kind:'partial',contentRef:'c2',observedAtMs:1000});f.flags.checkpointRemaining=1;q.checkpoint({eventId:'first',streamId:'stream-1',runId:'run',taskId:'stage',attemptId:'attempt',identityId:'identity',sourceOrdinal:1,kind:'partial',contentRef:'c1',observedAtMs:1000});expect(f.db.prepare("SELECT MAX(ordinal)n FROM orchestration_inbox_cursor WHERE scope='checkpoint'").get()).toEqual({n:null});});
 it('denies mutation or replace of every populated append-only row including migration marker',()=>{const f=fixture(),q=f.queue;q.request(f.request());q.respond({eventId:'response-event',requestId:'request-1',responseId:'response-1',responseOrdinal:1,responder:{id:'responder',revision:'v1'},contentRef:'response-ref',observedAtMs:1000});f.store.claimWaitResponse({requestId:'request-1',responseId:'response-1',claimedAtMs:1001});f.store.observeWaitDelivery({dispatchId:(f.db.prepare('SELECT dispatch_id FROM orchestration_wait_dispatch_claim').get() as any).dispatch_id,status:'unknown',observedAtMs:1002});for(const table of ['orchestration_wait_migration','orchestration_wait_request','orchestration_wait_inbox','orchestration_wait_resolution','orchestration_inbox_cursor','orchestration_wait_dispatch_claim','orchestration_wait_delivery_observation']){expect(()=>f.db.prepare(`UPDATE ${table} SET rowid=rowid`).run()).toThrow('immutable');expect(()=>f.db.prepare(`DELETE FROM ${table}`).run()).toThrow('immutable');expect(()=>f.db.prepare(`INSERT OR REPLACE INTO ${table} SELECT * FROM ${table}`).run()).toThrow('immutable');}});
 it('rolls back request, response, resolution and dispatch cut points without claiming an external rollback',()=>{const f=fixture(),q=f.queue;expect(()=>f.db.transaction(()=>{q.request(f.request());throw Error('cut-request');}).immediate()).toThrow('cut-request');expect(f.db.prepare('SELECT COUNT(*)n FROM orchestration_wait_request').get()).toEqual({n:0});q.request(f.request());const response={eventId:'response-event',requestId:'request-1',responseId:'response-1',responseOrdinal:1,responder:{id:'responder',revision:'v1'},contentRef:'response-ref',observedAtMs:1000};expect(()=>f.db.transaction(()=>{q.respond(response);throw Error('cut-response');}).immediate()).toThrow('cut-response');expect(f.db.prepare('SELECT COUNT(*)n FROM orchestration_wait_inbox').get()).toEqual({n:0});q.respond(response);expect(()=>f.db.transaction(()=>{f.store.claimWaitResponse({requestId:'request-1',responseId:'response-1',claimedAtMs:1001});throw Error('cut-dispatch');}).immediate()).toThrow('cut-dispatch');expect(f.db.prepare('SELECT COUNT(*)n FROM orchestration_wait_dispatch_claim').get()).toEqual({n:0});expect(f.db.prepare("SELECT COUNT(*)n FROM orchestration_inbox_cursor WHERE scope='wait'").get()).toEqual({n:0});expect(f.store.claimWaitResponse({requestId:'request-1',responseId:'response-1',claimedAtMs:1001})).toMatchObject({newlyClaimed:true});});
 it('requires the exact immutable final seal in terminal handoff and re-resolves changed bytes',()=>{const f=fixture(),q=f.queue;q.request(f.request());f.flags.terminal=true;const receipt={runId:'run',taskId:'stage',attemptId:'attempt',receiptId:'receipt',revision:1,outcome:'succeeded' as const,cleanup:'clean' as const,evidenceRef:'evidence',observedAtMs:1100};expect(()=>f.store.finish(receipt)).toThrow('terminal_checkpoint_seal_required');expect(f.db.prepare('SELECT COUNT(*)n FROM orchestration_receipt').get()).toEqual({n:0});q.checkpoint({eventId:'final',streamId:'stream-1',runId:'run',taskId:'stage',attemptId:'attempt',identityId:'identity',sourceOrdinal:1,kind:'final',contentRef:'c4',observedAtMs:1000});f.content.set('c4',Buffer.from('changed'));expect(()=>f.store.finish(receipt)).toThrow('terminal_checkpoint_seal_required');f.content.set('c4',Buffer.from('final'));expect(f.store.finish(receipt)).toMatchObject({state:'completed'});expect(()=>q.checkpoint({eventId:'late-final',streamId:'stream-1',runId:'run',taskId:'stage',attemptId:'attempt',identityId:'identity',sourceOrdinal:2,kind:'final',contentRef:'c4',observedAtMs:1000})).toThrow();});
 it('rejects responder, foreign lineage, claim authority and hostile acknowledgement without deltas',()=>{const f=fixture(),q=f.queue;q.request(f.request());const base={eventId:'response-event',requestId:'request-1',responseId:'response-1',responseOrdinal:1,responder:{id:'responder',revision:'v1'},contentRef:'response-ref',observedAtMs:1000};expect(()=>q.respond({...base,responder:{id:'foreign',revision:'v1'}})).toThrow();expect(()=>q.respond({...base,responseOrdinal:2})).toThrow();expect(f.db.prepare('SELECT COUNT(*)n FROM orchestration_wait_inbox').get()).toEqual({n:0});q.respond(base);f.flags.claim=false;expect(()=>f.store.claimWaitResponse({requestId:'request-1',responseId:'response-1',claimedAtMs:1001})).toThrow('denied');expect(f.db.prepare('SELECT COUNT(*)n FROM orchestration_wait_dispatch_claim').get()).toEqual({n:0});f.flags.claim=true;const claim=f.store.claimWaitResponse({requestId:'request-1',responseId:'response-1',claimedAtMs:1001});const hostile:any={dispatchId:claim.dispatchId,attemptId:'attempt',identityId:'identity',durableRef:'session:session-attempt',contentSha256:claim.contentSha256};Object.defineProperty(hostile,'contentSha256',{enumerable:true,get(){throw Error('getter-ran')}});expect(()=>f.store.observeWaitDelivery({dispatchId:claim.dispatchId,status:'delivered',observedAtMs:1002,acknowledgement:hostile})).toThrow('invalid_store');expect(f.db.prepare('SELECT COUNT(*)n FROM orchestration_wait_delivery_observation').get()).toEqual({n:0});});
 it('upgrades a copied pre-035 database once, fences old attempts, and fails raw payload writes without cue_sha256',()=>{const f=fixture();f.db.close();dbs.splice(dbs.indexOf(f.db),1);const raw=new Database(f.path);const triggers=raw.prepare("SELECT name FROM sqlite_master WHERE type='trigger' AND name LIKE 'wait_%' OR type='trigger' AND name LIKE 'checkpoint_%'").all() as {name:string}[];for(const t of triggers)raw.exec(`DROP TRIGGER ${t.name}`);for(const table of ['orchestration_wait_delivery_observation','orchestration_wait_dispatch_claim','orchestration_checkpoint_final_seal','orchestration_inbox_cursor','orchestration_wait_resolution','orchestration_wait_inbox','orchestration_wait_request','orchestration_wait_legacy','orchestration_wait_migration'])raw.exec(`DROP TABLE ${table}`);raw.close();const upgraded=openLedger(f.path);dbs.push(upgraded);expect(upgraded.prepare("SELECT reason FROM orchestration_wait_legacy WHERE attempt_id='attempt'").get()).toEqual({reason:'legacy-wait-unavailable'});upgraded.close();dbs.splice(dbs.indexOf(upgraded),1);const reopened=openLedger(f.path);dbs.push(reopened);expect(reopened.prepare('SELECT COUNT(*)n FROM orchestration_wait_legacy').get()).toEqual({n:1});const untrusted=new Database(f.path);expect(()=>untrusted.prepare("INSERT INTO orchestration_wait_request VALUES('raw','run','stage','attempt','identity',1,'raw-stream','external-response','cue-wait-response-v1',1,2,'r','v',?,?)").run('0'.repeat(64),Buffer.from('{}'))).toThrow(/cue_sha256|function/);untrusted.close();});
});
