import { afterEach,describe,expect,it } from 'vitest';
import Database from 'better-sqlite3';
import { createHash } from 'node:crypto';
import { mkdtempSync,rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { openLedger,type Ledger } from '../src/ledger.js';
import { createBudgetManager } from '../src/budget.js';
import { bindRunSelectionPolicy,saveSelectionPolicy } from '../src/selection/policy-store.js';
import { bindInitialDefault,readInitialDefault,readInitialDefaultAttempt,recordInitialDefaultAttempt,type InitialDefaultConfig } from '../src/selection/initial-default.js';
import { createInitialSelectionLedgerFixture,initialSelectionRequest } from './fixtures/initial-selection-ledger.js';

const dbs:Ledger[]=[],roots:string[]=[];afterEach(()=>{for(const db of dbs.splice(0))if(db.open)db.close();for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
function setup(path?:string){const db=openLedger(path);dbs.push(db);const envelope='e'.repeat(64);db.prepare("INSERT INTO task VALUES('task-run','awaiting_approval',NULL,'now')").run();db.prepare("INSERT INTO envelope VALUES(?,'C:/fixture','[]','now')").run(envelope);db.prepare("INSERT INTO run VALUES('run','task-run',?,0,'now')").run(envelope);const policy=saveSelectionPolicy(db,{policyId:'policy',expectedRevision:null,createdAt:'2026-09-14T00:00:00.000Z',sourceVersion:'fixture',policy:{version:'cue-selection-v1',mode:'efficiency',qualityMinimum:.8,costBasis:1,timeBasisMs:1000,currency:'TEST',costLimit:100,remainingTimeMs:5000,maxEstimateAgeMs:100,allowedCandidateIds:['agent'],pinnedCandidateId:null}});bindRunSelectionPolicy(db,{runId:'run',policyId:'policy',revision:1,digest:policy.digest,boundAt:'2026-09-14T00:00:00.000Z'});createBudgetManager(db,{verifyFinalReceipt:()=>false}).initialize({runId:'run',currency:'TEST',unit:'micro',limitUnits:100,policyRevision:'policy:1',source:'fixture',observedAtMs:1000});const input:InitialDefaultConfig={version:'cue-initial-default-v1',runId:'run',policyId:'policy',policyRevision:1,policyDigest:policy.digest,defaultCandidateId:'agent',conservativeEstimate:{scope:'verified-completion-total',quality:.9,expectedCost:20,conservativeMaxCost:30,expectedTimeMs:1000,conservativeMaxTimeMs:2000,currency:'TEST',source:'trusted-baseline',observedAtMs:950},source:'trusted-host-config',boundAtMs:1000};return{db,input,policy,envelope};}

describe('S2 immutable initial default store',()=>{
  it('binds once and returns a frozen canonical snapshot after reopen',()=>{const root=mkdtempSync(join(tmpdir(),'cue-default-'));roots.push(root);const path=join(root,'ledger.db'),f=setup(path),stored=bindInitialDefault(f.db,f.input);expect(bindInitialDefault(f.db,{...f.input,source:'trusted-host-config'})).toEqual(stored);expect(Object.isFrozen(stored)&&Object.isFrozen(stored.conservativeEstimate)).toBe(true);f.db.close();const reopened=openLedger(path);dbs.push(reopened);expect(readInitialDefault(reopened,'run')).toEqual(stored);});
  it('rejects conflicting, foreign, stale, incomplete and policy-unsafe defaults',()=>{const f=setup();bindInitialDefault(f.db,f.input);expect(()=>bindInitialDefault(f.db,{...f.input,source:'other'})).toThrow(/conflict/);for(const input of [{...f.input,defaultCandidateId:'other'},{...f.input,policyDigest:'a'.repeat(64)},{...f.input,conservativeEstimate:{...f.input.conservativeEstimate,currency:'USD'}},{...f.input,conservativeEstimate:{...f.input.conservativeEstimate,quality:.7}},{...f.input,conservativeEstimate:{...f.input.conservativeEstimate,conservativeMaxCost:null}},{...f.input,conservativeEstimate:{...f.input.conservativeEstimate,conservativeMaxTimeMs:null}},{...f.input,conservativeEstimate:{...f.input.conservativeEstimate,observedAtMs:899}}])expect(()=>bindInitialDefault(setup().db,input as InitialDefaultConfig)).toThrow();});
  it('rejects proxies, accessors and extra fields without invoking traps',()=>{const f=setup();let calls=0;expect(()=>bindInitialDefault(f.db,new Proxy(f.input,{get(){calls++;throw Error('trap')}}))).toThrow(/input/);expect(calls).toBe(0);const estimate={...f.input.conservativeEstimate};Object.defineProperty(estimate,'quality',{enumerable:true,get(){calls++;return .9}});expect(()=>bindInitialDefault(f.db,{...f.input,conservativeEstimate:estimate} as InitialDefaultConfig)).toThrow(/accessor/);expect(calls).toBe(0);expect(()=>bindInitialDefault(f.db,{...f.input,unsafe:true} as unknown as InitialDefaultConfig)).toThrow(/fields/);});
  it('blocks late API and raw valid-hash authority after approval or first attempt',async()=>{const approved=setup();approved.db.prepare("INSERT INTO approval_event(run_id,envelope_hash,thread_id,item_id,approval_id,request_ordinal,decision,created_at) VALUES('run',?,'t','i',NULL,0,'accept','now')").run(approved.envelope);expect(()=>bindInitialDefault(approved.db,approved.input)).toThrow(/too late/);const encoded=Buffer.from(JSON.stringify(approved.input)),digest=createHash('sha256').update(encoded).digest('hex');expect(()=>approved.db.prepare('INSERT INTO initial_default VALUES(?,?,?,?,?,?,?)').run('run','policy',1,approved.policy.digest,'agent',digest,encoded)).toThrow(/too late/);
    const attempted=createInitialSelectionLedgerFixture();dbs.push(attempted.db);await attempted.engine.start(attempted.plan,initialSelectionRequest);const bound=attempted.db.prepare('SELECT digest FROM selection_run_policy WHERE run_id=?').get('run') as {digest:string};const input={...approved.input,policyDigest:bound.digest};expect(()=>bindInitialDefault(attempted.db,input)).toThrow(/too late/);});
  it('rejects a policy-unsafe raw preapproval payload even with its valid hash',()=>{const f=setup(),unsafe={...f.input,conservativeEstimate:{...f.input.conservativeEstimate,conservativeMaxCost:101}},encoded=Buffer.from(JSON.stringify(unsafe)),digest=createHash('sha256').update(encoded).digest('hex');expect(()=>f.db.prepare('INSERT INTO initial_default VALUES(?,?,?,?,?,?,?)').run('run','policy',1,f.policy.digest,'agent',digest,encoded)).toThrow(/lineage mismatch/);expect(readInitialDefault(f.db,'run')).toBeNull();});
  it('makes update/delete/replace/upsert immutable and detects row corruption',()=>{const f=setup(),saved=bindInitialDefault(f.db,f.input);expect(()=>f.db.exec("UPDATE initial_default SET default_candidate_id='other'")).toThrow(/immutable/);expect(()=>f.db.exec('DELETE FROM initial_default')).toThrow(/immutable/);expect(()=>f.db.exec('INSERT OR REPLACE INTO initial_default SELECT * FROM initial_default')).toThrow(/immutable/);expect(()=>f.db.exec('INSERT INTO initial_default SELECT * FROM initial_default ON CONFLICT(run_id) DO UPDATE SET default_candidate_id=excluded.default_candidate_id')).toThrow();f.db.exec('DROP TRIGGER initial_default_update');f.db.prepare("UPDATE initial_default SET digest=?").run('b'.repeat(64));expect(()=>readInitialDefault(f.db,'run')).toThrow(/integrity/);expect(saved.digest).not.toBe('b'.repeat(64));});
  it('treats a pre-040 ledger as absent and a partial migration as corrupt',()=>{const legacy=new Database(':memory:') as unknown as Ledger;dbs.push(legacy);expect(readInitialDefault(legacy,'run')).toBeNull();const f=setup();f.db.exec('DROP TABLE initial_default_attempt');expect(()=>readInitialDefault(f.db,'run')).toThrow(/migration_incomplete/);});
  it('provides immutable attempt provenance for later same-transaction engine wiring',async()=>{const f=createInitialSelectionLedgerFixture();dbs.push(f.db);const policy=f.db.prepare('SELECT policy_id,revision,digest FROM selection_run_policy WHERE run_id=?').get('run') as any;const config=bindInitialDefault(f.db,{version:'cue-initial-default-v1',runId:'run',policyId:policy.policy_id,policyRevision:policy.revision,policyDigest:policy.digest,defaultCandidateId:'agent',conservativeEstimate:{scope:'verified-completion-total',quality:1,expectedCost:1,conservativeMaxCost:1,expectedTimeMs:1,conservativeMaxTimeMs:1,currency:'TEST',source:'fixture',observedAtMs:1000},source:'fixture',boundAtMs:1000});await f.engine.start(f.plan,initialSelectionRequest);const saved=f.db.transaction(()=>recordInitialDefaultAttempt(f.db,{version:'cue-initial-default-v1',attemptId:'attempt-1',runId:'run',requestId:'request-1',disposition:'legacy-observation-absent',candidateId:'agent',defaultDigest:config.digest,observation:null})).immediate();expect(readInitialDefaultAttempt(f.db,'attempt-1')).toEqual(saved);expect(Object.isFrozen(saved)).toBe(true);expect(()=>f.db.exec('DELETE FROM initial_default_attempt')).toThrow(/immutable/);});
});
