import { afterEach, expect, test } from 'vitest';
import { createHash } from 'node:crypto';
import { mkdtempSync, mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, win32 } from 'node:path';
import { createGeneratedJsonHost } from '../../app/generated-json-host.mjs';
import { openLedger, type Ledger } from '../src/ledger.js';
import { normalizeEnvelope, envelopeHash } from '../src/envelope.js';
import { MODEL_PROBES } from '../src/capability-admission.js';
import { SUBJECT_FIELDS, subjectDigest, type MeasurementSubject } from '../src/measurement-subject.js';
import { bindRunSelectionPolicy, saveSelectionPolicy, type StoredSelectionPolicy } from '../src/selection/policy-store.js';
import { createPolicyPromotionStore, qualifiedPolicyComparisonDigest, type QualifiedPolicyComparison } from '../src/selection/policy-promotion.js';
import type { ModelControlBundle } from '../src/model-control-bundle.js';

const roots:string[]=[],dbs:Ledger[]=[];afterEach(()=>{for(const db of dbs.splice(0))if(db.open)db.close();for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true})});
const h=(c:string)=>c.repeat(64),identity=(p:StoredSelectionPolicy)=>({policyId:p.policyId,revision:p.revision,digest:p.digest});
function bundle(clientKind:'model'|'json-checker'):ModelControlBundle{const v={version:'cue-model-control-v1' as const,clientKind,nodeSha256:h('1'),launcherSha256:h('2'),guardianSha256:h('3'),clientSha256:h('4'),checkerCoreSha256:clientKind==='model'?null:h('5')};return{...v,sha256:createHash('sha256').update(JSON.stringify(Object.values(v))).digest('hex')}}
function saved(db:Ledger,id:string,mode:'efficiency'|'performance'|'value'|'speed'){return saveSelectionPolicy(db,{policyId:id,expectedRevision:null,createdAt:new Date(1000).toISOString(),sourceVersion:'synthetic-fixture',policy:{version:'cue-selection-v1',mode,qualityMinimum:.5,costBasis:1,timeBasisMs:1,currency:'TEST',costLimit:null,remainingTimeMs:null,maxEstimateAgeMs:10000,allowedCandidateIds:['fixture-model','fixture-checker'],pinnedCandidateId:null}})}
function qualified(baseline:StoredSelectionPolicy,candidate:StoredSelectionPolicy):QualifiedPolicyComparison{const body={version:'cue-qualified-policy-comparison-v1',authority:'host-authenticated-empirical-comparison',qualificationId:'synthetic-qualification',authorityId:'synthetic-test-authority',baseline:identity(baseline),candidate:identity(candidate),dataset:{id:'dataset',revision:'r1',digest:h('6'),caseCommitments:[h('7')]},holdout:{id:'holdout',revision:'r1',digest:h('8'),caseCommitments:[h('9')]},metric:{id:'metric',revision:'r1',digest:h('a')},environment:{id:'environment',revision:'r1',digest:h('b')},accountLimits:{id:'limits',revision:'r1',digest:h('c')},measures:{baselineFactDigests:[h('d')],candidateFactDigests:[h('e')],qualityDelta:.1,elapsedDeltaMs:-1,costDeltaUnits:-1},priceTimeEvidenceDigest:h('f'),trialEvidenceDigest:h('0'),comparisonEvidenceDigest:h('1'),verdict:'qualified-improvement',qualifiedAtMs:1100} as Omit<QualifiedPolicyComparison,'digest'>;return{...body,digest:qualifiedPolicyComparisonDigest(body)}}
test('an explicit deployment channel affects only future runs while exact policy references stay pinned',()=>{
  const root=mkdtempSync(join(tmpdir(),'cue-policy-host-'));roots.push(root);const work=join(root,'work');mkdirSync(work);const db=openLedger();dbs.push(db);const baseline=saved(db,'efficiency-baseline','efficiency'),candidate=saved(db,'efficiency-candidate','efficiency');
  const policies:any={efficiency:{deploymentChannelId:'generated-efficiency'}};for(const mode of ['performance','value','speed'] as const){const p=saved(db,mode,mode);policies[mode]=identity(p)}
  const q=qualified(baseline,candidate),deployment=createPolicyPromotionStore(db,{resolveQualification(id){return id===q.qualificationId?q:null}},()=>2000);deployment.initialize({transitionId:'initialize',channelId:'generated-efficiency',mode:'efficiency',policy:identity(baseline),recordedAtMs:1000});
  const subject=Object.fromEntries(SUBJECT_FIELDS.map(key=>[key,key.endsWith('Sha256')?h('a'):key])) as MeasurementSubject,refs:Record<string,{id:string;sha256:string}>={},evidence=new Map<string,Buffer>();for(const probe of MODEL_PROBES){const bytes=Buffer.from(JSON.stringify({probe,subjectDigest:subjectDigest(subject),measuredAt:new Date(1500).toISOString(),kind:'live',status:'pass'}));evidence.set(probe,bytes);refs[probe]={id:probe,sha256:createHash('sha256').update(bytes).digest('hex')}}
  const candidates:any=Object.fromEntries(['model','checker'].map(kind=>[kind,{record:{canonicalId:`fixture-${kind}`,toolId:`fixture-${kind}`,kind,aliases:[],installation:'installed',protocol:'verified',authReference:'synthetic-account',authAvailable:true,sourceVersion:'synthetic-only',observedAt:new Date(1500).toISOString(),subjectDigest:subjectDigest(subject),binding:kind==='model'?{endpointId:'fixed-localhost',modelId:'qwen38-27b-unc'}:null},currentSubject:()=>subject,evidenceReferences:()=>refs,observeCandidate:()=>({id:`fixture-${kind}`,checks:{eligible:true,authenticated:true,compatible:true,dataAllowed:true,resourceAvailable:true,quotaAvailable:true},estimate:{scope:'verified-completion-total',quality:1,expectedCost:1,conservativeMaxCost:1,expectedTimeMs:1,conservativeMaxTimeMs:2,currency:'TEST',source:'synthetic-fixture',observedAtMs:1500}})}]));
  const options:any={db,now:()=>2000,inputForRun:(run:any)=>run.goal,installation:{nodeExecutable:process.execPath,nodeSha256:h('1'),modelControlBundle:bundle('model'),checkerControlBundle:bundle('json-checker'),taskRootBase:win32.join(root,'tasks'),profileRootBase:win32.join(root,'profiles')},candidates,evidence:{now:()=>2000,maxAgeMs:10000,resolveEvidence:(ref:any)=>evidence.get(ref.id)},policies,accounting:{currency:'TEST',unit:'micro',limitUnits:100,unitsPerCost:10,source:'synthetic-fixture',observedAtMs:1500,upperUnitsByKind:{model:10,checker:10}}};const ready=createGeneratedJsonHost(options);expect(ready.available).toBe(true);if(!ready.available)return;
  const run=(runId:string)=>{const envelope=normalizeEnvelope({run_id:runId,worktree_realpath:work,allowed_actions:['command'],egress:['http://127.0.0.1:8085/v1'],expires_at:new Date(100000).toISOString(),autonomy_level:'bounded'});return{runId,taskId:'root',envelope,envelopeHash:envelopeHash(envelope),goal:'{"value":1}',scope:'document',selectionMode:'efficiency' as const}};
  const first=run('first');db.prepare("INSERT INTO task VALUES('first-task','awaiting_approval',NULL,'now')").run();db.prepare("INSERT INTO envelope VALUES(?,?,?,'now')").run(first.envelopeHash,work,JSON.stringify(first.envelope.egress));db.prepare("INSERT INTO run VALUES('first','first-task',?,0,'now')").run(first.envelopeHash);const firstConfig=ready.host.prepare(first);expect(firstConfig.policy).toEqual(identity(baseline));bindRunSelectionPolicy(db,{runId:'first',...identity(baseline),boundAt:new Date(1600).toISOString()});deployment.promote({transitionId:'promote',channelId:'generated-efficiency',expectedGeneration:1,candidate:identity(candidate),qualificationId:q.qualificationId,recordedAtMs:1200});expect(ready.host.prepare(first).policy).toEqual(identity(baseline));const restarted=createGeneratedJsonHost(options);expect(restarted.available).toBe(true);if(restarted.available)expect(restarted.host.prepare(first).policy).toEqual(identity(baseline));expect(ready.host.prepare(run('second')).policy).toEqual(identity(candidate));
  const pinned={...policies,efficiency:identity(baseline)},pinnedReady=createGeneratedJsonHost({...options,installation:{...options.installation,taskRootBase:win32.join(root,'tasks2'),profileRootBase:win32.join(root,'profiles2')},policies:pinned});expect(pinnedReady.available).toBe(true);if(pinnedReady.available)expect(pinnedReady.host.prepare(run('pinned')).policy).toEqual(identity(baseline));
});
