import {EventEmitter} from 'node:events';
import {PassThrough,Writable} from 'node:stream';
import {beforeEach,describe,expect,test,vi} from 'vitest';
import {SUBJECT_FIELDS,type MeasurementSubject} from '../src/measurement-subject.js';

const fixture=vi.hoisted(()=>({requests:[] as any[],alive:true,descriptor:null as any,child:null as any,account:{type:'chatgpt',email:'Person@Example.COM',planType:'plus'} as any,dropMethod:'',terminationFails:false,cleanupCalls:0,beforeResponse:[] as any[],afterResponse:[] as any[],closeFrames:[] as any[],jsonrpc:false,oversizeMethod:'',stderrFloodMethod:'',duplicateMethod:'',oversizeAfterMethod:'',stderrAfterMethod:'',accountSequence:[] as any[],capacity:{rateLimits:{primary:null}} as any,usage:{summary:{lifetimeTokens:null},dailyUsageBuckets:null,threadUsage:null} as any,measuredSubject:null as any,measuredDigest:'',installationDigest:'e'.repeat(64),installationCurrent:true,issuerDrift:false}));
vi.mock('node:fs',async importOriginal=>{const actual=await importOriginal<typeof import('node:fs')>();return{...actual,readFileSync:(path:any,...args:any[])=>{const value=(actual.readFileSync as any)(path,...args);return fixture.issuerDrift&&String(path).includes('native-account-observation')?Buffer.concat([Buffer.from(value),Buffer.from('drift')]):value;}};});
vi.mock('../../app/provider-installation.mjs',()=>({assertCurrentProviderInstallation:(value:unknown)=>{if(value!==fixture.descriptor||!fixture.installationCurrent)throw Error('provider_installation_unavailable_or_drifted');return true;}}));
vi.mock('../src/tool-home.js',()=>({createCleanCodexHome:()=>String.raw`C:\fixture\codex-home-owned`,safeCleanupCodexHome:()=>{fixture.cleanupCalls++;},vendorCodexLaunchSpec:(binary:string,args:string[])=>({command:binary,args,env:{CODEX_HOME:String.raw`C:\fixture\codex-home-owned`}})}));
vi.mock('../src/native-provider-measurement-subject.js',()=>({measureNativeProviderSubject:()=>{if(!fixture.installationCurrent)throw Error('provider_installation_unavailable_or_drifted');return{subject:fixture.measuredSubject,subjectDigest:fixture.measuredDigest,manifest:{installationDigest:fixture.installationDigest},limitations:[]};}}));
vi.mock('../src/host-runtime-native-identity.js',()=>({observeOwnedNativeProcess:()=>({pid:4242,createdFileTime:'123456789'})}));
vi.mock('../src/process-termination.js',()=>({observeProcessTree:()=>({descendants:fixture.alive?[{pid:4242,createdAt:'2026-09-16T00:00:00.000Z'}]:[]}),terminateVerifiedTree:()=>{if(fixture.terminationFails)throw Error('process_tree_termination_unverified');fixture.alive=false;fixture.child.exitCode=1;queueMicrotask(()=>fixture.child.emit('close',1,null));}}));
vi.mock('../src/process-launch.js',()=>({spawnOwned:(_db:unknown,_owner:unknown,command:string,args:string[],options:any)=>{expect(command).toBe(String.raw`C:\vendor\codex.exe`);expect(args).toEqual(['-a','on-request','app-server']);expect(options.env.CODEX_HOME).toBe(String.raw`C:\fixture\codex-home-owned`);const stdout=new PassThrough(),stderr=new PassThrough(),child=Object.assign(new EventEmitter(),{pid:4242,exitCode:null,signalCode:null,stdout,stderr,stdin:null as any});child.stdin=new Writable({write(chunk,_encoding,done){const message=JSON.parse(String(chunk));fixture.requests.push(message);if(message.id&&message.method!==fixture.dropMethod){let result:any={};if(message.method==='account/read')result={account:fixture.accountSequence.length?fixture.accountSequence.shift():fixture.account,requiresOpenaiAuth:true};if(message.method==='account/usage/read')result=fixture.usage;if(message.method==='account/rateLimits/read')result=fixture.capacity;queueMicrotask(()=>{if(message.method===fixture.oversizeMethod){stdout.write('x'.repeat(64*1024+1));return;}if(message.method===fixture.stderrFloodMethod)stderr.write(Buffer.alloc(1024*1024+1));for(const frame of fixture.beforeResponse)stdout.write(`${JSON.stringify(frame)}\n`);fixture.beforeResponse=[];const response={...(fixture.jsonrpc?{jsonrpc:'2.0'}:{}),id:message.id,result};stdout.write(`${JSON.stringify(response)}\n`);if(message.method===fixture.duplicateMethod)stdout.write(`${JSON.stringify(response)}\n`);for(const frame of fixture.afterResponse)stdout.write(`${JSON.stringify(frame)}\n`);fixture.afterResponse=[];if(message.method===fixture.oversizeAfterMethod)stdout.write('x'.repeat(64*1024+1));if(message.method===fixture.stderrAfterMethod)stderr.write(Buffer.alloc(1024*1024+1));});}done();},final(done){for(const frame of fixture.closeFrames)stdout.write(`${JSON.stringify(frame)}\n`);fixture.closeFrames=[];done();}});fixture.child=child;return{child,session:{handle:'fixture-session',pid:4242,start_time:'now',cwd:'C:/fixture',task_id:'task',run_id:'run'}};}}));

import {observeNativeProviderAccount,readIssuedNativeAccountObservation,observeNativeServiceAuthentication,readIssuedNativeServiceAuthentication,observeNativeServiceCapacity,readIssuedNativeServiceCapacity} from '../src/native-account-observation.js';

const subject=Object.freeze(Object.fromEntries(SUBJECT_FIELDS.map(key=>[key,key.endsWith('Sha256')?'a'.repeat(64):`fixture-${key}`])) as MeasurementSubject);
function descriptor(){return Object.freeze({provider:'codex',executablePath:String.raw`C:\vendor\codex.exe`,executable:Object.freeze({sha256:'b'.repeat(64),size:1,dev:'1',ino:'2',mtimeMs:1,ctimeMs:1,signerSubject:'OpenAI',signerThumbprint:'C'.repeat(40)}),version:Object.freeze({kind:'package',value:'1.0.0',packageName:'@openai/codex',manifestPath:String.raw`C:\vendor\package.json`,manifestSha256:'d'.repeat(64)}),authProfiles:Object.freeze([Object.freeze({path:String.raw`C:\fixture\auth.json`,size:4,dev:'1',ino:'3',mtimeMs:1,ctimeMs:1})]),status:'unqualified',authenticated:false,entitled:false,qualified:false} as const);}
const input=(overrides:Record<string,unknown>={})=>({db:{} as any,owner:{cwd:String.raw`C:\fixture`,task_id:'task',run_id:'run'},installation:fixture.descriptor,currentSubject:subject,authProfilePath:String.raw`C:\fixture\auth.json`,temporaryParent:String.raw`C:\fixture\temp`,nowMs:1000,maxAgeMs:100,...overrides});

beforeEach(async()=>{fixture.requests=[];fixture.alive=true;fixture.child=null;fixture.descriptor=descriptor();fixture.account={type:'chatgpt',email:'Person@Example.COM',planType:'plus'};fixture.dropMethod='';fixture.terminationFails=false;fixture.cleanupCalls=0;fixture.beforeResponse=[];fixture.afterResponse=[];fixture.closeFrames=[];fixture.jsonrpc=false;fixture.oversizeMethod='';fixture.stderrFloodMethod='';fixture.duplicateMethod='';fixture.oversizeAfterMethod='';fixture.stderrAfterMethod='';fixture.accountSequence=[];fixture.capacity={rateLimits:{primary:null}};fixture.usage={summary:{lifetimeTokens:null},dailyUsageBuckets:null,threadUsage:null};fixture.measuredSubject=subject;fixture.measuredDigest=(await import('../src/measurement-subject.js')).subjectDigest(subject);fixture.installationDigest='e'.repeat(64);fixture.installationCurrent=true;fixture.issuerDrift=false;});

describe('native account observation',()=>{
 test('owns the fixed app-server probe and issues sanitized account-presence evidence',async()=>{const observed=await observeNativeProviderAccount(input());expect(fixture.requests.map(value=>value.method)).toEqual(['initialize','initialized','account/read']);expect(fixture.requests[2].params).toEqual({refreshToken:false});expect(observed).toMatchObject({provider:'codex',accountPresence:'present',authentication:'unknown',entitlement:'unknown',capability:'unknown',protocol:{requiresOpenaiAuth:true,rateLimitsMethod:'not-requested'},process:{pid:4242,cleanup:'verified-absent'}});expect(observed.accountRef).toMatch(/^account:[a-f0-9]{64}$/u);const issued=readIssuedNativeAccountObservation(observed,{installation:fixture.descriptor,currentSubject:subject,nowMs:1050,maxAgeMs:100}),source=Buffer.from(issued.sourceBytes()).toString('utf8');expect(source).not.toContain('Person@Example.COM');expect(source).not.toContain('person@example.com');expect(source).toContain(observed.accountIdentityDigest!);expect(Object.isFrozen(observed)).toBe(true);});
 test('observes rate limits only under explicit policy without deriving entitlement',async()=>{const observed=await observeNativeProviderAccount(input({observeRateLimits:true}));expect(fixture.requests.map(value=>value.method)).toEqual(['initialize','initialized','account/read','account/rateLimits/read']);expect(observed.protocol).toMatchObject({rateLimitsMethod:'account/rateLimits/read',rateLimitsObservation:'observed'});expect(observed.entitlement).toBe('unknown');expect(observed.capability).toBe('unknown');});
 test('rejects shaped, foreign-installation, subject-drift, and stale receipts',async()=>{const observed=await observeNativeProviderAccount(input());const read={installation:fixture.descriptor,currentSubject:subject,nowMs:1050,maxAgeMs:100};expect(()=>readIssuedNativeAccountObservation({...observed},read)).toThrow('native_account_observation_unissued');const foreign=descriptor();expect(()=>readIssuedNativeAccountObservation(observed,{...read,installation:foreign})).toThrow('native_account_observation_unissued');const drift=Object.freeze({...subject,osBuild:'changed'});expect(()=>readIssuedNativeAccountObservation(observed,{...read,currentSubject:drift})).toThrow('native_account_observation_stale');expect(()=>readIssuedNativeAccountObservation(observed,{...read,nowMs:1101})).toThrow('native_account_observation_stale');});
 test('does not invent a shared identity for distinct API-key credential profiles',async()=>{fixture.account={type:'apiKey'};const first=await observeNativeProviderAccount(input());fixture.alive=true;fixture.descriptor=descriptor();const second=await observeNativeProviderAccount(input({installation:fixture.descriptor}));for(const observed of [first,second])expect(observed).toMatchObject({accountPresence:'present',accountRef:null,accountIdentityDigest:null,authentication:'unknown'});});
 test('verifies timeout cleanup and retains the owned home when termination is unverified',async()=>{fixture.dropMethod='account/read';await expect(observeNativeProviderAccount(input({requestTimeoutMs:5}))).rejects.toThrow('native_account_observation_timeout');expect(fixture.cleanupCalls).toBe(1);expect(fixture.alive).toBe(false);fixture.alive=true;fixture.cleanupCalls=0;fixture.terminationFails=true;await expect(observeNativeProviderAccount(input({requestTimeoutMs:5}))).rejects.toThrow('process_tree_termination_unverified');expect(fixture.cleanupCalls).toBe(0);expect(fixture.alive).toBe(true);});
 test('accepts optional JSON-RPC and safe interleaved notifications but invalidates on account updates',async()=>{fixture.jsonrpc=true;fixture.beforeResponse=[{jsonrpc:'2.0',method:'thread/started',params:{thread:{id:'irrelevant'}}}];await expect(observeNativeProviderAccount(input())).resolves.toMatchObject({accountPresence:'present'});fixture.alive=true;fixture.beforeResponse=[{method:'account/updated',params:{}}];await expect(observeNativeProviderAccount(input())).rejects.toThrow('native_account_observation_changed');});
 test('caps unterminated stdout, drains bounded stderr, and rejects duplicate responses',async()=>{fixture.oversizeMethod='account/read';await expect(observeNativeProviderAccount(input())).rejects.toThrow('native_account_observation_frame');fixture.alive=true;fixture.oversizeMethod='';fixture.stderrFloodMethod='account/read';await expect(observeNativeProviderAccount(input())).rejects.toThrow('native_account_observation_stderr');fixture.alive=true;fixture.stderrFloodMethod='';fixture.duplicateMethod='initialize';await expect(observeNativeProviderAccount(input())).rejects.toThrow('native_account_observation_frame');});
 test('keeps identity stable across plan changes and treats null email as identity unavailable',async()=>{fixture.account={type:'chatgpt',email:'same@example.com',planType:'plus'};const first=await observeNativeProviderAccount(input());fixture.alive=true;fixture.account={type:'chatgpt',email:'same@example.com',planType:'pro'};const second=await observeNativeProviderAccount(input());expect(second.accountRef).toBe(first.accountRef);fixture.alive=true;fixture.account={type:'chatgpt',email:null,planType:'plus'};await expect(observeNativeProviderAccount(input())).resolves.toMatchObject({accountPresence:'present',accountRef:null,accountIdentityDigest:null});});
 test('rejects invalidation and duplicate responses after the final account result, including before process close',async()=>{fixture.afterResponse=[{method:'account/updated',params:{}}];await expect(observeNativeProviderAccount(input())).rejects.toThrow('native_account_observation_changed');fixture.alive=true;fixture.afterResponse=[];fixture.duplicateMethod='account/read';await expect(observeNativeProviderAccount(input())).rejects.toThrow('native_account_observation_frame');fixture.alive=true;fixture.duplicateMethod='';fixture.closeFrames=[{method:'account/updated',params:{}}];await expect(observeNativeProviderAccount(input())).rejects.toThrow('native_account_observation_changed');});
 test('issues repeatably readable service acceptance only for stable ChatGPT identity around validated usage',async()=>{const observed=await observeNativeServiceAuthentication(input());expect(fixture.requests.map(value=>value.method)).toEqual(['initialize','initialized','account/read','account/usage/read','account/read']);expect(observed).toMatchObject({serviceAccepted:true,scope:'account-usage-read',authentication:'service-accepted',modelEntitlement:'unknown',capability:'unknown',billing:'unknown'});const read={installation:fixture.descriptor,currentSubject:subject,authProfilePath:String.raw`C:\fixture\auth.json`,accountRef:observed.accountRef,nowMs:1050,maxAgeMs:100};const first=readIssuedNativeServiceAuthentication(observed,read),second=readIssuedNativeServiceAuthentication(observed,read);expect(first.observation).toBe(observed);expect(second.observation).toBe(observed);expect(Buffer.from(first.sourceBytes())).toEqual(Buffer.from(second.sourceBytes()));expect(Buffer.from(first.sourceBytes()).toString()).not.toContain('Person@Example.COM');});
 test('refuses absent identity, account drift, malformed usage, and shaped service receipts',async()=>{fixture.account={type:'apiKey'};await expect(observeNativeServiceAuthentication(input())).rejects.toThrow('native_service_authentication_account');fixture.alive=true;fixture.account={type:'chatgpt',email:'Person@Example.COM',planType:'plus'};fixture.accountSequence=[fixture.account,{type:'chatgpt',email:'other@example.com',planType:'plus'}];await expect(observeNativeServiceAuthentication(input())).rejects.toThrow('native_service_authentication_account');fixture.alive=true;fixture.accountSequence=[];fixture.usage={summary:{lifetimeTokens:null},dailyUsageBuckets:[{startDate:'2026-09-16',tokens:-1}],threadUsage:null};await expect(observeNativeServiceAuthentication(input())).rejects.toThrow('native_service_authentication_usage');fixture.alive=true;fixture.usage={summary:{lifetimeTokens:null},dailyUsageBuckets:null,threadUsage:null};const observed=await observeNativeServiceAuthentication(input());expect(()=>readIssuedNativeServiceAuthentication({...observed},{installation:fixture.descriptor,currentSubject:subject,authProfilePath:String.raw`C:\fixture\auth.json`,accountRef:observed.accountRef,nowMs:1050,maxAgeMs:100})).toThrow('native_service_authentication_unissued');});
 test('direct service reader refuses wrong profile/account/installation/subject/time/issuer and protects source bytes',async()=>{const profileA=Object.freeze({path:String.raw`C:\fixture\auth-a.json`,size:4,dev:'1',ino:'30',mtimeMs:1,ctimeMs:1}),profileB=Object.freeze({path:String.raw`C:\fixture\auth-b.json`,size:4,dev:'1',ino:'31',mtimeMs:1,ctimeMs:1});fixture.descriptor=Object.freeze({...descriptor(),authProfiles:Object.freeze([profileA,profileB])});const observed=await observeNativeServiceAuthentication(input({authProfilePath:profileA.path})),base={installation:fixture.descriptor,currentSubject:subject,authProfilePath:profileA.path,accountRef:observed.accountRef,nowMs:1050,maxAgeMs:100};expect(()=>readIssuedNativeServiceAuthentication(observed,{...base,authProfilePath:profileB.path})).toThrow('native_service_authentication_unissued');expect(()=>readIssuedNativeServiceAuthentication(observed,{...base,accountRef:'account:'+ 'f'.repeat(64)})).toThrow('native_service_authentication_unissued');expect(()=>readIssuedNativeServiceAuthentication(observed,{...base,installation:descriptor()})).toThrow('native_service_authentication_unissued');expect(()=>readIssuedNativeServiceAuthentication(observed,{...base,currentSubject:Object.freeze({...subject,osBuild:'drift'})})).toThrow('native_service_authentication_stale');expect(()=>readIssuedNativeServiceAuthentication(observed,{...base,nowMs:999})).toThrow('native_service_authentication_stale');expect(()=>readIssuedNativeServiceAuthentication(observed,{...base,nowMs:1101})).toThrow('native_service_authentication_stale');expect(()=>readIssuedNativeServiceAuthentication(observed,{...base,nowMs:1060,maxAgeMs:50})).toThrow('native_service_authentication_stale');fixture.installationCurrent=false;expect(()=>readIssuedNativeServiceAuthentication(observed,base)).toThrow('provider_installation_unavailable_or_drifted');fixture.installationCurrent=true;fixture.issuerDrift=true;expect(()=>readIssuedNativeServiceAuthentication(observed,base)).toThrow('native_service_authentication_stale');fixture.issuerDrift=false;const first=readIssuedNativeServiceAuthentication(observed,base).sourceBytes();first[0]^=255;const second=readIssuedNativeServiceAuthentication(observed,base).sourceBytes();expect(second[0]).not.toBe(first[0]);});
});

test.each([
 {permission:true,spend:false,account:'account-private',state:'available'},
 {permission:false,spend:false,account:'account-private',state:'denied'},
 {permission:true,spend:true,account:'account-private',state:'denied'},
 {permission:null,spend:false,account:'account-private',state:'unknown'},
 {permission:undefined,spend:false,account:'account-private',state:'unknown'},
 {permission:true,spend:false,account:null,state:'unknown'},
])('capacity binds explicit included-usage permission: %#',async ({permission,spend,account,state})=>{
 fixture.capacity={ordinaryUsageAllowed:permission,accountId:account,rateLimits:{primary:{usedPercent:0,resetsAt:1},spendControlReached:spend}};
 const value=await observeNativeServiceCapacity(input());
 expect(fixture.requests.map(value=>value.method)).toEqual(['initialize','initialized','account/read','account/usage/read','account/rateLimits/read','account/read']);
 const args={installation:fixture.descriptor,currentSubject:subject,authProfilePath:String.raw`C:\fixture\auth.json`,accountRef:value.accountRef,nowMs:1050,maxAgeMs:100};
 const read=readIssuedNativeServiceCapacity(value,args);
 expect(read.available).toBe(state==='available');expect(value.capacity?.state).toBe(state);
 expect(value.modelEntitlement).toBe('unknown');expect(value.billing).toBe('unknown');
 expect(Buffer.from(read.sourceBytes()).toString()).not.toContain('account-private');
 expect(()=>readIssuedNativeServiceCapacity({...value},args)).toThrow('unissued');
 expect(()=>readIssuedNativeServiceCapacity(value,{...args,nowMs:1101})).toThrow('stale');
 expect(()=>readIssuedNativeServiceCapacity(value,{...args,authProfilePath:'other'})).toThrow('unissued');
});

test('capacity cannot be created from authentication alone or malformed permission',async()=>{
 const auth=await observeNativeServiceAuthentication(input());
 expect(()=>readIssuedNativeServiceCapacity(auth,{installation:fixture.descriptor,currentSubject:subject,authProfilePath:String.raw`C:\fixture\auth.json`,accountRef:auth.accountRef,nowMs:1050,maxAgeMs:100})).toThrow('capacity_missing');
 fixture.alive=true;fixture.capacity={ordinaryUsageAllowed:'true',accountId:'private',rateLimits:{}};
 await expect(observeNativeServiceCapacity(input())).rejects.toThrow('capacity_response');
});

test('capacity is not issued when the account changes around the service request',async()=>{
 fixture.capacity={ordinaryUsageAllowed:true,accountId:'private',rateLimits:{spendControlReached:false}};
 fixture.accountSequence=[fixture.account,{...fixture.account,email:'other@example.com'}];
 await expect(observeNativeServiceCapacity(input())).rejects.toThrow('authentication_account');
});
