import { afterEach, describe, expect, test } from 'vitest';
import { spawn, type ChildProcess } from 'node:child_process';
import { spawnSync } from 'node:child_process';
import { EventEmitter } from 'node:events';
import { PassThrough } from 'node:stream';
import { createHash } from 'node:crypto';
import { existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createInterface } from 'node:readline';
import { tmpdir } from 'node:os';
import { basename, dirname, isAbsolute, join, resolve } from 'node:path';
import { openLedger } from '../src/ledger.js';
import { observeProcessTree, terminateVerifiedTree } from '../src/process-termination.js';

type Identity={pid:number;createdAt:string};type Root={path:string;retain:boolean};
const fixture=join(process.cwd(),'test','fixtures','integration-driver-publication-crash-child.mjs'),roots:Root[]=[],children=new Map<ChildProcess,{identity:Identity;closed:Promise<any>;root:Root}>();
const sha=(value:string|Buffer)=>createHash('sha256').update(value).digest('hex');
class JsonFrames{private queue:any[]=[];private waiters:Array<{resolve:(value:any)=>void;reject:(error:Error)=>void;timer:NodeJS.Timeout}>=[];private terminal:Error|null=null;constructor(stream:NodeJS.ReadableStream,lifecycle:EventEmitter){const lines=createInterface({input:stream});lines.on('line',line=>{let value;try{value=JSON.parse(line)}catch{this.fail(Error('publication_restart_invalid_frame'));return}const waiter=this.waiters.shift();if(waiter){clearTimeout(waiter.timer);waiter.resolve(value)}else this.queue.push(value)});lifecycle.once('error',error=>this.fail(error instanceof Error?error:Error(String(error))));lifecycle.once('close',()=>this.fail(Error('publication_restart_premature_close')))}private fail(error:Error){if(this.terminal)return;this.terminal=error;for(const waiter of this.waiters.splice(0)){clearTimeout(waiter.timer);waiter.reject(error)}}next(timeoutMs=10_000):Promise<any>{if(this.queue.length)return Promise.resolve(this.queue.shift());if(this.terminal)return Promise.reject(this.terminal);return new Promise((resolve,reject)=>{const waiter={resolve,reject,timer:setTimeout(()=>{this.waiters=this.waiters.filter(value=>value!==waiter);reject(Error('publication_restart_frame_timeout'))},timeoutMs)};this.waiters.push(waiter)})}}
function launch(mode:string,database:string,worktree:string){return spawn(process.execPath,[fixture,mode,database,worktree],{cwd:process.cwd(),windowsHide:true,stdio:['pipe','pipe','pipe']})}
const closedOf=(child:ChildProcess)=>new Promise<any[]>(resolve=>child.once('close',(...args)=>resolve(args)));
const registerForContinuation=<T>(register:()=>void,proceed:()=>T)=>{register();return proceed};
async function observeIdentity(pid:number){const deadline=Date.now()+10_000;do{const row=observeProcessTree(pid).descendants.find(value=>value.pid===pid);if(row)return{pid:row.pid,createdAt:row.createdAt};await new Promise(resolve=>setTimeout(resolve,25))}while(Date.now()<deadline);throw Error('publication_restart_identity_timeout')}
async function closeExact(child:ChildProcess,identity:{pid:number;createdAt:string},closed=closedOf(child)){if(child.exitCode!==null||child.signalCode!==null)return;const row=observeProcessTree(identity.pid).descendants.find(value=>value.pid===identity.pid);if(!row||row.createdAt!==identity.createdAt)throw Error('publication_restart_identity_changed');await Promise.resolve(terminateVerifiedTree(identity.pid));await closed}
async function startOwned(mode:string,database:string,worktree:string,root:Root){const child=launch(mode,database,worktree),closed=closedOf(child);let observed:Identity;try{observed=await observeIdentity(child.pid!)}catch(error){root.retain=true;throw error}const continueChild=registerForContinuation(()=>children.set(child,{identity:observed,closed,root}),()=>child.stdin!.write('continue\n')),frames=new JsonFrames(child.stdout!,child),hello=await frames.next();if(hello.kind!=='identity'||hello.mode!==mode||hello.pid!==observed.pid||hello.createdAt!==observed.createdAt)throw Error('publication_restart_handshake_mismatch');continueChild();return{child,closed,frames,identity:observed}}
afterEach(async()=>{const failures:unknown[]=[];for(const [child,owned] of [...children]){try{await closeExact(child,owned.identity,owned.closed);children.delete(child)}catch(error){owned.root.retain=true;failures.push(error)}}const base=resolve(tmpdir());for(const root of roots.splice(0)){if(root.retain)continue;try{const target=resolve(root.path);if(!isAbsolute(target)||dirname(target)!==base||!basename(target).startsWith('cue-publication-real-restart-')||lstatSync(target).isSymbolicLink())throw Error('publication_restart_cleanup_path');rmSync(target,{recursive:true,force:true});if(existsSync(target))throw Error('publication_restart_cleanup_failed')}catch(error){failures.push(error)}}if(failures.length)throw new AggregateError(failures,'publication_restart_cleanup_unverified')},30_000);

test('bounded frame reader rejects missing and prematurely closed streams',async()=>{const missing=new PassThrough(),missingLife=new EventEmitter(),timeout=new JsonFrames(missing,missingLife);await expect(timeout.next(5)).rejects.toThrow('publication_restart_frame_timeout');const closed=new PassThrough(),closedLife=new EventEmitter(),premature=new JsonFrames(closed,closedLife);closedLife.emit('close');await expect(premature.next()).rejects.toThrow('publication_restart_premature_close')});
test('owned registration precedes continuation and failed registration prevents effects',()=>{const events:string[]=[],owned=new Map<number,Identity>(),identity={pid:1,createdAt:'fixture'},proceed=registerForContinuation(()=>{owned.set(identity.pid,identity);events.push('owned')},()=>{expect(owned.get(1)).toEqual(identity);events.push('continue')});expect(events).toEqual(['owned']);proceed();expect(events).toEqual(['owned','continue']);let effects=0;expect(()=>registerForContinuation(()=>{throw Error('register-failed')},()=>{effects++})).toThrow('register-failed');expect(effects).toBe(0)});

describe.skipIf(process.platform!=='win32'||process.env.CUE_ACTUAL_PUBLICATION_RESTART!=='1')('A04 real publication crash/reopen',()=>{
 test('holds an actual external write after process death and never resumes it on reopen',async()=>{
  const rootRecord={path:mkdtempSync(join(tmpdir(),'cue-publication-real-restart-')),retain:false};roots.push(rootRecord);const root=rootRecord.path,database=join(root,'ledger.db'),worktree=join(root,'worktree'),target=join(worktree,'final.txt');mkdirSync(worktree);expect(spawnSync('git',['init'],{cwd:worktree,windowsHide:true}).status).toBe(0);writeFileSync(target,'before');expect(spawnSync('git',['add','final.txt'],{cwd:worktree,windowsHide:true}).status).toBe(0);const staged=spawnSync('git',['status','--short'],{cwd:worktree,windowsHide:true,encoding:'utf8'});expect(staged.status,staged.stderr).toBe(0);expect(staged.stdout.trimEnd()).toBe('A  final.txt');
  const firstOwned=await startOwned('crash-window',database,worktree,rootRecord),first=firstOwned.child;let firstError='';first.stderr!.on('data',chunk=>{firstError+=String(chunk)});const before=await firstOwned.frames.next();process.stdout.write(`${JSON.stringify({kind:'publication-crash-before-kill',...before})}\n`);
  expect(before).toMatchObject({mode:'crash-window',intentCount:1,resultCount:0,outcome:{state:'committed'},fileBytes:'published-after-crash-window'});expect(before.fileSha256).toBe(sha('published-after-crash-window'));expect(readFileSync(target,'utf8')).toBe('published-after-crash-window');
  const prekill=openLedger(database);try{expect(prekill.prepare("SELECT COUNT(*) n FROM change_publication_intent WHERE publication_id='publication-real-restart'").get()).toEqual({n:1});expect(prekill.prepare("SELECT COUNT(*) n FROM change_publication_result WHERE publication_id='publication-real-restart'").get()).toEqual({n:0})}finally{prekill.close()}
  await closeExact(first,firstOwned.identity,firstOwned.closed);children.delete(first);expect(firstError).toBe('');
  const dead=observeProcessTree(before.pid).descendants.find(value=>value.pid===before.pid&&value.createdAt===before.createdAt);expect(dead).toBeUndefined();
  const secondOwned=await startOwned('reopen',database,worktree,rootRecord),second=secondOwned.child;let secondError='';second.stderr!.on('data',chunk=>{secondError+=String(chunk)});const reopened=await secondOwned.frames.next(),[code]=await secondOwned.closed;children.delete(second);process.stdout.write(`${JSON.stringify({kind:'publication-crash-reopened',...reopened,exitCode:code})}\n`);
  expect(code,secondError).toBe(0);expect(reopened.pid).not.toBe(before.pid);expect(reopened).toMatchObject({kind:'reopen',mode:'reopen',held:[{attemptId:'publication-attempt',changeSetId:'publication-real-restart-set',state:'held',revision:0,reason:'interrupted-native-journal'}],reconciled:1,replay:{publicationId:'publication-real-restart',state:'pending'},root:{state:'blocked',blocked_reason:'crash'},attempt:{state:'blocked',cleanup_verified:0},heldRow:{attempt_id:'publication-attempt',change_set_id:'publication-real-restart-set',state:'held',revision:0,reason:'interrupted-native-journal',final_seal:null},heldTransitionCount:1,recoveryDecisionCount:0,recoveryActivationCount:0,leaseCount:1,receiptCount:0,acceptanceCount:0,attemptCount:1,replacementAttemptCount:0,resultCount:0,recoveryCount:1,authorizeCalls:0,executeCalls:0,fileBytes:'published-after-crash-window'});expect(reopened.heldRow.payload_sha256).toBe(sha(reopened.heldRow.payload));expect(JSON.parse(reopened.heldRow.payload)).toMatchObject({schemaVersion:'cue-held-recovery-v1',caseId:reopened.heldRow.case_id,attemptId:'publication-attempt',changeSetId:'publication-real-restart-set',state:'held',revision:0,reason:'interrupted-native-journal'});expect(reopened.gitStatusArtifacts).toHaveLength(1);expect(reopened.gitStatusArtifacts[0].content.trimEnd()).toBe('AM final.txt');expect(reopened.fileSha256).toBe(before.fileSha256);expect(readFileSync(target,'utf8')).toBe('published-after-crash-window');
  const final=openLedger(database);try{expect(final.prepare("SELECT COUNT(*) n FROM workspace_write_lease WHERE run_id='publication-run'").get()).toEqual({n:1});expect(final.prepare("SELECT COUNT(*) n FROM change_publication_result WHERE publication_id='publication-real-restart'").get()).toEqual({n:0});expect(final.prepare("SELECT state,revision,final_seal FROM held_recovery WHERE attempt_id='publication-attempt'").get()).toEqual({state:'held',revision:0,final_seal:null})}finally{final.close()}
 },60_000);
});
