import {mkdtempSync,readFileSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {afterAll,expect,test} from 'vitest';
import {runProcessSync} from '../src/process-launch.js';
import {parseReadonlyWfpDiagnostic} from '../src/readonly-wfp-diagnostic.js';
const root=mkdtempSync(join(tmpdir(),'cue-wfp-wire-'));afterAll(()=>{const p=resolve(root),b=resolve(tmpdir())+'\\';if(!p.startsWith(b)||!p.slice(b.length).startsWith('cue-wfp-wire-'))throw Error('unsafe');rmSync(p,{recursive:true,force:true});});
const base=readFileSync(resolve('src/readonly-verifier-launch.ps1'),'utf8').match(/Add-Type -TypeDefinition @'\r?\n([\s\S]*?)\r?\n'@/)![1];
const collector=readFileSync(resolve('../scripts/reuse/native/readonly-wfp-collector.cs'),'utf8'),adapter=readFileSync(resolve('src/readonly-wfp-observation.cs'),'utf8');
const harness=String.raw`
public sealed class WireNative:IWfpNative{public Action<WfpEvent> callback;public uint Open(out IntPtr x){x=(IntPtr)1;return 0;}public uint GetCollection(IntPtr x,out int v){v=1;return 0;}public uint GetAppId(string p,out IntPtr x,out byte[] b){x=(IntPtr)2;b=new byte[]{1};return 0;}public uint Subscribe(IntPtr e,WfpRequest r,byte[] a,Action<WfpEvent> c,out IntPtr s,out object o){callback=c;o=c;s=(IntPtr)3;c(new WfpEvent{Timestamp=ulong.MaxValue,Flags=uint.MaxValue,IpVersion=1,Protocol=6,RemoteAddress=2130706433,RemotePort=48193,PackageSid="S-1-15-2-1",AppId=new byte[]{0,255},Capability=-1,FilterId=ulong.MaxValue,IsLoopback=true});return 0;}public uint Unsubscribe(IntPtr e,IntPtr s){return 0;}public void Free(ref IntPtr p){p=IntPtr.Zero;}public uint Close(IntPtr e){return 0;}public void Wait(int x){}}
public sealed class ThrowWriter:System.IO.StringWriter{public override void WriteLine(string value){throw new InvalidOperationException("writer");}}
public static class WireHarness{public static string Run(string mode){var n=new WireNative();var r=new WfpRequest{ExecutablePath="C:\\node.exe",PackageSid="S-1-15-2-1",RemotePort=48193,DurationMs=1};var i=new CueWfpDiagnosticInvocation(n,r,h=>0);var l=(CueWfpObservationLease)i.Provider((IntPtr)7,(IntPtr)8);l.Ready();l.ObserveProcessDeath((IntPtr)7);l.Dispose();if(mode=="duplicate")try{i.Provider((IntPtr)7,(IntPtr)8);}catch{}var old=Console.Out;var w=new System.IO.StringWriter();Console.SetOut(mode=="writer"?(System.IO.TextWriter)new ThrowWriter():w);try{i.Emit(mode=="badnonce"?"A"+new String('a',63):new String('a',64),"root-id");i.Emit(new String('a',64),"root-id");}finally{Console.SetOut(old);}return mode=="writer"?"preserved":w.ToString().Trim();}}
`;
function invoke(mode:string){const strip=(v:string)=>v.replace(/^using .*;\r?$/gm,''),source=`using System;\nusing System.Collections.Generic;\nusing System.ComponentModel;\nusing System.Runtime.InteropServices;\nusing System.Security.Principal;\nusing System.Threading;\n${strip(base)}\n${strip(collector)}\n${strip(adapter)}\n${harness}`,cs=join(root,mode+'.cs'),ps=join(root,mode+'.ps1');writeFileSync(cs,source);writeFileSync(ps,`$ErrorActionPreference='Stop';Add-Type -Path '${cs.replaceAll("'","''")}';[WireHarness]::Run('${mode}')`);const r=runProcessSync('powershell.exe',['-NoLogo','-NoProfile','-NonInteractive','-File',ps],{encoding:'utf8',windowsHide:true,timeout:20000,maxBuffer:1048576});expect(r.status,r.stderr).toBe(0);return r.stdout.trim();}
test('serializes the exact bounded precision-safe wire frame once and the real parser accepts it',()=>{const line=invoke('ok');expect(line.match(/CUE_READONLY_WFP=/g)).toHaveLength(1);const v=JSON.parse(line.slice('CUE_READONLY_WFP='.length));expect(Object.keys(v)).toEqual(['version','nonce','rootIdentity','state','overflow','events']);expect(v).toMatchObject({version:'cue-readonly-wfp-diagnostic-v1',nonce:'a'.repeat(64),rootIdentity:'root-id',state:'captured',overflow:false});expect(v.events[0]).toEqual({timestamp:'18446744073709551615',flags:4294967295,ipVersion:1,protocol:6,remoteAddress:2130706433,remotePort:48193,packageSid:'S-1-15-2-1',appId:'AP8=',capability:-1,filterId:'18446744073709551615',isLoopback:true});expect(parseReadonlyWfpDiagnostic(line+'\n','a'.repeat(64),'root-id',true)).toMatchObject({state:'captured',events:[v.events[0]]});});
test('duplicate provider invalidates captured evidence through the real parser',()=>{const line=invoke('duplicate'),v=JSON.parse(line.slice('CUE_READONLY_WFP='.length));expect(v).toMatchObject({state:'unknown',events:[]});expect(parseReadonlyWfpDiagnostic(line+'\n','a'.repeat(64),'root-id',true)).toEqual({state:'unknown',overflow:false,events:[]});});
test('invalid nonce emits no unbound frame and consumes the one-shot attempt',()=>{expect(invoke('badnonce')).toBe('');});
test('writer failure is swallowed and a second emission is not attempted',()=>{expect(invoke('writer')).toBe('preserved');});
