import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { copyFileSync, existsSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { createCueCore, initializeConfig } from '../../app/core.mjs';
import { createCleanCodexHome, vendorCodexLaunchSpec } from '../src/tool-home.js';
import { openLedger } from '../src/ledger.js';
import { normalizeEnvelope, type Envelope } from '../src/envelope.js';
import { runWorkerLifecycle } from '../src/worker-enforcement.js';

const roots:string[]=[];
const temp=(name:string)=>{const p=mkdtempSync(resolve(`.test-state-p10-${name}-`));roots.push(p);return p;};
const vendor=process.env.CUE_VENDOR_CODEX??join(process.env.APPDATA!,'npm','node_modules','@openai','codex','node_modules','@openai','codex-win32-x64','vendor','x86_64-pc-windows-msvc','bin','codex.exe');
const auth=join(process.env.USERPROFILE!,'.codex','auth.json');
const waitFor=async(check:()=>boolean,ms=180_000)=>{const end=Date.now()+ms;while(Date.now()<end){if(check())return;await new Promise(r=>setTimeout(r,100));}throw new Error('timed out');};
type Live={root:string;core:any;prepared:any;artifact:string;pid:number;content:string};
const lives:Live[]=[];

async function live(goal:string):Promise<Live>{
  const root=temp('goal');copyFileSync(auth,join(root,'auth.json'));writeFileSync(join(root,'config.toml'),'[features]\nhooks=false\nmcp=false\nplugins=false\nskills=false\n');const home=root,config=initializeConfig(join(root,'data'),{worktreeRoot:root}),core=createCueCore(config,undefined,{binary:vendor,codexHome:home});
  const prepared=core.prepareGoal(goal);core.approve(prepared.runId);const running=core.execute(prepared.runId);expect(running.status).toBe('작업 중');
  await waitFor(()=>core.completion(prepared.taskId).state!=='running');const card=core.completion(prepared.taskId);expect(card.state).toBe('completed');
  const row=core.daemon.db.prepare('SELECT pid FROM session_handle WHERE run_id=?').get(prepared.runId) as {pid:number};
  const artifact=((prepared.envelope.allowed_actions as string[])[0]).slice(6),content=readFileSync(join(root,artifact),'utf8');const result={root,core,prepared,artifact,pid:row.pid,content};lives.push(result);return result;
}

describe.sequential('Phase 10 real engine connection',()=>{
  let a:Live,b:Live;
  beforeAll(async()=>{expect(process.platform).toBe('win32');expect(existsSync(vendor)).toBe(true);expect(existsSync(auth)).toBe(true);a=await live('알파 릴리스 체크리스트를 작성한다');b=await live('베타 회고 요약을 작성한다');},400_000);
  afterAll(()=>{for(const item of lives)item.core.close();for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});

  it('P10-1 derives immutable actions from each goal and removes the old literal',()=>{expect(a.prepared.envelope.allowed_actions).not.toEqual(b.prepared.envelope.allowed_actions);expect(readFileSync(resolve('../app/core.mjs'),'utf8')).not.toContain('cue-p9-live.txt');});
  it('P10-2 records real sessions, executions, and AppContainer PIDs',()=>{for(const item of [a,b]){expect(item.pid).toBeGreaterThan(0);expect(item.core.daemon.db.prepare('SELECT count(*) n FROM execution_event WHERE run_id=?').get(item.prepared.runId)).toEqual({n:1});}expect(readFileSync(resolve('../app/core.mjs'),'utf8')).not.toContain('writeFileSync');});
  it('P10-3 produces distinct goal-reflecting artifacts in distinct processes',()=>{expect(a.artifact).not.toBe(b.artifact);expect(a.content).toContain('알파 릴리스 체크리스트를 작성한다');expect(b.content).toContain('베타 회고 요약을 작성한다');expect(a.content).not.toBe(b.content);expect(a.pid).not.toBe(b.pid);console.info(`P10-3 LIVE A pid=${a.pid} path=${join(a.root,a.artifact)} content=${JSON.stringify(a.content.trim())}`);console.info(`P10-3 LIVE B pid=${b.pid} path=${join(b.root,b.artifact)} content=${JSON.stringify(b.content.trim())}`);});
  it('P10-4 stop terminates the owned live process and ledgers cancellation',async()=>{const root=temp('stop'),home=createCleanCodexHome(join(root,'homes'),auth),core=createCueCore(initializeConfig(join(root,'data'),{worktreeRoot:root}),undefined,{binary:vendor,codexHome:home});const p=core.prepareGoal('오래 기다린 뒤 중단 검증 파일을 작성한다');core.approve(p.runId);core.execute(p.runId);await waitFor(()=>((core.daemon.db.prepare('SELECT pid FROM session_handle WHERE run_id=?').get(p.runId) as {pid:number}).pid)!==undefined,30_000);const pid=(core.daemon.db.prepare('SELECT pid FROM session_handle WHERE run_id=?').get(p.runId) as {pid:number}).pid;expect(core.stop(p.runId)).toBe(true);await waitFor(()=>{try{process.kill(pid,0);return false;}catch{return true;}},30_000);expect(core.completion(p.taskId).state).toBe('blocked');console.info(`P10-4 LIVE stopped_pid=${pid}`);core.close();});
  it('P10-5 blocks an AppContainer junction escape and records violation',()=>{const work=temp('escape-work'),outside=temp('escape-out'),db=openLedger(),task='t',run='r',now=new Date().toISOString();db.prepare('INSERT INTO task VALUES(?,?,?,?)').run(task,'running',null,now);const envelope=normalizeEnvelope({run_id:run,worktree_realpath:work,egress:[],expires_at:'2099-01-01T00:00:00Z',autonomy_level:'bounded',allowed_actions:['command']} satisfies Envelope),hash='h';db.prepare('INSERT INTO envelope VALUES(?,?,?,?)').run(hash,work,'[]',now);db.prepare('INSERT INTO run VALUES(?,?,?,?,?)').run(run,task,hash,0,now);symlinkSync(outside,join(work,'escape'),'junction');const target=join(outside,'blocked.txt'),result=runWorkerLifecycle(envelope,{executable:'powershell.exe',args:['-NoProfile','-Command',`Set-Content -LiteralPath '${join(work,'escape','blocked.txt')}' -Value bad`],cwd:work,inspectedPaths:[target]},{db,execution:{run_id:run,thread_id:'p10',item_id:'escape',approval_id:null,execution_id:'e',execution_ordinal:0}});expect(result.violation).toBe('filesystem');expect(existsSync(target)).toBe(false);expect(db.prepare("SELECT content FROM artifact WHERE run_id=? AND kind='enforcement_violation'").get(run)).toEqual({content:'filesystem'});db.close();});
  it('P10-6 detects forbidden network and stops with the preserved detection-layer grade',()=>{const work=temp('network'),db=openLedger(),now=new Date().toISOString();db.prepare('INSERT INTO task VALUES(?,?,?,?)').run('tn','running',null,now);db.prepare('INSERT INTO envelope VALUES(?,?,?,?)').run('hn',work,'[]',now);db.prepare('INSERT INTO run VALUES(?,?,?,?,?)').run('rn','tn','hn',0,now);const envelope=normalizeEnvelope({run_id:'rn',worktree_realpath:work,egress:[],expires_at:'2099-01-01T00:00:00Z',autonomy_level:'bounded',allowed_actions:['command']} satisfies Envelope);const result=runWorkerLifecycle(envelope,{executable:'powershell.exe',args:['-NoProfile','-Command','Invoke-WebRequest https://example.com'],cwd:work},{db,execution:{run_id:'rn',thread_id:'p10',item_id:'net',approval_id:null,execution_id:'en',execution_ordinal:0}});expect(result.violation).toBe('network_gate');expect(result.result?.status).toBe(77);db.close();});
  it('P10-7 reads running then completed status from ledger-backed cards',()=>{expect(a.core.completion(a.prepared.taskId).status).toBe('완료');expect(a.core.daemon.db.prepare('SELECT state FROM task WHERE id=?').get(a.prepared.taskId)).toEqual({state:'completed'});});
  it('P10-8 attempts bounded recovery only at autonomy ③',async()=>{for(const level of [3,1] as const){const root=temp(`recovery-${level}`),home=createCleanCodexHome(join(root,'homes'),auth),core=createCueCore(initializeConfig(join(root,'data'),{worktreeRoot:root}),undefined,{binary:vendor,codexHome:home,extraArgs:['--model','definitely-invalid-model']});const p=core.prepareGoal('실패 복구 검증',level);core.approve(p.runId);core.execute(p.runId);await waitFor(()=>core.completion(p.taskId).state!=='running');const card=core.completion(p.taskId);expect(card.recoveryAttempts).toBe(level===3?4:0);expect(card.state).toBe('blocked');core.close();}});
  it('P10-9 preserves approval and immutable-envelope gates',()=>{const root=temp('approval'),core=createCueCore(initializeConfig(join(root,'data'),{worktreeRoot:root}));const p=core.prepareGoal('승인 게이트');expect(()=>core.execute(p.runId)).toThrow('approval required');expect(()=>core.daemon.db.prepare('UPDATE envelope SET egress_json=? WHERE envelope_hash=?').run('["*"]',(core.daemon.db.prepare('SELECT envelope_hash FROM run WHERE id=?').get(p.runId) as any).envelope_hash)).toThrow('envelope is immutable');core.close();});
  it('P10-10 strips credential-like parent environment values',()=>{process.env.P10_SECRET_TOKEN='must-not-leak';try{const spec=vendorCodexLaunchSpec(vendor,['--version'],join(a.root,'homes'));expect(spec.env.P10_SECRET_TOKEN).toBeUndefined();expect(JSON.stringify(spec.env)).not.toContain('must-not-leak');}finally{delete process.env.P10_SECRET_TOKEN;}});
  it('P10-11 has no progress notification path',()=>{const app=['core.mjs','ipc.mjs','main.mjs'].map(x=>readFileSync(resolve('../app',x),'utf8')).join('\n');expect(app).not.toMatch(/new Notification|\.showNotification|webContents\.send/iu);});
  it('P10-12 keeps the historical PARTIAL labels intact',()=>{expect(readFileSync(resolve('../evidence/P3/p3c_result.json'),'utf8')).toContain('PARTIAL');expect(readFileSync(resolve('../evidence/P4/p4_result.json'),'utf8')).toContain('PARTIAL');expect(readFileSync(resolve('../evidence/P6/p6_result.json'),'utf8')).toContain('PARTIAL');});
});
