import {expect,test} from 'vitest';import {parseReadonlyWfpDiagnostic} from '../src/readonly-wfp-diagnostic.js';
const nonce='a'.repeat(64),root='1:2';
const event=()=>({timestamp:'18446744073709551615',flags:0xffffffff,ipVersion:0,protocol:6,remoteAddress:0x7f000001,remotePort:48193,packageSid:'S-1-15-2-1',appId:Buffer.from([0,1,2]).toString('base64'),capability:-1,filterId:'18446744073709551615',isLoopback:true});
const frame=(override:any={})=>'CUE_READONLY_WFP='+JSON.stringify({version:'cue-readonly-wfp-diagnostic-v1',nonce,rootIdentity:root,state:'captured',overflow:false,events:[event()],...override})+'\n';
test('accepts one exact bounded frame and deeply freezes it',()=>{const v=parseReadonlyWfpDiagnostic(frame(),nonce,root,true);expect(v.state).toBe('captured');expect(v.events).toHaveLength(1);expect(Object.isFrozen(v)&&Object.isFrozen(v.events)&&Object.isFrozen(v.events[0])).toBe(true);});
test('valid unknown or failed worker retains bounded events without promotion',()=>{expect(parseReadonlyWfpDiagnostic(frame({state:'unknown'}),nonce,root,true)).toMatchObject({state:'unknown',events:[event()]});expect(parseReadonlyWfpDiagnostic(frame(),nonce,root,false)).toMatchObject({state:'unknown',events:[event()]});expect(parseReadonlyWfpDiagnostic(frame({overflow:true}),nonce,root,true).state).toBe('unknown');});
test('invalid, foreign, excessive, or ambiguous frames become empty unknown',()=>{const cases=[ '',frame()+frame(),frame({nonce:'b'.repeat(64)}),frame({rootIdentity:'x'}),frame({extra:true}),frame({events:Array.from({length:65},event)}),frame({events:[{...event(),timestamp:'18446744073709551616'}]}),frame({events:[{...event(),appId:Buffer.alloc(4097).toString('base64')}]}),'CUE_READONLY_WFP={bad}\n','CUE_READONLY_WFP='+JSON.stringify({version:'cue-readonly-wfp-diagnostic-v1'})];for(const value of cases)expect(parseReadonlyWfpDiagnostic(value,nonce,root,true)).toEqual({state:'unknown',overflow:false,events:[]});});
test('accepts exact maximum collection and byte boundaries but rejects noncanonical integers',()=>{const events=Array.from({length:64},()=>({...event(),timestamp:'0',filterId:'0',appId:Buffer.alloc(4096).toString('base64'),packageSid:'x\n"y'}));expect(parseReadonlyWfpDiagnostic(frame({events}),nonce,root,true)).toMatchObject({state:'captured',events});for(const field of ['timestamp','filterId'])expect(parseReadonlyWfpDiagnostic(frame({events:[{...event(),[field]:'00'}]}),nonce,root,true)).toEqual({state:'unknown',overflow:false,events:[]});});
test('enforces the complete stdout and frame byte ceilings',()=>{expect(parseReadonlyWfpDiagnostic('x'.repeat(1_048_577),nonce,root,true)).toEqual({state:'unknown',overflow:false,events:[]});const oversized='CUE_READONLY_WFP='+JSON.stringify({version:'cue-readonly-wfp-diagnostic-v1',nonce,rootIdentity:root,state:'unknown',overflow:false,events:[],padding:'x'.repeat(524288)})+'\n';expect(parseReadonlyWfpDiagnostic(oversized,nonce,root,true)).toEqual({state:'unknown',overflow:false,events:[]});});
