import { createHash, randomUUID } from 'node:crypto';
import { isAbsolute, resolve, sep } from 'node:path';
import type { Ledger } from './ledger.js';
import { getChangeSnapshotHelperMetadata, identifyChangeSnapshotRoot, snapshotRelativeNative } from './change-snapshot-host.js';

export type ObjectKind='absent'|'file'|'directory'|'symlink'|'reparse'|'other'|'unknown';
export interface FileSnapshot { relativePath:string; objectKind:ObjectKind; canonicalParent:string; canonicalRealpath:string|null; fileIdentity:string|null; byteLength:number|null; sha256:string|null; comparisonHash:string|null; bytes:Buffer|null; restorable:boolean; restorableReason:string }
export interface CaptureLimits { maxTargets:number; maxBackupBytes:number }
export interface ChangeTargetDeclaration { taskId:string; targetId:string; relativePath:string; maxBackupBytes:number }
export interface CaptureChangeSetInput { changeSetId?:string; runId:string; taskId:string; attemptId:string; stageEnvelopeHash:string; launchIntentId:string; worktree:string; targets:readonly string[]; limits:CaptureLimits; nowMs?:number }
const sha=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex'),canonical=(value:unknown)=>JSON.stringify(value);
const safeId=(value:string)=>typeof value==='string'&&value.length>0&&value.length<=256&&!/[\0\r\n]/.test(value);
function validateRelative(path:string){if(!safeId(path)||isAbsolute(path)||path.includes(':'))throw Error('change_target_invalid');const parts=path.replace(/\\/g,'/').split('/');if(parts.some(p=>!p||p==='.'||p==='..'||/[. ]$/.test(p)||/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\..*)?$/i.test(p)))throw Error('change_target_invalid');return parts.join(sep);}
function rootRow(db:Ledger,runId:string,taskId:string){return db.prepare('SELECT * FROM change_root_contract WHERE run_id=? AND task_id=?').get(runId,taskId) as any|undefined;}
function parsedHashed(row:any,payloadKey='payload',hashKey='payload_sha256'){const bytes=Buffer.from(row[payloadKey]);if(sha(bytes)!==row[hashKey])throw Error('change_journal_corrupt');return JSON.parse(bytes.toString('utf8'));}
function assertRoot(root:any){const p=parsedHashed(root);if(p.schemaVersion!=='cue-change-root-contract-v1'||p.runId!==root.run_id||p.taskId!==root.task_id||p.worktreeRealpath!==root.worktree_realpath||p.volumeSerial!==root.volume_serial||p.fileId!==root.file_id||p.snapshotProtocol!==root.snapshot_protocol||p.snapshotHelperSha256!==root.snapshot_helper_sha256||p.observedAtMs!==root.observed_at_ms||!Array.isArray(p.targets))throw Error('change_root_contract_corrupt');return p;}

export function registerNativeChangeJournal(db:Ledger,input:{runId:string;worktreeRealpath:string;targets:readonly ChangeTargetDeclaration[];observedAtMs:number}){
 if(!safeId(input.runId)||typeof input.worktreeRealpath!=='string'||!Number.isSafeInteger(input.observedAtMs)||input.observedAtMs<0||!Array.isArray(input.targets)||input.targets.length<1||input.targets.length>64)throw Error('change_root_registration_invalid');
 const byTask=new Map<string,ChangeTargetDeclaration[]>(),aliases=new Set<string>();for(const target of input.targets){if(!safeId(target.taskId)||!safeId(target.targetId)||!Number.isSafeInteger(target.maxBackupBytes)||target.maxBackupBytes<1||target.maxBackupBytes>16*1024*1024)throw Error('change_target_registration_invalid');const relativePath=validateRelative(target.relativePath),key=`${target.taskId}\0${relativePath.toLocaleLowerCase('en-US')}`;if(aliases.has(key))throw Error('change_target_registration_duplicate');aliases.add(key);const list=byTask.get(target.taskId)??[];list.push({...target,relativePath});byTask.set(target.taskId,list);}
 for(const targets of byTask.values()){const cap=targets[0]!.maxBackupBytes;if(targets.some(target=>target.maxBackupBytes!==cap)||targets.length*cap>16*1024*1024)throw Error('change_target_common_cap_required');}
 const helper=getChangeSnapshotHelperMetadata();if(!helper)throw Error('change_snapshot_helper_unavailable');const identified=identifyChangeSnapshotRoot(input.worktreeRealpath);if(identified.state!=='ok')throw Error('change_root_identity_unavailable');
 return db.transaction(()=>{const summaries:any[]=[];for(const [taskId,unsorted] of byTask){const targets=[...unsorted].sort((a,b)=>a.relativePath.localeCompare(b.relativePath));for(const target of targets)db.prepare('INSERT INTO change_target_contract VALUES(?,?,?,?,?)').run(input.runId,taskId,target.targetId,target.relativePath,target.maxBackupBytes);const body={schemaVersion:'cue-change-root-contract-v1',runId:input.runId,taskId,worktreeRealpath:input.worktreeRealpath,volumeSerial:identified.identity.volumeSerial,fileId:identified.identity.fileId,snapshotProtocol:helper.protocol,snapshotHelperSha256:helper.helperSha256,observedAtMs:input.observedAtMs,targets:targets.map(({targetId,relativePath,maxBackupBytes})=>({targetId,relativePath,maxBackupBytes}))},encoded=canonical(body),digest=sha(encoded);db.prepare('INSERT INTO change_root_contract VALUES(?,?,?,?,?,?,?,?,?,?)').run(input.runId,taskId,input.worktreeRealpath,identified.identity.volumeSerial,identified.identity.fileId,helper.protocol,helper.helperSha256,input.observedAtMs,digest,Buffer.from(encoded));for(const target of targets)summaries.push(Object.freeze({taskId,targetId:target.targetId,relativePath:target.relativePath,maxBackupBytes:target.maxBackupBytes,rootContractDigest:digest}));}return Object.freeze(summaries);}).immediate();
}
function payloadOf(s:FileSnapshot){return {schemaVersion:'cue-change-entry-v1',relativePath:s.relativePath,objectKind:s.objectKind,canonicalParent:s.canonicalParent,canonicalRealpath:s.canonicalRealpath,fileIdentity:s.fileIdentity,byteLength:s.byteLength,sha256:s.sha256,comparisonHash:s.comparisonHash,restorable:s.restorable,restorableReason:s.restorableReason};}
function nativeBatch(root:any,targets:readonly string[],maxBytes:number){const response=snapshotRelativeNative({root:root.worktree_realpath,expectedRoot:{volumeSerial:root.volume_serial,fileId:root.file_id},targets,maxBytes});if(response.state!=='ok'||response.results.length!==targets.length)throw Error('change_snapshot_unavailable');return response.results;}
function mapped(root:string,result:any):FileSnapshot{if(result.state==='absent')return {relativePath:result.path,objectKind:'absent',canonicalParent:root,canonicalRealpath:null,fileIdentity:null,byteLength:null,sha256:null,comparisonHash:null,bytes:null,restorable:true,restorableReason:'created-file-removable'};if(result.state!=='ok'||!result.identity||!Buffer.isBuffer(result.bytes))throw Error('change_snapshot_uncertain');return {relativePath:result.path,objectKind:'file',canonicalParent:root,canonicalRealpath:null,fileIdentity:`${result.identity.volumeSerial}:${result.identity.fileId}`,byteLength:result.byteLength,sha256:result.sha256,comparisonHash:result.sha256,bytes:result.bytes,restorable:true,restorableReason:'stored-preimage'};}

export function captureChangeSet(db:Ledger,input:CaptureChangeSetInput){
 if(!safeId(input.runId)||!safeId(input.taskId)||!safeId(input.attemptId)||!safeId(input.launchIntentId)||!Number.isSafeInteger(input.limits.maxTargets)||input.limits.maxTargets<1||!Number.isSafeInteger(input.limits.maxBackupBytes)||input.limits.maxBackupBytes<1)throw Error('change_capture_invalid');if(db.prepare('SELECT 1 FROM native_change_journal_legacy WHERE attempt_id=?').get(input.attemptId))throw Error('legacy_native_journal_unavailable');
 const root=rootRow(db,input.runId,input.taskId),helper=getChangeSnapshotHelperMetadata();if(!root||!helper||root.worktree_realpath.toLocaleLowerCase('en-US')!==input.worktree.toLocaleLowerCase('en-US')||root.snapshot_protocol!==helper.protocol||root.snapshot_helper_sha256!==helper.helperSha256)throw Error('change_root_contract_unavailable');assertRoot(root);
 const contracts=db.prepare('SELECT relative_path,max_backup_bytes,target_id FROM change_target_contract WHERE run_id=? AND task_id=?').all(input.runId,input.taskId) as any[],contractCaps=new Set(contracts.map(c=>c.max_backup_bytes)),contractByPath=new Map<string,any>(contracts.map(c=>[c.relative_path.toLocaleLowerCase('en-US'),c])),folded=new Set<string>();const ordered=input.targets.map(path=>{const normalized=validateRelative(path),key=normalized.toLocaleLowerCase('en-US');if(folded.has(key))throw Error('change_target_alias');folded.add(key);return normalized;}).sort((a,b)=>a.localeCompare(b));if(contractCaps.size!==1||contracts.length*(contracts[0]?.max_backup_bytes??0)>16*1024*1024||!ordered.length||ordered.length>input.limits.maxTargets||contracts.length!==ordered.length||ordered.some(path=>{const c=contractByPath.get(path.toLocaleLowerCase('en-US'));return !c;}))throw Error('change_targets_not_preapproved');const rp=assertRoot(root);if(rp.targets.length!==contracts.length||rp.targets.some((target:any)=>{const c=contractByPath.get(String(target.relativePath).toLocaleLowerCase('en-US'));return !c||target.targetId!==c.target_id||target.relativePath!==c.relative_path||target.maxBackupBytes!==c.max_backup_bytes;}))throw Error('change_root_targets_corrupt');
 const replay=db.prepare('SELECT * FROM change_set WHERE attempt_id=?').get(input.attemptId) as any;if(replay){const p=parsedHashed(replay),binding=db.prepare('SELECT * FROM change_native_binding WHERE change_set_id=?').get(replay.change_set_id) as any,entries=db.prepare('SELECT * FROM change_entry WHERE change_set_id=? ORDER BY ordinal').all(replay.change_set_id) as any[];let valid=Boolean(binding);try{valid=valid&&p.schemaVersion==='cue-change-set-v1'&&p.changeSetId===replay.change_set_id&&p.runId===replay.run_id&&p.taskId===replay.task_id&&p.attemptId===replay.attempt_id&&p.stageEnvelopeHash===replay.stage_envelope_hash&&p.launchIntentId===replay.launch_intent_id&&p.worktreeRealpath===replay.worktree_realpath&&canonical(p.targets)===replay.approved_targets_json&&canonical(p.limits)===replay.scan_limits_json&&p.preimageManifestDigest===replay.preimage_manifest_digest&&p.createdAtMs===replay.created_at_ms;const bp=parsedHashed(binding);valid=valid&&bp.schemaVersion==='cue-change-native-binding-v1'&&bp.changeSetId===binding.change_set_id&&bp.runId===binding.run_id&&bp.taskId===binding.task_id&&bp.volumeSerial===binding.volume_serial&&bp.fileId===binding.file_id&&bp.snapshotProtocol===binding.snapshot_protocol&&bp.snapshotHelperSha256===binding.snapshot_helper_sha256&&binding.run_id===input.runId&&binding.task_id===input.taskId&&binding.volume_serial===root.volume_serial&&binding.file_id===root.file_id&&binding.snapshot_protocol===root.snapshot_protocol&&binding.snapshot_helper_sha256===root.snapshot_helper_sha256;const payloads=entries.map((entry,index)=>{if(entry.ordinal!==index)throw Error();const ep=parsedHashed(entry);if(ep.schemaVersion!=='cue-change-entry-v1'||ep.relativePath!==entry.relative_path||ep.objectKind!==entry.object_kind||ep.canonicalParent!==entry.canonical_parent||ep.canonicalRealpath!==entry.canonical_realpath||ep.fileIdentity!==entry.file_identity||ep.byteLength!==entry.byte_length||ep.sha256!==entry.sha256||ep.comparisonHash!==JSON.parse(Buffer.from(entry.payload).toString('utf8')).comparisonHash||Number(ep.restorable)!==entry.restorable||ep.restorableReason!==entry.restorable_reason||(entry.preimage&&sha(entry.preimage)!==entry.sha256))throw Error();return ep;});valid=valid&&entries.length===ordered.length&&sha(canonical(payloads))===replay.preimage_manifest_digest;}catch{valid=false;}if(!valid||replay.run_id!==input.runId||replay.task_id!==input.taskId||replay.stage_envelope_hash!==input.stageEnvelopeHash||replay.launch_intent_id!==input.launchIntentId||replay.worktree_realpath!==root.worktree_realpath||replay.approved_targets_json!==canonical(ordered)||replay.scan_limits_json!==canonical(input.limits)||(input.changeSetId&&replay.change_set_id!==input.changeSetId))throw Error('change_set_replay_mismatch');return Object.freeze({changeSetId:replay.change_set_id,worktreeRealpath:replay.worktree_realpath,preimageManifestDigest:replay.preimage_manifest_digest,entries:Object.freeze([]),replay:true});}
 return db.transaction(()=>{const entries=nativeBatch(root,ordered,input.limits.maxBackupBytes).map(result=>{if(result.state==='ok'&&result.byteLength!>contractByPath.get(result.path.toLocaleLowerCase('en-US')).max_backup_bytes)throw Error('change_snapshot_target_cap');return mapped(root.worktree_realpath,result);}),manifestDigest=sha(canonical(entries.map(payloadOf))),changeSetId=input.changeSetId??randomUUID(),nowMs=input.nowMs??Date.now();const body={schemaVersion:'cue-change-set-v1',changeSetId,runId:input.runId,taskId:input.taskId,attemptId:input.attemptId,stageEnvelopeHash:input.stageEnvelopeHash,launchIntentId:input.launchIntentId,worktreeRealpath:root.worktree_realpath,targets:ordered,limits:input.limits,preimageManifestDigest:manifestDigest,createdAtMs:nowMs},encoded=canonical(body);db.prepare('INSERT INTO change_set VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(changeSetId,input.runId,input.taskId,input.attemptId,input.stageEnvelopeHash,input.launchIntentId,root.worktree_realpath,canonical(ordered),canonical(input.limits),manifestDigest,nowMs,sha(encoded),Buffer.from(encoded));entries.forEach((entry,ordinal)=>{const p=canonical(payloadOf(entry));db.prepare('INSERT INTO change_entry VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(changeSetId,ordinal,entry.relativePath,entry.objectKind,entry.canonicalParent,entry.canonicalRealpath,entry.fileIdentity,entry.byteLength,entry.sha256,entry.restorable?1:0,entry.restorableReason,entry.bytes,sha(p),Buffer.from(p));});const binding={schemaVersion:'cue-change-native-binding-v1',changeSetId,runId:input.runId,taskId:input.taskId,volumeSerial:root.volume_serial,fileId:root.file_id,snapshotProtocol:root.snapshot_protocol,snapshotHelperSha256:root.snapshot_helper_sha256},p=canonical(binding);db.prepare('INSERT INTO change_native_binding VALUES(?,?,?,?,?,?,?,?,?)').run(changeSetId,input.runId,input.taskId,root.volume_serial,root.file_id,root.snapshot_protocol,root.snapshot_helper_sha256,sha(p),Buffer.from(p));return Object.freeze({changeSetId,worktreeRealpath:root.worktree_realpath,preimageManifestDigest:manifestDigest,entries:Object.freeze(entries),replay:false});}).immediate();
}
export function observeChangeSet(db:Ledger,changeSetId:string,options:{nowMs?:number}={}){
 const set=db.prepare('SELECT s.*,b.volume_serial,b.file_id,b.snapshot_protocol,b.snapshot_helper_sha256,b.payload_sha256 binding_sha,b.payload binding_payload FROM change_set s JOIN change_native_binding b USING(change_set_id) WHERE s.change_set_id=?').get(changeSetId) as any;if(!set)throw Error('change_set_missing');if(db.prepare("SELECT 1 FROM held_recovery WHERE change_set_id=? AND (state<>'held' OR final_seal IS NOT NULL)").get(changeSetId))throw Error('change_observation_sealed');const rows=db.prepare('SELECT ordinal,relative_path,object_kind,canonical_parent,canonical_realpath,file_identity,byte_length,sha256,preimage,payload FROM change_entry WHERE change_set_id=? ORDER BY ordinal').all(changeSetId) as any[];
 const latest=(db.prepare('SELECT MAX(observed_at_ms) at FROM change_observation WHERE change_set_id=?').get(changeSetId) as any).at??-1,requested=options.nowMs??Date.now(),at=Math.max(requested,latest+1),root=rootRow(db,set.run_id,set.task_id),helper=getChangeSnapshotHelperMetadata();let current:FileSnapshot[];try{const binding=parsedHashed(set,'binding_payload','binding_sha'),rp=assertRoot(root);if(binding.changeSetId!==changeSetId||binding.runId!==set.run_id||binding.taskId!==set.task_id||binding.volumeSerial!==set.volume_serial||binding.fileId!==set.file_id||binding.snapshotProtocol!==set.snapshot_protocol||binding.snapshotHelperSha256!==set.snapshot_helper_sha256||!helper||root.snapshot_helper_sha256!==helper.helperSha256||root.volume_serial!==set.volume_serial||root.file_id!==set.file_id||rp.targets.length!==rows.length)throw Error();current=nativeBatch(root,rows.map(r=>r.relative_path),JSON.parse(set.scan_limits_json).maxBackupBytes).map(result=>mapped(root.worktree_realpath,result));}catch{current=rows.map(row=>({relativePath:row.relative_path,objectKind:'unknown',canonicalParent:set.worktree_realpath,canonicalRealpath:null,fileIdentity:null,byteLength:null,sha256:null,comparisonHash:null,bytes:null,restorable:false,restorableReason:'snapshot-failed'}));}
 return db.transaction(()=>Object.freeze(rows.map((row,index)=>{const value=current[index]!,prior=JSON.parse(Buffer.from(row.payload).toString('utf8'));let status:string;if(value.objectKind==='unknown')status='unknown';else if(row.object_kind==='absent')status=value.objectKind==='absent'?'unchanged':'created';else if(value.objectKind==='absent')status='deleted';else if(value.objectKind!==row.object_kind)status='type-changed';else if(row.file_identity&&value.fileIdentity&&row.file_identity!==value.fileIdentity)status='moved';else status=row.object_kind==='file'&&!(row.byte_length===value.byteLength&&prior.comparisonHash===value.comparisonHash&&Buffer.isBuffer(row.preimage)&&value.bytes?.equals(row.preimage))?'modified':'unchanged';const observationId=randomUUID(),body={...payloadOf(value),schemaVersion:'cue-change-observation-v1',observationId,changeSetId,ordinal:row.ordinal,status,observedAtMs:at},encoded=canonical(body);db.prepare('INSERT INTO change_observation VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(observationId,changeSetId,row.ordinal,status,value.objectKind,value.canonicalParent,value.canonicalRealpath,value.fileIdentity,value.byteLength,value.sha256,value.bytes,at,sha(encoded),Buffer.from(encoded));return Object.freeze({observationId,ordinal:row.ordinal,status,current:value});}))).immediate();
}
export interface AtomicRestoreHost { replaceIfExact(args:{path:string;expected:Readonly<FileSnapshot>;bytes:Buffer}):boolean; removeIfExact(args:{path:string;expected:Readonly<FileSnapshot>}):boolean }
export function restoreStoppedChangeSet(db:Ledger,changeSetId:string,host?:AtomicRestoreHost){const set=db.prepare('SELECT run_id,attempt_id,worktree_realpath FROM change_set WHERE change_set_id=?').get(changeSetId) as any;if(!set)throw Error('change_set_missing');const stopped=db.prepare("SELECT 1 FROM orchestration_recovery_decision WHERE prior_attempt_id=? AND action='stop'").get(set.attempt_id),lease=db.prepare('SELECT 1 FROM workspace_write_lease WHERE run_id=? AND lower(worktree_realpath)=lower(?)').get(set.run_id,set.worktree_realpath);if(!stopped||!lease)throw Error('restore_authority_missing');if(!host)return Object.freeze({restored:false,reason:'atomic-race-closure-unsupported'});return Object.freeze({restored:false,reason:'atomic-race-closure-unsupported'});}
