import {createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {types} from 'node:util';
import type {Ledger} from './ledger.js';
import type {MeasurementSubject} from './measurement-subject.js';
import {subjectDigest} from './measurement-subject.js';
import type {SessionOwner} from './session-spawn.js';
import {spawnOwned} from './process-launch.js';
import {createCleanCodexHome,safeCleanupCodexHome,vendorCodexLaunchSpec} from './tool-home.js';
import {observeOwnedNativeProcess} from './host-runtime-native-identity.js';
import {observeProcessTree,terminateVerifiedTree} from './process-termination.js';
import {measureNativeProviderSubject} from './native-provider-measurement-subject.js';
import {assertCurrentProviderInstallation,type ProviderInstallationDescriptor} from '../../app/provider-installation.mjs';

const SHA=/^[a-f0-9]{64}$/u,MAX_LINE=64*1024;
const hash=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex');
function canonical(value:unknown):string{if(value===null||typeof value==='boolean'||typeof value==='string'||typeof value==='number')return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(canonical).join(',')}]`;if(!value||typeof value!=='object')throw Error('native_account_observation_invalid');return`{${Object.keys(value as object).sort().map(key=>`${JSON.stringify(key)}:${canonical((value as Record<string,unknown>)[key])}`).join(',')}}`;}
function plain(value:unknown,keys:readonly string[]):Record<string,unknown>{if(!value||typeof value!=='object'||types.isProxy(value)||Object.getPrototypeOf(value)!==Object.prototype)throw Error('native_account_observation_invalid');const d=Object.getOwnPropertyDescriptors(value),own=Reflect.ownKeys(d);if(own.length!==keys.length||keys.some(key=>!d[key]?.enumerable||!Object.hasOwn(d[key],'value')))throw Error('native_account_observation_invalid');return value as Record<string,unknown>;}
function currentInstallation(value:ProviderInstallationDescriptor){assertCurrentProviderInstallation(value);if(value.provider!=='codex'||value.authProfiles.length<1||value.authProfiles.length>4)throw Error('native_account_observation_installation');return value;}

export type NativeAccountObservation=Readonly<{
 version:'cue-native-account-observation-v1';provider:'codex';installationDigest:string;accountRef:string|null;accountIdentityDigest:string|null;
 subjectDigest:string;accountPresence:'present'|'absent';authentication:'unknown';entitlement:'unknown';capability:'unknown';
 observedAtMs:number;validUntilMs:number;sourceRef:string;sourceDigest:string;
 issuer:Readonly<{id:'cue-native-account-observer';revision:string}>;
 protocol:Readonly<{accountMethod:'account/read';refreshToken:false;requiresOpenaiAuth:boolean;rateLimitsMethod:'not-requested'|'account/rateLimits/read';rateLimitsObservation:'not-requested'|'observed'}>;
 process:Readonly<{pid:number;createdFileTime:string;cleanup:'verified-absent'}>;
}>;
type Issued=Readonly<{value:NativeAccountObservation;installation:ProviderInstallationDescriptor;subjectDigest:string;source:Buffer}>;
const issued=new WeakMap<object,Issued>();
export type NativeServiceAuthentication=Readonly<{
 version:'cue-native-service-authentication-v1';provider:'codex';installationDigest:string;authProfileRef:string;accountRef:string;accountIdentityDigest:string;subjectDigest:string;
 serviceAccepted:true;scope:'account-usage-read';authentication:'service-accepted';modelEntitlement:'unknown';capability:'unknown';billing:'unknown';
 observedAtMs:number;validUntilMs:number;sourceRef:string;sourceDigest:string;
 issuer:Readonly<{id:'cue-native-service-auth-observer';revision:string}>;
 protocol:Readonly<{accountMethod:'account/read';refreshToken:false;serviceMethod:'account/usage/read';stableAccount:true}>;
 process:Readonly<{pid:number;createdFileTime:string;cleanup:'verified-absent'}>;
 capacity?:NativeServiceCapacity;
}>;
export type NativeServiceCapacity=Readonly<{method:'account/rateLimits/read';scope:'ordinary-included-usage';state:'available'|'denied'|'unknown';available:boolean;responseDigest:string;accountIdDigest:string|null}>;
type IssuedService=Readonly<{value:NativeServiceAuthentication;installation:ProviderInstallationDescriptor;authProfilePath:string;authProfileRef:string;subjectDigest:string;accountRef:string;source:Buffer}>;
function capacityResult(raw:unknown):NativeServiceCapacity {
 const response=allowed(raw,['accountId','ordinaryUsageAllowed','rateLimits','rateLimitsByLimitId','rateLimitResetCredits','rateLimitUpsell'],['rateLimits']);
 const snapshot=allowed(response.rateLimits,['credits','individualLimit','limitId','limitName','normalModelSlug','planType','primary','secondary','rateLimitReachedType','spendControlReached']);
 const permission=response.ordinaryUsageAllowed,spend=snapshot.spendControlReached,accountId=response.accountId;
 if(permission!==undefined&&permission!==null&&typeof permission!=='boolean'||spend!==undefined&&spend!==null&&typeof spend!=='boolean'
   ||accountId!==undefined&&accountId!==null&&(typeof accountId!=='string'||!accountId||accountId.length>1024))throw Error('native_service_capacity_response');
 // Backend permission is authoritative; usage percentages and reset clocks never
 // manufacture recovery. Unknown permission or account binding stays unavailable.
 const state=permission===false||spend===true?'denied':permission===true&&typeof accountId==='string'?'available':'unknown';
 return Object.freeze({method:'account/rateLimits/read',scope:'ordinary-included-usage',state,available:state==='available',
   responseDigest:hash(canonical(response)),accountIdDigest:typeof accountId==='string'?hash(accountId):null});
}
const issuedService=new WeakMap<object,IssuedService>();

type Rpc=Readonly<{request(method:string,params:Record<string,unknown>):Promise<unknown>;notify(method:string,params:Record<string,unknown>):void;beginClose():void;assertHealthy():void;dispose():void}>;
function rpc(child:NonNullable<ReturnType<typeof spawnOwned>['child']>,timeoutMs:number):Rpc{
 if(!child.stdin||!child.stdout||!child.stderr)throw Error('native_account_observation_pipes');
 const pending=new Map<number,{resolve:(value:unknown)=>void;reject:(error:Error)=>void;timer:NodeJS.Timeout}>(),seen=new Set<number>();let next=0,disposed=false,shuttingDown=false,fatal:Error|undefined,buffer=Buffer.alloc(0),notifications=0,stderrBytes=0;
 const fail=(error:Error)=>{if(disposed||fatal)return;fatal=error;for(const item of pending.values()){clearTimeout(item.timer);item.reject(error);}pending.clear();};
 const frame=(bytes:Buffer)=>{let message:Record<string,unknown>;try{message=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes)) as Record<string,unknown>;if(!message||typeof message!=='object'||Array.isArray(message)||types.isProxy(message)||Object.getPrototypeOf(message)!==Object.prototype)throw Error();const jsonrpc=message.jsonrpc;if(jsonrpc!==undefined&&jsonrpc!=='2.0')throw Error();if(typeof message.method==='string'){
    const expected=jsonrpc===undefined?['method','params']:['jsonrpc','method','params'];plain(message,expected);if(message.id!==undefined||!message.method||message.method.length>256||!message.params||typeof message.params!=='object'||Array.isArray(message.params)||types.isProxy(message.params))throw Error();if(++notifications>64)throw Error();if(message.method==='account/updated')throw Error('account-updated');return;
   }
   const hasResult=Object.hasOwn(message,'result'),hasError=Object.hasOwn(message,'error'),expected=jsonrpc===undefined?(hasError?['id','error']:['id','result']):(hasError?['jsonrpc','id','error']:['jsonrpc','id','result']);plain(message,expected);if(hasResult===hasError||!Number.isSafeInteger(message.id)||(message.id as number)<1)throw Error();const id=message.id as number;if(seen.has(id)||!pending.has(id))throw Error();seen.add(id);const item=pending.get(id)!;pending.delete(id);clearTimeout(item.timer);if(hasError)item.reject(Error('native_account_observation_rpc'));else item.resolve(message.result);
  }catch(error){fail(Error(error instanceof Error&&error.message==='account-updated'?'native_account_observation_changed':'native_account_observation_frame'));}};
 const onData=(chunk:Buffer|string)=>{if(disposed||fatal)return;const incoming=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);for(let offset=0;offset<incoming.length;){const newline=incoming.indexOf(10,offset),end=newline===-1?incoming.length:newline,length=buffer.length+end-offset;if(length>MAX_LINE){fail(Error('native_account_observation_frame'));return;}if(end>offset)buffer=Buffer.concat([buffer,incoming.subarray(offset,end)],length);if(newline===-1)return;frame(buffer);buffer=Buffer.alloc(0);if(fatal)return;offset=newline+1;}};
 const onEnd=()=>{if(buffer.length)fail(Error('native_account_observation_frame'));else if(!shuttingDown||pending.size)fail(Error('native_account_observation_eof'));};
 const onError=()=>fail(Error('native_account_observation_process'));
 const onStderr=(chunk:Buffer|string)=>{stderrBytes+=Buffer.byteLength(chunk);if(stderrBytes>1024*1024)fail(Error('native_account_observation_stderr'));};
 child.stdout.on('data',onData);child.stdout.once('end',onEnd);child.once('error',onError);child.stderr.on('data',onStderr);
 const send=(value:Record<string,unknown>)=>{if(fatal)throw fatal;if(disposed||shuttingDown||child.stdin!.destroyed)throw Error('native_account_observation_closed');child.stdin!.write(`${JSON.stringify(value)}\n`);};
 return Object.freeze({request(method,params){const id=++next;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(Error('native_account_observation_timeout'));},timeoutMs);timer.unref?.();pending.set(id,{resolve,reject,timer});send({id,method,params});});},notify(method,params){send({method,params});},beginClose(){if(fatal)throw fatal;shuttingDown=true;child.stdin!.end();},assertHealthy(){if(fatal)throw fatal;if(pending.size)throw Error('native_account_observation_pending');},dispose(){disposed=true;child.stdout!.off('data',onData);child.stdout!.off('end',onEnd);child.off('error',onError);child.stderr!.off('data',onStderr);for(const item of pending.values()){clearTimeout(item.timer);item.reject(Error('native_account_observation_closed'));}pending.clear();}});
}
function accountResult(raw:unknown){const result=plain(raw,['account','requiresOpenaiAuth']);if(typeof result.requiresOpenaiAuth!=='boolean')throw Error('native_account_observation_account');if(result.account===null)return{presence:'absent' as const,identity:null,requiresOpenaiAuth:result.requiresOpenaiAuth};const account=result.account as unknown;const type=(account as {type?:unknown})?.type;if(type==='chatgpt'){const value=plain(account,['type','email','planType']);if((value.email!==null&&typeof value.email!=='string')||(typeof value.email==='string'&&!value.email.trim())||typeof value.planType!=='string'||!value.planType.trim())throw Error('native_account_observation_account');return{presence:'present' as const,identity:value.email===null?null:{type:'chatgpt',email:(value.email as string).trim().toLocaleLowerCase('en-US')},requiresOpenaiAuth:result.requiresOpenaiAuth};}if(type==='apiKey'){plain(account,['type']);return{presence:'present' as const,identity:null,requiresOpenaiAuth:result.requiresOpenaiAuth};}throw Error('native_account_observation_account');}
function allowed(value:unknown,keys:readonly string[],required:readonly string[]=[]):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value)||types.isProxy(value)||Object.getPrototypeOf(value)!==Object.prototype)throw Error('native_service_authentication_usage');const descriptors=Object.getOwnPropertyDescriptors(value),own=Reflect.ownKeys(descriptors);if(own.some(key=>typeof key!=='string'||!keys.includes(key)||!descriptors[key as string]?.enumerable||!Object.hasOwn(descriptors[key as string]!,'value'))||required.some(key=>!Object.hasOwn(value,key)))throw Error('native_service_authentication_usage');return value as Record<string,unknown>;}
function usageResult(raw:unknown){const response=allowed(raw,['summary','dailyUsageBuckets','threadUsage'],['summary']),summary=allowed(response.summary,['currentStreakDays','lifetimeTokens','longestRunningTurnSec','longestStreakDays','peakDailyTokens']);for(const value of Object.values(summary))if(value!==null&&(!Number.isSafeInteger(value)||Number(value)<0))throw Error('native_service_authentication_usage');if(response.threadUsage!==undefined&&response.threadUsage!==null)throw Error('native_service_authentication_usage');const daily=response.dailyUsageBuckets;if(daily!==undefined&&daily!==null){if(!Array.isArray(daily)||types.isProxy(daily)||daily.length>4096)throw Error('native_service_authentication_usage');for(const item of daily){const bucket=plain(item,['startDate','tokens']);if(typeof bucket.startDate!=='string'||!bucket.startDate||bucket.startDate.length>64||!Number.isSafeInteger(bucket.tokens)||Number(bucket.tokens)<0)throw Error('native_service_authentication_usage');}}return Object.freeze({summaryDigest:hash(canonical(summary)),dailyUsageDigest:daily===undefined||daily===null?null:hash(canonical(daily)),dailyUsageState:daily===undefined?'absent':daily===null?'null':'observed',threadUsageState:response.threadUsage===undefined?'absent':'null'});}
async function closed(child:ReturnType<typeof spawnOwned>['child']){if(child.exitCode!==null||child.signalCode!==null)return;await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('native_account_observation_cleanup')),10_000);child.once('close',()=>{clearTimeout(timer);resolve();});});}

export async function observeNativeProviderAccount(input:Readonly<{db:Ledger;owner:SessionOwner;installation:ProviderInstallationDescriptor;currentSubject:MeasurementSubject;authProfilePath:string;temporaryParent:string;nowMs:number;maxAgeMs:number;requestTimeoutMs?:number;observeRateLimits?:boolean}>):Promise<NativeAccountObservation>{
 const installation=currentInstallation(input.installation);if(!Number.isSafeInteger(input.nowMs)||!Number.isSafeInteger(input.maxAgeMs)||input.maxAgeMs<1||input.maxAgeMs>86_400_000||!installation.authProfiles.some(profile=>profile.path===input.authProfilePath))throw Error('native_account_observation_input');
 const measuredSubject=subjectDigest(input.currentSubject),installationDigest=hash(canonical(installation)),home=createCleanCodexHome(input.temporaryParent,input.authProfilePath),spec=vendorCodexLaunchSpec(installation.executablePath,['-a','on-request','app-server'],home);
 let launched:ReturnType<typeof spawnOwned>|undefined,identity:{pid:number;createdFileTime:string}|undefined,createdAt:string|undefined,source:Buffer|undefined,value:NativeAccountObservation|undefined,channel:Rpc|undefined,cleanupVerified=false;
 const stop=async()=>{if(!launched)return;if(launched.child.exitCode===null&&launched.child.signalCode===null){if(!createdAt)throw Error('native_account_observation_cleanup');terminateVerifiedTree(launched.child.pid!,createdAt);}await closed(launched.child);if(observeProcessTree(launched.child.pid!).descendants.some(row=>row.pid===launched!.child.pid!))throw Error('native_account_observation_cleanup');cleanupVerified=true;};
 try{
  launched=spawnOwned(input.db,input.owner,spec.command,spec.args,{env:spec.env,stdio:['pipe','pipe','pipe'],windowsHide:true});identity=observeOwnedNativeProcess(launched.child.pid!,launched.child.pid!);createdAt=observeProcessTree(launched.child.pid!).descendants.find(row=>row.pid===launched!.child.pid!)?.createdAt;if(!createdAt)throw Error('native_account_observation_process');channel=rpc(launched.child,input.requestTimeoutMs??30_000);
  await channel.request('initialize',{clientInfo:{name:'cue_desktop',title:'Cue Desktop',version:'0.1.0'},capabilities:{experimentalApi:true}});channel.notify('initialized',{});
  const account=accountResult(await channel.request('account/read',{refreshToken:false}));let rateLimitsObservation:'not-requested'|'observed'='not-requested';
  if(input.observeRateLimits===true){await channel.request('account/rateLimits/read',{});rateLimitsObservation='observed';}
  currentInstallation(installation);if(subjectDigest(input.currentSubject)!==measuredSubject)throw Error('native_account_observation_subject_changed');
  const accountIdentityDigest=account.identity===null?null:hash(canonical(account.identity)),accountRef=accountIdentityDigest===null?null:`account:${accountIdentityDigest}`;
  const body={version:'cue-native-account-observation-source-v1' as const,provider:'codex' as const,installationDigest,accountRef,accountIdentityDigest,subjectDigest:measuredSubject,accountPresence:account.presence,authentication:'unknown' as const,entitlement:'unknown' as const,capability:'unknown' as const,observedAtMs:input.nowMs,validUntilMs:input.nowMs+input.maxAgeMs,protocol:{accountMethod:'account/read' as const,refreshToken:false as const,requiresOpenaiAuth:account.requiresOpenaiAuth,rateLimitsMethod:input.observeRateLimits===true?'account/rateLimits/read' as const:'not-requested' as const,rateLimitsObservation}};source=Buffer.from(canonical(body));const sourceDigest=hash(source),sourceRef=`native-account:${sourceDigest}`,revision=hash(readFileSync(fileURLToPath(import.meta.url)));
  channel.beginClose();await stop();channel.assertHealthy();
  const finalized:NativeAccountObservation=Object.freeze({...body,version:'cue-native-account-observation-v1' as const,sourceRef,sourceDigest,issuer:Object.freeze({id:'cue-native-account-observer' as const,revision}),protocol:Object.freeze(body.protocol),process:Object.freeze({...identity!,cleanup:'verified-absent' as const})});value=finalized;
  issued.set(finalized,Object.freeze({value:finalized,installation,subjectDigest:measuredSubject,source:Buffer.from(source)}));return finalized;
 }finally{if(channel){try{channel.beginClose();}catch{};}if(launched&&!cleanupVerified)await stop();let protocolError:unknown;try{channel?.assertHealthy();}catch(error){protocolError=error;}channel?.dispose();if(!launched||cleanupVerified)safeCleanupCodexHome(home);if(protocolError)throw protocolError;}
}

export async function observeNativeServiceAuthentication(input:Readonly<{db:Ledger;owner:SessionOwner;installation:ProviderInstallationDescriptor;currentSubject:MeasurementSubject;authProfilePath:string;temporaryParent:string;nowMs:number;maxAgeMs:number;requestTimeoutMs?:number;observeCapacity?:boolean}>):Promise<NativeServiceAuthentication>{
 const installation=currentInstallation(input.installation),measurement=measureNativeProviderSubject(installation),authProfile=installation.authProfiles.find(profile=>profile.path===input.authProfilePath);if(!Number.isSafeInteger(input.nowMs)||!Number.isSafeInteger(input.maxAgeMs)||input.maxAgeMs<1||input.maxAgeMs>86_400_000||!authProfile||subjectDigest(input.currentSubject)!==measurement.subjectDigest)throw Error('native_service_authentication_input');const authProfileRef=`profile:${hash(canonical(authProfile))}`;
 const home=createCleanCodexHome(input.temporaryParent,input.authProfilePath),spec=vendorCodexLaunchSpec(installation.executablePath,['-a','on-request','app-server'],home);let launched:ReturnType<typeof spawnOwned>|undefined,identity:{pid:number;createdFileTime:string}|undefined,createdAt:string|undefined,channel:Rpc|undefined,cleanupVerified=false,finalized:NativeServiceAuthentication|undefined,source:Buffer|undefined;
 const stop=async()=>{if(!launched)return;if(launched.child.exitCode===null&&launched.child.signalCode===null){if(!createdAt)throw Error('native_service_authentication_cleanup');terminateVerifiedTree(launched.child.pid!,createdAt);}await closed(launched.child);if(observeProcessTree(launched.child.pid!).descendants.some(row=>row.pid===launched!.child.pid!))throw Error('native_service_authentication_cleanup');cleanupVerified=true;};
 try{
  launched=spawnOwned(input.db,input.owner,spec.command,spec.args,{env:spec.env,stdio:['pipe','pipe','pipe'],windowsHide:true});identity=observeOwnedNativeProcess(launched.child.pid!,launched.child.pid!);createdAt=observeProcessTree(launched.child.pid!).descendants.find(row=>row.pid===launched!.child.pid!)?.createdAt;if(!createdAt)throw Error('native_service_authentication_process');channel=rpc(launched.child,input.requestTimeoutMs??30_000);
  await channel.request('initialize',{clientInfo:{name:'cue_desktop',title:'Cue Desktop',version:'0.1.0'},capabilities:{experimentalApi:true}});channel.notify('initialized',{});
  const before=accountResult(await channel.request('account/read',{refreshToken:false}));if(!before.requiresOpenaiAuth||before.identity===null)throw Error('native_service_authentication_account');const accountIdentityDigest=hash(canonical(before.identity)),accountRef=`account:${accountIdentityDigest}`;
  const usage=usageResult(await channel.request('account/usage/read',{}));
  const capacity=input.observeCapacity===true?capacityResult(await channel.request('account/rateLimits/read',{})):undefined;
  const after=accountResult(await channel.request('account/read',{refreshToken:false}));if(!after.requiresOpenaiAuth||after.identity===null||hash(canonical(after.identity))!==accountIdentityDigest)throw Error('native_service_authentication_account');
  const current=measureNativeProviderSubject(installation);if(current.subjectDigest!==measurement.subjectDigest||subjectDigest(input.currentSubject)!==measurement.subjectDigest||current.manifest.installationDigest!==measurement.manifest.installationDigest)throw Error('native_service_authentication_subject_changed');
  const body={version:'cue-native-service-authentication-source-v1' as const,provider:'codex' as const,installationDigest:measurement.manifest.installationDigest,authProfileRef,accountRef,accountIdentityDigest,subjectDigest:measurement.subjectDigest,serviceAccepted:true as const,scope:'account-usage-read' as const,authentication:'service-accepted' as const,modelEntitlement:'unknown' as const,capability:'unknown' as const,billing:'unknown' as const,observedAtMs:input.nowMs,validUntilMs:input.nowMs+input.maxAgeMs,usage,...(capacity?{capacity}:{}),protocol:{accountMethod:'account/read' as const,refreshToken:false as const,serviceMethod:'account/usage/read' as const,stableAccount:true as const}};source=Buffer.from(canonical(body));const sourceDigest=hash(source),sourceRef=`native-service-auth:${sourceDigest}`,revision=hash(readFileSync(fileURLToPath(import.meta.url)));
  channel.beginClose();await stop();channel.assertHealthy();finalized=Object.freeze({...body,version:'cue-native-service-authentication-v1' as const,sourceRef,sourceDigest,issuer:Object.freeze({id:'cue-native-service-auth-observer' as const,revision}),protocol:Object.freeze(body.protocol),process:Object.freeze({...identity!,cleanup:'verified-absent' as const})});issuedService.set(finalized,Object.freeze({value:finalized,installation,authProfilePath:input.authProfilePath,authProfileRef,subjectDigest:measurement.subjectDigest,accountRef,source:Buffer.from(source)}));return finalized;
 }finally{if(channel){try{channel.beginClose();}catch{};}if(launched&&!cleanupVerified)await stop();let protocolError:unknown;try{channel?.assertHealthy();}catch(error){protocolError=error;}channel?.dispose();if(!launched||cleanupVerified)safeCleanupCodexHome(home);if(protocolError)throw protocolError;}
}

export function readIssuedNativeServiceAuthentication(observation:unknown,input:Readonly<{installation:ProviderInstallationDescriptor;currentSubject:MeasurementSubject;authProfilePath:string;accountRef:string;nowMs:number;maxAgeMs:number}>):Readonly<{observation:NativeServiceAuthentication;sourceBytes():Uint8Array}>{
 if(!observation||typeof observation!=='object'||types.isProxy(observation))throw Error('native_service_authentication_unissued');const record=issuedService.get(observation as object);if(!record||record.value!==observation||record.installation!==input.installation||record.authProfilePath!==input.authProfilePath||record.accountRef!==input.accountRef)throw Error('native_service_authentication_unissued');const measurement=measureNativeProviderSubject(input.installation),digest=subjectDigest(input.currentSubject),issuerRevision=hash(readFileSync(fileURLToPath(import.meta.url))),profile=input.installation.authProfiles.find(value=>value.path===input.authProfilePath),profileRef=profile?`profile:${hash(canonical(profile))}`:null;if(digest!==measurement.subjectDigest||digest!==record.subjectDigest||digest!==record.value.subjectDigest||measurement.manifest.installationDigest!==record.value.installationDigest||profileRef!==record.authProfileRef||profileRef!==record.value.authProfileRef||record.value.issuer.revision!==issuerRevision||!Number.isSafeInteger(input.nowMs)||!Number.isSafeInteger(input.maxAgeMs)||input.maxAgeMs<1||input.nowMs<record.value.observedAtMs||input.nowMs>record.value.validUntilMs||input.nowMs-record.value.observedAtMs>input.maxAgeMs||hash(record.source)!==record.value.sourceDigest||!SHA.test(record.value.sourceDigest))throw Error('native_service_authentication_stale');return Object.freeze({observation:record.value,sourceBytes:()=>Uint8Array.from(record.source)});
}

export async function observeNativeServiceCapacity(input:Parameters<typeof observeNativeServiceAuthentication>[0]):Promise<NativeServiceAuthentication>{
 return observeNativeServiceAuthentication({...input,observeCapacity:true});
}
export function readIssuedNativeServiceCapacity(observation:unknown,input:Parameters<typeof readIssuedNativeServiceAuthentication>[1]){
 const issued=readIssuedNativeServiceAuthentication(observation,input);
 if(!issued.observation.capacity)throw Error('native_service_capacity_missing');
 return Object.freeze({...issued,available:issued.observation.capacity.available});
}

export function readIssuedNativeAccountObservation(observation:unknown,input:Readonly<{installation:ProviderInstallationDescriptor;currentSubject:MeasurementSubject;nowMs:number;maxAgeMs:number}>):Readonly<{observation:NativeAccountObservation;sourceBytes():Uint8Array}>{
 if(!observation||typeof observation!=='object'||types.isProxy(observation))throw Error('native_account_observation_unissued');const record=issued.get(observation as object);if(!record||record.value!==observation||record.installation!==input.installation)throw Error('native_account_observation_unissued');currentInstallation(input.installation);const digest=subjectDigest(input.currentSubject);if(digest!==record.subjectDigest||digest!==record.value.subjectDigest||!Number.isSafeInteger(input.nowMs)||!Number.isSafeInteger(input.maxAgeMs)||input.maxAgeMs<1||input.nowMs<record.value.observedAtMs||input.nowMs>record.value.validUntilMs||input.nowMs-record.value.observedAtMs>input.maxAgeMs||hash(record.source)!==record.value.sourceDigest||!SHA.test(record.value.sourceDigest))throw Error('native_account_observation_stale');return Object.freeze({observation:record.value,sourceBytes:()=>Uint8Array.from(record.source)});
}
