import { existsSync, lstatSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { runProcessSync } from './process-launch.js';
import { createCleanupObservationStore } from './cleanup-observation-store.js';
import type { Ledger } from './ledger.js';
import type { NativeRuntimeReceipt } from './orchestration/native-runtime-receipts.js';

type QueryResult=Readonly<{pid:number;createdFileTime:string|null;liveness:'alive'|'exited'|'absent'|'unknown'}>;
const script=fileURLToPath(new URL('./native-process-observation.ps1',import.meta.url));
function queryNative(processes:readonly Readonly<{pid:number}>[]):readonly QueryResult[]{const all:QueryResult[]=[];for(let offset=0;offset<processes.length;offset+=3){const chunk=processes.slice(offset,offset+3),padded=[...chunk];let paddingPid=1;while(padded.length<3){while(padded.some(entry=>entry.pid===paddingPid))paddingPid++;padded.push({pid:paddingPid++});}const request={version:'cue-native-query-v1',nonce:randomUUID(),processes:padded};const result=runProcessSync('C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe',['-NoLogo','-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',script,'-PayloadBase64',Buffer.from(JSON.stringify(request)).toString('base64')],{encoding:'utf8',timeout:10000,maxBuffer:65536,windowsHide:true});if(result.status!==0||result.error||result.stderr.trim())throw Error('native_cleanup_query');const parsed=JSON.parse(result.stdout);if(parsed?.version!==request.version||parsed?.nonce!==request.nonce||!Array.isArray(parsed.processes)||parsed.processes.length!==3)throw Error('native_cleanup_query');all.push(...parsed.processes.slice(0,chunk.length));}return Object.freeze(all);}
export function createNativeProcessCleanup(db:Ledger,fixture?:Readonly<{query(processes:readonly Readonly<{pid:number}>[]):readonly QueryResult[];pathAbsent(path:string):boolean}>){const query=fixture?.query??queryNative,pathAbsent=fixture?.pathAbsent??(path=>{try{return !existsSync(path)||(lstatSync(path),false);}catch{return false;}});return Object.freeze({observe(receipt:NativeRuntimeReceipt){const expected=[receipt.controller,...receipt.workers];let result:'verified-clean'|'residual'|'unknown'='unknown',reason='observation-unavailable';try{const observed=query(expected.map(p=>({pid:p.pid})));if(observed.length!==expected.length)throw Error('count');let residual=false,uncertain=false;for(let i=0;i<expected.length;i++){const actual=observed[i]!,wanted=expected[i]!;if(actual.pid!==wanted.pid||!['alive','exited','absent','unknown'].includes(actual.liveness))throw Error('shape');if(actual.liveness==='unknown')uncertain=true;else if(actual.createdFileTime!==null&&actual.createdFileTime!==wanted.createdFileTime){/* PID reuse is clean for the owned process. */}else if(actual.liveness==='alive')residual=true;else if(actual.liveness==='exited'||actual.liveness==='absent'){/* clean */}else uncertain=true;}for(const resource of receipt.resources){if(resource.ownership==='retained-authorized'){if(resource.cleanup!=='retained')uncertain=true;continue;}if(resource.cleanup!=='absent'||!pathAbsent(resource.path))residual=true;}result=residual?'residual':uncertain?'unknown':'verified-clean';reason=residual?'owned-process-or-resource-remains':uncertain?'observation-uncertain':'exact-owned-resources-absent';}catch{result='unknown';reason='observation-unavailable';}const row=db.prepare('SELECT pid,start_time,handle,cwd,task_id,run_id FROM session_handle WHERE handle=?').get(receipt.sessionHandle) as Record<string,unknown>|undefined;if(!row)throw Error('native_cleanup_session');const observation=Object.freeze({runId:receipt.attemptId,candidateId:receipt.candidateId,role:receipt.taskId==='implement'?'implementation':'model',subjectDigest:receipt.subjectDigest,measuredAt:new Date(receipt.observedAtMs).toISOString(),result,providerStopped:'unknown',billing:'unknown',reason,session:row,processes:Object.freeze(expected.map(p=>Object.freeze({pid:p.pid,createdFileTime:p.createdFileTime}))),resources:receipt.resources});const evidenceRef=createCleanupObservationStore(db).persist(observation);return Object.freeze({runId:receipt.attemptId,subjectDigest:receipt.subjectDigest,result,evidenceRef});}});}

