import { createHash } from 'node:crypto';
import { types } from 'node:util';
import type { Ledger } from './ledger.js';
import type { SessionRecord } from './session-spawn.js';

const sha=(v:Uint8Array)=>createHash('sha256').update(v).digest('hex'), hash=(v:unknown):v is string=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v);
const id=(v:unknown):v is string=>typeof v==='string'&&/^[A-Za-z0-9][A-Za-z0-9:_-]{0,127}$/.test(v);
function plain(v:unknown,keys:readonly string[]){if(!v||typeof v!=='object'||types.isProxy(v)||Object.getPrototypeOf(v)!==Object.prototype)throw Error('readonly_identity_data');const d=Object.getOwnPropertyDescriptors(v);if(Reflect.ownKeys(d).length!==keys.length||keys.some(k=>!d[k]?.enumerable||!Object.hasOwn(d[k],'value')))throw Error('readonly_identity_fields');return Object.fromEntries(keys.map(k=>[k,d[k]!.value]));}
export interface ReadonlyVerifierIdentity {version:'cue-readonly-verifier-identity-v1';attemptId:string;candidateId:string;subjectDigest:string;controlDigest:string;commandDigest:string;environmentDigest:string;rootIdentity:string;session:Readonly<SessionRecord>;worker:{pid:number;createdFileTime:string};observedAt:string}
export interface ReadonlyVerifierCleanup {version:'cue-readonly-verifier-cleanup-v1';attemptId:string;identitySha256:string;result:'verified-clean';aclRestored:true;profileAbsent:true;runtimeAbsent:true;processesDead:true;rootIdentity:string;observedAt:string}
function encode(v:unknown){const b=Buffer.from(JSON.stringify(v));if(!b.length||b.length>32768)throw Error('readonly_identity_bounds');return b;}
function identity(input:ReadonlyVerifierIdentity){const v=plain(input,['version','attemptId','candidateId','subjectDigest','controlDigest','commandDigest','environmentDigest','rootIdentity','session','worker','observedAt']);
 if(v.version!=='cue-readonly-verifier-identity-v1'||!id(v.attemptId)||typeof v.candidateId!=='string'||!hash(v.subjectDigest)||!hash(v.controlDigest)||!hash(v.commandDigest)||!hash(v.environmentDigest)||typeof v.rootIdentity!=='string'||typeof v.observedAt!=='string'||!Number.isFinite(Date.parse(v.observedAt)))throw Error('readonly_identity_invalid');
 const s=plain(v.session,['handle','pid','start_time','cwd','task_id','run_id']),w=plain(v.worker,['pid','createdFileTime']);if(!id(s.handle)||s.run_id!==v.attemptId||!id(s.task_id)||typeof s.cwd!=='string'||!s.cwd||typeof s.start_time!=='string'||!s.start_time||!Number.isSafeInteger(s.pid)||Number(s.pid)<1||!Number.isSafeInteger(w.pid)||Number(w.pid)<1||w.pid===s.pid||typeof w.createdFileTime!=='string'||!/^[1-9]\d{0,19}$/.test(w.createdFileTime))throw Error('readonly_identity_invalid');return Object.freeze({...v,session:Object.freeze(s),worker:Object.freeze(w)}) as unknown as ReadonlyVerifierIdentity;}
export function createReadonlyVerifierIdentityStore(db:Ledger){return Object.freeze({
 record(input:ReadonlyVerifierIdentity){if(db.inTransaction)throw Error('readonly_identity_outer_transaction');const v=identity(input),payload=encode(v),digest=sha(payload);db.transaction(()=>{const old=db.prepare('SELECT payload FROM readonly_verifier_identity WHERE attempt_id=? OR sha256=?').get(v.attemptId,digest) as {payload:Buffer}|undefined;if(old){if(!old.payload.equals(payload))throw Error('readonly_identity_conflict');}else db.prepare('INSERT INTO readonly_verifier_identity VALUES(?,?,?,?,?)').run(digest,v.attemptId,v.session.handle,v.subjectDigest,payload);}).immediate();return 'cue-readonly-identity:'+digest;},
 cleanup(input:ReadonlyVerifierCleanup){if(db.inTransaction)throw Error('readonly_cleanup_outer_transaction');const v=plain(input,['version','attemptId','identitySha256','result','aclRestored','profileAbsent','runtimeAbsent','processesDead','rootIdentity','observedAt']);if(v.version!=='cue-readonly-verifier-cleanup-v1'||!id(v.attemptId)||!hash(v.identitySha256)||v.result!=='verified-clean'||v.aclRestored!==true||v.profileAbsent!==true||v.runtimeAbsent!==true||v.processesDead!==true||typeof v.rootIdentity!=='string'||typeof v.observedAt!=='string'||!Number.isFinite(Date.parse(v.observedAt)))throw Error('readonly_cleanup_invalid');const payload=encode(v),digest=sha(payload);db.transaction(()=>{const old=db.prepare('SELECT payload FROM readonly_verifier_cleanup WHERE attempt_id=? OR sha256=?').get(v.attemptId,digest) as {payload:Buffer}|undefined;if(old){if(!old.payload.equals(payload))throw Error('readonly_cleanup_conflict');}else db.prepare('INSERT INTO readonly_verifier_cleanup VALUES(?,?,?,?)').run(digest,v.attemptId,v.identitySha256,payload);}).immediate();return 'cue-readonly-cleanup:'+digest;}
 });}
