using System;
using System.Collections.Generic;
public delegate uint CueProcessWaitZero(IntPtr processHandle);
public sealed class CueWfpLeaseDiagnostic { public string State="unknown";public bool Overflow;public WfpEvent[] Events=new WfpEvent[0]; }
public sealed class CueWfpObservationLease : ICueObservationLease {
 readonly IWfpNative native;readonly WfpRequest request;readonly CueProcessWaitZero waitZero;readonly IntPtr expectedProcess,expectedJob;readonly List<WfpEvent> events=new List<WfpEvent>();
 IntPtr engine,appId,subscription;byte[] appBytes;object callbackRoot;bool guardHeld,ready,deathObserved,disposed,quarantined,refused,overflow,captureCompleted;
 public CueWfpObservationLease(IWfpNative n,WfpRequest scope,CueProcessWaitZero wait,IntPtr process,IntPtr job){if(n==null||scope==null||wait==null)throw new ArgumentNullException();native=n;request=new WfpRequest{ExecutablePath=scope.ExecutablePath,PackageSid=scope.PackageSid,RemotePort=scope.RemotePort,DurationMs=scope.DurationMs};waitZero=wait;expectedProcess=process;expectedJob=job;}
 public bool Ready(){if(disposed||quarantined||ready||expectedProcess==IntPtr.Zero||expectedJob==IntPtr.Zero||!WfpRequestValidator.IsValid(request))return false;if(!WfpNativeLifetimeGuard.TryBegin())return false;guardHeld=true;try{uint c=native.Open(out engine);if(c!=0||engine==IntPtr.Zero)return Refuse();int enabled;c=native.GetCollection(engine,out enabled);if(c!=0||enabled!=1)return Refuse();c=native.GetAppId(request.ExecutablePath,out appId,out appBytes);if(c!=0||appId==IntPtr.Zero||appBytes==null||appBytes.Length<1||appBytes.Length>4096)return Refuse();c=native.Subscribe(engine,request,appBytes,Capture,out subscription,out callbackRoot);if(c!=0||subscription==IntPtr.Zero){if(subscription!=IntPtr.Zero)return Poison();return Refuse();}ready=true;return true;}catch{Poison();throw;}}
 void Capture(WfpEvent e){lock(events){if(e==null||events.Count>=64){overflow=true;return;}events.Add(new WfpEvent{Timestamp=e.Timestamp,Flags=e.Flags,IpVersion=e.IpVersion,Protocol=e.Protocol,RemoteAddress=e.RemoteAddress,RemotePort=e.RemotePort,PackageSid=e.PackageSid,AppId=e.AppId==null?null:(byte[])e.AppId.Clone(),Capability=e.Capability,FilterId=e.FilterId,IsLoopback=e.IsLoopback});}}
 static WfpEvent CopyEvent(WfpEvent e){return new WfpEvent{Timestamp=e.Timestamp,Flags=e.Flags,IpVersion=e.IpVersion,Protocol=e.Protocol,RemoteAddress=e.RemoteAddress,RemotePort=e.RemotePort,PackageSid=e.PackageSid,AppId=e.AppId==null?null:(byte[])e.AppId.Clone(),Capability=e.Capability,FilterId=e.FilterId,IsLoopback=e.IsLoopback};}
 public CueWfpLeaseDiagnostic ReadDiagnostic(){lock(events){var copy=new WfpEvent[events.Count];for(int i=0;i<events.Count;i++)copy[i]=CopyEvent(events[i]);return new CueWfpLeaseDiagnostic{State=captureCompleted&&!quarantined&&!overflow?"captured":"unknown",Overflow=overflow,Events=copy};}}
 bool Refuse(){try{if(appId!=IntPtr.Zero)native.Free(ref appId);if(engine!=IntPtr.Zero){uint c=native.Close(engine);if(c!=0)return Poison();engine=IntPtr.Zero;}if(guardHeld){WfpNativeLifetimeGuard.Release();guardHeld=false;}refused=true;return false;}catch{return Poison();}}
 bool Poison(){quarantined=true;WfpNativeLifetimeGuard.Quarantine(native,engine,appId,subscription,callbackRoot,this);guardHeld=false;return false;}
 public bool ObserveProcessDeath(IntPtr p){if((!ready&&!refused)||disposed||quarantined||p!=expectedProcess)return false;try{if(waitZero(p)!=0)return false;deathObserved=true;return true;}catch{return false;}}
 public void Dispose(){if(disposed)return;if(quarantined)throw new InvalidOperationException("WFP observation lease quarantined");if(refused&&deathObserved){disposed=true;return;}if(!ready||!deathObserved){Poison();throw new InvalidOperationException("WFP observation lease disposal before verified process death");}try{if(native.Unsubscribe(engine,subscription)!=0){Poison();throw new InvalidOperationException("WFP unsubscribe failed");}subscription=IntPtr.Zero;if(appId!=IntPtr.Zero)native.Free(ref appId);if(native.Close(engine)!=0){Poison();throw new InvalidOperationException("WFP engine close failed");}engine=IntPtr.Zero;callbackRoot=null;appBytes=null;ready=false;disposed=true;captureCompleted=true;if(guardHeld){WfpNativeLifetimeGuard.Release();guardHeld=false;}}catch{if(!quarantined)Poison();throw;}}
}
public static class CueWfpObservationLeaseFactory {
 static WfpRequest Snapshot(WfpRequest r){if(r==null)return null;return new WfpRequest{ExecutablePath=r.ExecutablePath,PackageSid=r.PackageSid,RemotePort=r.RemotePort,DurationMs=r.DurationMs};}
 public static CueObservationLeaseProvider CreateProvider(WfpRequest request){WfpRequest frozen=Snapshot(request);return delegate(IntPtr p,IntPtr j){return new CueWfpObservationLease(new NativeWfp(),frozen,CueAppContainer.ObserveProcessDeathNow,p,j);};}
 public static CueObservationLeaseProvider CreateProvider(IWfpNative native,WfpRequest request,CueProcessWaitZero wait){WfpRequest frozen=Snapshot(request);return delegate(IntPtr p,IntPtr j){return new CueWfpObservationLease(native,frozen,wait,p,j);};}
}
public sealed class CueWfpDiagnosticInvocation {
 readonly CueObservationLeaseProvider inner;CueWfpObservationLease lease;bool providerCalled,emitted,invalid;
 public CueWfpDiagnosticInvocation(WfpRequest request){inner=CueWfpObservationLeaseFactory.CreateProvider(request);}
 public CueWfpDiagnosticInvocation(IWfpNative native,WfpRequest request,CueProcessWaitZero wait){inner=CueWfpObservationLeaseFactory.CreateProvider(native,request,wait);}
 public CueObservationLeaseProvider Provider { get { return delegate(IntPtr process,IntPtr job){if(providerCalled){invalid=true;throw new InvalidOperationException("WFP diagnostic provider reused");}providerCalled=true;var owned=inner(process,job) as CueWfpObservationLease;if(owned==null){invalid=true;throw new InvalidOperationException("WFP diagnostic lease unavailable");}lease=owned;return owned;};} }
 static string Q(string value){if(value==null)return "null";var b=new System.Text.StringBuilder("\"");foreach(char c in value){switch(c){case '\"':b.Append("\\\"");break;case '\\':b.Append("\\\\");break;case '\b':b.Append("\\b");break;case '\f':b.Append("\\f");break;case '\n':b.Append("\\n");break;case '\r':b.Append("\\r");break;case '\t':b.Append("\\t");break;default:if(c<32)b.Append("\\u"+((int)c).ToString("x4"));else b.Append(c);break;}}return b.Append('\"').ToString();}
 static string EventJson(WfpEvent e,out bool valid){valid=e!=null&&(e.PackageSid==null||e.PackageSid.Length<=184)&&(e.AppId==null||e.AppId.Length<=4096);if(!valid)return null;string app=e.AppId==null?"null":Q(Convert.ToBase64String(e.AppId));return "{\"timestamp\":"+Q(e.Timestamp.ToString(System.Globalization.CultureInfo.InvariantCulture))+",\"flags\":"+e.Flags.ToString(System.Globalization.CultureInfo.InvariantCulture)+",\"ipVersion\":"+e.IpVersion.ToString(System.Globalization.CultureInfo.InvariantCulture)+",\"protocol\":"+e.Protocol.ToString(System.Globalization.CultureInfo.InvariantCulture)+",\"remoteAddress\":"+e.RemoteAddress.ToString(System.Globalization.CultureInfo.InvariantCulture)+",\"remotePort\":"+e.RemotePort.ToString(System.Globalization.CultureInfo.InvariantCulture)+",\"packageSid\":"+Q(e.PackageSid)+",\"appId\":"+app+",\"capability\":"+e.Capability.ToString(System.Globalization.CultureInfo.InvariantCulture)+",\"filterId\":"+Q(e.FilterId.ToString(System.Globalization.CultureInfo.InvariantCulture))+",\"isLoopback\":"+(e.IsLoopback?"true":"false")+"}";}
 static bool Invocation(string nonce,string root){if(String.IsNullOrEmpty(root)||root.Length>256||nonce==null||nonce.Length!=64)return false;for(int i=0;i<nonce.Length;i++)if(!((nonce[i]>='0'&&nonce[i]<='9')||(nonce[i]>='a'&&nonce[i]<='f')))return false;return true;}
 string Json(string nonce,string root){CueWfpLeaseDiagnostic d=null;try{d=lease==null?null:lease.ReadDiagnostic();}catch{}bool overflow=d!=null&&d.Overflow,valid=!invalid&&Invocation(nonce,root)&&d!=null&&d.Events!=null&&d.Events.Length<=64;var parts=new List<string>();if(valid)foreach(var e in d.Events){bool ok;string p=EventJson(e,out ok);if(!ok){valid=false;break;}parts.Add(p);}string state=valid&&!overflow&&d.State=="captured"?"captured":"unknown";if(!valid||overflow)parts.Clear();string json="{\"version\":\"cue-readonly-wfp-diagnostic-v1\",\"nonce\":"+Q(nonce)+",\"rootIdentity\":"+Q(root)+",\"state\":\""+state+"\",\"overflow\":"+(overflow?"true":"false")+",\"events\":["+String.Join(",",parts.ToArray())+"]}";if(System.Text.Encoding.UTF8.GetByteCount(json)>524288)json="{\"version\":\"cue-readonly-wfp-diagnostic-v1\",\"nonce\":"+Q(nonce)+",\"rootIdentity\":"+Q(root)+",\"state\":\"unknown\",\"overflow\":true,\"events\":[]}";return json;}
 public void Emit(string nonce,string rootIdentity){if(emitted)return;emitted=true;if(!Invocation(nonce,rootIdentity))return;try{Console.Out.WriteLine("CUE_READONLY_WFP="+Json(nonce,rootIdentity));}catch{}}
}
