import { createHash, randomBytes } from 'node:crypto';
import { existsSync, lstatSync, mkdirSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, join, relative, resolve } from 'node:path';
import { types } from 'node:util';
import type { Ledger } from './ledger.js';
import type { StageEnvelopeBinding } from './orchestration/stage-envelope.js';
import { identifyChangeSnapshotRoot } from './change-snapshot-host.js';
import { resolveOwnedExecutable, spawnOwned } from './process-launch.js';
import { terminateVerifiedTree, verifyProcessesDead } from './process-termination.js';
import { createReadonlyVerifierIdentityStore } from './readonly-verifier-identity-store.js';
import { snapshotReadonlyVerifierControl, verifyReadonlyVerifierControl, type ReadonlyVerifierControlBundle } from './readonly-verifier-control.js';
import { parseReadonlyWfpDiagnostic, type ReadonlyWfpDiagnostic } from './readonly-wfp-diagnostic.js';

const sha=(v:string|Uint8Array)=>createHash('sha256').update(v).digest('hex');
const quote=(v:string)=>`"${v.replace(/(\\*)"/g,'$1$1\\"').replace(/(\\+)$/,'$1$1')}"`;
function plain(v:unknown,keys:readonly string[]){if(!v||typeof v!=='object'||types.isProxy(v)||Object.getPrototypeOf(v)!==Object.prototype)throw Error('readonly_worker_data');const d=Object.getOwnPropertyDescriptors(v);if(Reflect.ownKeys(d).length!==keys.length||keys.some(k=>!d[k]?.enumerable||!Object.hasOwn(d[k],'value')))throw Error('readonly_worker_fields');return Object.fromEntries(keys.map(k=>[k,d[k]!.value]));}
function strings(v:unknown,max:number){if(!Array.isArray(v)||types.isProxy(v)||Object.getPrototypeOf(v)!==Array.prototype||v.length>max||Reflect.ownKeys(v).length!==v.length+1)throw Error('readonly_worker_list');return v.map((_,i)=>{const d=Object.getOwnPropertyDescriptor(v,String(i));if(!d?.enumerable||!Object.hasOwn(d,'value')||typeof d.value!=='string'||d.value.length>32768||d.value.includes('\0'))throw Error('readonly_worker_list');return d.value as string;});}
function contained(root:string,path:string){const r=relative(root,path);return r===''||(!isAbsolute(r)&&r.split(/[\\/]/u)[0]!=='..');}
export function assertReadonlyRuntimeSeparated(worktree:string,runtime:string):void{const w=realpathSync.native(worktree),r=realpathSync.native(runtime);if(contained(w,r)||contained(r,w))throw Error('readonly_runtime_worktree_overlap');}
export interface ReadonlyVerifierCommand {readonly argv:readonly string[];readonly timeoutMs:number;readonly commandDigest:string}
export interface ReadonlyVerifierResult {readonly outcome:'succeeded'|'failed';readonly exitCode:number|null;readonly stdoutSha256:string;readonly stderrSha256:string;readonly identityRef:string|null;readonly cleanupRef:string|null;readonly wfpDiagnostic:ReadonlyWfpDiagnostic}

/** Native isolation only. This boundary does not decide checker truth or acceptance. */
export function createReadonlyVerifierWorker(host:{db:Ledger;control:ReadonlyVerifierControlBundle;runtimeRootBase:string;resolveBinding(attemptId:string):{stage:StageEnvelopeBinding;command:ReadonlyVerifierCommand}|null}){
 const control=snapshotReadonlyVerifierControl(host.control),base=realpathSync.native(host.runtimeRootBase);if(contained(base,control.executable)||contained(base,control.launcher))throw Error('readonly_control_inside_runtime');
 const environmentContractDigest=sha(JSON.stringify({version:'cue-readonly-env-v1',keys:['APPDATA','HOME','LOCALAPPDATA','TEMP','TMP','USERPROFILE','SystemRoot','WINDIR'],systemRoot:process.env.SystemRoot??'C:\\Windows'}));
 return Object.freeze({async launch(attemptId:string,signal:AbortSignal):Promise<ReadonlyVerifierResult>{
  if(host.db.inTransaction||signal.aborted)throw Error('readonly_worker_launch_state');const resolved=host.resolveBinding(attemptId);if(!resolved)throw Error('readonly_worker_binding_missing');
  const stage=resolved.stage,c=plain(resolved.command,['argv','timeoutMs','commandDigest']),argv=strings(c.argv,64);if(stage.attemptId!==attemptId||stage.owner.run_id!==attemptId||stage.owner.cwd!==stage.envelope.worktree_realpath||stage.envelope.egress.length||stage.envelope.allowed_actions.includes('file_change')||!stage.envelope.allowed_actions.includes('command'))throw Error('readonly_worker_stage');
  const task=host.db.prepare("SELECT json_extract(t.value,'$.role') role,a.candidate_id,l.expected_subject_digest FROM orchestration_attempt a JOIN orchestration_launch_intent l ON l.attempt_id=a.attempt_id JOIN orchestration_plan p ON p.run_id=a.run_id JOIN json_each(p.payload,'$.tasks') t WHERE a.attempt_id=? AND json_extract(t.value,'$.id')=a.task_id").get(attemptId) as {role:string;candidate_id:string;expected_subject_digest:string}|undefined;
  if(task?.role!=='verifier'||!Number.isSafeInteger(c.timeoutMs)||Number(c.timeoutMs)<100||Number(c.timeoutMs)>120000||typeof c.commandDigest!=='string'||c.commandDigest!==sha(JSON.stringify({argv,timeoutMs:c.timeoutMs,control:control.sha256,environmentContractDigest})))throw Error('readonly_worker_contract');
  if(!verifyReadonlyVerifierControl(control))throw Error('readonly_control_drift');const worktree=realpathSync.native(stage.owner.cwd);if(lstatSync(worktree).isSymbolicLink())throw Error('readonly_worktree_reparse');
  const root=identifyChangeSnapshotRoot(worktree);if(root.state!=='ok')throw Error('readonly_root_identity');
  const powershell=resolveOwnedExecutable(host.db,stage.owner,join(process.env.SystemRoot??'C:\\Windows','System32','WindowsPowerShell','v1.0','powershell.exe'));
  const acl=await new Promise<string>((ok,bad)=>{let p:ReturnType<typeof spawnOwned>;try{p=spawnOwned(host.db,stage.owner,powershell,['-NoProfile','-NonInteractive','-Command',`(Get-Acl -LiteralPath '${worktree.replaceAll("'","''")}').Sddl`],{windowsHide:true,stdio:['ignore','pipe','pipe'],env:{SystemRoot:process.env.SystemRoot??'C:\\Windows',WINDIR:process.env.SystemRoot??'C:\\Windows',PATHEXT:'.EXE'}});}catch(error){bad(error);return;}let out='',err='',bytes=0,settled=false;
   const finish=(error?:Error,value?:string)=>{if(settled)return;settled=true;clearTimeout(timer);signal.removeEventListener('abort',abort);error?bad(error):ok(value!);};
   const stop=()=>{if(settled)return;settled=true;clearTimeout(timer);signal.removeEventListener('abort',abort);let failure=Error('readonly_acl_observation');try{terminateVerifiedTree(p.child.pid!);}catch{failure=Error('readonly_acl_termination_unverified');}bad(failure);};
   const append=(current:string,x:unknown)=>{const value=String(x);bytes+=Buffer.byteLength(value);if(bytes>65536){stop();return current;}return current+value;};
   const abort=()=>stop(),timer=setTimeout(stop,5000);signal.addEventListener('abort',abort,{once:true});if(signal.aborted){stop();return;}
   p.child.stdout?.on('data',x=>{out=append(out,x);});p.child.stderr?.on('data',x=>{err=append(err,x);});p.child.once('error',stop);p.child.once('close',code=>{const value=out.trim();code===0&&!err.trim()&&value?finish(undefined,value):finish(Error('readonly_acl_observation'));});});
  if(signal.aborted)throw Error('readonly_worker_launch_state');
  assertReadonlyRuntimeSeparated(worktree,base);
  const runtime=join(base,'Cue.Verifier.'+randomBytes(16).toString('hex')),profile='Cue.Verifier.'+randomBytes(16).toString('hex');
  const env=Object.freeze([`APPDATA=${runtime}`,`HOME=${runtime}`,`LOCALAPPDATA=${runtime}`,`TEMP=${runtime}`,`TMP=${runtime}`,`USERPROFILE=${runtime}`,`SystemRoot=${process.env.SystemRoot??'C:\\Windows'}`,`WINDIR=${process.env.SystemRoot??'C:\\Windows'}`].sort());
  const environmentDigest=sha(JSON.stringify(env)),nonce=randomBytes(32).toString('hex'),cancelMarker=join(runtime,'cancel-'+nonce),payload={profileName:profile,worktree,runtimeRoot:runtime,executable:control.executable,executableSha256:control.executableSha256,commandLine:[control.executable,...argv].map(quote).join(' '),timeoutMs:c.timeoutMs,cancelMarker,rootIdentity:`${root.identity.volumeSerial}:${root.identity.fileId}`,originalSddl:acl,environment:env,nonce};
  const launcherBytes=readFileSync(control.launcher);if(sha(launcherBytes)!==control.launcherSha256)throw Error('readonly_control_drift');
  mkdirSync(runtime);let launched:ReturnType<typeof spawnOwned>;try{launched=spawnOwned(host.db,stage.owner,powershell,['-NoLogo','-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-Command','-'],{windowsHide:true,stdio:['pipe','pipe','pipe'],env:{SystemRoot:process.env.SystemRoot??'C:\\Windows',WINDIR:process.env.SystemRoot??'C:\\Windows',PATHEXT:'.EXE'}});}catch(error){rmSync(runtime,{recursive:true,force:true});throw error;}
  let stdout='',stderr='',workerPid=0,created='',aborted=false,settled=false;const markCancelled=()=>{aborted=true;try{writeFileSync(cancelMarker,nonce,{flag:'wx'});}catch{}};
  const exitCode=await new Promise<number|null>((resolveExit,rejectExit)=>{let timer:ReturnType<typeof setTimeout>;
   const finish=(code:number|null)=>{if(settled)return;settled=true;clearTimeout(timer);signal.removeEventListener('abort',abort);resolveExit(code);};
   const stop=()=>{if(settled)return;settled=true;clearTimeout(timer);signal.removeEventListener('abort',abort);markCancelled();try{terminateVerifiedTree(launched.child.pid!);resolveExit(null);}catch{rejectExit(Error('readonly_launcher_termination_unverified'));}};
   const append=(current:string,x:unknown)=>{if(settled)return current;const next=current+String(x);if(Buffer.byteLength(next)>1_048_576){stop();return current;}return next;};
   const abort=()=>stop();timer=setTimeout(stop,Number(c.timeoutMs)+15000);signal.addEventListener('abort',abort,{once:true});
   launched.child.stdout?.on('data',x=>{stdout=append(stdout,x);if(settled)return;const m=/^CUE_READONLY_PID=(\d+);CREATED_FILE_TIME=(\d+)\r?$/mu.exec(stdout);if(m){workerPid=Number(m[1]);created=m[2]!;}});launched.child.stderr?.on('data',x=>{stderr=append(stderr,x);});launched.child.once('error',stop);launched.child.once('close',finish);
   const stdin=launched.child.stdin;if(!stdin){stop();return;}stdin.once('error',stop);if(signal.aborted){stop();return;}try{const script=launcherBytes.toString('base64'),input=Buffer.from(JSON.stringify(payload)).toString('base64');stdin.end(`$s=[ScriptBlock]::Create([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('${script}')));& $s -PayloadBase64 '${input}'\n`);}catch{stop();}
  });let identityRef:null|string=null,cleanupRef:null|string=null,runtimeRemovalAuthorized=true;
  try{if(workerPid)try{verifyProcessesDead([workerPid]);}catch{runtimeRemovalAuthorized=false;}if(runtimeRemovalAuthorized&&existsSync(runtime))rmSync(runtime,{recursive:true});const expectedRoot=`${root.identity.volumeSerial}:${root.identity.fileId}`,after=identifyChangeSnapshotRoot(worktree),lines=stdout.split(/\r?\n/u).filter(Boolean),cleanupLine=lines.find(line=>line.startsWith('CUE_READONLY_CLEANUP=')),cleanup=cleanupLine?JSON.parse(cleanupLine.slice(21)):null,clean=runtimeRemovalAuthorized&&lines.filter(line=>line.startsWith('CUE_READONLY_CLEANUP=')).length===1&&cleanup?.nonce===nonce&&cleanup.rootIdentity===expectedRoot&&cleanup.aclRestored===true&&cleanup.profileAbsent===true&&after.state==='ok'&&after.identity.volumeSerial===root.identity.volumeSerial&&after.identity.fileId===root.identity.fileId&&realpathSync.native(worktree)===worktree&&!existsSync(runtime)&&launched.child.exitCode!==null;
   if(!aborted&&exitCode===0&&workerPid&&created&&clean&&verifyReadonlyVerifierControl(control)){const store=createReadonlyVerifierIdentityStore(host.db),identity=store.record({version:'cue-readonly-verifier-identity-v1',attemptId,candidateId:task.candidate_id,subjectDigest:task.expected_subject_digest,controlDigest:control.sha256,commandDigest:String(c.commandDigest),environmentDigest,rootIdentity:`${root.identity.volumeSerial}:${root.identity.fileId}`,session:Object.freeze(launched.session),worker:{pid:workerPid,createdFileTime:created},observedAt:new Date().toISOString()});identityRef=identity;cleanupRef=store.cleanup({version:'cue-readonly-verifier-cleanup-v1',attemptId,identitySha256:identity.slice('cue-readonly-identity:'.length),result:'verified-clean',aclRestored:true,profileAbsent:true,runtimeAbsent:true,processesDead:true,rootIdentity:`${root.identity.volumeSerial}:${root.identity.fileId}`,observedAt:new Date().toISOString()});}
  }catch{}
  const outcome=exitCode===0&&identityRef&&cleanupRef?'succeeded':'failed';
  return Object.freeze({outcome,exitCode,stdoutSha256:sha(stdout),stderrSha256:sha(stderr),identityRef,cleanupRef,wfpDiagnostic:parseReadonlyWfpDiagnostic(stdout,nonce,`${root.identity.volumeSerial}:${root.identity.fileId}`,outcome==='succeeded')}) as ReadonlyVerifierResult;
 }});}
