import { types } from 'node:util';

export type ReadonlyWfpEvent = Readonly<{timestamp:string;flags:number;ipVersion:number;protocol:number;remoteAddress:number;remotePort:number;packageSid:string|null;appId:string|null;capability:number;filterId:string;isLoopback:boolean}>;
export type ReadonlyWfpDiagnostic = Readonly<{state:'captured'|'unknown';overflow:boolean;events:readonly ReadonlyWfpEvent[]}>;
const empty=()=>Object.freeze({state:'unknown' as const,overflow:false,events:Object.freeze([])}) as ReadonlyWfpDiagnostic;
function record(v:unknown,keys:string[]){if(!v||typeof v!=='object'||types.isProxy(v)||Object.getPrototypeOf(v)!==Object.prototype)return null;const d=Object.getOwnPropertyDescriptors(v);if(Reflect.ownKeys(d).length!==keys.length||keys.some(k=>!d[k]?.enumerable||!Object.hasOwn(d[k],'value')))return null;return Object.fromEntries(keys.map(k=>[k,d[k]!.value]));}
const u64=(v:unknown)=>typeof v==='string'&&/^(0|[1-9][0-9]{0,19})$/u.test(v)&&BigInt(v)<=18446744073709551615n;
export function parseReadonlyWfpDiagnostic(stdout:string,nonce:string,rootIdentity:string,workerSucceeded:boolean):ReadonlyWfpDiagnostic{
 try{
  if(typeof stdout!=='string'||Buffer.byteLength(stdout)>1_048_576||!/^[a-f0-9]{64}$/u.test(nonce)||!rootIdentity||rootIdentity.length>256)return empty();
  const lines=stdout.split(/\r?\n/u).filter(line=>line.startsWith('CUE_READONLY_WFP='));if(lines.length!==1)return empty();const json=lines[0]!.slice(17);if(Buffer.byteLength(json)>524288)return empty();
  const f=record(JSON.parse(json),['version','nonce','rootIdentity','state','overflow','events']);if(!f||f.version!=='cue-readonly-wfp-diagnostic-v1'||f.nonce!==nonce||f.rootIdentity!==rootIdentity||!['captured','unknown'].includes(f.state)||typeof f.overflow!=='boolean'||!Array.isArray(f.events)||types.isProxy(f.events)||Object.getPrototypeOf(f.events)!==Array.prototype||f.events.length>64||Reflect.ownKeys(f.events).length!==f.events.length+1)return empty();
  const events:ReadonlyWfpEvent[]=[];for(let i=0;i<f.events.length;i++){const d=Object.getOwnPropertyDescriptor(f.events,String(i));if(!d||!Object.hasOwn(d,'value'))return empty();const e=record(d.value,['timestamp','flags','ipVersion','protocol','remoteAddress','remotePort','packageSid','appId','capability','filterId','isLoopback']);const appBytes=typeof e?.appId==='string'?Buffer.from(e.appId,'base64'):null;if(!e||!u64(e.timestamp)||!u64(e.filterId)||!Number.isInteger(e.flags)||e.flags<0||e.flags>0xffffffff||!Number.isInteger(e.ipVersion)||e.ipVersion<0||e.ipVersion>0xffffffff||!Number.isInteger(e.protocol)||e.protocol<0||e.protocol>0xffffffff||!Number.isInteger(e.remoteAddress)||e.remoteAddress<0||e.remoteAddress>0xffffffff||!Number.isInteger(e.remotePort)||e.remotePort<0||e.remotePort>65535||(e.packageSid!==null&&(typeof e.packageSid!=='string'||e.packageSid.length>184))||(e.appId!==null&&(typeof e.appId!=='string'||!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/u.test(e.appId)||appBytes!.length>4096||appBytes!.toString('base64')!==e.appId))||!Number.isInteger(e.capability)||e.capability< -2147483648||e.capability>2147483647||typeof e.isLoopback!=='boolean')return empty();events.push(Object.freeze(e as ReadonlyWfpEvent));}
  const state=f.state==='captured'&&!f.overflow&&workerSucceeded?'captured':'unknown';return Object.freeze({state,overflow:f.overflow,events:Object.freeze(events)});
 }catch{return empty();}
}
