import { createHash } from 'node:crypto';
import { types } from 'node:util';
import type { Ledger } from './ledger.js';

export interface WaitRequestInput { requestId:string;runId:string;taskId:string;attemptId:string;identityId:string;requestOrdinal:number;streamId:string;reason:'external-response';responseSchema:'cue-wait-response-v1';createdAtMs:number;deadlineAtMs:number;expectedResponder:Readonly<{id:string;revision:string}> }
export interface WaitResponseInput { eventId:string;requestId:string;responseId:string;responseOrdinal:number;responder:Readonly<{id:string;revision:string}>;contentRef:string;observedAtMs:number }
export interface CheckpointInput { eventId:string;streamId:string;runId:string;taskId:string;attemptId:string;identityId:string;sourceOrdinal:number;kind:'partial'|'final';contentRef:string;observedAtMs:number }
export interface WaitContext { readonly runId:string;readonly taskId:string;readonly attemptId:string;readonly identityId:string }
export interface RequestQueueHost {
  authorizeWaitRequest?(context:WaitContext,request:Readonly<WaitRequestInput>):boolean;
  authorizeResponder?(context:WaitContext,request:Readonly<WaitRequestInput>,response:Readonly<WaitResponseInput>):boolean;
  authorizeResponseContent?(contentRef:string,requestId:string,attemptId:string):boolean;
  resolveResponseContent?(contentRef:string,requestId:string,attemptId:string):Uint8Array|null;
  authorizeCheckpoint?(context:WaitContext,checkpoint:Readonly<CheckpointInput>):boolean;
  authorizeCheckpointContent?(contentRef:string,streamId:string,attemptId:string):boolean;
  resolveCheckpointContent?(contentRef:string,streamId:string,attemptId:string):Uint8Array|null;
  now():number;
}
type RequestRow={request_id:string;run_id:string;task_id:string;attempt_id:string;identity_id:string;request_ordinal:number;stream_id:string;created_at_ms:number;deadline_at_ms:number;responder_id:string;responder_revision:string;payload:Buffer;payload_sha256:string};
type InboxRow={event_id:string;event_type:string;request_id:string|null;response_id:string|null;response_ordinal:number|null;responder_id:string|null;responder_revision:string|null;stream_id:string|null;run_id:string|null;task_id:string|null;attempt_id:string;identity_id:string;source_ordinal:number|null;kind:string|null;content_ref:string;content_sha256:string;content_length:number;observed_at_ms:number;payload:Buffer;payload_sha256:string};
const sha=(v:Uint8Array|string)=>createHash('sha256').update(v).digest('hex');
function plain(v:unknown,keys:readonly string[]){if(!v||typeof v!=='object'||types.isProxy(v)||Object.getPrototypeOf(v)!==Object.prototype||Reflect.ownKeys(v).length!==keys.length)throw Error('invalid_wait_input');for(const k of keys){const d=Object.getOwnPropertyDescriptor(v,k);if(!d||!d.enumerable||!Object.hasOwn(d,'value'))throw Error('invalid_wait_input');}}
function ident(...vs:string[]){for(const v of vs)if(typeof v!=='string'||!/^[A-Za-z0-9][A-Za-z0-9._:/-]{0,127}$/u.test(v)||Buffer.from(v).toString()!==v)throw Error('invalid_wait_id');}
function integer(...vs:number[]){for(const v of vs)if(!Number.isSafeInteger(v)||v<0)throw Error('invalid_wait_number');}
function bytes(value:Uint8Array|null|undefined){if(!(value instanceof Uint8Array)||value.byteLength>1048576)throw Error('wait_content_unavailable');return Buffer.from(value);}
function encode(value:object){const b=Buffer.from(JSON.stringify(value));if(b.length>32768)throw Error('wait_payload_too_large');return b;}
function frozenRequest(r:RequestRow):Readonly<WaitRequestInput>{return Object.freeze({requestId:r.request_id,runId:r.run_id,taskId:r.task_id,attemptId:r.attempt_id,identityId:r.identity_id,requestOrdinal:r.request_ordinal,streamId:r.stream_id,reason:'external-response',responseSchema:'cue-wait-response-v1',createdAtMs:r.created_at_ms,deadlineAtMs:r.deadline_at_ms,expectedResponder:Object.freeze({id:r.responder_id,revision:r.responder_revision})});}
function rowIntegrity(r:RequestRow){if(sha(r.payload)!==r.payload_sha256||!r.payload.equals(encode(frozenRequest(r))))throw Error('wait_request_integrity');}

export function createRequestQueue(db:Ledger,host:RequestQueueHost){
 const now=()=>{const n=host.now();integer(n);return n;};
 const context=(a:any):WaitContext=>Object.freeze({runId:a.run_id,taskId:a.task_id,attemptId:a.attempt_id,identityId:a.identity_id});
 function current(attemptId:string,identityId:string){
  const r=db.prepare(`SELECT a.run_id,a.task_id,a.attempt_id,a.state,i.identity_id,i.payload identity_payload,i.payload_sha256 identity_hash,l.payload intent_payload,l.payload_sha256 intent_hash,s.stage_json
   FROM orchestration_attempt a JOIN orchestration_attempt_identity i ON i.attempt_id=a.attempt_id JOIN orchestration_launch_intent l ON l.attempt_id=a.attempt_id
   JOIN orchestration_stage_envelope s ON s.attempt_id=a.attempt_id WHERE a.attempt_id=? AND i.identity_id=?`).get(attemptId,identityId) as any;
  if(!r||r.state!=='running'||sha(r.identity_payload)!==r.identity_hash||sha(r.intent_payload)!==r.intent_hash||db.prepare('SELECT 1 FROM orchestration_wait_legacy WHERE attempt_id=?').get(attemptId))throw Error('wait_attempt_unavailable');return r;
 }
 function requestRow(idValue:string){const r=db.prepare('SELECT * FROM orchestration_wait_request WHERE request_id=?').get(idValue) as RequestRow|undefined;if(!r)throw Error('wait_request_missing');rowIntegrity(r);return r;}
 function replay(table:string,key:string,value:string,payload:Buffer){const r=db.prepare(`SELECT payload FROM ${table} WHERE ${key}=?`).get(value) as {payload:Buffer}|undefined;if(!r)return false;if(!r.payload.equals(payload))throw Error('wait_replay_mismatch');return true;}
 function makeCheckpoint(c:Readonly<CheckpointInput>){const a=current(c.attemptId,c.identityId);if(a.run_id!==c.runId||a.task_id!==c.taskId)throw Error('wait_lineage_mismatch');return a;}
 function reconcileCheckpointTx(streamId:string,prepared?:Map<number,Buffer>){
  let cursor=(db.prepare("SELECT MAX(ordinal) n FROM orchestration_inbox_cursor WHERE scope='checkpoint' AND scope_id=?").get(streamId) as {n:number|null}).n??0,advanced=0;
  while(advanced<256){const e=db.prepare("SELECT * FROM orchestration_wait_inbox WHERE stream_id=? AND source_ordinal=?").get(streamId,cursor+1) as InboxRow|undefined;if(!e)break;
   const checkpoint=Object.freeze({eventId:e.event_id,streamId:e.stream_id!,runId:e.run_id!,taskId:e.task_id!,attemptId:e.attempt_id,identityId:e.identity_id,sourceOrdinal:e.source_ordinal!,kind:e.kind as 'partial'|'final',contentRef:e.content_ref,observedAtMs:e.observed_at_ms});
   let a:any;try{a=makeCheckpoint(checkpoint);}catch{break;}if(e.payload_sha256!==sha(e.payload)||!e.payload.equals(encode(checkpoint))||host.authorizeCheckpoint?.(context(a),checkpoint)!==true)break;
   const b=prepared?.get(cursor+1)??(host.authorizeCheckpointContent?.(e.content_ref,streamId,e.attempt_id)===true?bytes(host.resolveCheckpointContent?.(e.content_ref,streamId,e.attempt_id)):null);
   if(!b||sha(b)!==e.content_sha256||b.length!==e.content_length)break;
   db.prepare("INSERT INTO orchestration_inbox_cursor VALUES('checkpoint',?,?,?,?,NULL,NULL)").run(streamId,cursor+1,cursor,e.event_id);cursor++;advanced++;
   if(e.event_type==='checkpoint-final'){db.prepare('INSERT INTO orchestration_checkpoint_final_seal VALUES(?,?,?,?,?,?,?)').run(streamId,e.event_id,cursor,e.content_ref,e.content_sha256,e.content_length,now());break;}
  }return Object.freeze({streamId,cursor,advanced,sealed:Boolean(db.prepare('SELECT 1 FROM orchestration_checkpoint_final_seal WHERE stream_id=?').get(streamId))});
 }
 return Object.freeze({
  request(input:WaitRequestInput){plain(input,['requestId','runId','taskId','attemptId','identityId','requestOrdinal','streamId','reason','responseSchema','createdAtMs','deadlineAtMs','expectedResponder']);plain(input.expectedResponder,['id','revision']);ident(input.requestId,input.runId,input.taskId,input.attemptId,input.identityId,input.streamId,input.expectedResponder.id,input.expectedResponder.revision);integer(input.requestOrdinal,input.createdAtMs,input.deadlineAtMs);if(input.requestOrdinal<1||input.requestOrdinal>128||input.reason!=='external-response'||input.responseSchema!=='cue-wait-response-v1')throw Error('invalid_wait_request');const copy=Object.freeze({...input,expectedResponder:Object.freeze({...input.expectedResponder})}),p=encode(copy);
   return db.transaction(()=>{if(replay('orchestration_wait_request','request_id',input.requestId,p))return frozenRequest(requestRow(input.requestId));const a=current(input.attemptId,input.identityId),clock=now();let expiry=0;try{expiry=Date.parse(JSON.parse(a.stage_json).expires_at);}catch{}if(a.run_id!==input.runId||a.task_id!==input.taskId||input.createdAtMs>clock||clock>=input.deadlineAtMs||!Number.isSafeInteger(expiry)||input.deadlineAtMs>expiry)throw Error('wait_request_inactive');const max=(db.prepare('SELECT MAX(request_ordinal) n FROM orchestration_wait_request WHERE attempt_id=?').get(input.attemptId) as {n:number|null}).n??0;if(input.requestOrdinal!==max+1)throw Error('wait_request_out_of_order');if((db.prepare('SELECT COUNT(DISTINCT stream_id) n FROM orchestration_wait_request WHERE attempt_id=?').get(input.attemptId) as {n:number}).n>=16)throw Error('wait_stream_limit');if(host.authorizeWaitRequest?.(context(a),copy)!==true)throw Error('wait_request_denied');db.prepare('INSERT INTO orchestration_wait_request VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(input.requestId,input.runId,input.taskId,input.attemptId,input.identityId,input.requestOrdinal,input.streamId,input.reason,input.responseSchema,input.createdAtMs,input.deadlineAtMs,input.expectedResponder.id,input.expectedResponder.revision,sha(p),p);return copy;}).immediate();
  },
  respond(input:WaitResponseInput){plain(input,['eventId','requestId','responseId','responseOrdinal','responder','contentRef','observedAtMs']);plain(input.responder,['id','revision']);ident(input.eventId,input.requestId,input.responseId,input.responder.id,input.responder.revision,input.contentRef);integer(input.responseOrdinal,input.observedAtMs);const copy=Object.freeze({...input,responder:Object.freeze({...input.responder})}),p=encode(copy);
   return db.transaction(()=>{if(replay('orchestration_wait_inbox','event_id',input.eventId,p))return Object.freeze({accepted:true,replay:true});const r=requestRow(input.requestId),a=current(r.attempt_id,r.identity_id),clock=now();if(input.responseOrdinal!==r.request_ordinal||input.responder.id!==r.responder_id||input.responder.revision!==r.responder_revision||clock>=r.deadline_at_ms||input.observedAtMs>clock||db.prepare('SELECT 1 FROM orchestration_wait_resolution WHERE request_id=?').get(r.request_id))throw Error('wait_response_inactive');if(host.authorizeResponder?.(context(a),frozenRequest(r),copy)!==true||host.authorizeResponseContent?.(input.contentRef,r.request_id,r.attempt_id)!==true)throw Error('wait_response_denied');const b=bytes(host.resolveResponseContent?.(input.contentRef,r.request_id,r.attempt_id));db.prepare("INSERT INTO orchestration_wait_inbox VALUES(?,'response',?,?,?,?,?,NULL,NULL,NULL,?,?,NULL,NULL,?,?,?,?,?,?)").run(input.eventId,input.requestId,input.responseId,input.responseOrdinal,input.responder.id,input.responder.revision,r.attempt_id,r.identity_id,input.contentRef,sha(b),b.length,input.observedAtMs,sha(p),p);db.prepare("INSERT INTO orchestration_wait_resolution VALUES(?,'responded',?,?)").run(r.request_id,input.eventId,input.observedAtMs);return Object.freeze({accepted:true,replay:false});}).immediate();
  },
  resolve(requestId:string,status:'cancelled'|'expired',resolvedAtMs:number){ident(requestId);integer(resolvedAtMs);return db.transaction(()=>{const r=requestRow(requestId),old=db.prepare('SELECT status FROM orchestration_wait_resolution WHERE request_id=?').get(requestId) as {status:string}|undefined;if(old){if(old.status!==status)throw Error('wait_resolution_conflict');return old;}const clock=now();if(status==='expired'&&clock<r.deadline_at_ms)throw Error('wait_not_expired');if(status==='cancelled'&&resolvedAtMs>clock)throw Error('wait_future_resolution');db.prepare('INSERT INTO orchestration_wait_resolution VALUES(?,?,NULL,?)').run(requestId,status,resolvedAtMs);return Object.freeze({status});}).immediate();},
  checkpoint(input:CheckpointInput){plain(input,['eventId','streamId','runId','taskId','attemptId','identityId','sourceOrdinal','kind','contentRef','observedAtMs']);ident(input.eventId,input.streamId,input.runId,input.taskId,input.attemptId,input.identityId,input.contentRef);integer(input.sourceOrdinal,input.observedAtMs);if(input.sourceOrdinal<1||input.sourceOrdinal>4096||!['partial','final'].includes(input.kind))throw Error('invalid_checkpoint');const copy=Object.freeze({...input}),p=encode(copy);
   return db.transaction(()=>{if(replay('orchestration_wait_inbox','event_id',input.eventId,p))return reconcileCheckpointTx(input.streamId);const a=makeCheckpoint(copy),cursor=(db.prepare("SELECT MAX(ordinal) n FROM orchestration_inbox_cursor WHERE scope='checkpoint' AND scope_id=?").get(input.streamId) as {n:number|null}).n??0;if(input.sourceOrdinal>cursor+256)throw Error('checkpoint_gap_limit');if(input.observedAtMs>now()||host.authorizeCheckpoint?.(context(a),copy)!==true||host.authorizeCheckpointContent?.(input.contentRef,input.streamId,input.attemptId)!==true)throw Error('checkpoint_denied');const b=bytes(host.resolveCheckpointContent?.(input.contentRef,input.streamId,input.attemptId));db.prepare(`INSERT INTO orchestration_wait_inbox VALUES(?,?,NULL,NULL,NULL,NULL,NULL,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(input.eventId,`checkpoint-${input.kind}`,input.streamId,input.runId,input.taskId,input.attemptId,input.identityId,input.sourceOrdinal,input.kind,input.contentRef,sha(b),b.length,input.observedAtMs,sha(p),p);return reconcileCheckpointTx(input.streamId,new Map([[input.sourceOrdinal,b]]));}).immediate();
  },
  reconcileCheckpoint(streamId:string){ident(streamId);return db.transaction(()=>reconcileCheckpointTx(streamId)) .immediate();},
  reconcileWait(attemptId:string){ident(attemptId);return db.transaction(()=>{let cursor=(db.prepare("SELECT MAX(ordinal)n FROM orchestration_inbox_cursor WHERE scope='wait' AND scope_id=?").get(attemptId) as {n:number|null}).n??0,advanced=0;while(advanced<256){const r=db.prepare(`SELECT q.*,x.status FROM orchestration_wait_request q JOIN orchestration_wait_resolution x ON x.request_id=q.request_id WHERE q.attempt_id=? AND q.request_ordinal=? AND x.status IN('cancelled','expired')`).get(attemptId,cursor+1) as any;if(!r)break;let a:any;try{rowIntegrity(r);a=current(r.attempt_id,r.identity_id);}catch{break;}if(host.authorizeWaitRequest?.(context(a),frozenRequest(r))!==true)break;db.prepare("INSERT INTO orchestration_inbox_cursor VALUES('wait',?,?,?,NULL,?,?)").run(attemptId,cursor+1,cursor,r.request_id,r.status);cursor++;advanced++;}return Object.freeze({attemptId,cursor,advanced});}).immediate();},
  status(attemptId:string){ident(attemptId);const requests=(db.prepare('SELECT COUNT(*) n FROM orchestration_wait_request WHERE attempt_id=?').get(attemptId) as {n:number}).n,cursor=(db.prepare("SELECT MAX(ordinal)n FROM orchestration_inbox_cursor WHERE scope='wait' AND scope_id=?").get(attemptId) as {n:number|null}).n??0,pending=(db.prepare(`SELECT COUNT(*)n FROM orchestration_wait_resolution r JOIN orchestration_wait_request q ON q.request_id=r.request_id WHERE q.attempt_id=? AND q.request_ordinal>?`).get(attemptId,cursor) as {n:number}).n;return Object.freeze({availability:db.prepare('SELECT 1 FROM orchestration_wait_legacy WHERE attempt_id=?').get(attemptId)?'legacy-wait-unavailable':'recorded',requests,cursor,pending});}
 });
}
