import { createHash } from 'node:crypto';
import { reportJson, type ReportIR } from './ir.js';
import { sourceArchitecture } from './architecture.js';

const style = 'body{font:16px system-ui,sans-serif;max-width:1100px;margin:2rem auto;padding:0 1rem;color:#172033;background:#f7f8fc}table{border-collapse:collapse;width:100%;background:white}td,th{border:1px solid #ccd2df;text-align:left;padding:.6rem;overflow-wrap:anywhere}pre{white-space:pre-wrap;overflow-wrap:anywhere}li{margin:.5rem 0}h1{overflow-wrap:anywhere}@media print{body{margin:0;max-width:none}}';
const sha = (value: string, encoding: 'hex' | 'base64' = 'hex') => createHash('sha256').update(value).digest(encoding);
const escape = (value: unknown) => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
const sourceStyle = 'p,summary{overflow-wrap:anywhere}.architecture{background:white;border:1px solid #ccd2df;border-radius:12px;padding:1rem;margin:1.5rem 0}.architecture h2{margin-top:0}.architecture-total{font-weight:600}.architecture-layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(210px,1fr);gap:1rem;align-items:start}.architecture-matrix{width:100%;max-width:460px;height:auto;color:#172033}.architecture-matrix text{font:14px system-ui;fill:#172033}.matrix-filled{fill:#c7dcff;stroke:#7a9fdb}.matrix-empty{fill:#f3f5fa;stroke:#dce2ec}.architecture-groups{list-style:none;padding:0;margin:0;display:grid;gap:.4rem}.architecture-groups li{margin:0;padding:.5rem;background:#f7f8fc;border-radius:6px;display:grid;grid-template-columns:2rem minmax(0,1fr);gap:.15rem .4rem;overflow-wrap:anywhere}.architecture-groups small{grid-column:2;color:#465571}.architecture-alternative{margin-top:1rem}.source-inventory{margin:1rem 0;border:1px solid #ccd2df;border-radius:8px;padding:.8rem}.source-inventory summary{font-weight:600;cursor:pointer}.source-inventory th:nth-child(3){min-width:7rem}@media(max-width:640px){.architecture-layout{grid-template-columns:minmax(0,1fr)}.architecture-matrix{max-width:420px}.source-inventory{padding:.5rem}}';

/** No file writes, browser bridge, scripts, external links, or network assets. */
export function renderReportHtml(report: ReportIR) {
  const specification = reportJson(report);
  const source = report.kind === 'source', selectedStyle = style + (source ? sourceStyle : '');
  const csp = `default-src 'none'; script-src 'none'; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'; style-src 'sha256-${sha(selectedStyle, 'base64')}'`;
  const html = `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="${escape(csp)}"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cue 보고서</title><style>${selectedStyle}</style></head><body><h1>${escape(report.identity)}</h1><p>보고서 종류: ${escape(report.kind)} · 기준: ${escape(report.revision)}</p><p>관측 상태와 계획된 관계를 구분합니다. 소스 선언은 미검증이며 역사적 인수 기록은 현재 파일 검증이 아닙니다. 이 그림은 영향·안전·효율을 입증하지 않습니다.</p><p>IR digest: ${report.digest}</p>${source?sourceArchitecture(report)+`<details class="source-inventory"><summary>전체 파일/노드 목록 · ${report.nodes.length}개</summary>`:''}<h2>구성 요소 · 단계</h2><table><thead><tr><th>ID</th><th>설명</th><th>상태</th><th>출처</th></tr></thead><tbody>${report.nodes.map(n => `<tr><td>${escape(n.id)}</td><td>${escape(n.label)}</td><td>${escape(n.state)}</td><td>${escape(n.provenance)}</td></tr>`).join('')}</tbody></table>${source?`</details><details class="source-inventory"><summary>전체 원본 관계 목록 · ${report.edges.length}개</summary>`:''}<h2>관계</h2><ul>${report.edges.map(e => `<li>${escape(e.from)} → ${escape(e.to)} (${escape(e.provenance)})</li>`).join('')}</ul>${source?'</details>':''}<details><summary>근거와 불확실성</summary><pre>${escape(JSON.stringify(report.details, null, 2))}</pre></details></body></html>`;
  return Object.freeze({ html, specificationSha256: sha(specification), specificationBytes: Buffer.byteLength(specification), artifactSha256: sha(html), artifactBytes: Buffer.byteLength(html),
    delivery: 'not-written', upstreamValidation: 'not-run', browserEvidence: 'not-run', visualReview: 'not-run' });
}
